### ISSUE TITLE
Cannot write to data directory

### ISSUE THREAD

**Issue by Drehmini** [nextcloud/docker#1003]
I'm using docker swarm to deploy a nextcloud stack. Traefik is providing SSL termination.
Everything is working except that when I try to install nextcloud, I receive an error: `Can't create or write into the data directory /nextcloud_data`

Here's my docker file

```
version: "3.7"

services:
  nextcloud:
    image: nextcloud:latest
    env_file: /docker/nextcloud/nextcloud.env
    networks:
      - internal
      - traefik_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
        - "traefik.http.routers.nextcloud.entrypoints=web"
        - "traefik.http.routers.nextcloud.rule=Host(`subdomain.example.com`)"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.nextcloud.middlewares=https-redirect"
        - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
        - "traefik.http.routers.nextcloud-secure.rule=Host(`subdomain.example.com`)"
        - "traefik.http.middlewares.nextcloud-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
        - "traefik.http.middlewares.nextcloud-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
        - "traefik.http.middlewares.nextcloud-rep.redirectregex.permanent=true"
        - "traefik.http.middlewares.nextcloud-header.headers.customFrameOptionsValue=SAMEORIGIN"
        - "traefik.http.routers.nextcloud-secure.middlewares=nextcloud-rep,nextcloud-header"
        - "traefik.http.routers.nextcloud-secure.tls=true"
        - "traefik.http.routers.nextcloud-secure.service=nextcloud"
    volumes:
      - /docker/nextcloud/html:/var/www/html
      - /docker/nextcloud/apps:/var/www/html/custom_apps
      - /docker/nextcloud/config:/var/www/html/config
      - /docker/nextcloud/data:/nextcloud_data
    
  
  db:
    image: mariadb:10
    env_file: /docker/nextcloud/nextcloud.env
    networks:
      - internal
    volumes:
      - /docker/nextcloud/runtime/db:/var/lib/mysql
  
  db-backup:
    image: mariadb:10
    env_file: /docker/nextcloud/nextcloud-db-backup.env
    volumes:
      - /docker/nextcloud/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - internal
  
  redis:
    image: redis:alpine
    networks:
      - internal
    volumes:
      - /docker/nextcloud/runtime/redis:/data
  
  cron:
    image: nextcloud:latest
    volumes:
      - /docker/nextcloud:/var/www/html
    user: www-data
    networks:
      - internal
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while [ ! -f /var/www/html/config/config.php ]; do
        sleep 1
      done
      while true; do
        php -f /var/www/html/cron.php
        sleep 15m
      done
      EOF'

networks:
  traefik_net:
    external: true
    name: traefik_net
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.12.0/24
```

My nextcloud environment file:
```
MYSQL_HOST=db
MYSQL_ROOT_PASSWORD=***************
MYSQL_DATABASE=nextcloud
MYSQL_USER=nextcloud
MYSQL_PASSWORD=*************
NEXTCLOUD_DATA_DIR=/nextcloud_data
REDIS_HOST=redis
NEXTCLOUD_TRUSTED_DOMAINS=subdomain.example.com
```

Here's the config file that I've modified to include the `check_data_directory_permissions` flag
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'oczqtxbh6dlb',
  'check_data_directory_permissions' => false,
);
```
