### ISSUE TITLE
Error at admin creation after docker-compose creation: `SQLSTATE[HY000] [2006] MySQL server has gone away`

### ISSUE THREAD

**Issue by yyoZGIT** [nextcloud/docker#1013]
I've followed the mariadb with nginx proxy example and adapted it to my domain name, Server is running fine, but can't seem to be able to create the first admin user : 

Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away 

I've tried changing the database host from db to the IP address, with the port, but it still fails.

Any help would be greatly appreciated.

**Comment by yyoZGIT** [comment]
What is strange, is that following the simpler version with only docker on the very same server : 
`docker run --name mariadb -e MYSQL_ROOT_PASSWORD='mypassword' -e MYSQL_PASSWORD='anotherpassword' -e MYSQL_USER='someuser' -e MYSQL_DATABASE='databasename' -d -v mariadb:/var/lib/mysql mariadb/server
``docker run --name nextcloud -d -p 80:80 -v nextcloud:/var/www/html -v data:/var/www/html/data nextcloud:latest`
it did work...

**Comment by andremmfaria** [comment]
Having the same issue. I have changed from mariadb to postgres without success. Here is my docker-compose.yml
`version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./nextcloud_data:/var/www/html
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud_data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
      - app

  redis:
    image: redis:alpine
    restart: always`

**Comment by KevinNThomas** [comment]
Has anyone figured this out yet? I'm also getting `SQLSTATE[HY000] [2006] MySQL server has gone away `. Here's my compose file:
```
version: "2.1"

volumes:
  nextcloud:
  db:

services:
  ...
  
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
```
I've tried lots of different things to no avail: originally I was using an external custom network so I combined all my services into one compose file because I noticed the db container would not stay connected to the external network. That didn't fix it. I've tried using older mariadb images and that also hasn't worked. If anyone has figure this out I'd really appreciate the help.
