### ISSUE TITLE
Nextcloud 18 update: upload_max_filesize 2 MB

### ISSUE THREAD

**Issue by paderick** [nextcloud/docker#1014]
Since the update to nc 18 the upload and post max size is decreased to 2MB. 

I can't find a way to set a larger filesize. Please help.

**Comment by choffm** [comment]
I am running nextcloud 18 from the official docker images.

In the admin settings -> system -> PHP, Upload max size is showing 2MB. However, I am still able to upload large files (tested a 700MB file) via a browser. I am using nginx as a proxy which is setup with `client_max_body_size 10G`.

According to the [documentation](https://docs.nextcloud.com/server/18/admin_manual/configuration_files/big_file_upload_configuration.html#configuring-upload-limits-within-the-gui), these settings can be changed with `nextcloud/.htaccess` and `nextcloud/.user.ini`. In `.htaccess` and `.user.ini`, `upload_max_filesize` and `post_max_size` is both `511M`, and `memory_limit` is `512M` (auto-generated default values). Changing the values there doesn't change anything in the nextcloud settings UI (even after a container restart).

I found that changing settings in `/usr/local/etc/php/conf.d/memory_limit.php` has an effect. Changes in this file are actually reflected in the admin settings interface. 

This is odd, as changing values there is not persistent - `/usr/local/etc/php/conf.d/` is not a volume. Moreover this is not documented, and the official documentation seems wrong. 
Moreover, what's the recommended value for nextcloud? From the browser, I see that big files are uploaded in 10MB chunks (which works even if nextcloud shows 2MB max upload size).

**Comment by paderick** [comment]
The changes in `memory-limits.php` take effect, after restarting the container.

@pierreozoux: But why isn't there a way to change the values permanently?

**Comment by gbalcewicz** [comment]
You can add own file by volume all files from conf.d folders are loaded:
in docker-compose.yml
```
- ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
```
or by the docker command
```
-v /path/to/your/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
```

And the file can look like:
```
upload_max_filesize=512M
post_max_size=550M
memory_limit=1G
```

then restart the container and this should work

**Comment by choffm** [comment]
I am wondering why per default, `upload_max_filesize` and `post_max_size` are both 2 MB, but uploading large files is still possible. Is nextcloud served via apache using the values from `.htaccess` or `user.ini`, but `occ` uses the globally defined ones (`/usr/local/etc/php/conf.d/`)?  So in the end, this modificationi isn't even required?

**Comment by b3nis** [comment]
> or by the docker command
> 
> ```
> -v /path/to/your/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
> ```

@gbalcewicz, can you add to an existing container with this command? Also, I guess that you need to have more perameters in that command? Maybe understood by most, but I am still very much learning how to manage Docker containers. Big thanks in advance!

**Comment by gbalcewicz** [comment]
For example in this command.
```
docker run -d \
-v nextcloud:/var/www/html \
-v apps:/var/www/html/custom_apps \
-v config:/var/www/html/config \
-v data:/var/www/html/data \
-v theme:/var/www/html/themes/<YOUR_CUSTOM_THEME> \
-v /path/to/your/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
nextcloud
```
In the README there are different scenarios and it's just another command parameter to fit your needs.
The -v parameter tells docker to mount file as the zzz-custom.ini (volumes don't have to be directories, they can be single files also). The zzz is to ensure that this config will load last and override other ini files in that directory.

**Comment by b3nis** [comment]
Thanks a lot @gbalcewicz! It works! Nextcloud now reports 2GB for PHP. You are amazing.

**Comment by wiltonsr** [comment]
> And the file can look like:
> 
> ```
> upload_max_filesize=512M
> post_max_size=550M
> memory_limit=1G
> ```

I'm still having issues with this. Even setting 512 to `.ini` file I still can upload files larger than 512MB. I'm using Docker Apache Imagem from Nextcloud 20.

Any tips?

**Comment by wolfallein** [comment]
> > And the file can look like:
> > ```
> > upload_max_filesize=512M
> > post_max_size=550M
> > memory_limit=1G
> > ```
> 
> I'm still having issues with this. Even setting 512 to `.ini` file I still can upload files larger than 512MB. I'm using Docker Apache Imagem from Nextcloud 20.
> 
> Any tips?

Same problem here with NC20 and Docker.

I also tried to copy the *ini file using Dockerfile:

````
FROM nextcloud:apache

COPY timeout.ini /usr/local/etc/php/conf.d/timeout.ini
````

But it copies to the wrong image, and not to the one php is installed.

I'm using the following docker-compose.yml example:

https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/docker-compose.yml

**Comment by paderick** [comment]
Hi @wiltonsr, did yout tried @gbalcewicz answer?
In the worst case try the following: 
```bash
docker exec -it nextcloud /bin/bash
vi /usr/local/etc/php/conf.d/memory-limit.ini
```
add there your three lines, exit the container and restart it.

**Comment by wiltonsr** [comment]
Hi @paderick, thanks for answering.

I tried exactly this solution and the NC simply ignores the parameter and I can upload any size file. I ran the test with a 2GB file and the upload worked.

**Comment by paderick** [comment]
@wiltonsr sorry - I've no idea.  
Is the file stored correctly after your test-upload?

**Comment by wiltonsr** [comment]
I believe so. 

Even if I execute `php -i | grep upload_max_filesize` inside container I have the following return `upload_max_filesize => 512M => 512M` that is expected by the configuration file. However, I can still upload larger files.

**Comment by paderick** [comment]
@wiltonsr It's not a bug, it's a feature!

**Comment by gbalcewicz** [comment]
Can you paste conmand you are using to run the container?

**Comment by wiltonsr** [comment]
Dockerfile:
```dockerfile
FROM nextcloud:20

COPY ./custom.ini "$PHP_INI_DIR/conf.d"
```

custom.ini
```file
upload_max_filesize=512M
post_max_size=550M
memory_limit=1G
```
Build commando: `docker build -t my-next .`

Run command:  `docker run -p 8080:80 --rm --name next my-next`

**Comment by paderick** [comment]
Old command before using the custom.ini:
```bash
docker run -d --expose 443 \
--name nextcloud \
--link nextcloud_mariadb:mysql \
--restart always \
-e "VIRTUAL_HOST=nextcloud.domain.com" \
-e "LETSENCRYPT_HOST=nextcloud.domain.com" \
-e "LETSENCRYPT_EMAIL=admin@domain.com" \
-v /home/nextcloud:/var/www/html:Z \
nextcloud:latest
```

New command with using the custom.ini:
```bash
docker run -d --expose 443 \
--name nextcloud \
--link nextcloud_mariadb:mysql \
--restart always \
-e "VIRTUAL_HOST=nextcloud.domain.com" \
-e "LETSENCRYPT_HOST=nextcloud.domain.com" \
-e "LETSENCRYPT_EMAIL=admin@domain.com" \
-v /home/nextcloud:/var/www/html:Z \
-v /home/nextcloud/custom.ini:/usr/local/etc/php/conf.d/upload-max-filesize.ini \
nextcloud:latest
```

I use the official container. Not a container build by my own.

**Comment by gbalcewicz** [comment]
It could be the order of the configs are loaded, did you try to rename the custom.ini to zzz-custom.ini?

**Comment by wiltonsr** [comment]
Even when I execute with `docker run -p 8080:80 --rm --name next nextcloud:20` using a non-builded image that returns the default value `upload_max_filesize => 2M => 2M` I can still upload larger files.

**Comment by gbalcewicz** [comment]
Are you uploding with sync client? If yes in the docs https://docs.nextcloud.com/server/15/admin_manual/configuration_files/big_file_upload_configuration.html there is a note that says the limit won't work as the files are sent in small chunks

**Comment by wiltonsr** [comment]
How can I check if sync client is enabled? Enabled is the default value, because in the last test there is no change in containers.

From logs, I saw many lines scrolling when upload ocurrs.

**Comment by choffm** [comment]
The documentation refers to the desktop and mobile clients, when mentioning sync clients. Even he browser UI uploads large files in 10M chunks.

**Comment by wiltonsr** [comment]
So, how can I limit user max upload size?

**Comment by Marcus-0815** [comment]
Is it also possible to change the execution time of php scripts via the custom php.ini.
I work with slow disks and sometimes have problems with execution time.

**Comment by J0WI** [comment]
Closed by #1379

**Comment by sebastiansterk** [comment]
No need to change the php ini files manually in your running docker container.
a) your changes will be gone after updating to a new docker image of nextcloud
b) there is a much easier way.

Recommendation: Just set the env variable in your docker container run command or set it in your docker-compose file: `PHP_UPLOAD_LIMIT=16G`

**Comment by chrisfoster121** [comment]
Hello,

I am getting the following error when uploading larger files:
`client intended to send too large body: 2465089 bytes`

my docker-compose looks like the following:

```
version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/sdc1/NextCloudDataVault/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=~~~~~~~~~~~
      - MYSQL_PASSWORD=~~~~~~~~~~~
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: unless-stopped
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - /mnt/sdc1/NextCloudDataVault/html:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    environment:
      - MYSQL_PASSWORD=~~~~~~~~~~
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - VIRTUAL_HOST=~~~~~~~~~~~~~
      - LETSENCRYPT_HOST=~~~~~~~~~~~~~~
      - LETSENCRYPT_EMAIL=~~~~~~~~~~~~
networks:
  nextcloud_network:

```

My php.ini file looks like:
```
upload_max_filesize=2G   
post_max_size=1100M
memory_limit=2G

```

I was reading this thread and saw the volume path addition for the php.ini file. It does seem to change in the settings page :

![image](https://user-images.githubusercontent.com/36481654/136138991-4753300a-eb59-472f-80ef-5f1772315d8c.png)


Have I done something wrong?

**Comment by RSerejo** [comment]
> You can add own file by volume all files from conf.d folders are loaded: in docker-compose.yml
> 
> ```
> - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
> ```
> 
> or by the docker command
> 
> ```
> -v /path/to/your/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
> ```
> 
> And the file can look like:
> 
> ```
> upload_max_filesize=512M
> post_max_size=550M
> memory_limit=1G
> ```
> 
> then restart the container and this should work

i was with that problem too and it worked to me

**Comment by StanislasJEANGEY** [comment]
You can change de `php-local.ini` too 
See here : https://discourse.linuxserver.io/t/nextcloud-27-1-1-cant-change-the-upload-max-filesize-php-8-2/8126

**Comment by joshtrichards** [comment]
> upload_max_filesize=512M
> post_max_size=550M
> memory_limit=1G


For those landing here, keep in mind this is a 4+ year old Issue and the information is outdated. 

The reason it's closed is because native support was added for these parameters. 

There is *zero* need to manually modify `php.ini` for them.

See the image's documentation. Specifically [PHP Configuration](https://github.com/nextcloud/docker#php-configuration).

**Comment by Sieboldianus** [comment]
If you are not using the AIO wrapper container image, but the base nextcloud docker container, use this:
```yaml
services:
  db:
    ...
  redis:
    ...
  app:
    image: nextcloud:32-apache
    restart: always
    ...
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
```

Verify here if it was correctly applied: https://your.cloud.com/settings/admin/serverinfo
