### ISSUE TITLE
Base version with docker compose and mariadb latest does not work anymore

### ISSUE THREAD

**Issue by rchovan** [nextcloud/docker#1038]
Hi, 
base docker compose config with mariadb latest does not work anymore. Something changed in mariadb image between versions 10.3 and 10.4. In Newest version 10.4+, 10.5+ Nextcloud can't connect to database, Last working version is 10.3.x . Tested with Adminer after installation. 

connection worked with mariadb version 10.3.22

![image](https://user-images.githubusercontent.com/6713920/77043744-783a2280-69be-11ea-8376-04c576446a36.png)

same settings in compose file, but can't connect to mariadb version 10.4
(on screenshot password is not filled, but it was deleted after error message)
![image](https://user-images.githubusercontent.com/6713920/77043808-9869e180-69be-11ea-9c1c-5b6d629270f7.png)

docker-compose.yml
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.3.22
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --log-bin
    restart: always
    volumes:
      - /data/_docker/mariadb/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_PASSWORD=pwd
      - MYSQL_DATABASE=nc
      - MYSQL_USER=nc
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=supersecret

  adminer:
    links:
      - db
    image: adminer
    restart: always
    ports:
      - 8081:8080


```
