### ISSUE TITLE
REDIS_HOST is not sufficient to enable Redis file locking

### ISSUE THREAD

**Issue by myroad94** [nextcloud/docker#1066]
Hi,

Environment:
docker-compose.yaml:
```
  nextcloud:
    image: nextcloud:18.0.3-fpm
    environment:
      - REDIS_HOST=redis
    networks:
      - nextcloud
    tty: true
    volumes:
      - ${dockerdata}/var/nextcloud/data:/var/www/html
    restart: always

  redis:
    image: redis:5.0.8
    restart: always
    networks:
      - nextcloud
```

I try to enable Redis as per Nextcloud recommendation. Reading carefully the documentation at https://hub.docker.com/_/nextcloud, I can see I just need to set a REDIS_HOST variable to use it.

However, after enabling it, I know Redis is used because I can check it.
```
docker exec -ti prod1_redis_1 bash                                                                                                                                                                                                                                                                                         
root@fd2027ff2e5f:/data# redis-cli            
127.0.0.1:6379> KEYS *
1) "PHPREDIS_SESSION:f69c39d55d6a737ec2cf647e2af3ce2d"
2) "PHPREDIS_SESSION:c91b2b6e2baec44535ec6a9e4bfe04e6"     
```

But looking at server info at https://[NextcloudUrl]/ocs/v2.php/apps/serverinfo/api/v1/info, I see:
```
<memcache.local>\OC\Memcache\APCu</memcache.local>
<memcache.distributed>none</memcache.distributed>
<filelocking.enabled>yes</filelocking.enabled><memcache.locking>none</memcache.locking>
```

I had to follow https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/files_locking_transactional.html and put some settings in config.php to have
`<memcache.locking>\OC\Memcache\Redis</memcache.locking>`

Then I found that the Nextcloud image already provide a configuration for this: https://github.com/nextcloud/docker/blob/cef7ec58da449bf78729c5781e8e49f236f6c032/18.0/fpm/config/redis.config.php

So my question is, why do I need to configure config.php if Nextcloud image is supposed to do all the necessary work to enable Redis and file locking, according to the documentation? Thank you!
