### ISSUE TITLE
Set correct nextcloud permissions for local storage access

### ISSUE THREAD

**Issue by 33Fraise33** [nextcloud/docker#1087]
I'm running Nextcloud in Docker through Ansible: 

```
- name: setup nextcloud docker container
  docker_container:
    name: nextcloud
    image: nextcloud:latest
    networks:
      - name: fraise_network
        ipv4_address: "{{ docker_network.nextcloud }}"
    purge_networks: yes
    volumes:
      - "/data/nextcloud/www:/var/www/html"
      - "/data:/data"
    user: 33:1003
    env:
      NEXTCLOUD_ADMIN_USER: gianni
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "files.frai.se"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "{{ db_nextcloud_password }}"
      MYSQL_HOST: "{{ docker_network.nextcloud_db }}"
    restart: yes
    restart_policy: always
    state: started
    pull: true
```

I would like to be able to write into my /data directory through the external storage access. 

A group was created on the Docker host with the name 'data' where I added in http and changed the folder permissions of all folders to `775` and owner: `root:data`. 

When adding the external storage I see "You don't have permission to upload or create files here". 
After giving a certain folder temporary 777 permissios I see that nextcloud still writes as http:http. 

Is it possible to change this when running in docker?
