### ISSUE TITLE
Apache-Image with mariadb: unable to create admin user?

### ISSUE THREAD

**Issue by robowraith** [nextcloud/docker#1096]
HI, I'm usign the apache image (nextcloud) with mariadb bhind a traefik proxy.
This is my docker-compose.yaml:
```yaml
version: "3.4"

services:
  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_app
    volumes:
      - "nextcloud:/var/www/nextcloud"
    links:
      - nextcloud_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.routers.nc.entrypoints=web"
      - "traefik.http.routers.nc.rule=(Host(`exampe.com`) && Path(`/nextcloud`)) || Host(`nextcloud.example.com`)"
      - "traefik.http.routers.nc-secure.rule=(Host(`example.com) && Path(`/nextcloud`)) || Host(`nextcloud.example.com`)"
      - "traefik.http.routers.nc-secure.entrypoints=websecure"
      - "traefik.http.routers.nc-secure.tls=true"
      - "traefik.http.routers.nc-secure.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_default

volumes:
  nextcloud:
  db:
```
(User, passwords and domain are for documentation purposes only. I have put in real values, obviously.)

When I start the containers and open the URL, I am greeted by the account setup page of nextcloud, where I enter all the data and recevice this:
<img width="342" alt="Bildschirmfoto 2020-04-29 um 16 42 21" src="https://user-images.githubusercontent.com/46055342/80609489-6b3a3580-8a38-11ea-988e-aa63680c2d1c.png">
This remains teh same, even if I enter the port (3306) in the database address-field, as requested and also, when I enter "nextcloud_db:3306".

Traeffik does not appear to be a factor as the containers behave the same if I remove the labels from the compose-file and add a port to reach the containers directly.

The only error messages in the log are from Appache:
```syslog
nextcloud_app    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.28.0.3. Set the 'ServerName' directive globally to suppress this message
```
(That one I can remove by adding a "hostname" parameter to the docker-compose.yaml)

and from Nextcloud
```syslog
nextcloud_app    | [Wed Apr 29 14:46:10.141370 2020] [access_compat:error] [pid 29] [client XXX.XXX.XXX.XXX:0] AH01797: client denied by server configuration: /var/www/html/data/htaccesstest.txt
```

Any help or hint woudl be greatly appreciated.

**Comment by robowraith** [comment]
OK. I found out, that I would have needed port 3307 not 3306. Result is the same. 
Connecting to 127.0.0.1:3307 gets me "Coknnection refused" instead of "File not found".
If I exec bash on nextcloud_db and try to connect to the database, with the aboe credentials, it works.
If I try the same from the nextcloud_pp-container, it does not.

**Comment by robowraith** [comment]
Now I added the nextcloud_db container to the traefik-network and I can connect to the database from the commandlline of the nextcloud_app-container but not from the nextcloud-setup dialog. I still get 

> Error while trying to create admin user: Failed to connect to the database: An exception   
> occurred in driver: SQLSTATE[HY000] [2002] Connection refused

**Comment by robowraith** [comment]
This is the docker-compose.yaml now:
```yaml
version: "3.4"

services:
  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
    networks:
      - traefik

  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_app
    environment:
      - MYSQL_HOST=nextcloud_db
    volumes:
      - "nextcloud:/var/www/nextcloud"
    links:
      - nextcloud_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.routers.nc.entrypoints=web"
      - "traefik.http.routers.nc.rule=(Host(`example.com`) && Path(`/nextcloud`)) || Host(`nextcloud.example.com`)"
      - "traefik.http.routers.nc-secure.rule=(Host(`example.com`) && Path(`/nextcloud`)) || Host(`nextcloud.example.com`)"
      - "traefik.http.routers.nc-secure.entrypoints=websecure"
      - "traefik.http.routers.nc-secure.tls=true"
      - "traefik.http.routers.nc-secure.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_default

volumes:
  nextcloud:
  db:
```
But still it does not work
