### ISSUE TITLE
Cannot update from 18.0.3 to 18.0.4

### ISSUE THREAD

**Issue by Stokel** [nextcloud/docker#1112]
My Nextcloud instance doesn't seem to update itself, even though it seems to have pulled the newest version.

I did several pulls via docker-compose, docker system prune, docker image prune, docker volume prune and restarts but my web interface still says version 18.0.3 and tells me to update to 18.0.4.

Inside the container `echo $NEXTCLOUD_VERSION` gives me `18.0.4`, though.
I am using the nextcloud:apache version on Raspberry Pi 4.

On a side note my apache also frequently crashes without any errors or warnings which I 'solved' by using a cronjob that calls `exec -T nextcloud /usr/sbin/service apache2 start` every 10 minutes (doesn't seem to spawn extra processes if already running). So maybe something else is already broken on my install...

```
Docker-compose file:
 nextcloud:
    image: nextcloud:apache
    hostname: nextcloud
    restart: always
    depends_on:
      - pihole
      - postgres
      - redis
    entrypoint: /cron.sh
    environment:
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=xxxxxxxxxxxxx
      - TZ=${TZ}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - ${NEXTCLOUD_PORT}:80
    volumes:
      - ${USERDIR}/docker/nextcloud:/var/www/html
      - ${USERDIR}/docker/logs:/log
```
