### ISSUE TITLE
nextcloud_fpm does not start: from docker-compose.yml

### ISSUE THREAD

**Issue by big-bigchen** [nextcloud/docker#114]
Hi,

I've started to pratice the example on my QNAP Container Station.
It went ok and almost all constainers are running, except the nextcloud_fpm. It always complains:
`[27-Jun-2017 22:47:14] ERROR: failed to create new listening socket: socket(): Address family not supported by protocol (97)                      
[27-Jun-2017 22:47:14] ERROR: failed to create new listening socket: socket(): Address family not supported by protocol (97)                      
[27-Jun-2017 22:47:14] ERROR: FPM initialization failed                                                                                           
[27-Jun-2017 22:47:14] ERROR: FPM initialization failed   `

Has someone a pointer? I assume, it is something with IP4/IP6, but I don't know where to fix...

Thanks!

**Comment by big-bigchen** [comment]
...no one?

**Comment by biocyberman** [comment]
Are you able to start an `nginx` image? Just to test if your setup and user can actually run docker image first. And posting output of `docker-compose config` could be helpful.

**Comment by smarmie** [comment]
Hi,
Same issue here, same circumstances.
Output from docker-compose:
```
docker-compose -f nextcloud.yml up -d   
Creating redis ... 
Creating collabora ... 
Creating ngingx-proxy ... 
Creating nextcloud-mariadb ... 
Creating collabora
Creating ngingx-proxy
Creating redis
Creating ngingx-proxy ... done
Creating letsencrypt-companion ... 
Creating redis ... done
Creating nextcloud ... 
Creating nextcloud ... done
Creating nextcloud-webserver ... 
Creating nextcloud-webserver ... error

ERROR: for nextcloud-webserver  Cannot start service nextcloud-webserver: Cannot link to a non running container: /nextcloud AS /nextcloud-webserver/nextcloud

ERROR: for nextcloud-webserver  Cannot start service nextcloud-webserver: Cannot link to a non running container: /nextcloud AS /nextcloud-webserver/nextcloud
ERROR: Encountered errors while bringing up the project.
```
nextcloud:fpm container console output:
```
[03-Sep-2017 20:57:57] ERROR: failed to create new listening socket: socket(): Address family not supported by protocol (97)                      
[03-Sep-2017 20:57:57] ERROR: failed to create new listening socket: socket(): Address family not supported by protocol (97)                      
[03-Sep-2017 20:57:57] ERROR: FPM initialization failed                                                                                           
[03-Sep-2017 20:57:57] ERROR: FPM initialization failed                                                                                           
```
docker-compose config:
```
docker-compose -f nextcloud.yml config
services:
  collabora:
    cap_add:
    - MKNOD
    container_name: collabora
    environment:
      domain: <DOMAIN>
    image: collabora/code
    labels:
      com.qnap.qcs.network.mode: nat
      com.qnap.qcs.version: ''
    network_mode: bridge
  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    labels:
      com.qnap.qcs.network.mode: nat
      com.qnap.qcs.version: ''
    network_mode: bridge
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /share/Container/nginx-proxy/certs:/etc/nginx/certs:rw
    volumes_from:
    - service:nginx-proxy:rw
  nextcloud:
    container_name: nextcloud
    image: nextcloud:fpm
    labels:
      com.qnap.qcs.network.mode: nat
      com.qnap.qcs.version: ''
    links:
    - nextcloud-mariadb
    network_mode: bridge
    volumes:
    - /share/Container/nextcloud:/var/www/html:rw
    - /share/Container/nextcloud/apps:/var/www/html/apps:rw
    - /share/Container/nextcloud/custom_apps:/var/www/html/custom_apps:rw
    - /share/Container/nextcloud/config:/var/www/html/config:rw
    - /share/Container/nextcloud/data:/var/www/html/data:rw
    - /share/Container/nextcloud/themes:/var/www/html/themes:rw
  nextcloud-mariadb:
    container_name: nextcloud-mariadb
    environment:
      MYSQL_DATABASE: <DATABASE>
      MYSQL_PASSWORD: <PASSWORD>
      MYSQL_ROOT_PASSWORD: <ROOT_PASSWORD>
      MYSQL_USER: <USER>
    image: mariadb
    labels:
      com.qnap.qcs.network.mode: nat
      com.qnap.qcs.version: ''
    network_mode: bridge
    volumes:
    - /share/Container/nextcloud/db:/var/lib/mysql:rw
  nextcloud-webserver:
    container_name: nextcloud-webserver
    environment:
      LETSENCRYPT_EMAIL: <EMAIL>
      LETSENCRYPT_HOST: <DOMAIN>
      VIRTUAL_HOST: <DOMAIN>
      VIRTUAL_PORT: '80'
    image: nginx
    labels:
      com.qnap.qcs.network.mode: nat
      com.qnap.qcs.version: ''
    links:
    - nextcloud
    - collabora
    network_mode: bridge
    volumes:
    - /share/Container/nginx-nextcloud.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
    - service:nextcloud:rw
  nginx-proxy:
    container_name: ngingx-proxy
    image: jwilder/nginx-proxy
    labels:
      com.qnap.qcs.network.mode: nat
      com.qnap.qcs.version: ''
    network_mode: bridge
    ports:
    - 80:80/tcp
    - 443:443/tcp
    volumes:
    - /share/Container/nginx-proxy/conf.d:/etc/nginx/conf.d:rw
    - /share/Container/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
    - /share/Container/nginx-proxy/html:/usr/share/nginx/html:rw
    - /share/Container/nginx-proxy/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    container_name: redis
    image: redis
    labels:
      com.qnap.qcs.network.mode: nat
      com.qnap.qcs.version: ''
    network_mode: bridge
version: '2.0'
volumes: {}
```
