### ISSUE TITLE
[ Question ], it is possible to change the Linux user for write the data ?

### ISSUE THREAD

**Issue by simepy** [nextcloud/docker#1144]
Hello everyone !

For some reasons I need to change the Linux user when Nextcloud write the data in `/var/www/html/data`
I overwrite the default configuration for put my data directory.

I try to put a `user: html` in nextcloud service in the docker-compose but I have this error:
`ERROR: for app  Cannot start service app: unable to find user html: no matching entries in passwd file`

Do you know how can I write the data with a define Linux user ?

My docker-compose.yml
```
version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=**********
    env_file:
      - db.env

  app:
    image: nextcloud:stable-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/hdDrive/data:/var/www/html/data
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=**************
      - LETSENCRYPT_HOST=***************
      - LETSENCRYPT_EMAIL=****************@************.****
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
```
