### ISSUE TITLE
CSP issues after container update

### ISSUE THREAD

**Issue by sgrunt91** [nextcloud/docker#1149]
Hi,

Today I wanted to update my nextcloud containers to the latest ones, but after update I got many blocked content about rainloop app and also some `/core/js/*` files.

Browser console say that it's due to an incorrect MIME type (« text/html ») and (X-Content-Type-Options: nosniff).

I didn't changed my config before or after upgrade, and permissions on files seems ok :/
Do you know what could cause that with the `nextcloud:latest` image (apache one) ?

Here is my `docker-compose.yml` if it can be useful:
```yaml
version: "3.3"
services:
  app:
    image: nextcloud:latest
    hostname: nc
    depends_on:
      - mariadb
    restart: always
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: 'cloud.mydomain.com'
    volumes:
      - "apps:/var/www/html/custom_apps"
      - "config:/var/www/html/config"
      - "data:/var/www/html/data"
    networks:
      - "webgateway"
      - "default"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_webgateway"
      # HTTP
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.mydomain.com`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.nextcloud-https.rule=Host(`cloud.mydomain.com`)"
      - "traefik.http.routers.nextcloud-https.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-https.tls.certresolver=tlschallenge"
      - "traefik.http.routers.nextcloud-https.tls=true"
      # Redirect HTTP to HTTPS
      - "traefik.http.routers.nextcloud.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      # caldav redirects
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-caldav@docker"

  mariadb:
    image: mariadb
    hostname: nc_db
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "secret"
    volumes:
      - "mysql:/var/lib/mysql"
    restart: always

volumes:
  "apps":
    driver: local
  "config":
    driver: local
  "data":
    driver: local
  "mysql":
    driver: local

networks:
  webgateway:
    external:
      name: traefik_webgateway
```
