### ISSUE TITLE
Cannot write into "config" directory!

### ISSUE THREAD

**Issue by jkaberg** [nextcloud/docker#1158]
I've got an setup using nginx and the fpm image, largely based on [this example](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/docker-compose.yml). 

However I get permission errors whenever I try to access NC from either web or occ command
```
root@gunder:~/majo# docker-compose exec -u www-data nextcloud-app php occ
Cannot write into "config" directory!
This can usually be fixed by giving the webserver write access to the config directory

Or, if you prefer to keep config.php file read only, set the option "config_is_read_only" to true in it.
See https://docs.nextcloud.com/server/19/go.php?to=admin-config
root@gunder:~/majo# docker-compose exec nextcloud-app bash
root@cloud:/var/www/html# id www-data
uid=33(www-data) gid=33(www-data) groups=33(www-data)
root@cloud:/var/www/html# ls -la /var/www/html/config/
total 32
drw-r--r--  3 www-data root 4096 Jun 18 09:14 .
drwxr-xr-x 14 www-data root 4096 Jun  5 22:00 ..
-rw-r--r--  1 www-data root 2499 Jun 18 09:14 config.php
-rw-r--r--  1 www-data root 1547 Apr 15  2018 config.php.bak
-rw-r--r--  1 www-data root 1629 Jul 21  2018 config.php.bak2
drw-r--r--  2 www-data root 4096 Jul 29  2019 keys
-rw-r--r--  1 www-data root   35 Feb 11  2019 mimetypealiases.json
-rw-r--r--  1 www-data root   46 Feb 11  2019 mimetypemapping.json
root@cloud:/var/www/html#
```

```
  nextcloud-web:
    image: nginx
    restart: unless-stopped
    depends_on:
      - nextcloud-app
    labels:
      - 'traefik.frontend.rule=Host:cloud.${DOMAIN}'
      - 'traefik.docker.network=traefik'
      - 'traefik.port=80'
      - 'traefik.enable=true'
      - 'traefik.frontend.headers.referrerPolicy=no-referrer'
      - 'traefik.frontend.headers.STSPreload=true'
      - 'traefik.frontend.headers.STSSeconds=31536000'
      - 'traefik.frontend.redirect.permanent=true'
      - 'traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav'
      - 'traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/'
    volumes:
      - ${STORAGE_DIR}/web/cloud/cloud.conf:/etc/nginx/nginx.conf:ro
      - ${STORAGE_DIR}/nextcloud/base:/var/www/html #:ro
    networks:
      - traefik
      - backend

  nextcloud-app:
    image: nextcloud:fpm
    hostname: cloud.${DOMAIN}
    restart: unless-stopped
    depends_on:
      - openldap
      - onlyoffice
      - mariadb
      - redis
    volumes:
      - ${STORAGE_DIR}/nextcloud/php.ini:/usr/local/etc/php/php.ini:ro
      - /etc/localtime:/etc/localtime:ro
      - ${STORAGE_DIR}/nextcloud/base:/var/www/html
      - ${STORAGE_DIR}/nextcloud/data:/var/www/html/data
      - ${STORAGE_DIR}/nextcloud/config:/var/www/html/config
      - ${STORAGE_DIR}/nextcloud/apps:/var/www/html/custom_apps
      - ${STORAGE_DIR}/nextcloud/themes:/var/www/html/themes
    environment:
      - TZ=Europe/Oslo
      - MYSQL_DATABASE=${NEXTCLOUD_DB}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PW}
      - MYSQL_HOST=${NEXTCLOUD_DB_HOST}
      - USE_ZEND_ALLOC=0
    networks:
      - backend
      - traefik
```

What am I not seeing here?
