### ISSUE TITLE
NC docker tries (and fails) to access ./proxy/conf.d

### ISSUE THREAD

**Issue by soleroitsolutionsltd** [nextcloud/docker#1176]
Hi

I am trying to deploy a nextcloud instance on a Synology NAS and I'm having some issues...

Here is my docker-compose.yml

```
version: '3' 

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxx
      - MYSQL_PASSWORD=xxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=nextcloud.domain.tld
      - LETSENCRYPT_HOST=nextcloud.domain.tld
      - LETSENCRYPT_EMAIL=me@domain.tld
    restart: unless-stopped

volumes:
  nextcloud:
  db:
  
networks:
  nextcloud_network:
```
which fails with

```
admin@imnas:/volume1/docker$ sudo docker-compose up -d
Removing nextcloud-proxy
Starting nextcloud-mariadb              ... done
Recreating a601fd2b0e39_nextcloud-proxy ... error

ERROR: for a601fd2b0e39_nextcloud-proxy  Cannot start service proxy: Bind mount failed: '/volume1/docker/proxy/conf.d' does not exists

ERROR: for proxy  Cannot start service proxy: Bind mount failed: '/volume1/docker/proxy/conf.d' does not exists
ERROR: Encountered errors while bringing up the project.

```
I'd guess my issue is with the directive

`volumes:      - ./proxy/conf.d:/etc/nginx/conf.d:rw`

but etc/nginx/conf.d:rw does exist... so this should work ?
