### ISSUE TITLE
The reverse proxy header configuration is incorrect

### ISSUE THREAD

**Issue by umardraz** [nextcloud/docker#1178]
Hello

I am getting (The reverse proxy header configuration is incorrect). I am using Treafik as frontend and here is my docker-compose file

```
 app:
    image: nextcloud
    depends_on:
      - db
    networks:
      - web
    restart: unless-stopped
    env_file:
      - ../.env
    container_name: mycontainer.local
    volumes:
      - /var/www/html/mycontainer.local:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NCADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NCADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${TRUSTED_DOMAINS}
      NEXTCLOUD_TRUSTED_PROXIES: ${TRUSTED_PROXIES}
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.backend=mycontainer.local"
      - "traefik.frontend.rule=Host:mycontainer.local"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=80"
```

Would you please help how to solve this trusted proxy issue?
