### ISSUE TITLE
Apache entrypoint result of ` Command "maintenance:install" is not defined.`

### ISSUE THREAD

**Issue by shiipou** [nextcloud/docker#1196]
Hi,

Today, my Nextcloud server was stopped and can't restart.

```
root@nocturlab-01:/data/stacks# docker logs -f cb1257608136
Initializing nextcloud 19.0.1.1 ...
Initializing finished
New nextcloud instance
Installing with PostgreSQL database
starting nextcloud installation
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

                                                 
  Command "maintenance:install" is not defined.  
                                                 
  Did you mean one of these?                     
      app:install                                
      maintenance:data-fingerprint               
      maintenance:mimetype:update-db             
      maintenance:mimetype:update-js             
      maintenance:mode                           
      maintenance:repair                         
      maintenance:theme:update                   
      maintenance:update:htaccess                
                                                 

retrying install...
```

Why the entrypoint try to call `php occ maintenance:install` if `php occ` does not have this command ?

https://github.com/nextcloud/docker/blob/abe8cd69a6a3eee4952d4faea9dfbda64c4cdb2b/19.0/apache/entrypoint.sh#L152-L157

Someone can see how to fix it ?

The entrypoint file was run with arguments : 
```bash
/entrypoint.sh apache2-foreground
```

**Comment by shiipou** [comment]
More information about it :

Now, when I create a new nextcloud instance in my docker swarm cluster, 
I got a running Nextcloud on my server. But after the first restart, Nextcloud show the message 
```
Command "maintenance:install" is not defined. 
```

Here my configuration : 
```yaml
version: "3.7"
services:

  web:
    image: nextcloud:19
    environment :
      NEXTCLOUD_TABLE_PREFIX: nc_
      NEXTCLOUD_TRUSTED_DOMAINS: https://cloud.nocturlab.fr
      NEXTCLOUD_TRUSTED_PROXIES: 10.0.1.4
      NEXTCLOUD_ADMIN_USER: shiishii
      NEXTCLOUD_ADMIN_PASSWORD: RKKTNQ#tfv360
      POSTGRES_HOST: db:5432
      POSTGRES_DB: cloud
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: ******
      SMTP_HOST: ssl0.ovh.net
      SMTP_SECURE: ssl
      SMTP_PORT: 465
      SMTP_AUTHTYPE: LOGIN
      SMTP_NAME: postmaster@nocturlab.fr
      SMTP_PASSWORD: ******
      MAIL_FROM_ADDRESS: noreply
      MAIL_DOMAIN: nocturlab.fr
    networks:
      - ingress_net
      - db
    volumes:
      - data:/var/www/html/data:rw
      - config:/var/www/html/config:rw
      - apps:/var/www/html/apps:rw
    deploy:
      labels:
        ###   ###
        # Cloud #
        ###   ###

        ##
        # Service
        #
        # Enable this endpoint
        - "traefik.enable=true"
        # Set the service port
        - "traefik.http.services.cloud.loadbalancer.server.port=80"
        - "traefik.http.services.cloud.loadbalancer.server.scheme=http"
        - "traefik.http.services.cloud.loadbalancer.passHostHeader=true"
        #
        ##

        ##
        # Http
        #
        # Set the service route
        - "traefik.http.routers.cloud-http.rule=Host(`cloud.nocturlab.fr`)"
        # Set the entrypoint (http or https)
        - "traefik.http.routers.cloud-http.entrypoints=http"
        # Enable https redirection
        - "traefik.http.routers.cloud-http.middlewares=https-redirect"
        #
        ##

        ##
        # Https
        #
        # Set the service route
        - "traefik.http.routers.cloud-https.rule=Host(`cloud.nocturlab.fr`)"
        # Set the entrypoint (http or https)
        - "traefik.http.routers.cloud-https.entrypoints=https"
        # Enable Let's encrypt auto certificat creation
        - "traefik.http.routers.cloud-https.tls.certresolver=certbot"
        #
        ##
      replicas: 1

 cron:
    image: nextcloud:19
    entrypoint: /cron.sh
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
    deploy:
      replicas: 1

  collabora:
    image: collabora/code
    environment:
      - DONT_GEN_SSL_CERT=true
      - domain=cloud.nocturlab.fr
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    ports:
      - 9980:9980
    networks:
      - ingress_net
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.cloud-word.entryPoints=https
        - traefik.http.routers.cloud-word.rule=Host(`word.cloud.nocturlab.fr`)
        - traefik.http.routers.cloud-word.tls.certresolver=certbot
        - traefik.http.services.cloud-word.loadbalancer.server.port=9980
      replicas: 1

networks:
  cloud:
    driver: overlay
  ingress_net:
    external: true
    driver: overlay
  db:
    name: db_db
    external: true

volumes:
  data:
  config:
  apps:

```

**Comment by shiipou** [comment]
More information about it :

Now, when I create a new nextcloud instance in my docker swarm cluster, 
I got a running Nextcloud on my server. But after the first restart, Nextcloud show the message 
```
Command "maintenance:install" is not defined. 
```

Here my configuration : 
```yaml
version: "3.7"
services:

  web:
    image: nextcloud:19
    environment :
      NEXTCLOUD_TABLE_PREFIX: nc_
      NEXTCLOUD_TRUSTED_DOMAINS: https://cloud.nocturlab.fr
      NEXTCLOUD_TRUSTED_PROXIES: 10.0.1.4
      NEXTCLOUD_ADMIN_USER: shiishii
      NEXTCLOUD_ADMIN_PASSWORD: ******
      POSTGRES_HOST: db:5432
      POSTGRES_DB: cloud
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: ******
      SMTP_HOST: ssl0.ovh.net
      SMTP_SECURE: ssl
      SMTP_PORT: 465
      SMTP_AUTHTYPE: LOGIN
      SMTP_NAME: postmaster@nocturlab.fr
      SMTP_PASSWORD: ******
      MAIL_FROM_ADDRESS: noreply
      MAIL_DOMAIN: nocturlab.fr
    networks:
      - ingress_net
      - db
    volumes:
      - data:/var/www/html/data:rw
      - config:/var/www/html/config:rw
      - apps:/var/www/html/apps:rw
    deploy:
      labels:
        ###   ###
        # Cloud #
        ###   ###

        ##
        # Service
        #
        # Enable this endpoint
        - "traefik.enable=true"
        # Set the service port
        - "traefik.http.services.cloud.loadbalancer.server.port=80"
        - "traefik.http.services.cloud.loadbalancer.server.scheme=http"
        - "traefik.http.services.cloud.loadbalancer.passHostHeader=true"
        #
        ##

        ##
        # Http
        #
        # Set the service route
        - "traefik.http.routers.cloud-http.rule=Host(`cloud.nocturlab.fr`)"
        # Set the entrypoint (http or https)
        - "traefik.http.routers.cloud-http.entrypoints=http"
        # Enable https redirection
        - "traefik.http.routers.cloud-http.middlewares=https-redirect"
        #
        ##

        ##
        # Https
        #
        # Set the service route
        - "traefik.http.routers.cloud-https.rule=Host(`cloud.nocturlab.fr`)"
        # Set the entrypoint (http or https)
        - "traefik.http.routers.cloud-https.entrypoints=https"
        # Enable Let's encrypt auto certificat creation
        - "traefik.http.routers.cloud-https.tls.certresolver=certbot"
        #
        ##
      replicas: 1

 cron:
    image: nextcloud:19
    entrypoint: /cron.sh
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
    deploy:
      replicas: 1

  collabora:
    image: collabora/code
    environment:
      - DONT_GEN_SSL_CERT=true
      - domain=cloud.nocturlab.fr
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    ports:
      - 9980:9980
    networks:
      - ingress_net
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.cloud-word.entryPoints=https
        - traefik.http.routers.cloud-word.rule=Host(`word.cloud.nocturlab.fr`)
        - traefik.http.routers.cloud-word.tls.certresolver=certbot
        - traefik.http.services.cloud-word.loadbalancer.server.port=9980
      replicas: 1

networks:
  cloud:
    driver: overlay
  ingress_net:
    external: true
    driver: overlay
  db:
    name: db_db
    external: true

volumes:
  data:
  config:
  apps:

```

**Comment by shiipou** [comment]
Ok, to resolve the issue, I've changed the YAML : 

```yaml
version: "3.7"
services:

  web:
    [...]
    volumes:
      - data:/var/www/html:rw
  cron:
    [...]

collabora:
    [...]

volumes:
  data:
```
