### ISSUE TITLE
Docker compose install fails, cannot connect to any DB type

### ISSUE THREAD

**Issue by rmoreRojoli** [nextcloud/docker#1217]
Using the provided docker compose file (without the volumes) fails to connect to DB
**docker-compose.yml**
```
version: '3.2'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    image: nextcloud
    restart: always
    ports:
      - 8000:80
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: ./postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: ./postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: ./postgres_user.txt # put postgresql username to this file
```

The files for the secrets are present with string values like nextcloud. After docker-compose up the logs show that it cannot connect to the DB and thus fails after several tries.

Postgres logs:
```
db_1   | The files belonging to this database system will be owned by user "postgres".
db_1   | This user must also own the server process.
db_1   | 
db_1   | The database cluster will be initialized with locale "en_US.utf8".
db_1   | The default database encoding has accordingly been set to "UTF8".
db_1   | The default text search configuration will be set to "english".
db_1   | 
db_1   | Data page checksums are disabled.
db_1   | 
db_1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1   | creating subdirectories ... ok
db_1   | selecting dynamic shared memory implementation ... posix
db_1   | selecting default max_connections ... 100
db_1   | selecting default shared_buffers ... 128MB
db_1   | selecting default time zone ... Etc/UTC
db_1   | creating configuration files ... ok
db_1   | running bootstrap script ... ok
db_1   | performing post-bootstrap initialization ... ok
db_1   | syncing data to disk ... ok
db_1   | 
db_1   | 
db_1   | Success. You can now start the database server using:
db_1   | 
db_1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1   | 
db_1   | initdb: warning: enabling "trust" authentication for local connections
db_1   | You can change this by editing pg_hba.conf or using the option -A, or
db_1   | --auth-local and --auth-host, the next time you run initdb.
db_1   | waiting for server to start....2020-08-27 15:40:51.610 UTC [49] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1   | 2020-08-27 15:40:51.612 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2020-08-27 15:40:51.630 UTC [50] LOG:  database system was shut down at 2020-08-27 15:40:51 UTC
db_1   | 2020-08-27 15:40:51.635 UTC [49] LOG:  database system is ready to accept connections
db_1   |  done
db_1   | server started
db_1   | CREATE DATABASE
db_1   | 
db_1   | 
db_1   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1   | 
db_1   | 2020-08-27 15:40:51.851 UTC [49] LOG:  received fast shutdown request
db_1   | waiting for server to shut down....2020-08-27 15:40:51.853 UTC [49] LOG:  aborting any active transactions
db_1   | 2020-08-27 15:40:51.855 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
db_1   | 2020-08-27 15:40:51.857 UTC [51] LOG:  shutting down
db_1   | 2020-08-27 15:40:51.872 UTC [49] LOG:  database system is shut down
db_1   |  done
db_1   | server stopped
db_1   | 
db_1   | PostgreSQL init process complete; ready for start up.
db_1   | 
db_1   | 2020-08-27 15:40:51.967 UTC [1] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1   | 2020-08-27 15:40:51.967 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2020-08-27 15:40:51.967 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2020-08-27 15:40:51.971 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2020-08-27 15:40:51.988 UTC [67] LOG:  database system was shut down at 2020-08-27 15:40:51 UTC
db_1   | 2020-08-27 15:40:51.993 UTC [1] LOG:  database system is ready to accept connections
```
Nextcloud logs:
```
app_1  | Initializing nextcloud 19.0.1.1 ...
app_1  | Initializing finished
app_1  | New nextcloud instance
app_1  | Installing with PostgreSQL database
app_1  | starting nextcloud installation
app_1  | PostgreSQL username and/or password not valid
app_1  |  -> You need to enter details of an existing account.
app_1  | retrying install...
app_1  | An unhandled exception has been thrown:
app_1  | OC\DatabaseException: An exception occurred while executing 'SHOW SERVER_VERSION':
app_1  | 
app_1  | Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: No route to host
app_1  | 	Is the server running on host "db" (172.23.0.2) and accepting
app_1  | 	TCP/IP connections on port 5432? in /var/www/html/lib/private/legacy/OC_DB.php:73
app_1  | Stack trace:
app_1  | #0 /var/www/html/lib/private/legacy/OC_DB.php(139): OC_DB::prepare('SHOW SERVER_VER...', NULL, NULL)
app_1  | #1 /var/www/html/lib/private/legacy/OC_Util.php(971): OC_DB::executeAudited(Array)
app_1  | #2 /var/www/html/lib/private/legacy/OC_Util.php(951): OC_Util::checkDatabaseVersion()
app_1  | #3 /var/www/html/lib/private/Console/Application.php(161): OC_Util::checkServer(Object(OC\SystemConfig))
app_1  | #4 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
app_1  | #5 /var/www/html/occ(11): require_once('/var/www/html/c...')
app_1  | #6 {main}retrying install...
app_1  | An unhandled exception has been thrown:
app_1  | OC\DatabaseException: An exception occurred while executing 'SHOW SERVER_VERSION':
app_1  | 
app_1  | Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: No route to host
app_1  | 	Is the server running on host "db" (172.23.0.2) and accepting
app_1  | 	TCP/IP connections on port 5432? in /var/www/html/lib/private/legacy/OC_DB.php:73
app_1  | Stack trace:
app_1  | #0 /var/www/html/lib/private/legacy/OC_DB.php(139): OC_DB::prepare('SHOW SERVER_VER...', NULL, NULL)
app_1  | #1 /var/www/html/lib/private/legacy/OC_Util.php(971): OC_DB::executeAudited(Array)
app_1  | #2 /var/www/html/lib/private/legacy/OC_Util.php(951): OC_Util::checkDatabaseVersion()
app_1  | #3 /var/www/html/lib/private/Console/Application.php(161): OC_Util::checkServer(Object(OC\SystemConfig))
app_1  | #4 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
app_1  | #5 /var/www/html/occ(11): require_once('/var/www/html/c...')
app_1  | #6 {main}retrying install...
```

Starting the nextcloud with Mariadb connection results in the same issues of not being able to connect to the DB.

**Comment by Sellig28** [comment]
Hi, 

Usually the error is to have a bad dns name for the container database.

Do you have a firewall in place ?

**Comment by rmoreRojoli** [comment]
I have given a name to the DB container the name db and even with that it gave the same issues. Also simplified the docker compose file, this time with mariadb

```
version: '3.5'

services:
  db:
    image: mariadb
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: 'nextcloud'
      MYSQL_USER: 'xxx'
      MYSQL_PASSWORD: 'xxx'
      MYSQL_ROOT_PASSWORD: 'xxx'
  nextcloud:
    image: nextcloud
    ports:
      - 8000:80
    depends_on:
      - db
    restart: always
    environment:
      MYSQL_DATABASE: 'nextcloud'
      MYSQL_USER: 'xxx'
      MYSQL_PASSWORD: 'xxx'
      MYSQL_HOST: 'db'
      NEXTCLOUD_ADMIN_USER: 'xxx'
      NEXTCLOUD_ADMIN_PASSWORD: 'xxx'
```

I am running CentosOS 8, so firewalld is enabled with only the necessary ports opened.
