### ISSUE TITLE
X-Robots-Tag error

### ISSUE THREAD

**Issue by ptoulouse** [nextcloud/docker#1218]
Nextcloud 19.0.1

I am running behind Traefik and I get an error message on the Admin Overview page stating that the X-Robot-Tags header is not set to "none". The problem is that Nextcloud seems to check that the header is set to "none" **only** and nothing else.

Snippet of my Traefik dynamic rules (yaml):
```
http:
    middlewares:
        secure-headers:
           headers:
              customResponseHeaders:
                 X-Robots-Tags: "none, noarchive, nosnippet, notranslate, noimageindex"
```

This cause the error.

Changing X-Robots-Tags to `X-Robots-Tags: "none"` makes the error disappear.
