### ISSUE TITLE
"Can't create or write into the data directory" error with docker and external drive

### ISSUE THREAD

**Issue by minnixtx** [nextcloud/docker#1222]
Hardware: Raspberry Pi 4 4GB booting OS from 80GB SSD connected to USB 3.0
OS: Ubuntu 20.04 64 bit for ARM
Data drive: 4TB SSD connected to USB 3.0
Installation method: docker-compose

I am using the example docker-compose file from the docker hub site to run behind my nginx proxy:

```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always

```

When I go to my local IP address and choose "/media/usb-drive/data" in the field to store my data on the setup page, I get the error: "Can't create or write into the data directory /media/usb-drive/data". My normal unprivileged user can write to the data folder on the drive no problem. If I just leave it as default, the installation succeeds, but the data folder is then on the main OS drive which I do not want. 

What do I need to add to my docker-compose.yml to get this to work correctly and where do I need to add it?

**Comment by arichtman** [comment]
+1 for this - popped some screens on the [Nextcloud forums](https://help.nextcloud.com/t/cant-create-or-write-into-the-data-directory-error-with-docker-docker-compose-and-external-drive/90777). I'm thinking modify the entrypoint to change the owner of the folder using the environment variable?

**Comment by M4lik** [comment]
As you host nextcloud in a docker container the path `/media/usb-drive/data` probably doesn't exists INSIDE of the container
You have to mount that directory to your NC Data path. Somthing like:

```yaml
    volumes:
      - /media/usb-drive/data:/var/www/html/data
```

Furthermore the user that nextcloud runs on (default `www-data`) needs to have write permissions to that folder, so you would probably have to do something like

```bash
chown -R :www-data /media/usb-drive/data
chmod -R g+rwx /media/usb-drive/data
```

Aditionally if this should be a permanent setup I would suggest mounting you USB drive on a persistant path on you RasPi.
For further informations look [here](https://www.raspberrypi.org/documentation/configuration/external-storage.md) and/or [here](https://wiki.archlinux.org/index.php/fstab)

**Comment by carryonrewardless** [comment]
I am getting this error but cannot see where my problem is having followed the above.

Hardware: Raspberry Pi 2 1GB booting OS from 16GB microSD with USB connected 2TB ext4 drive
OS: Raspbian GNU/Linux 10 \n \l

Data drive: 2TB SSD connected to USB 2.0
My docker-compose.yml is:

```
version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      - /mnt/ncdata:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

volumes:
  db:
  nextcloud:

```
where db.env contains:
```

POSTGRES_PASSWORD=password
POSTGRES_DB=nextcloud
POSTGRES_USER=nextcloud
NEXTCLOUD_DATA_DIR=/mnt/ncdata
```

Permissions look like this:

```
sudo ls -la /mnt/ncdata/
total 28
drwxrwx--- 2 www-data www-data  4096 Apr 24 22:35 .
drwxr-xr-x 3 root     root      4096 Apr 21 22:12 ..
-rw-r--r-- 1 www-data www-data   542 Apr 24 22:35 .htaccess
-rw-r--r-- 1 www-data www-data     0 Apr 24 22:35 index.html
-rw-r----- 1 www-data www-data 12698 Apr 24 22:35 nextcloud.log
-rw-rwxr-- 1 www-data www-data     0 Apr 24 21:09 test1
```
and the line in /etc/fstab is
PARTUUID=ac85cc5c-01  /mnt/ncdata ext4  defaults,auto,users,rw,nofail 0  0

Thanks for any tips here.
