### ISSUE TITLE
POSTGRES_* are ignored when NEXTCLOUD_ADMIN_* are omitted.

### ISSUE THREAD

**Issue by raldone01** [nextcloud/docker#1228]
# What is happening?

The postgresql database configuration values are ignored.

# What should happen?

The postgresql database configuration should be used.

# Setup

Docu:
```
If you set any values, they will not be asked in the install page on first run. With a complete configuration by using all variables for your database type, you can additionally configure your Nextcloud instance by setting admin user and password (only works if you set both):
    NEXTCLOUD_ADMIN_USER Name of the Nextcloud admin user.
    NEXTCLOUD_ADMIN_PASSWORD Password for the Nextcloud admin user.
```
Example docker-compose: (I omitted my reverse proxy)
```
version: '3.2'
services:
    nextcloud-db:
        image: postgres
        restart: unless-stopped
        volumes:
         - ${CONTAINERP}/nextcloud-db:/var/lib/postgresql/data
        environment:
         - POSTGRES_DB_FILE=/run/secrets/postgres_db
         - POSTGRES_USER_FILE=/run/secrets/postgres_user
         - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        secrets:
         - postgres_db
         - postgres_password
         - postgres_user
        networks:
         - back-nextcloud
    nextcloud:
        restart: unless-stopped
        image: nextcloud
        volumes:
         - ${CONTAINERP}/nextcloud/nextcloud:/var/www/html
         - ${CONTAINERP}/nextcloud/apps:/var/www/html/custom_apps
         - ${CONTAINERP}/nextcloud/config:/var/www/html/config
         - ${CONTAINERP}/nextcloud/data:/var/www/html/data
        environment:
          - POSTGRES_HOST=nextcloud-db
          - POSTGRES_DB_FILE=/run/secrets/postgres_db
          - POSTGRES_USER_FILE=/run/secrets/postgres_user
          - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
#          - NEXTCLOUD_ADMIN_PASSWORD=pwd # REQUIRED?
#          - NEXTCLOUD_ADMIN_USER=admin
        secrets:
         - postgres_db
         - postgres_password
         - postgres_user
        ports:
         - 8080:80
        networks:
         - front
         - back-nextcloud
        depends_on:
         - nextcloud-db
networks:
    front:
    back-nextcloud:
secrets:
  postgres_db:
    file: ./secrets/postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: ./secrets/postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: ./secrets/postgres_user.txt # put postgresql username to this file
```
[Repository](https://github.com/raldone01/nextcloud-docker-compose) to reproduce.
