### ISSUE TITLE
No redirect after log in

### ISSUE THREAD

**Issue by rmoreRojoli** [nextcloud/docker#1234]
After filling in the login details and pushing log in, it will get stuck in a "logging in" state, network tab shows a cancelled request to /login
On the server side the nextcloud container reports a POST request and nothing else:
`nextcloud       | 172.20.0.1 - - [02/Sep/2020:17:31:41 +0000] "POST /login HTTP/1.1" 303 1130 "-" "browser agent list"`

After a page refresh on the /login will take successfully to the logged in page of /apps/files/

The container is running behind Traefik v2 reverse proxy

Relevant docker compose section:
```
  pg-nextcloud:
    image: postgres
    container_name: pg-nextcloud
    restart: always
    networks:
      - nextcloud
    environment:
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_USER=xxx
      - POSTGRES_DB=nextcloud
  nextcloud:
    image: nextcloud:19
    container_name: nextcloud
    restart: always
    depends_on:
      - pg-nextcloud
    networks:
      - nextcloud
      - traefik
    environment:
      POSTGRES_DB: 'nextcloud'
      POSTGRES_USER: 'xxx'
      POSTGRES_PASSWORD: 'xxx'
      POSTGRES_HOST: 'pg-nextcloud'
      NEXTCLOUD_ADMIN_USER: 'xxx'
      NEXTCLOUD_ADMIN_PASSWORD: 'xxx'
      NEXTCLOUD_TRUSTED_DOMAINS: 'example.com'
      TRUSTED_PROXIES: '172.0.0.0/8'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`example.com`)"
      - "traefik.http.routers.nextcloud.middlewares=sec-header@file,nextcloud-redirectregex"
      - "traefik.http.routers.nextcloud.tls.certResolver=letsencrypt"
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.permanent=true"
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.replacement=https://$${1}/remote.php/dav/"
```

Relevant traefik dynamic config:
```
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
    sec-header:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        sslRedirect: true
        sslForceHost: true
        customResponseHeaders:
          Strict-Transport-Security: "max-age=63072000"

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

OS: Centos 8
latest docker and docker compose
