### ISSUE TITLE
Fresh installation of NC v20 image has server error on setup

### ISSUE THREAD

**Issue by MaxVRAM** [nextcloud/docker#1258]
I'm keen to try out NC20 and I'm reusing the same docker-compose, but just changed from `latest` image to `nextcloud:20-rc`.

When I spool it up and provide an admin user/password, the next page is the blue "Internal Server Error" message:

> The server was unable to complete your request.
> If this happens again, please send the technical details below to the server administrator.
> More details can be found in the server log.

I can't make any sense of the server log (too bloated to paste here, so using Pastebin):
[Pastbin Link](https://pastebin.com/sCyNZWqV)

```
version: '2'

volumes:
  db:

services:
  db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    image: nextcloud:20-rc
    ports:
      - 7006:80
    volumes:
      - /opt/cloud:/var/www/html
    restart: unless-stopped
    environment:
      - NEXTCOULD_TRUSTED_DOMAINS=localhost 192.168.1.22
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
```
