### ISSUE TITLE
New instalation docker-compose dont work - back to login page without warning/error

### ISSUE THREAD

**Issue by piotr-sikora-v** [nextcloud/docker#1291]
Hello,

I have try to reinstall my previous instance with new config... I removed all nextcloud data, all databases, cleared redis.
Installation process end with timout (so I thinks is normal), but later, I can't log in.
on debug I only see this:
```
{"reqId":"YjpqTiHmcHC23JRxr66i","level":0,"time":"2020-10-27T19:31:29+00:00","remoteAddr":"10.0.0.2","user":"--","app":"files_sharing","method":"POST","url":"/login","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","version":"20.0.1.1"}
{"reqId":"kwRg9QWIWhfN3sp7eKLo","level":0,"time":"2020-10-27T19:31:29+00:00","remoteAddr":"10.0.0.2","user":"--","app":"files_sharing","method":"GET","url":"/apps/dashboard/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","version":"20.0.1.1"}
{"reqId":"kwRg9QWIWhfN3sp7eKLo","level":0,"time":"2020-10-27T19:31:29+00:00","remoteAddr":"10.0.0.2","user":"--","app":"core","method":"GET","url":"/apps/dashboard/","message":{"Exception":"OC\\AppFramework\\Middleware\\Security\\Exceptions\\NotLoggedInException","Message":"Current user is not logged in","Code":401,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":98,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware","type":"->","args":[{"__class__":"OCA\\Dashboard\\Controller\\DashboardController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":98,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[{"__class__":"OCA\\Dashboard\\Controller\\DashboardController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Dashboard\\Controller\\DashboardController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Dashboard\\Controller\\DashboardController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"dashboard.dashboard.index"}]},{"file":"/var/www/html/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/dashboard/"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php","Line":143,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","version":"20.0.1.1"}
{"reqId":"ps2VXmjH1wTqxojU0v8a","level":0,"time":"2020-10-27T19:31:29+00:00","remoteAddr":"10.0.0.2","user":"--","app":"files_sharing","method":"GET","url":"/login?redirect_url=/apps/dashboard/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","version":"20.0.1.1"}
```

On web browser debug I see that they try to set cookis, and delete it.
```
set-cookie: ocz1umvvhu3i=d1f5422cdf1d9cc8567232bbc534a7a5; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocz1umvvhu3i=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
```

I checked truested domains,overrieds, everything... and still same problem :+1: 

I use nextcloud-php-alpine + traefik

my config.php
```<?php
$CONFIG = array (
'loglevel' => 0,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379,
  ),
  'instanceid' => 'ocz1umvvhu3i',
  'passwordsalt' => 'zzzzzz',
  'secret' => dsadasdasd',
  'trusted_domains' => 
  array (
    0 => 'chmura.lhub.pl',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '20.0.1.1',
  'overwrite.cli.url' => 'https://nextcloud.something.pl,
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'zzzzzz',
  'installed' => true,
 'trusted_proxies'   => ['10.0.0.2'],
  'overwritehost'     => 'nextcloud.something.pl',
  'overwriteprotocol' => 'https',
);
```

my dokcer-compose:
```
version: '3.3'
services:
  app-php:
    image: nextcloud:fpm-alpine
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_HOST: db
      MYSQL_PASSWORD: xx
      MYSQL_USER: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.something.pl
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: 'false'
      TZ: Europe/Warsaw
    volumes:
     - nextcloud:/var/www/html
     - /storage0/nextcloud_data/:/var/www/html/data
    networks:
     - default
    logging:
      driver: json-file
    configs:
     - source: nextcloud-php-fpm.conf
       target: /usr/local/etc/php-fpm.d/www.conf
  db:
    image: mysql:8.0
    command:
     - --transaction-isolation=READ-COMMITTED
     - --binlog-format=ROW
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_PASSWORD: xx
      MYSQL_ROOT_PASSWORD: zz
      MYSQL_USER: nextcloud
    volumes:
     - db:/var/lib/mysql
    networks:
     - default
    logging:
      driver: json-file
  redis:
    image: redis:latest
    networks:
     - default
    logging:
      driver: json-file
    volumes:
      - redis-storage:/data
  web:
    image: nginx:latest
    labels:
      traefik.enable: 'true'
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.something.pl`)
      traefik.http.routers.nextcloud.tls.certresolver: le
    volumes:
     - nextcloud:/var/www/html:ro
     - /var/lib/docker/app-files/nginx-nextcloud.conf:/etc/nginx/nginx.conf:ro
    configs:
     - source: nextcloud-nginx.conf
       target: /etc/nginx/nginx2.conf
    networks:
     - frontend
     - default
    logging:
      driver: json-file
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
     - default
    ports:
     - 8088:80
    environment:
     PMA_HOST: db
networks:
  default:
    driver: overlay
  frontend:
    external: true
volumes:
  db:
    driver: local
  nextcloud:
    driver: local
  redis-storage:
    external:
      name: docker/volumes/nextcloud-redis

configs:
  nextcloud-nginx.conf:
    external: true
  nextcloud-php-fpm.conf:
    external: true
```

nextcloud-nginx.conf
```
worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  172.16.0.0/12;
    set_real_ip_from  192.168.0.0/16;
    real_ip_header    X-Real-IP;

    #gzip  on;

    upstream php-handler {
        server app-php:9000;
    }

    server {
        listen 80;

        # Add headers to serve security related headers
        # Before enabling Strict-Transport-Security headers please read into this
        # topic first.
        #add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;" always;
        #
        # WARNING: Only add the preload option once you read about
        # the consequences in https://hstspreload.org/. This option
        # will add the domain to a hardcoded list that is shipped
        # in all major browsers and getting removed from this list
        # could take several months.
        add_header Referrer-Policy "no-referrer" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-Download-Options "noopen" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Permitted-Cross-Domain-Policies "none" always;
        add_header X-Robots-Tag "none" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # Remove X-Powered-By, which is an information leak
        fastcgi_hide_header X-Powered-By;

        # Path to the root of your installation
        root /var/www/html;

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

        # The following 2 rules are only needed for the user_webfinger app.
        # Uncomment it if you're planning to use this app.
        #rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        #rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

        # The following rule is only needed for the Social app.
        # Uncomment it if you're planning to use this app.
        #rewrite ^/.well-known/webfinger /public.php?service=webfinger last;

        location = /.well-known/carddav {
            return 301 $scheme://$host:$server_port/remote.php/dav;
        }

        location = /.well-known/caldav {
            return 301 $scheme://$host:$server_port/remote.php/dav;
        }

        # set max upload size
        client_max_body_size 10G;
        fastcgi_buffers 64 4K;


        # Enable gzip but do not remove ETag headers
        gzip on;
        gzip_vary on;
        gzip_comp_level 4;
        gzip_min_length 256;
        gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
        gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

        # Uncomment if your server is build with the ngx_pagespeed module
        # This module is currently not supported.
        #pagespeed off;

        location / {
            rewrite ^ /index.php;
        }

        location ~ ^\/(?:build|tests|config|lib|3rdparty|templates|data)\/ {
            deny all;
        }
        location ~ ^\/(?:\.|autotest|occ|issue|indie|db_|console) {
            deny all;
        }

        location ~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+)\.php(?:$|\/) {
            fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
            set $path_info $fastcgi_path_info;
            try_files $fastcgi_script_name =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $path_info;
            # fastcgi_param HTTPS on;

            # Avoid sending the security headers twice
            fastcgi_param modHeadersAvailable true;

            # Enable pretty urls
            fastcgi_param front_controller_active true;
            fastcgi_pass php-handler;
            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
        }

        location ~ ^\/(?:updater|oc[ms]-provider)(?:$|\/) {
            try_files $uri/ =404;
            index index.php;
        }
        # Adding the cache control header for js, css and map files
        # Make sure it is BELOW the PHP block
        location ~ \.(?:css|js|woff2?|svg|gif|map)$ {
            try_files $uri /index.php$request_uri;
            add_header Cache-Control "public, max-age=15778463";
            # Add headers to serve security related headers (It is intended to
            # have those duplicated to the ones above)
            # Before enabling Strict-Transport-Security headers please read into
            # this topic first.
            #add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;" always;
            #
            # WARNING: Only add the preload option once you read about
            # the consequences in https://hstspreload.org/. This option
            # will add the domain to a hardcoded list that is shipped
            # in all major browsers and getting removed from this list
            # could take several months.
            add_header Referrer-Policy "no-referrer" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-Download-Options "noopen" always;
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Permitted-Cross-Domain-Policies "none" always;
            add_header X-Robots-Tag "none" always;
            add_header X-XSS-Protection "1; mode=block" always;

            # Optional: Don't log access to assets
            access_log off;
        }

        location ~ \.(?:png|html|ttf|ico|jpg|jpeg|bcmap|mp4|webm|json)$ {
            try_files $uri /index.php$request_uri;
            # Optional: Don't log access to other assets
            access_log off;
        }
    }
}
```

Any suggestions ?
