### ISSUE TITLE
Crontab not included in nextcloud:latest

### ISSUE THREAD

**Issue by y2klol** [nextcloud/docker#1293]
Freshly installing the latest nextcloud from dockerhub results in an install that does not include crontab. 
Cron can be manually activated with` docker exec --user www-data nextcloud php -f cron.php` however the docker container does not contain crontab (and hence `crontab -e` doesn't work) so nextcloud will not automatically run the cron. 
 
```
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "9089:80"
      - "9088:443"
    volumes:
      - ${PWD}/config:/config/www/nextcloud/config
      - ${PWD}/data:/config/www/nextcloud/data
      - ${PWD}/custom_apps:/config/www/nextcloud/custom_apps/
      - ${PWD}/themes:/config/www/nextcloud/themes
      - /mnt/:/mnt/
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - REDIS_HOST=nextcloud_redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=123
    restart: always
    networks:
      - t2_proxy
    labels:
      traefik.enable: true
      traefik.docker.network: t2_proxy
      traefik.http.routers.nc-rtr.entrypoints: web, websecure
      traefik.http.routers.nc-rtr.rule: Host(`cube.${DOMAINNAME}`)
      traefik.http.routers.nc-rtr.tls: "true"
      traefik.http.routers.nc-rtr.tls.certresolver: le
#      traefik.http.routers.nc-rtr.service: nc-svc
      traefik.http.services.nc-rtr.loadbalancer.server.port: "80"

```
