### ISSUE TITLE
Stuck upgrading from 20.0.0.9 to 20.0.1.1

### ISSUE THREAD

**Issue by 4s3ti** [nextcloud/docker#1296]
**What is expected to happen:** 

Nextcloud to start with Version 20.0.1.1 after starting with :latest image

**What happens?** 

Next cloud gets stuck and all can see in the logs is: 

```
cloud_nextcloud.1.puney2fq53f6@redacted.hostname.domain    | Initializing nextcloud 20.0.1.1 ...
cloud_nextcloud.1.puney2fq53f6@redacted.hostname.domain    | Upgrading nextcloud from 20.0.0.9 ...
```

Trying to access next-cloud  returns Bad Gateway error

Reverting back image tag `nextcloud:20.0.0` and it started working normally again. 

**System Details:**

Running on Docker swarm behind traefik reverse proxy

compose file: 

``` 
version: '3.3'

services:
  nextcloudb:
    image: mariadb
    networks:
      - private
    volumes:
      - /srv/data/cloud/nextcloudb:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.labels.type == private
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=

  nextcloud:
    image: nextcloud
    networks:
      - private
      - dockadmin_rp
    volumes:
       - /srv/data/cloud/nextcloudata:/var/www/html
    depends_on:
      - nextcloudb
    environment:
      - VIRTUAL_HOST=cloud.domain.foo
    deploy:
      placement:
        constraints:
          - node.labels.type == private
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.docker.network: "dockadmin_rp"
        traefik.http.routers.cloud.service: "cloud"
        traefik.http.routers.cloud.tls: "true"
        traefik.http.routers.cloud.tls.certResolver: "default"
        traefik.http.routers.cloud.middlewares: "defaultsecheaders@file, redirects"
        traefik.http.routers.cloud.rule: "Host(`cloud.domain.foo`)"
        traefik.http.services.cloud.loadbalancer.server.port: 80
        traefik.http.middlewares.redirects.redirectregex.permanent: "true"
        traefik.http.middlewares.redirects.redirectregex.regex: "^https://(.*)/.well-known/(card|cal)dav"
        traefik.http.middlewares.redirects.redirectregex.replacement: "https://$${1}/remote.php/dav/"



networks:
  dockadmin_rp:
    external: true
  private:
```

**Config file**
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxxx',
  'secret' => 'xxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'cloud.domain.foo',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '20.0.0.9',
  'overwrite.cli.url' => 'https://cloud.domain.foo',
  'dbname' => 'nextcloudb',
  'dbhost' => 'cloud_nextcloudb',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'redacted dbuser',
  'dbpassword' => 'redacted db password',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'domain.foo',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.domain.foo',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'someguy@mail.domain.foo',
  'mail_smtppassword' => 'redacted password',
  'has_rebuilt_cache' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'trusted_proxies' => 
  array (
    0 => '10.0.1.0/24',
  ),
  'overwriteprotocol' => 'https',
  'encryption.legacy_format_support' => true,
  'encryption.key_storage_migrated' => false,
);
```

Please let me know if there is anything else i can provide to help out.
