### ISSUE TITLE
Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by kromsam** [nextcloud/docker#1308]
I run Nextcloud Docker on an
Device: RockPro64
OS: openmediavault version 4.1.36-1
Kernel: Linux 4.4.190-1233-rockchip-ayufan-gd3f1be0ed310

After successfully installing and running Nextcloud in Docker for sometime. I suddenly got this error message when going to the Nextcloud instance:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

The Synchronization Client has stopped working as well.

I looked up the relevant log file. (Inside the container: /data/nextcloud.log. The last 100 entries were all a variation of this error message:
```
{"reqId":"[REDACTED]","level":3,"time":"2020-11-17T17:24:22+00:00","remoteAddr":"[REDACTED]","user":"--","app":"core","method":"GET","url":"/index.php/204","message":{"Exception":"Doctrine\\DBAL\\DBALException","Message":"Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused","Code":0,"Trace":[{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1449,"function":"connect","class":"OC\\DB\\Connection","type":"->","args":[]},{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":892,"function":"getWrappedConnection","class":"Doctrine\\DBAL\\Connection","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/DB/Connection.php","line":194,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT * FROM `oc_appconfig`",[],[],null]},{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT * FROM `oc_appconfig`",[],[]]},{"file":"/config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/AppConfig.php","line":332,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/AppConfig.php","line":110,"function":"loadConfigValues","class":"OC\\AppConfig","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/AppConfig.php","line":288,"function":"getApps","class":"OC\\AppConfig","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/legacy/OC_App.php","line":949,"function":"getValues","class":"OC\\AppConfig","type":"->","args":[false,"installed_version"]},{"file":"/config/www/nextcloud/lib/private/TemplateLayout.php","line":185,"function":"getAppVersions","class":"OC_App","type":"::","args":[]},{"file":"/config/www/nextcloud/lib/private/legacy/OC_Template.php","line":183,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["error",""]},{"file":"/config/www/nextcloud/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/legacy/OC_Template.php","line":332,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"/config/www/nextcloud/index.php","line":63,"function":"printExceptionErrorPage","class":"OC_Template","type":"::","args":[{"__class__":"Doctrine\\DBAL\\DBALException"},500]}],"File":"/config/www/nextcloud/lib/private/DB/Connection.php","Line":67,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.0.9"}
```

Of which the most important part probably is this.
```
Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
```

These are the relevant parts of the docker-compose file I use.
```
version: '3'
services:

# Let's Encrypt
  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/swag
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${TLD}
      - SUBDOMAINS=${SUBS}
      - VALIDATION=${VAL}
      - EMAIL=${MAILADRES}
    volumes:
      - ${APPDATA}/Letsencrypt:/config
    networks:
      - nextcloud_net
    ports:
      - 446:443
      - 82:80
    cap_add:
      - NET_ADMIN

# Nextcloud
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/Nextcloud:/config
      - ${NEXTCLOUD}:/data
      - ${DOWNLOADS}:/extern/downloads
      - ${MEDIA}:/extern/mediabieb
      - ${PERSOONLIJK}:/extern/persoonlijk
      - ${UPLOADMAP}:/extern/uploadmap
      - ${WATCHED}:/extern/watched
    depends_on:
      - mariadb
    networks:
      - nextcloud_net
  mariadb:
    container_name: nextclouddb
    image: linuxserver/mariadb
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${NCDBPASS}
    volumes:
      - ${APPDATA}/Nextclouddb:/config
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge
```

Important to note is that the Nextcloud instance _has been working_. This happened before. Then I did an entire reinstallation of my Nextcloud (I also deleted the container volumes). Because just removing the containers is not working.

But I don't want to do this again. Now I want to see what the actual problem is and hopefully fix it. Any ideas?

I also checked the MariaDB container. There were some odd going thing going on in the logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing...
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
201117 18:21:24 mysqld_safe Logging to syslog.
201117 18:21:24 mysqld_safe Starting mysqld daemon with databases from /config/databases
201117 18:21:31 mysqld_safe Logging to syslog.
201117 18:21:32 mysqld_safe Starting mysqld daemon with databases from /config/databases
201117 18:21:40 mysqld_safe Logging to syslog.
201117 18:21:40 mysqld_safe Starting mysqld daemon with databases from /config/databases
201117 18:21:51 mysqld_safe Logging to syslog.
201117 18:21:51 mysqld_safe Starting mysqld daemon with databases from /config/databases
201117 18:21:58 mysqld_safe Logging to syslog.
201117 18:21:58 mysqld_safe Starting mysqld daemon with databases from /config/databases
```

And this goes on and on. So maybe there is an issue with the MariaDB container? How would I see what's wrong here and fix it?
