### ISSUE TITLE
Use parameter to control UID|GID of www-data

### ISSUE THREAD

**Issue by Gofinge** [nextcloud/docker#1310]
I changed the UID and GID of www-data through

```bash
$ docker exec -it nextcloud_server usermod -u 1000 www-data
$ docker exec -it nextcloud_server groupmod -g 1000 www-data
$ docker restart nextcloud_server
```

But it is inconvenient to do that every time when I upgrade next-cloud.

I am new to docker, is it possible to make it controllable through docker_compose.yml?

**Comment by Oberfeldwedler** [comment]
It worked until i updated from version 19 to 20.

This is my docker-compose.yaml file:
```
services:
  nextcloud-mariadb:
    image: mariadb:10.5.6-focal
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes: *nextcloud-mariadb
    user: ${UID}:${GID}
    #environment:
    #  - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - db.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  nextcloud-fpm:
    networks:
      - default
    image: nextcloud:20-fpm-alpine
    restart: unless-stopped
    volumes: *nextcloud
    user: ${UID}:${GID}
    environment:
      - MYSQL_HOST=nextcloud-mariadb
    env_file:
      - db.env
    depends_on:
      - nextcloud-mariadb
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nextcloud-web:
    build: ./web
    restart: unless-stopped
    networks:
      - web
      - default
    volumes: *nextcloud-nginx
    user: ${UID}:${GID}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    expose:
      - 80
    depends_on:
      - nextcloud-fpm
```
