### ISSUE TITLE
Can't get this to work on RancherOS

### ISSUE THREAD

**Issue by Pumpapa** [nextcloud/docker#133]
I'm trying to use this docker-compose.yml in RancherOS, but it fails. One issue is volumes_from. I've tried to solve this by just listing the volumes, but the letsencrypt-companion service fails to start with an error
**_Error: can't get nginx-proxy container id !
Check that you use the --volumes-from option to mount volumes from the nginx-proxy._**
I've added labels, but to no avail

docker-compose snippet:
```
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
      - "com.github.jrcs.nginx_letsencrypt_companion.is_proxy=true"
    ports:
      - "8280:80"
      - "443:443"
    volumes:
      - /volumes/nextcloud/data/certs:/etc/nginx/certs:ro
      - /volumes/nextcloud/data/proxy/etcNginxVhostD:/etc/nginx/vhost.d
      - /volumes/nextcloud/data/proxy/usrShareNginxHtml:/usr/share/nginx/html
      - /volumes/nextcloud/data/proxy/init/nginxConfD:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    network_mode: "bridge"
    restart: always

  letsencrypt-companion:
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes:
      - /volumes/nextcloud/data/certs:/etc/nginx/certs:rw
      - /volumes/nextcloud/data/proxy/etcNginxVhostD:/etc/nginx/vhost.d
      - /volumes/nextcloud/data/proxy/init/nginxConfD:/etc/nginx/conf.d
      - /volumes/nextcloud/data/proxy/usrShareNginxHtml:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: "bridge"
    restart: always
```
