### ISSUE TITLE
Dockercompose examples for Let's Encrypt probably need updating

### ISSUE THREAD

**Issue by PathToLife** [nextcloud/docker#1362]
What:
`jrcs/letsencrypt-nginx-proxy-companion:latest`
Has changed, it now needs a new persistent volume
`./letsencrypt-acme:/etc/acme.sh # NEW CHANGE`

https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/730#issuecomment-748936276

> The single most important change is that the container now requires a volume mounted to /etc/acme.sh in order to persist ACME account keys and SSL certificates. The last tagged version that uses simp_le is v1.13.1.

Effects of not applying this new change:
- letsencrypt-nginx-proxy-companion will recreate new certificates and accounts on each `docker-compose down` -> `... up` cycle
- this will case a rate limit error, after 5 restarts (within a week); next-cloud will not be accessible on the 6th restart (self signed cert error)
- also lets encrypt account creation rate limit will kick in while you try to figure out what's going on 🤦‍♂️😂

My config using bind mounts with new volume applied:
`./letsencrypt-acme:/etc/acme.sh # NEW CHANGE`

```  
letsencrypt-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
            - ./letsencrypt-acme:/etc/acme.sh # NEW CHANGE
            - ./letsencrypt-certs:/etc/nginx/certs:rw
            - ./vhost.d:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - proxy-tier
        depends_on:
            - proxy
```

After i'm no longer rate limited and can confirm my config, I'll make a PR to https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml

Not confident with other docker-compose files (I'm new to them) but perhaps @SnowMB or @tilosp? :)
