### ISSUE TITLE
Nextcloud 20, error 504 gateway timeout on first launch with docker-compose and Traefik

### ISSUE THREAD

**Issue by Darktortue** [nextcloud/docker#1374]
Nextcloud version : Latest (20)
Operating system and version : Raspbian

The issue you are facing:
I can’t access my nextcloud web interface at all.

Is this the first time you’ve seen this error? (Y/N): Y

Steps to replicate it:

1) Configure docker-compose file
2) Launch your container
3) Access nextcloud’s web interface with the good URL

docker-compose.yml :

```
version: "3.7"
services:
  database:
    image: ghcr.io/linuxserver/mariadb
    restart: unless-stopped
    environment:
      - MYSQL_USER=user
      - MYSQL_DATABASE=name
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=root_password
    networks:
      - lan
    volumes:
      - db:/var/lib/mysql

  nextcloud:
    depends_on:
      - database
    image: nextcloud:latest
    restart: unless-stopped
    environment:
      NEXTCLOUD_ADMIN_PASSWORD: password
      NEXTCLOUD_ADMIN_USER: user
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.domain.com
    networks:
      - lan
      - web
    volumes:
      - nextcloud:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.domain.com`)"
      - "traefik.http.routers.nextcloud.entrypoints=web-secure"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls.certResolver=primary"
      - "traefik.http.routers.nextcloud.middlewares=trauth"

volumes:
  db:
  nextcloud:

networks:
  web:
    external: true

  lan:
```
The output of docker-compose logs :

https://pastebin.com/vZi3NMTa

I don’t have any error in my docker-compose logs of traefik and I really don’t think the problem is from traefik because it sees and handle without any problem my nextcloud container.

I started to have this error after removing this from my docker-compose.yml file :

```
command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
```

It’s suggested to use this line here : https://hub.docker.com/_/nextcloud but when I did, I had access to the login page, the setup page where you choose the database etc… and then infinite loading and crash. So I removed it and now I don’t have access at all.

Hope someone can help me, thanks :slight_smile:

EDIT : btw I have 4 others services running the same way without any problem so this is definitely NOT a docker or traefik issue.
