### ISSUE TITLE
nextcloud docker-compose with self-signed SSL?

### ISSUE THREAD

**Issue by biocyberman** [nextcloud/docker#141]
I have docker-compose starts up fine with `http` protocol. But I can't get letsencrypt part to run correctly because I am running inside a local network. However I still want to try the SSL setup so I can use something like this: `https://myhost.localdomain`. The current `docker-compose.yml` is too complex for me to figure out what to change. So some help to customize it is much appreciated.

**Comment by biocyberman** [comment]
Ok I figured it out. 
```
cd proxy/certs
openssl req -x509 -newkey rsa:4096 -keyout myhost.localdomain.pem -out myhost.localdomain.crt -days 365
```
After this, start docker-compose normally.

**Comment by SnowMB** [comment]
Closed for now, feel free to reopen if there are any further questions.

**Comment by jhk217626** [comment]
Any way to go into more detail with this? Where is proxy/certs located? Trying to get a self-signed SSL cert working with my docker-compose file.

**Comment by olinic** [comment]
Thank you all here for helping me figure this out!

Here is a sample docker_compose.yaml that works with the self-signed certificate. For newbies, you need some of the other files from the examples folder (db.env, proxy folder with files inside it).

The primary difference is setting the VIRTUAL_HOST and matching it to the SSL env variables.

```
version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

# self signed
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=example.com
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/example.com.key
      - SSL_CSR=/certs/example.com.csr
      - SSL_CERT=/certs/example.com.crt
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
```
