### ISSUE TITLE
Nextcloud hangs when starting with docker-compose

### ISSUE THREAD

**Issue by wutzi15** [nextcloud/docker#1410]
When I try to run a simple nextcloud instance with persistent data it hangs, when using docker-compose. 

When I start using ```docker run -d -v data:/var/www/html -p 9090:80 nextcloud``` it starts just fine. When I use this docker-compose.yml it hangs: 

```yml
version: '3.7'

services:
  nexcloud:
    image: nextcloud
    volumes:
      - ./data:/var/www/html
    restart: unless-stopped
    ports:
      - 9090:80
```

It just stays at: 
```
$: docker-compose up
Creating network "nextcloud_default" with the default driver
Creating nextcloud_nexcloud_1 ... done
Attaching to nextcloud_nexcloud_1
nexcloud_1  | Initializing nextcloud 20.0.7.1 ...
```

I run both commands in the same directory, the one containing the data directory for storage
