### ISSUE TITLE
Nextcloud Slow until I disable collabra

### ISSUE THREAD

**Issue by leier69** [nextcloud/docker#1434]
Nextcloud is painfully slow until I disable collabra. Why is this? and please reffer me to the correct issues If i missed it before opening this one.

**Comment by leier69** [comment]
Yea I can also see that in the docker logs this shows up when trying to open collabra.
```
127.0.0.1 - - [03/Mar/2021:23:14:47 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.15 (internal dummy connection)"
127.0.0.1 - - [03/Mar/2021:23:14:48 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.15 (internal dummy connection)"
127.0.0.1 - - [03/Mar/2021:23:14:49 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.15 (internal dummy connection)"
127.0.0.1 - - [03/Mar/2021:23:14:50 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.15 (internal dummy connection)"
127.0.0.1 - - [03/Mar/2021:23:14:51 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.15 (internal dummy connection)"
127.0.0.1 - - [03/Mar/2021:23:14:52 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.15 (internal dummy connection)"
```

**Comment by leier69** [comment]
I also tried to run nextcloud in the host network. This seems to solve some people's issues, but not mine.

This is quite frustrating as nextcloud is ALMOST perfect. aww man

**Comment by WhiteBahamut** [comment]
Which version of Collabora you are running? Collabora Online - Built-in CODE Server? This destroyed performance for me as well. Running a CODE server in own container solved what ever slowed the connection down for me (though you need x86/x64 container run-time).

**Comment by leier69** [comment]
@WhiteBahamut How did you do that? Could you post ur compose?

**Comment by WhiteBahamut** [comment]
Only have k8s deployment file :) but I get most info from https://www.collaboraoffice.com/code/docker/ 
Once your CODE server is running, you need do configure it in the Collabora app in NC.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora-code
  namespace: YOURNAMESPACE
spec:
  selector:
    matchLabels:
      app: collabora-code
  template:
    metadata:
      labels:
        app: collabora-code
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - "amd64"
      containers:
      - name: collabora-code
        image: collabora/code:6.4.6.2
        imagePullPolicy: IfNotPresent
        env:
        - name: domain
          value: "your.domain"  
        - name: username
          value: "admin" 
        - name: password
          value: "secert123"        
        ports:
        - containerPort: 9980
          protocol: TCP
        resources:
          requests:
            memory: "750Mi"
            cpu: "1000m"
          limits:
            memory: "2000Mi"
            cpu: "1750m"
        volumeMounts:
        - name: config
          mountPath: /etc/loolwsd
      volumes:
      - configMap:
          name: configs
          items:
            - key: loolwsd.xml
              path: loolwsd.xml              
        name: config
```
