### ISSUE TITLE
Can't login Mobile App and Windows App

### ISSUE THREAD

**Issue by starsareintherose** [nextcloud/docker#1436]
visit token error
error transferring my_domain server replied bad request
My docker-compose.yml
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 3380:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
```
And I can't use MySQL so I change the database. SQLite, I think.
Only one change is to add my web to the trusted list.
