### ISSUE TITLE
Database not found after moving docker volume from HDD to SSD

### ISSUE THREAD

**Issue by cgi1** [nextcloud/docker#1437]
So my initial setup held the database on Raid1 - which was only for testing purposes. Now I wanted to move it to an SSD storage and therefore moved the volume to SSD in the docker-compose:

```
version: '2'

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/raid1/ncloud/mysql' ###### THIS LINE
  nextcloud:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/raid1/ncloud/nextcloud'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=seriouspassword
      - MYSQL_PASSWORD=seriouspassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8091:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=seriouspassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db                        
```

So in order to do this, I moved all files from `device: '/mnt/raid1/ncloud/mysql'` to `device: '/opt/ncloud/mysql'` and tried to restart the docker container. However, it came back with an error:

```
ERROR: Configuration for volume db specifies "device" driver_opt /opt/ncloud/mysql, but a volume with the same name uses a different "device" driver_opt (/mnt/raid1/ncloud/mysql). If you wish to use the new configuration, please remove the existing volume "ncloud_db" first:
$ docker volume rm ncloud_db
```

So I did that and restarted, but now the database is not getting found at all. Can it be recovered somehow?

```
db_1   | 2021-03-07 19:24:31+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.9+maria~focal started.
db_1   | 2021-03-07 19:24:32+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1   | 2021-03-07 19:24:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.9+maria~focal started.
db_1   | 2021-03-07 19:24:32 0 [Note] mysqld (mysqld 10.5.9-MariaDB-1:10.5.9+maria~focal) starting as process 1 ...
db_1   | 2021-03-07 19:24:32 0 [Warning] You need to use --log-bin to make --binlog-format work.
db_1   | 2021-03-07 19:24:32 0 [Note] InnoDB: Uses event mutexes
db_1   | 2021-03-07 19:24:32 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1   | 2021-03-07 19:24:32 0 [Note] InnoDB: Number of pools: 1
db_1   | 2021-03-07 19:24:32 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
db_1   | 2021-03-07 19:24:32 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_1   | 2021-03-07 19:24:32 0 [Note] InnoDB: Using Linux native AIO
db_1   | 2021-03-07 19:24:32 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
db_1   | 2021-03-07 19:24:32 0 [Note] InnoDB: Completed initialization of buffer pool
db_1   | 2021-03-07 19:24:32 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1   | 2021-03-07 19:24:34 0 [Note] InnoDB: 128 rollback segments are active.
db_1   | 2021-03-07 19:24:34 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1   | 2021-03-07 19:24:34 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1   | 2021-03-07 19:24:34 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1   | 2021-03-07 19:24:34 0 [Note] InnoDB: 10.5.9 started; log sequence number 35268; transaction id 8
db_1   | 2021-03-07 19:24:34 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1   | 2021-03-07 19:24:34 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1   | 2021-03-07 19:24:34 0 [Note] InnoDB: Buffer pool(s) load completed at 210307 19:24:34
db_1   | 2021-03-07 19:24:34 0 [ERROR] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some plugins may be not loaded
db_1   | 2021-03-07 19:24:34 0 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
db_1   | 2021-03-07 19:24:34 0 [Note] Server socket created on IP: '::'.
db_1   | 2021-03-07 19:24:34 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.db' doesn't exist
db_1   | 2021-03-07 19:24:34 0 [ERROR] Aborting
```
