### ISSUE TITLE
Example docker-compose not working on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by skepticatgit** [nextcloud/docker#144]
Hi guys, thank you for the second set of eyes ;-) 

1. Question: which files / folders do I need in my working docker-compose folder? I assume I only needed nginx.conf from the examples folder.

2. I seem to have trouble bringing up the solution with example docker-compose. Running on Ubuntu 16.04 LTS. Getting error: connection refused. This [older docker-compose based on v10](https://github.com/SnowMB/nextcloud/tree/master/reverseproxy) works fine. I updated letsencrypt to JrCs version and it works. The moment I switch from [indiehosters' image](https://github.com/indiehosters/nextcloud) - it breaks. I noted docker files are quite different where v12-fpm creates and sets permissions on a few folders vs [indiehosters'](https://github.com/indiehosters/nextcloud)...

3. If I wanted to run this for a smaller number of users, can I just drop redis and collabora?

In the working folder I have created nginx.conf from example, .env and docker-compose.yml

```
$docker-compose --version
docker-compose version 1.8.0, build unknown
```

```
$docker --version
Docker version 17.06.0-ce, build 02c1d87

```
```
$touch .env
$nano .env
DOMAIN=www.<MY>.site
EMAIL=my@email.site
MYSQL_ROOT_PW=<PASS>
MYSQL_USER_PW=<PASS>

```

```
$sudo docker-compose config
networks:
  proxy-tier:
    external:
      name: nginx-proxy
services:
  app:
    container_name: nextcloud_fpm
    image: nextcloud:fpm
    links:
    - db
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /home/<user>/next2/nextcloud/apps:/var/www/html/custom_apps:rw
    - /home/<user>/next2/nextcloud/config:/var/www/html/config:rw
    - /home/<user>/next2/nextcloud/data:/var/www/html/data:rw
  collabora:
    cap_add:
    - MKNOD
    container_name: collabora
    environment:
      domain: www.<MY>.site
    image: collabora/code
    networks:
      proxy-tier: null
    restart: always
  db:
    container_name: db
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_PASSWORD: <PASS>
      MYSQL_ROOT_PASSWORD: <PASS>
      MYSQL_USER: nextcloud
    image: mariadb
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /home/<user>/next2/nextcloud/db:/var/lib/mysql:rw
  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/<user>/next2/proxy/certs:/etc/nginx/certs:rw
    volumes_from:
    - service:proxy:rw
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    networks:
      proxy-tier: null
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - /home/<user>/next2/proxy/conf.d:/etc/nginx/conf.d:rw
    - /home/<user>/next2/proxy/vhost.d:/etc/nginx/vhost.d:rw
    - /home/<user>/next2/proxy/html:/usr/share/nginx/html:rw
    - /home/<user>/next2/proxy/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    container_name: redis
    image: redis
    networks:
      proxy-tier: null
    restart: always
  web:
    container_name: nextcloud_webserver
    environment:
      ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
      LETSENCRYPT_EMAIL: my@email.site
      LETSENCRYPT_HOST: www.<MY>.site
      VIRTUAL_HOST: www.<MY>.site
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: '80'
    image: nginx
    links:
    - app
    - collabora
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /home/<user>/next2/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
    - service:app:rw
version: '2.0'
volumes: {}
```
```
$sudo docker-compose exec app ls -la /var/www/html/
total 172
drwxr-x--- 15 root     www-data  4096 Aug 15 23:10 .
drwxr-xr-x  3 root     root      4096 Aug  4 19:00 ..
-rw-r-----  1 root     www-data  2697 Aug  6 18:55 .htaccess
-rw-r-----  1 root     www-data   163 Aug  6 18:55 .user.ini
drwxr-x--- 31 root     www-data  4096 Aug  6 18:57 3rdparty
-rw-r-----  1 root     www-data  8868 Aug  6 18:55 AUTHORS
drwxr-x--- 36 root     www-data  4096 Aug  6 18:55 apps
drwxr-x---  2 www-data www-data  4096 Aug  7 22:05 config
-rw-r-----  1 root     www-data  4050 Aug  6 18:55 console.php
drwxr-x--- 16 root     www-data  4096 Aug  6 18:57 core
-rw-r-----  1 root     www-data  5057 Aug  6 18:55 cron.php
drwxr-x---  2 www-data www-data  4096 Aug  7 22:05 custom_apps
drwxr-x---  2 www-data www-data  4096 Aug  7 22:05 data
-rw-r-----  1 root     www-data 41077 Aug  6 18:55 db_structure.xml
-rw-r-----  1 root     www-data   179 Aug  6 18:55 index.html
-rw-r-----  1 root     www-data  2804 Aug  6 18:55 index.php
drwxr-x---  3 root     www-data  4096 Aug  6 18:55 l10n
drwxr-x---  6 root     www-data  4096 Aug  6 18:55 lib
-rwxr-x--x  1 root     www-data   283 Aug  6 18:55 occ
drwxr-x---  2 root     www-data  4096 Aug  6 18:55 ocs
drwxr-x---  2 root     www-data  4096 Aug  6 18:55 ocs-provider
-rw-r-----  1 root     www-data  3152 Aug  6 18:55 public.php
-rw-r-----  1 root     www-data  5323 Aug  6 18:55 remote.php
drwxr-x---  4 root     www-data  4096 Aug  6 18:55 resources
-rw-r-----  1 root     www-data    26 Aug  6 18:55 robots.txt
drwxr-x--- 14 root     www-data  4096 Aug  6 18:55 settings
-rw-r-----  1 root     www-data  2110 Aug  6 18:55 status.php
drwxr-x---  3 www-data www-data  4096 Aug  6 18:55 themes
-rw-r-----  1 root     www-data   435 Aug  6 18:57 version.php
```

**Comment by francois-travais** [comment]
I stumbled upon this issue an hour ago. The solution was printed in Mariadb container logs and the container was also restarting continuously. Latest version of Mariadb docker image requires an extra environment variable to allow empty root password: `MYSQL_ALLOW_EMPTY_PASSWORD=yes`.
I also had another issue while trying to fix it: when one runs `docker-compose down` it doesn't destroy volumes which drove me mad for a bit then I switched the right option: `docker-compose down -v`.

**Comment by skepticatgit** [comment]
Hi Francois. Great find, I will try it out with this variable. I found that running dicker compose not in the home directory tends to be cleaner when I bring it down. In /home/user I'd get network hanging with interfaces hanging even if I did `down -v`. I had to do `sudo docker <NETWORK> Inspect` and then `sudo docker network disconnect -f <NETWORK> <CONTAINER>` to clean up until I switched to /home/user/next1.

**Comment by skepticatgit** [comment]
Closing the issue. Confirmed solution see above: Add `MYSQL_ALLOW_EMPTY_PASSWORD=yes` environment variable to MariaDB container. I am also using JrCs letsencrypt container which is more up to date.
```
letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/<user>/next2/proxy/certs:/etc/nginx/certs:rw
    volumes_from:
    - service:proxy:rw
```
