### ISSUE TITLE
Mount my own data into nextcloud user directory

### ISSUE THREAD

**Issue by Whisper40** [nextcloud/docker#1440]
I would like to be able to access my own data that was owned by user:user.
Now i modified it to user:www-data ( because it seems that we have to do it...)

This is my docker-compose : 
```

db above..


  nextcloud_{{ user }}:
    image: nextcloud:latest
    container_name: nextcloud_{{ user }}
    restart: unless-stopped
    volumes:
      - $DATA_DIR/{{ user }}/config/nextcloud/html:/var/www/html
      - $DATA_DIR/{{ user }}/data:/var/www/html/data # i don't see my data... i only see default directory of nextcloud
    labels:
...
    environment:
      - PUID=${MYUID}
      - PGID=${MYGID}
      - TZ=${TZ}
      - MYSQL_PASSWORD=${passwd_{{ user }}}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db_{{ user }}
    networks:
      - proxy
```

I have set 0770 to my $DATA_DIR/{{ user }}/data owned by user:www-data

thanks for help
