### ISSUE TITLE
docker-compose recreate ssl certificates every time

### ISSUE THREAD

**Issue by nekym** [nextcloud/docker#1452]
I took the config from docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm made small changes for storing the data in another place and launched docker-compose. 
In the case when I made restart the `letsencrypt-companion` container recreate certificates every time and after some tries I got the limit message from letsencrypt. 

How do not recreate certificates in the case when they are actual?

```
version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - E:\db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passFromDB
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - E:\nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - E:\nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=myhost.example
      - LETSENCRYPT_HOST=myhost.example
      - LETSENCRYPT_EMAIL=email@example.com
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - E:\nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
```

**Comment by adripo** [comment]
I had the same problem and have to wait a week to unlock letsencrypt and try again.
In the meantime I checked similar problems and I think that docker doesn't connect the old volumes with the new volume that is created when loading docker compose again.
I found out that defining a local bind mount could fix the problem.

Try this and let me know if the certificate is still renewed every time

```
volumes:
  certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/appdata/nextcloud/certs'
```

If this doesn't solve the problem I think that the issue must be checked on the letsencrypt companion image.

**Comment by adripo** [comment]
Oh nvm, I found out that there are lot of issues on the same argument

#1362 
#1357  
#1032 

The fixes are in this pr #1358

You just have to add

```
services:
  letsencrypt-companion:
    volumes:
      - acme:/etc/acme.sh

[...]

volumes:
  acme:
```
