### ISSUE TITLE
Docker Compose Nextcloud Hangs on boot after upgrading.

### ISSUE THREAD

**Issue by meiremans** [nextcloud/docker#1455]
I use the standard Docker-compose file with the mariaDb & nextcloud image's.

If i'm not mistaken i upgraded 2 weaks ago from 20 to 21 by pulling the newest images.

After a server reboot now nextcloud won't start anymore:

even a curl to the nextcloud port on localhost will timeout.

My Docker-compose file:
```
version: '2'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_PASSWORD=***
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=***

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - clouddata:/var/www/html
    environment:
      - MYSQL_PASSWORD=***
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=***
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=*** 192.168.178.34
volumes:
  db:
  clouddata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/opslag/nextclouddocker

```

and the logs: 
```
Starting nextcloud_db_1 ... done
Starting nextcloud_app_1 ... done
Attaching to nextcloud_db_1, nextcloud_app_1
db_1   | 2021-03-23 13:25:34+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.9+maria~focal started.
db_1   | 2021-03-23 13:25:35+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1   | 2021-03-23 13:25:35+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.9+maria~focal started.
db_1   | 2021-03-23 13:25:35 0 [Note] mysqld (mysqld 10.5.9-MariaDB-1:10.5.9+maria~focal) starting as process 1 ...
db_1   | 2021-03-23 13:25:35 0 [Warning] You need to use --log-bin to make --binlog-format work.
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Uses event mutexes
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Number of pools: 1
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Using generic crc32 instructions
db_1   | 2021-03-23 13:25:35 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Using Linux native AIO
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Completed initialization of buffer pool
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: 128 rollback segments are active.
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: 10.5.9 started; log sequence number 6326776902; transaction id 3620359
db_1   | 2021-03-23 13:25:35 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1   | 2021-03-23 13:25:35 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1   | 2021-03-23 13:25:36 0 [Note] Server socket created on IP: '::'.
db_1   | 2021-03-23 13:25:36 0 [Warning] 'proxies_priv' entry '@% root@728b070a3b20' ignored in --skip-name-resolve mode.
db_1   | 2021-03-23 13:25:36 0 [Note] Reading of all Master_info entries succeeded
db_1   | 2021-03-23 13:25:36 0 [Note] Added new Master_info '' to hash table
db_1   | 2021-03-23 13:25:36 0 [Note] mysqld: ready for connections.
db_1   | Version: '10.5.9-MariaDB-1:10.5.9+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
db_1   | 2021-03-23 13:25:36 0 [Note] InnoDB: Buffer pool(s) load completed at 210323 13:25:36
app_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
app_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
app_1  | [Tue Mar 23 13:25:37.215845 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.16 configured -- resuming normal operations
app_1  | [Tue Mar 23 13:25:37.216006 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

```
