### ISSUE TITLE
Not possible to execute the cron job via CLI - error?

### ISSUE THREAD

**Issue by LeducH** [nextcloud/docker#1491]
I want to get rid of the cron error message. 

Currently it shows

> * It was not possible to execute the cron job via CLI. The following technical errors have appeared:
>    * Your data directory is invalid Ensure there is a file called ".ocdata" in the root of the data directory.

I expect the docker to run without error message 

I added the the file manually but I still get the issue. 

```
% docker-compose exec app ls -al /var/www/html/data | grep .ocdata
-rw-r--r--+  1 www-data www-data        0 Apr 28 22:13 .ocdata
```

What is the reason for this error message?

**Comment by sachindavra** [comment]
Hi @LeducH , I want to work on this issue. could you give some more detail.
I am new to open source and want to contribute.

**Comment by LeducH** [comment]
Hey 

```
cat Projects/nextcloud/docker-compose.yml
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /mnt/shared/AppData/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=<host>
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=<localIp>
      - OVERWRITEHOST=<host> 
```

what other details do you need?
