### ISSUE TITLE
Database Incompatibility with MariaDB 10.6.0

### ISSUE THREAD

**Issue by Wibias** [nextcloud/docker#1492]
Hey!

So I updated mariadb, which I use with nextcloud to version alpha 10.6.0.
Which this verison this came [https://mariadb.com/kb/en/innodb-system-variables/#innodb_read_only_compressed](url) and gave me this error:
![image](https://user-images.githubusercontent.com/37517432/117492381-d256c800-af71-11eb-9dac-22c4b53fa106.png)
To fix this I needed to add `command: --innodb-read-only-compressed=OFF` to my mariadb docker compose.
Just a head up when mariadb 10.6.0 becomes the stable version and anyone else get this problem.

**Comment by UbioZur** [comment]
Thank you for the work around.
I was stuck on that problem trying to install nextcloud and mariadb 10.6.1

**Comment by mreho** [comment]
Working perfectly fine, you made me save a couple of hours, thank you :smile:

**Comment by LukBukkit** [comment]
MariaDB 10.6.3 has been published under the `latest` tag on [Docker Hub](https://hub.docker.com/_/mariadb). My setup broke last night as I've upgrading all my images at midnight. I guess a lot of other installations are to follow. The work around did help, but how can me make sure, that people find it?

**Comment by mklemme1** [comment]
> MariaDB 10.6.3 has been published under the `latest` tag on [Docker Hub](https://hub.docker.com/_/mariadb). My setup broke last night as I've upgrading all my images at midnight. I guess a lot of other installations are to follow. The work around did help, but how can me make sure, that people find it?

Same here!
I changed `docker-compose` like this:

```
services:
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-read-only-compressed=OFF
    restart: unless-stopped
```

Still, I suggest that the Nextcloud team develops an update fix that changes the `ROW_FORMAT` in the database.
