### ISSUE TITLE
Postgres autoconfig does not work

### ISSUE THREAD

**Issue by giomf** [nextcloud/docker#1506]
I have discovered an error in the autoconfig via environment variables. I want to connect a postgres database and create an admin on first start.

I use the environment variables as specified in the documentation and I can confirm that they are correctly passed into the containers. All are transferred correctly except POSTGRES_USER and POSTGRES_PASSWORD. When I look at config.php the fields dbuser and dbpassword are incorrect.

dbuser is set as oc_{NEXTCLOUD_ADMIN_USER}.
dbpassword seems to be generated. 

I use the 20 fpm version. But i also had no success with the 21. or with the 19 version.
If I use MYSQL as database everything works as expected.

**Comment by Rob-Meijeren** [comment]
Had the same issue with the stable image. By downgrading to 20.0.9 I got it initializing on startup again. But obviously this should be fixed in the image.

**Comment by Giom-fm** [comment]
I find it strange that no one else is commenting on this.
Doesn't anyone use postgres?
Especially because the error stretches over several releases.

**Comment by Rob-Meijeren** [comment]
maybe they think well someone already pointed it out it will be fixed soon? 🤷‍♂️  I just wanted the maintainers to know I also found this happening on the apache version and its not a fpm only thing. (and to bring a bit more attention to this)

**Comment by Alukardz** [comment]
Same Issue, I spent almost an hour trying to fix it, thinking I messed up the build.

**Comment by JuniorJPDJ** [comment]
welp, nextcloud is very good at not fixing issues like this for a long time :)

**Comment by Giom-fm** [comment]
I know and this is really annoying.

**Comment by Alukardz** [comment]
Nevermind, my error was that I downloaded the nextcloud zip from the Main site and after unpacking it, I had docker-compose share the volume, but even if the versions match, it seems for autoconfig to work, it needs to download the nextcloud code itself, so the volume should have no folder on the host.

**Comment by john-TC** [comment]
I have the same issue. My `docker-compose.yml`:

```
version: '3.9'

services:
  postgres:
    image: postgres:13.4-alpine
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
        POSTGRES_PASSWORD=postgres
        POSTGRES_DB=nextcloud

  nextcloud:
    image: nextcloud:22.1.0-apache
    ports: 
      - 80:80
    volumes: 
      - nextcloud:/var/www/html
    environment: 
      - NEXTCLOUD_ADMIN_USER=admin
        NEXTCLOUD_ADMIN_PASSWORD=admin
        POSTGRES_DB=nextcloud
        POSTGRES_USER=postgres
        POSTGRES_PASSWORD=postgres
        POSTGRES_HOST=postgres
  
volumes: 
  nextcloud:
  postgres:
```
