### ISSUE TITLE
Unable to upgrade from 21.0.1 to 21.0.2

### ISSUE THREAD

**Issue by storm1er** [nextcloud/docker#1507]
Hi,

## `docker-composer.yml`

<details>

```
version: '3.7'
services:
  database:
    image: mariadb:10
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER_FILE: '/run/secrets/mysql-user'
      MYSQL_DATABASE_FILE: '/run/secrets/mysql-database'
      MYSQL_PASSWORD_FILE: '/run/secrets/mysql-password'
    secrets:
      - mysql-user
      - mysql-database
      - mysql-password
    networks:
      - lan 
    volumes: 
      - db:/var/lib/mysql

  nextcloud:
    depends_on:
      - database
    build:
      context: ./build
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: 2048M
      MYSQL_HOST: 'database'
      MYSQL_DATABASE_FILE: '/run/secrets/mysql-database'
      MYSQL_USER_FILE: '/run/secrets/mysql-user'
      MYSQL_PASSWORD_FILE: '/run/secrets/mysql-password'
      NEXTCLOUD_TRUSTED_DOMAINS: AWESOME_DOMAIN
    networks:
      - lan
      - outside
    volumes:
      - ./storage:/var/www/html
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: web
      traefik.http.routers.nextcloud.rule: Host(`AWESOME_DOMAIN`)
      traefik.http.routers.nextcloud.middlewares: https-redirect
      traefik.http.routers.nextcloud-secure.entrypoints: websecure
      traefik.http.routers.nextcloud-secure.rule: Host(`AWESOME_DOMAIN`)
      traefik.http.middlewares.nc-rep.redirectregex.regex: https://(.*)/.well-known/(card|cal)dav
      traefik.http.middlewares.nc-rep.redirectregex.replacement: https://$$1/remote.php/dav/
      traefik.http.middlewares.nc-rep.redirectregex.permanent: true
      traefik.http.middlewares.nc-header.headers.stsSeconds: 15552000
      traefik.http.middlewares.nc-header.headers.customFrameOptionsValue: SAMEORIGIN
      traefik.http.routers.nextcloud-secure.middlewares: nc-rep,nc-header
      traefik.http.routers.nextcloud-secure.tls: true
      traefik.http.routers.nextcloud-secure.tls.certresolver: myresolver
      traefik.http.routers.nextcloud-secure.service: nextcloud
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      traefik.docker.network: outside

volumes:
  db:
  html:

networks:
  outside:
    external: true
  lan:

secrets:
  mysql-user:
    file: ./secrets/mysql-user.txt

  mysql-database:
    file: ./secrets/mysql-database.txt

  mysql-password:
    file: ./secrets/mysql-password.txt
```

</details>

## `Dockerfile`

<details>

```
FROM nextcloud:21.0.2-fpm as builder

# Build and install dlib on builder

RUN apt-get update && \
    apt-get install -y build-essential wget cmake libx11-dev libopenblas-dev unzip && \
    rm -rf /var/lib/apt/lists/*

ARG DLIB_BRANCH=v19.21
RUN wget -c -q https://github.com/davisking/dlib/archive/$DLIB_BRANCH.tar.gz \
    && tar xf $DLIB_BRANCH.tar.gz \
    && mv dlib-* dlib \
    && cd dlib/dlib \
    && mkdir build \
    && cd build \
    && cmake -DBUILD_SHARED_LIBS=ON --config Release .. \
    && make \
    && make install

# Build and install PDLib on builder

ARG PDLIB_BRANCH=master
RUN wget -c -q https://github.com/matiasdelellis/pdlib/archive/$PDLIB_BRANCH.zip \
    && unzip $PDLIB_BRANCH \
    && mv pdlib-* pdlib \
    && cd pdlib \
    && phpize \
    && ./configure \
    && make \
    && make install

# Enable PDlib on builder

# If necesary take the php settings folder uncommenting the next line
# RUN php -i | grep "Scan this dir for additional .ini files"
RUN echo "extension=pdlib.so" > /usr/local/etc/php/conf.d/pdlib.ini

# Test PDlib instalation on builer

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/matiasdelellis/pdlib-min-test-suite.git \
    && cd pdlib-min-test-suite \
    && make

#
# If pass the tests, we are able to create the final image.
#

FROM nextcloud:apache

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        libmagickcore-6.q16-6-extra \
        procps \
        smbclient \
        supervisor \
        libreoffice \
        libopenblas-base \
    ; \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/lib/libdlib.so* /usr/local/lib/


# If is necesary take the php extention folder uncommenting the next line
# RUN php -i | grep extension_dir
COPY --from=builder /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pdlib.so /usr/local/lib/php/extensions/no-debug-non-zts-20190902/

# Enable PDlib on final image

RUN echo "extension=pdlib.so" > /usr/local/etc/php/conf.d/pdlib.ini

# Increse memory limits

RUN echo memory_limit=2048M > /usr/local/etc/php/conf.d/memory-limit.ini


RUN set -ex; \
    \
    savedAptMark="$(apt-mark showmanual)"; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libbz2-dev \
        libc-client-dev \
        libkrb5-dev \
        libsmbclient-dev \
    ; \
    \
    docker-php-ext-configure imap --with-kerberos --with-imap-ssl; \
    docker-php-ext-install \
        bz2 \
        imap \
    ; \
    pecl install smbclient; \
    docker-php-ext-enable smbclient; \
    \
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
    apt-mark auto '.*' > /dev/null; \
    apt-mark manual $savedAptMark; \
    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
        | awk '/=>/ { print $3 }' \
        | sort -u \
        | xargs -r dpkg-query -S \
        | cut -d: -f1 \
        | sort -u \
        | xargs -rt apt-mark manual; \
    \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p \
    /var/log/supervisord \
    /var/run/supervisord \
;

COPY supervisord.conf /

ENV NEXTCLOUD_UPDATE=1

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
```

</details>

## Upgrade steps done

- Updated `dockerfile` line `FROM nextcloud:21.0.1-fpm as builder` to `FROM nextcloud:21.0.2-fpm as builder`
- `docker-compose build --no-cache nextcloud`
- `docker-compose up -d`

Results:
- nextcloud container did recreate
- But I still run the old version 21.0.1

Did I miss something?
