### ISSUE TITLE
How to set up the cron job with docker compose?

### ISSUE THREAD

**Issue by LeducH** [nextcloud/docker#1510]
I want to resolve the issue 

> Some jobs didn’t execute since 5 months ago. Please consider switching to system cron

I use this docker compose file 
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/shared/AppData/nextcloud/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /mnt/shared/AppData/nextcloud/nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=
      - OVERWRITEHOST=

 ```

How do I run the system cron job described [here](https://docs.nextcloud.com/server/21/admin_manual/configuration_server/background_jobs_configuration.html) . 

Do i have to log in to the container  or can this be done from the compose file?

**Comment by ThxAndBye** [comment]
I personally use https://github.com/mcuadros/ofelia to execute the cron.  
In the config ini my entry looks like this:
```
[job-exec "Nextcloud Cron"]
schedule = @every 5m
container = Nextcloud
command = php -f /var/www/nextcloud/cron.php
user = www-data
```  

Works reliably for me and is independent from any settings on the host system.

**Comment by LeducH** [comment]
Looks all right. bit where do you specify the path to the `config.ini` for docker compose. The readMe is a little vage about that.

**Comment by Tofdu31** [comment]
Oh yes, thank ThxAndBye, but where do you specify the path to the `config.ini` 

We only have `config.php` files located in the config folder

**Comment by ThxAndBye** [comment]
> Looks all right. but where do you specify the path to the `config.ini` for docker compose. The readMe is a little vage about that.

In the `command`. For compose it has to look a little like this:
```
ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nextcloud
    command: daemon --config=/path/to/config.ini
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
