### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by on3iro** [nextcloud/docker#1549]
I am currently trying to migrate my regular nextcloud installation to a docker-compose setup. However I am struggling with this image.

The setup sometimes seems to work when I initially run `docker-compose up` and no volumes etc. exist, yet. However even this does not work reliably and if it does it  stops working as soon as I do a `compose down` and `compose up` again. By "stops working" I mean that I will get a 504 gateway timeout whenever I visit my nextcloud. Other services running through my reverse proxy are working fine and reliable. My DNS is configured correctly and I also have valid certificates for the domain.

This does happen if I run the setup locally on OSX as well as when I run it on my raspi 4 (the actual target system).

I am using traefik as a  reverse proxy and all logs are looking fine as far as I can tell (logs from nextcloud + traefik).

I also noticed that apparently the nextcloud container creates the `config.php` file and some other files dynamically. However sometimes this file is created completely empty. The whole "the container is starting and creating files" also does not seem to be logged anywhere, so I never know when this process is actually finished or if it finished at all. (apart from the echos from the entry point) Or is the config file creation done via the cron job?

#1374 might be related to this
I also looked into #1457 and even tried using another mariadb-image, but to  no avail.

Any ideas what could cause these problems?
Thanks in advance!

My current setup looks like this

### traefik-docker-compose.yml

```yaml
version: "3"

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    restart: always
    command:
      # Enables the web UI and tells Traefik to listen to docker
      - --api.dashboard=true
      - --api.insecure=true

      - --providers.docker=true
      - --providers.docker.exposedByDefault=false

      ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
      - --certificatesresolvers.certresolver.acme.dnschallenge=true
      - --certificatesresolvers.certresolver.acme.dnschallenge.provider=inwx
      - --certificatesresolvers.certresolver.acme.email=xxx
      # Staging/prod server uncomment the one in question
      # - --certificatesresolvers.certresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.certresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.certresolver.acme.storage=/letsencrypt/acme.json

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      # The HTTP port
      - "80:80"
      - "443:443" # <== https
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    environment:
      - INWX_USERNAME=xxx
      - INWX_PASSWORD=xxx
    networks:
      - web
      
 networks:
  web:
    name: web
```

### nextcloud-docker-compose.yml

```yaml
version: "3"

services:
  nextcloud:
    image: nextcloud:21.0.3-apache
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=localhost
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - APACHE_DISABLE_REWRITE_IP
      - TRUSTED_PROXIES=172.xx.xx.x
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - web
      - internal
    labels:
      - traefik.enable=true
      #  HTTP route including the necessary redirect to https
      #  TODO: remove path postfix, as soon as everything is configured correctly
      - traefik.http.routers.nextcloud.rule=Host(`xxx`) # && Path(`/nc`)
      - traefik.http.routers.nextcloud.entrypoints=web # <== Defining the entrypoint for http, **ref: line 30
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

      # Redirect to root path
      # - traefik.http.middlewares.to-root.replacepath.path=/
      # - traefik.http.routers.nextcloud-sec.middlewares=to-root
      # HTTPS route
      #  TODO: remove path postfix, as soon as everything is configured correctly
      - traefik.http.routers.nextcloud-sec.rule=Host(`xxx`) # && Path(`/nc`)
      - traefik.http.routers.nextcloud-sec.entrypoints=websecure
      - traefik.http.routers.nextcloud-sec.tls=true
      - traefik.http.routers.nextcloud-sec.tls.certresolver=certresolver

      # Caldav redirect
      - traefik.http.middlewares.nextcloud-redirect-regex.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-redirect-regex.redirectregex.replacement=https://$${1}/remote.php/dav/

  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
    env_file:
      - db.env
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal
      
      redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

  cron:
    image: nextcloud:21.0.3-apache
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:

networks:
  web:
    name: web
  internal:
    name: internal
```

**Comment by on3iro** [comment]
Ok, I did another test and circumvented the proxy - the setup seems to work fine without it. So it probably is an issue with the proxy I cannot yet pinpoint...

**Comment by on3iro** [comment]
I think I've found the error :)

Here's what I did:

* I gave my traefik proxy a fixed ip and set a custom IP range for the network the docker-compose file creates
* I made sure that I use the correct network-name inside the docker-compose.yml of my nextcloud app
* I added external: true to the top level network definition inside the nextcloud-docker-compose.yml

```yaml
# traefik

services:
    # ...
    networks:
        web:
            ipv4_address: 172.18.0.2
            
networks:
    web:
        name: web
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
```

```yaml
# nextcloud

services:
    # ...
    nextcloud:
        # ...
        networks:
            - web
            - internal

networks:
    internal:
        name: internal
    web: # name inside the nextcloud app
        name: web # name of the actual docker network being used
        external: true
```
