### ISSUE TITLE
Upgrade from derived image keeps failing with no error

### ISSUE THREAD

**Issue by xylphid** [nextcloud/docker#157]
I've build a derived image of [nextcloud:12.0.1](https://github.com/xylphid/dockers/blob/master/nextcloud-smb/12.0/apache/Dockerfile) and tried to upgrade it to 12.0.2 (also to 12.0.3) but it keeps failing with no logs on the container and on the daemon.

He is my configuration :
* Docker Swarm (1 manager, 5 nodes)
* Traefik as reverse proxy
* Portainer as swarm manager UI
* Initial swarm-compose file :
```
version: "3"

services:
  database:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        delay: 1m
    image: mysql:5.7.19
    environment:
      - "MYSQL_ROOT_PASSWORD=[hidden]"
      - "MYSQL_USER=[hidden]"
      - "MYSQL_PASSWORD=[hidden]"
      - "MYSQL_DATABASE=[hidden]"
    networks:
      - swarm-net
    volumes:
      - db-datas:/var/lib/mysql

  app:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: "Drive"
        traefik.frontend.rule: "Host:***********"
        traefik.port: 80
      replicas: 1
      restart_policy:
        condition: on-failure
    image: xylphid/nextcloud-smb:12.0.1
    networks:
      - swarm-net
    volumes:
      - app-html:/var/www/html
      - app-apps:/var/www/html/custom_apps
      - app-config:/var/www/html/config
      - app-data:/var/www/html/data
      - app-theme:/var/www/html/themes/xylphid

volumes:
  db-datas:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.10.16,rw
      device: ":/c/docker/drive/db"

  app-html:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.10.16,rw
      device: ":/c/docker/drive/web/html"

  app-apps:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.10.16,rw
      device: ":/c/docker/drive/web/apps"

  app-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.10.16,rw
      device: ":/c/docker/drive/web/config"

  app-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.10.16,rw
      device: ":/c/docker/drive/web/data"

  app-theme:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.10.16,rw
      device: ":/c/docker/drive/web/theme"

networks:
  traefik-net:
    external: true
```

I tried to upgrade the service via portainer changing the image tag but kept failing.
I also tried to update my swarm-compose file with the new tag but also failed.

Container logs tells me nothing and docker daemon log just says :
`Sep 23 12:11:20 dkr-2 dockerd[7727]: time="2017-09-23T12:11:20.053682711+02:00" level=error msg="fatal task error" error="task: non-zero exit (1)" module="node/agent/taskmanager" node.id=k9q5b0oagyujcetxqhgxsmkzo service.id=jtrben42rhfex21wlw535hbjw task.id=u7gjclqmcd38oxgiu60i54z6x`

I've no idea what to try next.
