### ISSUE TITLE
Docker Container restarting on latest version (22.1.1.2)

### ISSUE THREAD

**Issue by Moep90** [nextcloud/docker#1575]
# Container Logs
```
Attaching to nextcloud-app
nextcloud-app | Configuring Redis as session handler
nextcloud-app | Can't start Nextcloud because the version of the data (
nextcloud-app | Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdlib.so' (tried: /usr/lib/php7/modules/pdlib.so (Error relocating /usr/lib/php7/modules/pdlib.so: zend_parse_parameters_throw: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so: No such file or directory)) in Unknown on line 0
nextcloud-app | 22.1.0.1) is higher than the docker image version (
nextcloud-app | Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdlib.so' (tried: /usr/lib/php7/modules/pdlib.so (Error relocating /usr/lib/php7/modules/pdlib.so: zend_parse_parameters_throw: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so: No such file or directory)) in Unknown on line 0
nextcloud-app | 22.1.1.2) and downgrading is not supported. Are you sure you have pulled the newest image version?
nextcloud-app | Configuring Redis as session handler
nextcloud-app | Can't start Nextcloud because the version of the data (
nextcloud-app | Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdlib.so' (tried: /usr/lib/php7/modules/pdlib.so (Error relocating /usr/lib/php7/modules/pdlib.so: zend_parse_parameters_throw: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so: No such file or directory)) in Unknown on line 0
nextcloud-app | 22.1.0.1) is higher than the docker image version (
nextcloud-app | Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdlib.so' (tried: /usr/lib/php7/modules/pdlib.so (Error relocating /usr/lib/php7/modules/pdlib.so: zend_parse_parameters_throw: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so: No such file or directory)) in Unknown on line 0
nextcloud-app | 22.1.1.2) and downgrading is not supported. Are you sure you have pulled the newest image version?
nextcloud-app | Configuring Redis as session handler
nextcloud-app | Can't start Nextcloud because the version of the data (
nextcloud-app | Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/pdlib.so' (tried: /usr/lib/php7/modules/pdlib.so (Error relocating /usr/lib/php7/modules/pdlib.so: zend_parse_parameters_throw: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20200930//usr/lib/php7/modules/pdlib.so.so: No such file or directory)) in Unknown on line 0

```
# Dockerfile -> to support face recognition
## Images
```
nextcloud       fpm-alpine          f3fa17c947a0   32 hours ago     575MB
nextcloud       fpm-alpine-custom   142145c22b9b   19 minutes ago   731MB
```
## Custom changes
```
FROM nextcloud:fpm-alpine
RUN apk --no-cache \
        --update add \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        php7-pdlib php7-imagick bzip2-dev php7-pecl-redis \
  && \
    docker-php-ext-install bz2 \
  && \
    echo 'extension=/usr/lib/php7/modules/pdlib.so' > /usr/local/etc/php/conf.d/pdlib.ini

```
## docker-compose
```
[...]
  app:
    container_name: nextcloud-app
    build:
      context: ./nextcloud/files
    image: nextcloud:fpm-alpine-custom
    restart: always
    ports:
      - 80
      - 9000
    volumes:
      - ./nextcloud/data:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - NEXTCLOUD_UPDATE=0
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - OVERWRITEHOST=cloud.example.com
      - OVERWRITEPROTOCOL=https
      - MYSQL_PASSWORD=<pw>
      - MYSQL_DATABASE=<user>
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=cache
[...]
    depends_on:
      - db
      - cache
[...]

```
# version.php
```php
<?php 
$OC_Version = array(22,1,0,1);
$OC_VersionString = '22.1.0';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array (
  'nextcloud' => 
  array (
    '21.0' => true,
    '22.0' => true,
    '22.1' => true,
  ),
  'owncloud' => 
  array (
    '10.5' => true,
  ),
);
$OC_Build = '2021-08-04T05:44:18+00:00 525ff78aab408b7205f50e67a8129bb504147e61';
$vendor = 'nextcloud';
```

# Versions
```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$  docker-compose version
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
$  docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
# Steps to upgrade
```
docker-compose pull
docker-compose build
docker-compose up -d
```
