### ISSUE TITLE
Unable to update custom image with smb support

### ISSUE THREAD

**Issue by tincturaginseng** [nextcloud/docker#1587]
Docker version:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:06 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:35 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

My Dockerfile:
```
FROM nextcloud:production

RUN apt-get update && apt-get install -y procps smbclient && rm -rf /var/lib/apt/lists/*
```

My docker-compose.yml

```
version: '3'
services:

  app-test:
    build: ./app-server
    container_name: app-server-test
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - /app/nextcloud-test/app/nextcloud:/var/www/html
      - /app/nextcloud-test/app/data:/var/www/html/data
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=strongpassword
      - MYSQL_PASSWORD=samepass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db-test
    depends_on:
      - db-test

  db-test:
    image: mariadb
    container_name: db-server-test
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - /app/nextcloud-test/db/data:/var/lib/mysql
      - /app/nextcloud-test/db/opt:/opt
      - /app/nextcloud-test/db/conf.d:/etc/mysql/conf.d
      - /app/nextcloud-test/db/initdb:/docker-entrypoint-initdb.d
      - /app/nextcloud-test/db/mysql-files:/var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=strongpassword
      - MYSQL_PASSWORD=samepass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
```

I try to build and start stack:
```
docker-compose up -d --build
```

and it failed with this errors:
```
Creating config file /etc/samba/smb.conf with new version
stat: cannot statx '/run/samba/upgrades/smb.conf': Operation not permitted
dpkg: error processing package samba-common (--configure):
 installed samba-common package post-installation script subprocess returned error exit status 1

...

dpkg: dependency problems prevent configuration of smbclient:
 smbclient depends on samba-common (= 2:4.13.5+dfsg-2); however:
  Package samba-common is not configured yet.

dpkg: error processing package smbclient (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of samba-common-bin:
 samba-common-bin depends on samba-common (= 2:4.13.5+dfsg-2); however:
  Package samba-common is not configured yet.

dpkg: error processing package samba-common-bin (--configure):
 dependency problems - leaving unconfigured

...

Errors were encountered while processing:
 samba-common
 smbclient
 samba-common-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: Service 'app-test' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y procps smbclient && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

I noticed that compared to the previous Debian release, the path for generating a temporary Samba configuration file has changed: **/var/run/samba/updates/smb.conf** -> **/run/samba/updates/smb.conf**

With nextcloud image version 21.0.3 builds work fine
