### ISSUE TITLE
Docker container is not starting 

### ISSUE THREAD

**Issue by LeducH** [nextcloud/docker#1592]
I run my docker instance with the following compose file 

```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5 
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/shared/AppData/nextcloud/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /mnt/shared/AppData/nextcloud/nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=myDomain.com
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=192.168.178.52 # local reverse proxy IP
      - OVERWRITEHOST=myDomain.com 
      - OVERWRITEPROTOCOL=https
```

It runs behind a reverse proxy. here are the logs 

```
docker-compose up
Starting nextcloud_db_1 ... done
Starting nextcloud_app_1 ... done
Attaching to nextcloud_db_1, nextcloud_app_1
db_1   | 2021-09-25 20:13:29+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.12+maria~focal started.
db_1   | 2021-09-25 20:13:30+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1   | 2021-09-25 20:13:30+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.12+maria~focal started.
db_1   | 2021-09-25 20:13:30 0 [Note] mysqld (mysqld 10.5.12-MariaDB-1:10.5.12+maria~focal) starting as process 1 ...
db_1   | 2021-09-25 20:13:30 0 [Warning] You need to use --log-bin to make --binlog-format work.
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Uses event mutexes
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Number of pools: 1
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
db_1   | 2021-09-25 20:13:30 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
app_1  | Conf remoteip already disabled
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Using Linux native AIO
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Completed initialization of buffer pool
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: 128 rollback segments are active.
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: 10.5.12 started; log sequence number 13002246334; transaction id 8376220
db_1   | 2021-09-25 20:13:30 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
app_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
db_1   | 2021-09-25 20:13:30 0 [Note] InnoDB: Buffer pool(s) load completed at 210925 20:13:30
app_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
app_1  | [Sat Sep 25 20:13:30.451856 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.48 (Debian) PHP/8.0.11 configured -- resuming normal operations
app_1  | [Sat Sep 25 20:13:30.451889 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
db_1   | 2021-09-25 20:13:30 0 [Note] Server socket created on IP: '::'.
db_1   | 2021-09-25 20:13:30 0 [Warning] 'proxies_priv' entry '@% root@427774bb2097' ignored in --skip-name-resolve mode.
db_1   | 2021-09-25 20:13:30 0 [Note] Reading of all Master_info entries succeeded
db_1   | 2021-09-25 20:13:30 0 [Note] Added new Master_info '' to hash table
db_1   | 2021-09-25 20:13:30 0 [Note] mysqld: ready for connections.
db_1   | Version: '10.5.12-MariaDB-1:10.5.12+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
app_1  | 192.168.178.28 - - [25/Sep/2021:20:14:00 +0000] "GET / HTTP/1.1" 302 1354 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
app_1  | 192.168.178.28 - - [25/Sep/2021:20:13:50 +0000] "GET / HTTP/1.1" 302 1354 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
app_1  | 192.168.178.28 - - [25/Sep/2021:20:14:08 +0000] "GET / HTTP/1.1" 302 1354 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
```

when I use `myDomain.com` no response is shown. how do I debug this?
