### ISSUE TITLE
occ command throwing "Maximum execution time of 0 seconds exceeded" (new/bare installation)

### ISSUE THREAD

**Issue by kmpeterson** [nextcloud/docker#1593]
Reporting as a relatively new user - certainly new in the Docker environment.  

I've had a container running for 4-5 months but have been busy with other things, and went to pick back up on it.  I attempted to pull latest to update the instance created in April of this year; restarting the service seemed to work correctly, but the page displayed at the address after restart indicated that I had to initiate the update there, and had a button to start this.  This button immediately generated an error, the "detailed error" information simply also said that an error had occurred.  There was also a reference to using the `occ` command.  

Attempting to perform the update using `docker exec -it -u 33 nextcloud_app_1 /var/www/html/occ upgrade` - or, I found, other occ commands - generated the following:
`PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/www/html/lib/private/Files/AppData/AppData.php on line 41` 
(with variations on which script and line were referenced, depending on the command.)  UID 33 is www-data, which is the owner of /var/www/html.  

Since I had no "real" data in the instance, and hadn't even set up to secure it with TLS, I decided to wipe all of the associated volumes and retry the "bare" instance (installation), which seems to be running normally - but the `occ` command still fails. 

I'm attaching a copy of my docker-compose file.  I stripped off the custom network I had previously, and the IPv6 definitions, but it's still behaving the same. Two anomalous things that I do see which may be useful:

1. During initial installation, after choosing an admin user and continuing, my browser is redirected to http://index.php/core/apps/recommended , not the actual URL for the server.  
2. In certain variations of my configuration (using a custom network, fixing addresses, and IPv6) the container will refuse to restart indicating it can't bind to the request (IPv4) address.  Also, it appears that the app can't "reliably determine the server's fully qualified domain name" for the docker internal network (when using this) or the IPv6 address (when using IPv6).

Even though it does seem to work other than the problem with the `occ` command and updating, I'm hesitant to do much more until I know that I will be able to update it, or when I've tested recovery from backups.  Also, I thought for a bit and wondered if I really wanted the default "latest" tag - so I also tried this with "stable" - same result.  

Because PHP is one of those things I've never really worked with, there may be something very basic wrt configuration that I'm missing - and I apologize if that's the case - but presumably at least we could then update the docs to cover this.    Many thanks in advance for any ideas.  

[nextcloud_docker-compose.yml.txt](https://github.com/nextcloud/docker/files/7230435/nextcloud_docker-compose.yml.txt)

**Comment by kmpeterson** [comment]
So of course I still had to pick at this...

I found a [report](https://www.spinics.net/lists/stable/msg499206.html) involving Nextcloud that is related to a patch to the Kernel (!) in 5.14.4.  I'm running 5.13.17 on the server that I'm having difficulties with, but it's very suggestive, with an identical signature.  OTOH, I threw up a VM running a 5.4.0 kernel - and same configuration worked fine, same image, all good.   

The author of the post, Greg Kroah-Hartman, has a role in managing Linux kernel releases, so I suspect that the particular patch he referenced will be dealt with soon.  I myself don't know about the kernel release cycle to understand how likely it is that this problem is of the same origin, but I can't at this point make a case for asking for assistance.  (I'm running Docker on Clear Linux if anyone is interested).  

I will provide any updates I can.  Hopefully this is bleeding-edge enough that it doesn't turn out to be a canary for the team.  Thanks!

**Comment by CosminC82** [comment]
Hello,

I guess I have the same issue, also on ClearLinux server with 5.13.17-1074.native kernel, and using docker-compose.

My container log spams these kind of PHP errors:
`Maximum execution time of 0 seconds exceeded at /var/www/html/apps/dav/lib/Server.php#346`
`Maximum execution time of 0 seconds exceeded at /var/www/html/lib/private/legacy/OC_Defaults.php#344`
`Maximum execution time of 0 seconds exceeded at /var/www/html/lib/private/Console/Application.php#232
`
And so on, in different files and on different lines.

Aditionally, my install is broken in files view, not displaying any root data folders or files, even those created by default when first setting up Nextcloud. I am not able to create anything also. It says 
`This directory is unavailable, please check the logs or contact the administrator`.
The default files are present when browsing through a file manager.

Relevant docker-compose snippet (redacted for privacy). Of course MariaDB, redis are running ok, secrets files are in place, environment variables ok:
```
  nextcloud:
    container_name: nextcloud
    restart: always
    image: nextcloud
    depends_on:
      - mariadb
      - redis
    links:
      - mariadb
    volumes:
      - /home/data/nextcloud:/var/www/html/data
      - $DOCKERDIR/nextcloud/config:/var/www/html/config
      - $DOCKERDIR/nextcloud/:/var/www/html
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - mysql_root_password
      - nextcloud_mysql_password
    networks:
      - default
      - t2_proxy
    ports:
      - 12121:80
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.******.*** 192.168.1.*
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/nextcloud_mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=**********:3306
      - REDIS_HOST=**********
      - REDIS_HOST_PASSWORD=$REDIS_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.******.***`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.******.***`)"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.routers.nextcloud-secure.middlewares=nc-rep,nc-header"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=t2_proxy"
 
```
