### ISSUE TITLE
Upgrade to latest nextcloud:fpm-alpine image seems to have failed

### ISSUE THREAD

**Issue by michaelwm** [nextcloud/docker#1596]
I've upgraded to the latest nextcloud:fpm-alpine and have had a couple issues. First I downgraded my mariadb container image back to 10.5 and restored backups, then I followed the advice here (https://github.com/nextcloud/server/issues/28972) to fix the bug contained there and now my nc/redis/mariadb docker-compose setup is having issues doing any php occ command whatsoever. I get the following exception:

````
An unhandled exception has been thrown:
TypeError: OC\App\AppManager::__construct(): Argument #7 ($logger) must be of type OCP\ILogger, OC\Log\PsrLoggerAdapter given, called in /var/www/html/lib/private/Server.php on line 880 and defined in /var/www/html/lib/private/App/AppManager.php:115
Stack trace:
#0 /var/www/html/lib/private/Server.php(880): OC\App\AppManager->__construct(Object(OC\User\Session), Object(OC\AllConfig), Object(OC\AppConfig), Object(OC\Group\Manager), Object(OC\Memcache\Factory), Object(OC\EventDispatcher\SymfonyAdapter), Object(OC\Log\PsrLoggerAdapter))
#1 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC\{closure}(Object(OC\Server))
#2 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#4 /var/www/html/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\\App\\AppManag...', false)
#5 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\\App\\AppManag...')
#6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(182): OC\AppFramework\Utility\SimpleContainer->get('OC\\App\\AppManag...')
#7 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#8 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#9 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet('OCP\\App\\IAppMan...')
#10 /var/www/html/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\\App\\IAppMan...', false)
#11 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\\App\\IAppMan...')
#12 /var/www/html/lib/private/Server.php(1919): OC\AppFramework\Utility\SimpleContainer->get('OCP\\App\\IAppMan...')
#13 /var/www/html/lib/private/legacy/OC_App.php(384): OC\Server->getAppManager()
#14 /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php(82): OC_App::getEnabledApps()
#15 /var/www/html/lib/base.php(640): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#16 /var/www/html/lib/base.php(1083): OC::init()
#17 /var/www/html/console.php(48): require_once('/var/www/html/l...')
#18 /var/www/html/occ(11): require_once('/var/www/html/c...')
#19 {main}
````

It seems as if my /var/www/html didn't get updated correctly? Is there a way to rerun the update? I updated by updating images, attempting to downgrade back to where I was before seemed to fail.

My docker compose (without my mariadb password) is here:
````
version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
````
