### ISSUE TITLE
Postfix relay example

### ISSUE THREAD

**Issue by crazy-max** [nextcloud/docker#160]
Hi,

Would be nice to add an example with a postfix relay in a docker-compose like this one :

```yml
postfix:
    image: alterrebe/postfix-relay
    container_name: nextcloud-postfix
    networks:
      nextcloud:
        ipv4_address: 172.27.1.6
    depends_on:
      - app
    environment:
      - RELAY_HOST_NAME=nextcloud.example.com
      - ACCEPTED_NETWORK=0.0.0.0/0
      - EXT_RELAY_HOST=[smtp.example.com]
      - EXT_RELAY_PORT=587
      - SMTP_LOGIN=smtp@example.com
      - SMTP_PASSWORD=
      - USE_TLS=yes
      - TLS_VERIFY=may
    restart: always
```

More info on my gist : https://gist.github.com/crazy-max/d6706553c770c33285f7e8a520522f68

Cheers!
