### ISSUE TITLE
Max File Size Issue after changing PHP.ini

### ISSUE THREAD

**Issue by chrisfoster121** [nextcloud/docker#1603]
Hello,

I am getting the following error when uploading larger files:
`client intended to send too large body: 2465089 bytes`

my docker-compose looks like the following:

```
version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/sdc1/NextCloudDataVault/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=~~~~~~~~~~~
      - MYSQL_PASSWORD=~~~~~~~~~~~
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: unless-stopped
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - /mnt/sdc1/NextCloudDataVault/html:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    environment:
      - MYSQL_PASSWORD=~~~~~~~~~~
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - VIRTUAL_HOST=~~~~~~~~~~~~~
      - LETSENCRYPT_HOST=~~~~~~~~~~~~~~
      - LETSENCRYPT_EMAIL=~~~~~~~~~~~~
networks:
  nextcloud_network:

```

My php.ini file looks like:
```
upload_max_filesize=2G   
post_max_size=1100M
memory_limit=2G

```

I was reading this thread and saw the volume path addition for the php.ini file. It does seem to change in the settings page :

![image](https://user-images.githubusercontent.com/36481654/136138991-4753300a-eb59-472f-80ef-5f1772315d8c.png)

Have I done something wrong?
