### ISSUE TITLE
unable to create nextCloud instance that uses mounts for folders that need to be backed up

### ISSUE THREAD

**Issue by modernNeo** [nextcloud/docker#1620]
so  I have this compose file that I am trying to create

```
version: '3'

services:


  db:
    image: postgres:latest
    container_name: nextcloud-postgres
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:latest
    ports:
    - "8080:80"
    user: "1026:100"
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=toor
      - POSTGRES_HOST=nextcloud-postgres
      - VIRTUAL_HOST=nextcloud.YOUR-DOMAIN
      - LETSENCRYPT_HOST=nextcloud.YOUR-DOMAIN
      - LETSENCRYPT_EMAIL=YOUR-EMAIL
    restart: unless-stopped
volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:
```
Before running `docker-compose up -d`,the permissions are
```
jace@the-machine:/volume1/NextCloud$ ls -l app/
total 0
drwxrwxrwx+ 1 jace users 0 Oct 23 00:11 config
drwxrwxrwx+ 1 jace users 0 Oct 23 00:11 custom_apps
drwxrwxrwx+ 1 jace users 0 Oct 23 00:11 data
drwxrwxrwx+ 1 jace users 0 Oct 23 00:11 themes
```

But after I run the compose command, the permissions eventually get changed to
```
jace@the-machine:/volume1/NextCloud$ ls -l app/
total 0
d--------- 1 jace users 388 Oct 23 00:12 config
d--------- 1 jace users   0 Oct 23 00:11 custom_apps
d--------- 1 jace users   0 Oct 23 00:11 data
d--------- 1 jace users  26 Oct 23 00:12 themes

```

and the service complains that

```
Initializing nextcloud 22.2.0.2 ...
ls: cannot open directory '/var/www/html/config/': Permission denied
ls: cannot open directory '/var/www/html/data/': Permission denied
ls: cannot open directory '/var/www/html/custom_apps/': Permission denied
ls: cannot open directory '/var/www/html/themes/': Permission denied
Initializing finished
New nextcloud instance
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.128.3. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```

But, I don't see anything in the configuration setup about what to do in the docker-compose file to ensure that the permissions are set correctly when mounting them via the bind type.
