### ISSUE TITLE
Following official instructions results in broken Nextcloud docker environment.

### ISSUE THREAD

**Issue by fishscene** [nextcloud/docker#1624]
Following the official instructions: https://hub.docker.com/_/nextcloud

This is the *exact* configuration I'm using:
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW -innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=none
      - MYSQL_PASSWORD=none
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8122:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=none
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
```
Navigating to the webpage starts the initial admin user setup and configuration.
After filling out the information correctly, an error is thrown on the webpage when submitting the form:

`Error while trying to create admin user: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
![2021-11-01 14_17_17-Nextcloud - Brave](https://user-images.githubusercontent.com/1910351/139743310-19ec3007-cd1e-454b-a16f-a08e08abeb6b.png)
`
