### ISSUE TITLE
Login Credentials Are Sent Unencrypted

### ISSUE THREAD

**Issue by ducarrozb** [nextcloud/docker#1641]
### Problem
I have installed Nextcloud with my own SSL certificates using the official docker image and jwilder reverse-proxy on a Ubuntu 20.04.
I notice that the login data is sent unencrypted. See picture of this link:
https://help.nextcloud.com/uploads/default/original/3X/d/4/d47e8f8fe5f44043e9197257db5e7290858d1514.jpeg

Can someone please tell me what's happening? Is this a bug of the scripts inside the docker image?

### Steps to Reproduce
Operation System: Ubuntu 20.04.3 LTS

**docker-compose.yml**
```
     version: '3.9'
    
    volumes:
      nextcloud:
        name: nextcloud
      nextcloud-mariadb:
        name: nextcloud-mariadb
    
    services:
      nginx-proxy:
        restart: always
        environment:
          - TZ=Europe/Zurich
        image: jwilder/nginx-proxy:alpine
        container_name: nextcloud-reverse-proxy
        ports:
          - "8001:443"
        dns_search:
          - "myhost.ch"
        volumes:
          - "/var/run/docker.sock:/tmp/docker.sock:ro"
          - /volume/config/certs/uo:/etc/nginx/certs:ro
          - /volume/config/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
          - /volume/config/reverse-proxy/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
          - /volume/config/nextcloud/logfiles/error.log:/var/log/nginx/error.log
    
      php8.0.8-apache:
        restart: always
        image: php:8.0.8-apache
        container_name: nextcloud-php8.0.8-apache
        environment:
          - TZ=Europe/Zurich
        volumes:
          - /volume/usrdata:/var/www/html/
    
      nextcloud-mariadb:
        image: mariadb
        container_name: nextcloud-mariadb-3306
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
        links:
          - nginx-proxy
        volumes:
          - /volume/usrdata/nextcloud/mariadb:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=mypass
          - MYSQL_PASSWORD=mypass
          - MYSQL_DATABASE=nextcloud
          - MYSQL_USER=nextcloud
          - TZ=Europe/Zurich
      app:
        image: nextcloud
        restart: always
        container_name: nextcloud
        links:
          - nextcloud-mariadb
          - nginx-proxy
        volumes:
          - /volume/usrdata/nextcloud:/var/www/html
        environment:
          - VIRTUAL_HOST=myhost.ch
          - MYSQL_PASSWORD=mypass
          - MYSQL_DATABASE=nextcloud
          - MYSQL_USER=nextcloud
          - MYSQL_HOST=nextcloud-mariadb
          - TZ=Europe/Zurich
```
**nginx.conf**
```
 user  nginx;
    worker_processes  auto;
    
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    
    
    events {
        worker_connections  10240;
    }
    
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  ' -  [] "" '
                          '  "" '
                          '"" ""';
    
        access_log  /var/log/nginx/access.log  main;
    
        sendfile        on;
        #tcp_nopush     on;
    
        keepalive_timeout  65;
    
        #gzip  on;
        server_tokens off;
        proxy_set_header Proxy "";
        include /etc/nginx/conf.d/*.conf;
    
    
         server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
            ssl_certificate /etc/nginx/certs/myhost.ch.crt;
            ssl_certificate_key /etc/nginx/certs/myhost.ch.key;
        return 301 https://$host$request_uri;
        }
    }
    daemon off;
```
**config.php**
```
 <?php
    $CONFIG = array (
      'htaccess.RewriteBase' => '/',
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'apps_paths' => 
      array (
        0 => 
        array (
          'path' => '/var/www/html/apps',
          'url' => '/apps',
          'writable' => false,
        ),
        1 => 
        array (
          'path' => '/var/www/html/custom_apps',
          'url' => '/custom_apps',
          'writable' => true,
        ),
      ),
      'instanceid' => 'xxxxxxxxxxxxxxx',
      'passwordsalt' => 'xxxxxxxxxxxxxxx',
      'secret' => 'xxxxxxxxxxxxxxxx',
      'trusted_domains' => 
      array (
        0 => 'myhost.ch:8001',
      ),
      'datadirectory' => '/var/www/html/data',
      'dbtype' => 'mysql',
      'version' => '22.2.0.2',
      'overwrite.cli.url' => 'https://myhost.ch:8001',
      'dbname' => 'nextcloud',
      'dbhost' => 'nextcloud-mariadb',
      'dbport' => '',
      'dbtableprefix' => 'oc_',
      'mysql.utf8mb4' => true,
      'dbuser' => 'nextcloud',
      'dbpassword' => 'mypass',
      'installed' => true,
    );
```
