### ISSUE TITLE
NEXTCLOUD_TRUSTED_DOMAINS only sets first domain in list

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/docker#1666]
Multiple domains in `NEXTCLOUD_TRUSTED_DOMAINS` separated with spaces are ignored.

Example:

docker-compose:
```
NEXTCLOUD_TRUSTED_DOMAINS: cloud-test.example.com cloud-test.internal.example.com
```

config.php
```
'trusted_domains' =>
  array (
    0 => 'cloud-test.example.com',
  ),
````

**Comment by novaliswolf** [comment]
Also having the same issue on version: [24.0.1](https://hub.docker.com/layers/nextcloud/library/nextcloud/24.0.1/images/sha256-2e4063f0d02656f2b699f63f65693956c79d22b8d49d5d45723c8f221cbbe5d9?context=explore)

**Comment by jwaes** [comment]
Also having this issue ...

**Comment by im2c0ol** [comment]
Months later trying to get the trusted domain option working using CloudFlare without luck.
It's a great tool, but why it's so difficult to get this working externally?
I even edited the config.php
![image](https://user-images.githubusercontent.com/21378169/193502343-7fd29354-5307-47ff-9525-2e4e05f52a08.png)
Nextcloud version 24.0.5

**Comment by LinuxMeow** [comment]
For me it doesn't set even the first domain. I set only one. Then went on installation phase and page says "Access through untrusted domain".

**Comment by Ramalama2** [comment]
same here.
pretty annoying with all that nextcloud docker issues.

All i wanted is an easier upgrade method, through containers and traefik etc...
and its actually working all great, but this nextcloud docker container is just annoying.
i think its actually better to switch to a normal nginx instance.

Cheers

**Comment by rudolphh** [comment]
And seeing issues from even last year thought this was resolved until now.

**Comment by ariep** [comment]
> For me it doesn't set even the first domain. I set only one. Then went on installation phase and page says "Access through untrusted domain".

I have the same experience: we regularly install/run the nextcloud docker image as part of a CI run. We set `NEXTCLOUD_TRUSTED_DOMAINS` to a single domain. *Sometimes* this does not end up in the actual configuration (according to `php occ config:system:get trusted_domains`): which will be only `localhost` then. *Sometimes* it does work and `trusted_domains` will contain both `localhost` and the specified domain. I have not found any pattern predicting when it will work.

**Comment by nel0x** [comment]
@LinuxMeow Can confirm the most recent stable docker release 25.0.2 ignores the `NEXTCLOUD_TRUSTED_DOMAINS` environment variable too.

`docker exec nextcloud_app_1 printenv NEXTCLOUD_TRUSTED_DOMAINS` successfully prints out the defined trusted domain(s), so that's not the issue.

@BornToBeRoot mentioned only the first domain got set. Did you do the initial setup with that domain?
Currently, Nextcloud container seems to only set the domain/ip used for inital setup as trusted domain in `config.php`.

**Comment by BornToBeRoot** [comment]
@nel0x yes. I think it was that domain.

**Comment by sebastiansam55** [comment]
also having this issue, I don't even see that dev has commented on this issue thread. Is this a won't fix or something?

Is there a way to set that value with the occ command?

**Comment by sebastiansam55** [comment]
well for anyone else, this is possible via `occ` but still doesn't resolve the error message in the administration console;

from their documentation: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#config-commands-label

> To set one of multiple values, you need to specify the array index as the second name in the config:system:set command, separated by a space. For example, to replace sample.tld with example.com, trusted_domains => 2 needs to be set:
> 
> sudo -u www-data php occ config:system:set trusted_domains 2
> --value=example.com
> System config value trusted_domains => 2 set to string example.com
> 
> sudo -u www-data php occ config:system:get trusted_domains
> localhost
> nextcloud.local
> example.com

**Comment by Cadish** [comment]
Anyone found another solution to this already? Also having the issue with only 1 domain set

**Comment by rmelotte** [comment]
I believe the issue is also visible when at installation, when the container starts for the first time:
```
app_1  | Setting trusted domains…
app_1  | sh: 1: Syntax error: Unterminated quoted string
```

**Comment by steljwagh** [comment]
This issue took me a couple of hours without any solution.

The environment variable NEXTCLOUD_TRUSTED_DOMAINS is useless, it is not populated into the config.php

**Comment by fyears** [comment]
i also encounter the same issue in may 2024. it seems the trusted domain is completely ignore

**Comment by joshtrichards** [comment]
There are differences in handling of environment variables across Docker Compose versions unfortunately. 

https://github.com/docker/compose/issues/8763#issuecomment-1235679248

I suspect that's part of these reports the last couple years.

There are also other factors like shell interpretation, if using `-e` via `docker run`.

The original PR #500 used `\ ` in the example to escape the space when the list was provided at the command line.

If you're still having problems with `NEXTCLOUD_TRUSTED_DOMAINS` today please share:

- *precisely* (details matter) how you're providing the variable to Docker
- Docker Compose version
- Docker version

**Comment by joshtrichards** [comment]
> i also encounter the same issue in may 2024. it seems the trusted domain is completely ignore

It's definitely not ignored. I used it daily. :-)

But only works at installation time (once).

Please post details of your situation if it's not working. If there is a bug, can't be fixed if we can't reproduce it. For that we need specifics.

**Comment by BornToBeRoot** [comment]
@joshtrichards the problem is not related to docker. Nextcloud doesn't handle the environment variables properly.

The environment variables work at installation (for the first time), but changes afterwards to this is ignored. Either you make it clear that it's only for installation or you need to handle updates to this variables.

However, in temporary environments with Kubernetes, for example, it should be possible to set (and adjust) such settings dynamically via environment variables. It's doesn't make sense when you define everything as code via something like terraform, deploy it to kubernetes and than you need to manually adjust the config.php file.

Pi-hole (Docker) for example will adjust the config based on the environment variables on each time the container starts.

https://github.com/pi-hole/docker-pi-hole?tab=readme-ov-file#environment-variables

**Comment by joshtrichards** [comment]
> The environment variables work at installation (for the first time), but changes afterwards to this is ignored. Either you make it clear that it's only for installation or you need to handle updates to this variables.

See https://github.com/nextcloud/docker/issues/1544#issuecomment-1370172015 (among others).

**Comment by fyears** [comment]
> > i also encounter the same issue in may 2024. it seems the trusted domain is completely ignore
> 
> It's definitely not ignored. I used it daily. :-)
> 
> But only works at installation time (once).
> 
> Please post details of your situation if it's not working. If there is a bug, can't be fixed if we can't reproduce it. For that we need specifics.

@joshtrichards 

## more details

I already have a Caddy in front of me, so I would like to use caddy to reverse proxy my nextcloud docker, which requires me setting up trusted domain(s).

I am a newbie to docker and nextcloud. 

## first try - failed

In host machine's bash, I try the "most simple" command here:

```bash
sudo docker run \
  -p 8080:80 \
  -e NEXTCLOUD_TRUSTED_DOMAINS=example.com \
  nextcloud
```

Go to http://localhost:8080 , the installation page is shown. I set up a username and password, and use the default sqlite.

After the installation completes, in the host machine, I go inside docker machine to check whether the domain is configured.

```bash
sudo docker ps
# so that I can find out the container id

sudo docker exec -it $containerid bash
## /var/www/html

cat config/config.php
## ...
## 'trusted_domains' => 
##   array (
##     0 => 'localhost:8080',
##   ),
## ...
```

## second try - succeeded

In host machine's bash:

```bash
sudo docker run \
  -p 8080:80 \
  -e NEXTCLOUD_TRUSTED_DOMAINS=example.com \
  -e SQLITE_DATABASE=nextcloudsqlitedb \
  -e NEXTCLOUD_ADMIN_USER=admin1 \
  -e NEXTCLOUD_ADMIN_PASSWORD=123456 \
  nextcloud
```

Then I go to http://localhost:8080/, I am redirected to http://localhost:8080/login , skipping the installation page. And I can use `admin1` and `123456` to directly login.

Go inside docker to check the config:

```bash
sudo docker ps
# so that I can find out the container id

sudo docker exec -it $containerid bash
## /var/www/html
cd config/
cat config.php
## ...
##  'trusted_domains' => 
##  array (
##    0 => 'localhost',
##    1 => 'example.com',
##  ),
## ...
```

As we can see, the domain is successfully injected into `config.php` this time.

## My thoughts

So obviously showing up installation page or not makes a differences. A reasonable guess is that during the manual installation, maybe the environment variable is lost or the `config.php` is re-written. So to make it working, **a database setting and username and password must be combined with `NEXTCLOUD_TRUSTED_DOMAINS`.** I don't do further investigation though.

It seems that user @BornToBeRoot is saying the same thing in the above comment?

Maybe I am skimming the readme too fast, but maybe it's better to emphasize this "trick" in bold font in the readme file.

**Comment by aliuq** [comment]
Is `/var/www/html` bound? I also encountered this problem. From the above answer, I guess that `config/config.php` has not been changed. In my case, `NEXTCLOUD_TRUSTED_DOMAINS` was not added for the first time. At this time, the html already existed locally. When `NEXTCLOUD_TRUSTED_DOMAINS` was added later, the configuration in the html would not be modified.

**Comment by joshtrichards** [comment]
NEXTCLOUD_TRUSTED_DOMAINS must be accompanied by NEXTCLOUD_ADMIN_USER and NEXTCLOUD_ADMIN_PASSWORD. This is currently expected behavior, but the docs need clean-up. 

Work in progress in #2224

**Comment by nhohung** [comment]
> NEXTCLOUD_TRUSTED_DOMAINS must be accompanied by NEXTCLOUD_ADMIN_USER and NEXTCLOUD_ADMIN_PASSWORD. This is currently expected behavior, but the docs need clean-up.
> Work in progress in #2224

Hi, I've been accessing my Nextcloud service (version 27) from the external domain without problem until today tried to log in from my local network and found the same issue: the config.php only took the first trusted_domains value (which is my domain), and completely ignored my other local entries.

I reinstalled the latest Nextcloud docker version (version 29.0.1.1), defining NEXTCLOUD_TRUSTED_DOMAINS along side with NEXTCLOUD_ADMIN_USER and NEXTCLOUD_ADMIN_PASSWORD (see docker-compose.yml below). I notice the first initialization I can access the admin account creation page both locally and from my domain, but after setting that up, the config.php file only has one entry.

Any idea why?

- Docker version: 20.10.5
- Docker compose version: 1.25.0
- Variable passing:
```
version: "3.7"
services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    networks:
      - nextcloud
      - t2_proxy
    ports:
      - 8180:80
    volumes:
      - ./data:/var/www/html
    environment:
      REDIS_HOST: nc-redis
      NEXTCLOUD_TRUSTED_DOMAINS: localhost $NEXTCLOUD_DOMAIN_NAME 192.168.1.112 192.168.1.123 172.27.0.2 127.0.0.1 # I put everything I can think of into the list
      TRUSTED_PROXIES: 172.27.0.2
      OVERWRITEPROTOCOL: https
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin_pass
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`$NEXTCLOUD_DOMAIN_NAME`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.middlewares=chain-nextcloud@file" # No Authentication
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
```

**Comment by superstes** [comment]
Greetings!

I too have hit this issue.

NextCloud works if I connect over the IP. But the supplied hostname is ignored. (_even on first run_)

Docker-ce: `5:27.0.2-1`
Docker-compose-plugin: `2.28.1-1`

**CONFIG**:
```yaml
networks:
  nextcloud:
    driver: 'bridge'

services:
  mariadb:
    container_name: 'nextcloud-db'
    hostname: 'db'
    image: 'mariadb:lts'
    env_file: "/etc/nextcloud/db.env"
    volumes:
      - '/var/lib/nextcloud:/var/lib/mysql'
    ports:
      - '127.0.0.1:3306:3306'
    restart: always
    networks:
      - 'nextcloud'

  nextcloud:
    container_name: 'nextcloud'
    hostname: 'nextcloud'
    image: 'nextcloud:28.0.7'
    env_file: "/etc/nextcloud/nextcloud.env"
    volumes:
      - '/data/nextcloud:/var/www/html'
    ports:
      - '127.0.0.1:8080:80'
    restart: 'always'
    networks:
      - 'nextcloud'
```

```
# nextcloud.env
NEXTCLOUD_TRUSTED_DOMAINS=cloud.sub.domain.tld 192.168.1.100
# NOTE: I also tried to supply the trusted-domains in quotes

NEXTCLOUD_ADMIN_USER=admin
NEXTCLOUD_ADMIN_PASSWORD=<SECRET>
NEXTCLOUD_UPDATE=1
MYSQL_HOST=db
MYSQL_DATABASE=nextcloud
MYSQL_USER=nextcloud
MYSQL_PASSWORD=<SECRET>
```

----

**RUN**:

`docker compose -f /etc/nextcloud/docker-compose.yml up -d`

----

**RESULT**:

```
cat /data/nextcloud/config/config.php 
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'upgrade.disable-web' => true,
  'instanceid' => '<ID>',
  'passwordsalt' => '<SECRET>',
  'secret' => '<SECRET>',
  'trusted_domains' => 
  array (
    0 => '192.168.1.100',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '28.0.7.4',
  'overwrite.cli.url' => 'http://192.168.1.100',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '<SECRET>',
  'installed' => true,
);
```

**Comment by BestaBes** [comment]
for all who are interested how i solved this issue. i just mounted the location on local files in volumes. i can easy just edit the local file and update the container. easy going

```
    volumes:
      - ./config:/var/www/html/config:z
``` 

Just run the docker compose, go to web login of your nextcloud, create an admin user and select your apps, after using the wizards your config files will be written.
use vim on your local machine (you maybe need sudo), edit the file, rum docker-compose up -d again to update the instance. done.
you don't need to take the container down. works just fine. i'm using this with nxings proxy manager.

Here my files.

nexcloud docker-compose.yml

```
version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - nxc-db1:/var/lib/postgresql/data:Z
    env_file:
      - db.env
  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - nxc-app1:/var/www/html:z
      - ./config:/var/www/html/config:z
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nxc-app1:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  nxc-db1:
  nxc-app1:
``` 

db.env File

```
POSTGRES_PASSWORD=mypassword
POSTGRES_DB=nextcloud
POSTGRES_USER=myuser
``` 

nginx proxy manager docker-compose.yml

```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port default admin@example.com changeme
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
