### ISSUE TITLE
Add `overwrite.cli.url` as Docker Environment variable

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/docker#1670]
Feature: Add `overwrite.cli.url` as Docker Environment variable

**Comment by DerFireWal** [comment]
@BornToBeRoot Did you test if this is not already working?
Just tried that yesterday with the latest image and it's working on my side.

Snippet from my docker-compose.yml:

```
nextcloud:
    image: nextcloud
    container_name: nextcloud
    secrets:
      - nextcloudadmin
      - nextcloudadminpwd
...
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - data:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloudadmin
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloudadminpwd
   ...
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.yourdomain.tld
      - TRUSTED_PROXIES=172.27.0.4/16
      - OVERWRITEHOST=nextcloud.yourdomain.tld
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://nextcloud.yourdomain.tld
```
