### ISSUE TITLE
No default text editor available in fresh install

### ISSUE THREAD

**Issue by bitshiftnetau** [nextcloud/docker#1673]
When clicking on a file, it prompts to download. Right-click shows no editing options. 

Following docker-compose.yml from [https://hub.docker.com/_/nextcloud/](official) docker

```
services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /opt/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=<user>
    command:
      - --innodb-read-only-compressed=OFF

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /opt/nextcloud/www:/var/www/html
    environment:
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=central_local
      - MYSQL_HOST=db

```

Both Text and Collabora are enabled:

![nextcloud5](https://user-images.githubusercontent.com/26871600/148361886-b7175aef-ab6e-4699-8d9a-47d400f0186f.png)
![nextcloud7](https://user-images.githubusercontent.com/26871600/148361888-34048e0a-b9dc-4f5a-8b80-929bca4dec65.png)
