### ISSUE TITLE
Background jobs: Cron does not run

### ISSUE THREAD

**Issue by beryl03** [nextcloud/docker#1695]
Tag: latest (2022/02/04)
When trying to setup Cron as the background job, it seems it cannot work without a lot of work on top of the image
Missing:
Packages: Cron (and dependencies)
Service: Something to run Crontab jobs
Settings to Reproduce:
1) Install docker image from tag: latest
2) Setup dependencies (SQL DB) and config to get NextCloud started
3) Enable Cron background Job
  - Settings -> Basic Settings -> Select " Cron" Radio Button under "Background jobs" section
4) Wait 5 minutes and reload page
  - observe that the last job was run over 5 minutes ago (PROBLEM)
5) Log into docker container terminal as Root
6) Install Cron package and dependencies
7) Install editor and configure EDITOR env var (I used nano)
8) edit crontab (crontab -u www-data -e) to add recommended line per documentation (https://docs.nextcloud.com/server/23/admin_manual/configuration_server/background_jobs_configuration.html)
9) Wait 5 minutes and reload page
  - observe that the last job was run over 5 minutes ago (PROBLEM)
10) Further investigation you can see that there are no Cron logs at expected locations, which indicates Cron is not even running. I was unable to figure out how to start the Cron service since the docker image is stripped down version of Debian. SystemD does not seem to be installed.

Mitigation:
Mitigation is to setup Cron on Host and run "docker exec -u 33 -t nextcloud-app php -f /var/www/html/cron.php" (www-data UID = 33)
  - Note: on Fedora Server, Cron is not enabled/running after Cron is installed. the service has to be enabled for Cron jobs to run (systemctl enable crond.service)

Proposed Solution:
1) Create Docker Image with cron installed and setup such that  selecting Cron as a background job is enough to setup the cron job.
2) Update Documentation to note that official docker image[s] do not support Cron Jobs in a Docker Container and list links to solutions or mitigations.

**Comment by beryl03** [comment]
Here is some info from docker image inspect <image-id>:


 "Id": "sha256:df82fda354851c092a2e95bb49189231931c357c36ab03a4ec3c19fdd64c4925",                                                        
        "RepoTags": [                                                                                                                           
            "nextcloud:latest"                                                                                                                  
        ],                                                                                                                                      
        "RepoDigests": [                                                                                                                        
            "nextcloud@sha256:867d3f34d5a7baa1fb48b18b86e36486e406832881219c5bcd7f9952bc947366"                                                 
        ],

**Comment by kemoantemo** [comment]
The background cron should be run in a separate container
If you provide the docker-compose.yml you using I can help you with how to set up the cron container.
Or the rocker compose examples right here can help you.
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml
It should be like that
  ```
app:
    image: nextcloud:apache
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
```

**Comment by beryl03** [comment]
That could work but if it is starting a while new container, that sounds like a bit more RAM just to run Cron.php. also seeing two containers sharing the volume seems odd. Since you could have file IO errors.
If this is the recommended way, there was no mention of this method in any of the documentation (docs.nextcloud.com).

**Comment by martadinata666** [comment]
so few ways to use the cron is,
- use separate compose like above
- use host cron and docker exec command
- custom image to run cron apa apache in parallel

**Comment by beryl03** [comment]
@martadinata666 , I use the host to push a docket exec, and it works, and cron does it regularly.
With regards to all options, I did not find any documentation easily, or it is not linked in either documentation I looked:
https://github.com/nextcloud/docker/wiki
https://docs.nextcloud.com/server/23/admin_manual/configuration_server/background_jobs_configuration.html
It would have saved me a few hours if the documentation stated the docker image cron does not work and then states solutions and links.

**Comment by beryl03** [comment]
@kemoantemo ,
I am not saying that is good. I am saying me as a user never found that in all the searching I did. What good is that if a user cannot find it?
What I am asking is if we can help users (like me) find the information we need by putting the documentation or links to documentation where a [new] user would look.

**Comment by martadinata666** [comment]
everyone got personal preferences, in my case i rather not modify host so i create custom image with added supervisor to run cron and apache in parallel. Because i also need additional job yg full text search, and preview generator, and pretty messed up on upgrade as it get overwritten *cmiiw*

**Comment by danieljkemp** [comment]
The NC docker docs just mention cron briefly, pointing to the examples:

> The [examples folder](https://github.com/nextcloud/docker/blob/master/.examples) gives a few examples on how to add certain functionalities, like including the cron job, smb-support or imap-authentication.

[Here is where cron is defined in the examples](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml#L39)

This would be the correct way to do it with docker-compose*. Containers should be a single process to allow logs and error handling to  make sense.

Since almost every(?) instance needs cron, maybe it should be more prominent in the docs?

*(In Kubernetes you can use a `CronJob` to handle the cron script which feels somewhat nicer.)

**Comment by keunes** [comment]
Sorry to revive this a month later, but I am also facing issues with my Cron set-up.

<details>
  <summary>My docker-compose.yml</summary>

```yml
version: '2'

#volumes:
#  - /nextcloud-data:/var/www/html/data
#  - ./config:/var/www/html/config
#  - ./apps:/var/www/html/apps
#  - ./db:/var/lib/mysql

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=[pw]
      - MYSQL_PASSWORD=[pw]
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - redis
    volumes:
      - ./config:/var/www/html/config
      - ./apps:/var/www/html/custom_apps
      - /nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=[pw]
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - SMTP_HOST=mail.me.eu
      - SMTP_SECURE=tls
      - SMTP_PORT=587
      - SMTP_NAME=system@me.eu
      - SMTP_PASSWORD=[pw]
      - MAIL_DOMAIN=me.eu
      - MAIL_FROM_ADDRESS=system
      - TRUSTED_PROXIES=192.xxx.xxx.xx
      - TRUSTED_DOMAIN=cloud.me.eu
      - REDIS_HOST=redis

  cron:
    image: nextcloud
    restart: always
    volumes:
      - ./config:/var/www/html/config
      - ./apps:/var/www/html/custom_apps
      - /nextcloud-data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
```
</details>

Despite copying the [proposed cron container description](https://github.com/nextcloud/docker/blob/3a5086de638a87ee66a2529857fe660d783bca1a/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml#L35) - except the volumes as I'm only using more specific ones rather than just the generic `/var/www/html`. However, docker doesn't seem to do anything. I am still seeing the notification in Nextcloud admin pages that the 'last executed job was yesterday'.

I asked support on the forum but unfortunately the answers provided there don't really get me much further. On the one hand I'm hoping to get feedback on my situation. On the other hand I'm here to support the call for more documentation/explanation on using docker (more than only an example file that doesn't explain anything and isn't of much help when debugging).

**Comment by kemoantemo** [comment]
@keunes the /var/www/html is an essential for not just cron but also for upgrading you should have it first then take every custom data or config as you want after so try to make a volume for /var/www/html 
If you need help you can email me at kemoantemo20@gmail.com I'd love to help

**Comment by danieljkemp** [comment]
@keunes try setting the MYSQL variables in the environment of the cron container as well. They're not specifying any in the example, but I am going to guess that is because they are using defaults.

**Comment by kemoantemo** [comment]
@danieljkemp it's getting it from the config file no need to he just need to mount the /var/www/html

**Comment by keunes** [comment]
> @keunes the /var/www/html is an essential for not just cron but also for upgrading you should have it first then take every custom data or config as you want after so try to make a volume for /var/www/html

You're amazing, this worked! Just for my understanding: why is it that adding this 'parent' volume fixed it? Which directories/files are there that cron needs (or that the app needs to know that cron is running)?

I think it would be helpful to mention in the docs (docker Readme) what you told me also, namely that the parent folder must be there, and that child directories may be specified after. I see now that it is mentioned [Persistent data](https://github.com/nextcloud/docker#persistent-data) somewhat implicitly, but not mentioned in the [Docker compose](https://github.com/nextcloud/docker#running-this-image-with-docker-compose) section. I'll prepare a PR with some suggested changes later on.

Also, another question for my understanding: what happens behind the scenes when mounting a parent and then some child directories? On the first run with the global/first volume (when the `nextcloud` volume doesn't exist yet), does it work like this?
* first main volume created (replicating the files & structure from the image in the virtual file system), after which
* any other volume I defined is mounted in the 'parent'/first volume (for which I suppose the original files that were taken from the image are removed first)

All the best

**Comment by martadinata666** [comment]
The essential thing is the `/var/www/html` in your `cron` and `app` need to be inline, if it run separately, the data generated from cron won't available / written to `/var/www/html` in `app`. Dunno exactly what is it written or read, `/var/www/html/cron.php` if you love investigate further.

Assume you had `/var/www/html` called it `base` and you also had `/var/www/html/config` defined called `override`, both had `/var/www/html/config`. Container will read from the `override` not from the `base`.

**Comment by keunes** [comment]
Thanks all for the help and explanations (and sorry for replying only now). I managed to get it working! I think indeed the trick was to add the volume `nextcloud:/var/www/html` both to `app` and `cron`.

**Comment by ninadpchaudhari** [comment]
> @danieljkemp it's getting it from the config file no need to he just need to mount the /var/www/html

Thanks for that info, it answered my question, hope it helps someone else too.
Quesion:
since the config file needs to be retrieved from /var/www/html, why don't we just make the `cron` service's `depends_on` parameter to be on `app` instead of `db & redis` ? 

I feel, from the current example, if it only depends on DB, then we gotta give it all the environment parameters! Which is not really great thing to do.

**Comment by kemoantemo** [comment]
> Quesion: since the config file needs to be retrieved from /var/www/html, why don't we just make the `cron` service's `depends_on` parameter to be on `app` instead of `db & redis` ? Sounds this could be a good Pull Request?

`depends_on ` only makes the containers start after the dependency containers start what you want is
 ```
volumes_from:
      - app
```
and I did a pull request #1710 for it but it doesn't work with stack so they didn't implement it

**Comment by persching1978** [comment]
Hello to all,
I've the same problems, but adding the nextcloud:apache to my docker-compose.yml did not solve the problem! I've a Synology DS 220+ and installed portainer to do all the docker installations. In this installation I've to adapt the volume part to the right path of my synology. But I think this is the only modifcation. 
Nextcloud is working for a few weeks, but I've always the error message with cron, so I try to fix this...

Here is my portainer stack (I think it's nearly the same as the docker-compose.yml):

`services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - /volume1/docker/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - TZ=Europe/Berlin
    networks:
      - web
  
  redis:
    image: redis:latest

    restart: always
    networks:
      - web
    volumes:
      - /volume1/docker/redis:/var/lib/redis
      
  app:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    links:
      - db
    volumes:
      - /volume1/docker/nextcloud:/var/www/html
      - /volume1/docker/configfiles/nextcloud/.htaccess:/var/www/html/.htaccess

    logging:
      driver: "json-file"
      options:
          max-size: 10m
          max-file: "3"
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - TZ=Europe/Berlin
    networks:
      - web
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - /volume1/docker/nextcloud:/var/www/html
    entrypoint: /cron.sh
    networks:
      - web
    depends_on:
      - app
      - db
      - redis

networks:
  web:
    external: true`

**Comment by persching1978** [comment]
It's fantastic: after posting my comment I've rebooted my Diskstation and now nextcloud cron works fine. :)

**Comment by lawipac** [comment]
> 

Personally, I think docker exec is a better way, because is does not requires to change official nextcloud docker image, and automatic upgrade is possible.

**Comment by wekaz** [comment]
> The background cron should be run in a separate container If you provide the docker-compose.yml you using I can help you with how to set up the cron container. Or the docker compose examples right here can help you. https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml It should be like that
> 
> ```
> app:
>   image: nextcloud:apache
>   restart: always
>   ports:
>     - 127.0.0.1:8080:80
>   volumes:
>     - nextcloud:/var/www/html
>   environment:
>     - MYSQL_HOST=db
>     - REDIS_HOST=redis
>   env_file:
>     - db.env
>   depends_on:
>     - db
>     - redis
> 
> cron:
>   image: nextcloud:apache
>   restart: always
>   volumes:
>     - nextcloud:/var/www/html
>   entrypoint: /cron.sh
>   depends_on:
>     - db
>     - redis
> ```

mine doesn't work. i check the container log for the cron service and here's what i found:
`cron_1         | crond: file www-data:
cron_1         | crond:  line php -f /var/www/html/cron.php
cron_1         | crond: wakeup dt=60
cron_1         | crond: file www-data:
cron_1         | crond:  line php -f /var/www/html/cron.php
cron_1         | crond:  job: 0 php -f /var/www/html/cron.php
cron_1         | crond: child running /bin/bash
cron_1         | crond: USER www-data pid  17 cmd php -f /var/www/html/cron.php
cron_1         | Exception: Not installed in /var/www/html/lib/base.php:282
cron_1         | Stack trace:
cron_1         | #0 /var/www/html/lib/base.php(663): OC::checkInstalled(Object(OC\SystemConfig))
cron_1         | #1 /var/www/html/lib/base.php(1104): OC::init()
cron_1         | #2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
cron_1         | #3 {main}
cron_1         | crond: wakeup dt=10
`

**Comment by martadinata666** [comment]
The nextcloud volumes and cron volumes must inline

**Comment by wekaz** [comment]
> The nextcloud volumes and cron volumes must inline

already did

> `
>       - ./nextcloud_html:/var/www/html
> `

**Comment by martadinata666** [comment]
> > The nextcloud volumes and cron volumes must inline
> 
> already did
> 
> > `
> >       - ./nextcloud_html:/var/www/html
> > `

The config? The data? The custom?

**Comment by wekaz** [comment]
so i have to add these too?
> ```
>       - ./nextcloud_html:/var/www/html
>       - ./app/config:/var/www/html/config
>       - ./app/custom_apps:/var/www/html/custom_apps
>       - ./app/data:/var/www/html/data
>       - ./app/themes:/var/www/html/themes
>       - /etc/localtime:/etc/localtime:ro
> ```

**Comment by martadinata666** [comment]
> so i have to add these too?
> > ```
> >       - ./nextcloud_html:/var/www/html
> >       - ./app/config:/var/www/html/config
> >       - ./app/custom_apps:/var/www/html/custom_apps
> >       - ./app/data:/var/www/html/data
> >       - ./app/themes:/var/www/html/themes
> >       - /etc/localtime:/etc/localtime:ro
> > ```

Yes, because `/var/www/html` assuming that everything at that path, if you had separate mount for that then you also need to mount it too

**Comment by wekaz** [comment]
> 

yes, finally it works. thank you

**Comment by TopBanana123** [comment]
Sorry to revive an old issue, but I'm stumped by this. I setup the cron container about 15 mins ago and I'm still seeing this warning

![image](https://user-images.githubusercontent.com/43852644/189210625-1f231af7-99dc-4875-862f-806ebe760e21.png)

I see these logs in the cron container, look okay? To me it looks like it should be working

`crond: crond (busybox 1.30.1) started, log level 0
crond: user:www-data entry:(null)
100001000010000100001000010000100001000010000100001000010000
111111111111111111111111
11111111111111111111111111111111

111111111111
1111111
crond: user:www-data entry:(null)
100001000010000100001000010000100001000010000100001000010000
111111111111111111111111
11111111111111111111111111111111

111111111111
1111111
crond: wakeup dt=56
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  job: 0 php -f /var/www/html/cron.php
crond: child running /bin/bash
crond: USER www-data pid   7 cmd php -f /var/www/html/cron.php
Cannot write into "config" directory!
This can usually be fixed by giving the web server write access to the config directory.
But, if you prefer to keep config.php file read only, set the option "config_is_read_only" to true in it.
See https://docs.nextcloud.com/server/24/go.php?to=admin-config
crond: wakeup dt=10
crond: wakeup dt=50
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  job: 0 php -f /var/www/html/cron.php
crond: child running /bin/bash
crond: USER www-data pid   8 cmd php -f /var/www/html/cron.php
Cannot write into "config" directory!
This can usually be fixed by giving the web server write access to the config directory.
But, if you prefer to keep config.php file read only, set the option "config_is_read_only" to true in it.
See https://docs.nextcloud.com/server/24/go.php?to=admin-config
crond: wakeup dt=10
crond: wakeup dt=50
crond: file www-data:
`

Here is my compose file

```
version: '2'
    
services:
  db:
    container_name: nextcloud-db
    image: mariadb:10.5
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /media/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=

  app:
    container_name: nextcloud-app
    image: nextcloud
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - /media/nextcloud-docroot:/var/www/html
      - /media/nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_HOST=db	  
  cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    volumes:
      - /media/nextcloud-docroot:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
```

**Comment by TopBanana123** [comment]
Sorry to revive an old thread, but my cron container looks to be working as far as I can tell, but Nextcloud still complaints

Logs from the cron container

```
crond: crond (busybox 1.30.1) started, log level 0
crond: user:www-data entry:(null)
100001000010000100001000010000100001000010000100001000010000
111111111111111111111111
11111111111111111111111111111111

111111111111
1111111
crond: user:www-data entry:(null)
100001000010000100001000010000100001000010000100001000010000
111111111111111111111111
11111111111111111111111111111111

111111111111
1111111
crond: wakeup dt=52
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  job: 0 php -f /var/www/html/cron.php
crond: can't set groups: Operation not permitted
crond: USER www-data pid   7 cmd php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
```

And the error

![image](https://user-images.githubusercontent.com/43852644/189212812-9ca6df22-bd04-4bfc-8578-84744277ef65.png)

And my compose file

```
version: '2'
    
services:
  db:
    container_name: nextcloud-db
    image: mariadb:10.5
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /media/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hunter2
      - MYSQL_PASSWORD=hunter2
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    container_name: nextcloud-app
    image: nextcloud
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - /media/nextcloud-docroot:/var/www/html
      - /media/nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=hunter2
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db	  
  cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    user: "1000:1000"
    volumes:
      - /media/nextcloud-docroot:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
```

**Comment by megatonix** [comment]
for me cron is not working too, i don't know what to do anymore.
Here is my docker-compose:

`version: '3'

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:
    external: false

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
    - db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_PASSWORD=
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
    networks:
      - nextcloud_network

  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    networks:
      - nextcloud_network

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /docker/nextcloud/redis:/data
    networks:
      - nextcloud_network
    restart: unless-stopped`

![Cron](https://user-images.githubusercontent.com/56199368/190992153-033eae88-f77b-4e07-8d81-d9d07f447cac.png)

**Comment by Chimera20** [comment]
Found this page while looking up the same issue. After much trial and error, I found there is no need for an extra Container just to run Cron. The host OS is absolutely fine to run this task. However, what I found does contradict the Nextcloud documentation a bit. 

Running cron through _crontab -u www-data -e_ never quite worked for me. That could be a "me" problem as I missed something. 

Solution for me:
Edit the /etc/crontab file directly on the host OS, so the cron job becomes a system wide default but, still specify the user, and don't make _docker exec_ interactive. Drop the -it

My host OS /etc/crontab
*/5  *  *  *  * root /usr/bin/docker exec -u www-data nextcloud php -f /var/www/html/cron.php

Since this, I have had the little green light of joy showing on the web GUI for NC

**Comment by phatvnvc** [comment]
here is my yml file compose , please help me to run cron yml 

version: '3.7'

networks:
  vnvc-network:
    driver: bridge

volumes:
  disk-data:
    driver_opts:
      device: /home/nextcloud/db/
      type: none
      o: bind
  disk-app:
    driver_opts:
      device: /home/nextcloud/app/
      type: none
      o: bind

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - disk-data:/var/lib/mysql
    networks:
      - vnvc-network
#    ports:
#      - 27017:27017
    environment:
      - MYSQL_ROOT_PASSWORD=Vnvc@#HVT198
      - MYSQL_PASSWORD=Vnvc@HVT198
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    volumes:
      - disk-app:/var/www/html
    networks:
      - vnvc-network
    ports:
      - 8888:80
    environment:
      - MYSQL_PASSWORD=Vnvc@HVT198
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
    depends_on:
      - mariadb
   

Thanks a lots

**Comment by jjasoncool** [comment]
Dear all,

you can build your image below

```dockerfile
ARG NC_VERSION
FROM nextcloud:${NC_VERSION}

RUN apt-get install -y cron --no-install-recommends

# cron 
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
RUN echo '*/5 * * * * root /cron.sh >> /var/log/cron.log 2>&1' >> /etc/cron.d/cronjob
RUN chmod +x /etc/cron.d/cronjob
RUN touch /var/log/cron.log

CMD cron && php-fpm

```

**Comment by Glideh** [comment]
> so i have to add these too?
> 
> > ```
> >       - ./nextcloud_html:/var/www/html
> >       - ./app/config:/var/www/html/config
> >       - ./app/custom_apps:/var/www/html/custom_apps
> >       - ./app/data:/var/www/html/data
> >       - ./app/themes:/var/www/html/themes
> >       - /etc/localtime:/etc/localtime:ro
> > ```

I would use `volumes_from` to make sure every volumes are there

```yml
  cron:
    image: nextcloud:${VERSION}
    volumes_from:
      - nextcloud
    entrypoint: /cron.sh
```
