### ISSUE TITLE
Examples Improvement about cron

### ISSUE THREAD

**Issue by Karem-sobhy** [nextcloud/docker#1709]
after my issue https://github.com/nextcloud/server/issues/31373
and the fix was just to mount all volumes that are mounted in the app container to the cron container
thanks to https://github.com/nextcloud/server/issues/25852#issuecomment-997964401
so i wanted to suggest that all docker-compose examples
should be like that
```
cron:
    image: nextcloud:apache
    restart: always
    volumes_from:
      - app
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
```
instead of 
```
cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
```
I think that is more convenient to avoid such issues.
