### ISSUE TITLE
Imaginary Compose example

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/docker#1716]
nextcloud/server#24166 sounds promising. This is an opportunity to add experimental (and eventually, perhaps, official) examples for Nextcloud providers/administrators wishing to improve image thumbnail generation performance and security for container-capable deployments.

This issue is only a suggestion to add documentation so Imaginary can be easily tested. If it works out well maybe it will become a more permanent fixture.

**Comment by immanuelfodor** [comment]
The announcebent of this feature has come before the examples could have been provided? Well, subscribed to this issue

**Comment by Ornias1993** [comment]
It's absolutely trivial...
This seems to be all the code for kubernetes deployment at least:
```
image: {{ .Values.imaginaryImage.repository }}:{{ .Values.imaginaryImage.tag }}
imagePullPolicy: '{{ .Values.image.pullPolicy }}'
securityContext:
  runAsUser: 33
  runAsGroup: 33
  readOnlyRootFilesystem: true
  runAsNonRoot: true
ports:
  - containerPort: 9090
args: ["-enable-url-source"]
env:
  - name: 'PORT'
    value: '9090'
```
