### ISSUE TITLE
Docker Compose example for Elastic Search

### ISSUE THREAD

**Issue by keunes** [nextcloud/docker#1724]
Hello,

With the great help of the NC community I've started to use Docker Compose to run my Nextcloud instance. Now I would like to set up full text search. I already have installed the [Full text search](https://apps.nextcloud.com/apps/fulltextsearch) and the [Full text search - Files](https://apps.nextcloud.com/apps/files_fulltextsearch) apps (Core & Provider). Next step is is setting up the Platform app: [Full text search - Elasticsearch Platform](https://apps.nextcloud.com/apps/fulltextsearch_elasticsearch).

The [Platform app documentation](https://github.com/nextcloud/fulltextsearch_elasticsearch/wiki) refers to the Elastic Search docs for other than 'native' installation on Debian. The [single-node cluster instructions](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode) includes SSL set-up and all which isn't really necessary I guess (my whole NC instance is behind a reverse proxy). The [multi-node cluster instructions](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file) looks rather complex for me (I just started with Docker).

So I was wondering: would it be possible to provide an [example Docker Compose set-up](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb/apache) with Elastic Search in a separate container in the compose file (though with access to the NC application container, so I can correctly set the settings in the full-text search app)?

**Comment by martadinata666** [comment]
just add the elastic in your compose
```
es:
    image: elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - TZ=Asia/Jakarta
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
    user: 1000:1000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: 
      - nextcloud
    volumes:
      - ./esdata/data:/usr/share/elasticsearch/data
      - ./esdata/plugins:/usr/share/elasticsearch/plugins
```

`      - xpack.security.enabled=true` can be disable, but i prefer enable eitherway.
* exec into elastic install plugins. `bin/elasticsearch-plugin install ingest-attachment
`
* set password for elastic `bin/elasticsearch-reset-password interactive -u "http://localhost:9200"`
