### ISSUE TITLE
OBJECTSTORE_*_FILE via docker secrets

### ISSUE THREAD

**Issue by lukashartl** [nextcloud/docker#1726]
Hey 👋

I am trying to setup a docker-compose project for nextcloud+postgres+minio (s3).

The relevant part of my `docker-compose.yaml` looks like this:

```yaml
services:
  # ...

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - next_app:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db # works
      - POSTGRES_USER_FILE=/run/secrets/postgres_user # works
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password # works
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password # works
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user # works
      - OBJECTSTORE_S3_HOST=minio
      - OBJECTSTORE_S3_BUCKET=nextcloud
      - OBJECTSTORE_S3_KEY_FILE=/run/secrets/minio_user # not working
      - OBJECTSTORE_S3_SECRET_FILE=/run/secrets/minio_password # not working
      - OBJECTSTORE_S3_PORT=9000
      - OBJECTSTORE_S3_SSL=false
      - OBJECTSTORE_S3_USEPATH_STYLE=true
      - OBJECTSTORE_S3_LEGACYAUTH=true
      - OBJECTSTORE_S3_AUTOCREATE=true
    depends_on:
      - db
      - minio
    secrets:
      - minio_user
      - minio_password
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
# ...
```

I noticed, that the relevant configuration parameters keep being empty in the generated `config.php`, because nextcloud does not consider them coming from docker secrets:

https://github.com/nextcloud/docker/blob/da935d26bb87bec2708ba31ff1153ed62b05c7d4/23/apache/config/s3.config.php#L1-L27
