### ISSUE TITLE
relation "oc_appconfig" does not exist - after upgrade

### ISSUE THREAD

**Issue by audishos** [nextcloud/docker#1727]
Hello,

I recently upgraded the official nextcloud docker image and am seeing the following error in my postgres container:

```log
nextcloud-db   | 2022-03-30T23:05:15.148157583Z 2022-03-30 19:05:15.147 EDT [596] STATEMENT:  SELECT * FROM "oc_appconfig"
nextcloud-db   | 2022-03-30T23:06:15.631029015Z 2022-03-30 19:06:15.630 EDT [599] ERROR:  relation "oc_appconfig" does not exist at character 15
```

When attempting to access the web interface, it says to check the logs. For some reason, `nextcloud.log` is empty.

This is the error I'm seeing on the front end
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

The following is the relevant portion of my docker-compose file with sensitive information obscured:

```yml
version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - services
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    depends_on:
      - proxy
    networks:
      - services
    volumes_from:
      - proxy
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    restart: unless-stopped

  db:
    image: arm32v7/postgres:14
    container_name: nextcloud-db
    networks:
      - services
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=*******
      - POSTGRES_DB=nextcloud
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    networks:
      - services
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/10tb/nextcloud/config:/var/www/html/config
      - /mnt/10tb/nextcloud/custom_apps:/var/www/html/custom_apps
      - /mnt/10tb/nextcloud/data:/var/www/html/data
      - /mnt/10tb/nextcloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=*******
      - VIRTUAL_HOST=*******
      - LETSENCRYPT_HOST=*******
      - LETSENCRYPT_EMAIL=*******
      - HTTP_X_FORWARDED_HOST=*******
      - HTTP_X_FORWARDED_PROTO=ssl
      - NEXTCLOUD_TRUSTED_DOMAINS=*******
    restart: unless-stopped

volumes:
  nextcloud:
  db:
  acme:

networks:
  services:
```

I tried searching around, but couldn't find a relevant solution to my issue. While troubleshooting, I did notice that there was some incorrect information in my `config.php` file. This was resulting in `role not found` (wrong username) and `password incorrect` (wrong password) errors in the postgres container. These config values did not match those in the `docker-compose` file listed above. I manually corrected these values in the config which resulted in the `oc_appconfig` error above.

Any help is appreciated!
