### ISSUE TITLE
[Bug]: Upgrade 23.0.3 to 23.0.4 docker Server does not migrate

### ISSUE THREAD

**Issue by Y0ngg4n** [nextcloud/docker#1742]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If i want to update my docker Nextcloud installation i get the following issue, that it is waiting forever. But there is no other process running nextcloud.

```
Configuring Redis as session handler
Initializing nextcloud 23.0.4.1 ...
Upgrading nextcloud from 23.0.3.2 ...
Another process is initializing Nextcloud. Waiting 10 seconds...
Another process is initializing Nextcloud. Waiting 20 seconds...
Another process is initializing Nextcloud. Waiting 30 seconds...
Another process is initializing Nextcloud. Waiting 40 seconds...
Another process is initializing Nextcloud. Waiting 50 seconds...
Another process is initializing Nextcloud. Waiting 60 seconds...
Another process is initializing Nextcloud. Waiting 70 seconds...
Another process is initializing Nextcloud. Waiting 80 seconds...
```

### Steps to reproduce

1. Upgrade docker install from 23.0.3.2 to 23.0.4

### Expected behavior

Just upgrade it

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
accessibility  cloud_federation_api  dav                   files             files_sharing      firstrunwizard           notifications    privacy           settings       systemtags             updatenotification  weather_status
activity       comments              encryption            files_external    files_trashbin     logreader                oauth2           provisioning_api  sharebymail    text                   user_ldap           workflowengine
admin_audit    contactsinteraction   federatedfilesharing  files_pdfviewer   files_versions     lookup_server_connector  password_policy  recommendations   support        theming                user_status
circles        dashboard             federation            files_rightclick  files_videoplayer  nextcloud_announcements  photos           serverinfo        survey_client  twofactor_backupcodes  viewer
```

### Nextcloud Logs

```shell
Log is empty
```

**Comment by Mape6** [comment]
I have the exact the same problem. Updated from 23.0.3 to 23.0.4 with same log entries.
I reverted to old image and nextcloud is running again.

**Comment by Y0ngg4n** [comment]
I did the same. I will stick with the older version until this Bug gets fixed.

**Comment by skjnldsv** [comment]
Thanks for reporting. Let's investigate

**Comment by skjnldsv** [comment]
Can anyone here share their setup? How many containers are you running? Are you sharing the html volume between those?

**Comment by Mape6** [comment]
I have docker running on a raspberry pi and manage my containers via docker compose.
I have only one postgres and one nextcloud and one redis container running.

here is my docker compose file content:
```
volumes:
  data:
  db:

networks:
  frontend:
    name: nc_frontend
  backend:
    name: nc_backend
  reverse-proxy:
    external: true

services:
  postgres:
    container_name: nc_postgres
    image: postgres
    hostname: nc_postgres
    restart: unless-stopped
    command: --transaction-isolation="read committed"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=xxx
    networks:
      backend:

  redis:
    container_name: nc_redis
    image: redis
    restart: unless-stopped
    networks:
      backend:

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - data:/var/www/html
    environment:
      POSTGRES_HOST: nc_postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: xxx
      NEXTCLOUD_TRUSTED_DOMAINS: xxx
      NEXTCLOUD_TRUSTED_PROXIES: 172.29.0.0/16
      DEFAULT_LANGUAGE: de
      DEFAULT_LOCALE: de
      REDIS_HOST: redis
      MEMCACHE.LOCAL: \OC\Memcache\Redis
      MEMCACHE.LOCKING: \OC\Memcache\Redis
    networks:
      frontend:
      backend:
      reverse-proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse-proxy
      # http
      - traefik.http.routers.nextcloud.rule=Host(`xxx`)
      - traefik.http.routers.nextcloud.entrypoints=web
      - traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect,hsts-header
      # https
      - traefik.http.routers.nextcloud-https.rule=Host(`xxx`)
      - traefik.http.routers.nextcloud-https.entrypoints=websecure
      - traefik.http.routers.nextcloud-https.tls=true
      - traefik.http.routers.nextcloud-https.tls.certresolver=myresolver
      - traefik.http.routers.nextcloud-https.tls.options=default2@file
      - traefik.http.routers.nextcloud-https.middlewares=hsts-header
      # https redirect
      - traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.permanent=true
      # hsts
      - traefik.http.middlewares.hsts-header.headers.stsSeconds=31536000
      - traefik.http.middlewares.hsts-header.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.hsts-header.headers.stsPreload=true
      - traefik.http.middlewares.hsts-header.headers.forceSTSHeader=true
      
      - flame.type=application
      - flame.name=Nextcloud
      - flame.url=https://xxx
      - flame.icon=nextcloud
```

**Comment by wivaku** [comment]
`docker-compose.yaml`
```
version: '2'

# volumes:
#   nextcloud:
#   db:

services:
  db:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      # - db:/var/lib/mysql
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: .
    # image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 1100:80
    links:
      - db
    volumes:
      - ./web:/var/www/html
      - ./data:/var/www/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      # ---
      - NEXTCLOUD_DATA_DIR=/var/www/data
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      #- TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEHOST=${OVERWRITEHOST}
      - OVERWRITEPROTOCOL=https
      # ---
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
```

`Dockerfile`
```
FROM nextcloud:apache

RUN apt-get update && apt-get install -y \
	supervisor \
	procps smbclient \
	imagemagick \
	ocrmypdf \
	tesseract-ocr \
	tesseract-ocr-eng \ 
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* \
	&& mkdir /var/log/supervisord /var/run/supervisord

COPY build/supervisord.conf /

ENV NEXTCLOUD_UPDATE=1

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
```

**Comment by fdalvi** [comment]
> same here, upgrade breaks on 23. Can't specify a lower version in the 23 branch, my installation is completely down.

@scrummie02 Hope this helps: Locally, docker image `nextcloud:23.0.3` is available to pull and works fine while `latest` does not

**Comment by scrummie02** [comment]
> nextcloud:23.0.3

```
 [core:crit] [pid 1] (13)Permission denied: AH00078: alloc_listener: failed to get a socket for (null)
AH00526: Syntax error on line 5 of /etc/apache2/ports.conf:
Listen setup failed
```

I'm getting this now.

**Comment by scrummie02** [comment]
Can't even get into the docker container at all now, says it's not started even though it shows up.  What a disaster

**Comment by jokay** [comment]
I can confirm this problem for the update to **24.0.0.12** as well.

```sh
Configuring Redis as session handler
Initializing nextcloud 24.0.0.12 ...
Upgrading nextcloud from 23.0.3.2 ...
Another process is initializing Nextcloud. Waiting 10 seconds...
Another process is initializing Nextcloud. Waiting 20 seconds...
Another process is initializing Nextcloud. Waiting 30 seconds...
Another process is initializing Nextcloud. Waiting 40 seconds...
Another process is initializing Nextcloud. Waiting 50 seconds...
Another process is initializing Nextcloud. Waiting 60 seconds...
```

**Comment by skjnldsv** [comment]
Can anyone try to manually remove the lock file in your html directory and try again?
`/var/www/html/nextcloud-init-sync.lock`

I have no idea why this file would be created and not deleted after initialization.
Maybe something got wrong in your compose start process and you killed it?

One this file is deleted, the process will start again

**Comment by jokay** [comment]
@skjnldsv thx, this did work 👍🏼 

```sh
Configuring Redis as session handler
Initializing nextcloud 24.0.0.12 ...
Upgrading nextcloud from 23.0.3.2 ...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: twofactor_totp
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.12.0
Updating <oauth2> ...
Updated <oauth2> to 1.12.0
Updating <files> ...
Updated <files> to 1.19.0
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.7.0
Updating <dav> ...
Fix broken values of calendar objects

 Starting ...

Clean up old calendar subscriptions from deleted users that were not cleaned-up

    0/0 [>---------------------------]   0% Starting ...

Updated <dav> to 1.22.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.6.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.14.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.14.0
Updating <settings> ...
Updated <settings> to 1.6.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.13.0
Updating <viewer> ...
Updated <viewer> to 1.8.0
Update app twofactor_totp from App Store
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
The following apps have been disabled:
Initializing finished
```

**Comment by skjnldsv** [comment]
So, this is the issue with a lockfile, I don't think we can really detect if it has been created by accident or if the process that was using it, is actually still running? Anyone have ideas?
I would like to understand why it actually got created for any of you, but not deleted. Aside from killing the process, I cannot see why :thinking:

**Comment by scrummie02** [comment]
> Can anyone try to manually remove the lock file in your html directory and try again? `/var/www/html/nextcloud-init-sync.lock`
> 
> I have no idea why this file would be created and not deleted after initialization. Maybe something got wrong in your compose start process and you killed it?
> 
> One this file is deleted, the process will start again ending the `Another process is initializing Nextcloud. Waiting xxx seconds...` loop

I'll try

**Comment by scrummie02** [comment]
> So, this is the issue with a lockfile, I don't think we can really detect if it has been created by accident or if the process that was using it, is actually still running? Anyone have ideas? I would like to understand why it actually got created for any of you, but not deleted. Aside from killing the process, I cannot see why 🤔

didn't work for me...it comes back.

**Comment by skjnldsv** [comment]
> > So, this is the issue with a lockfile, I don't think we can really detect if it has been created by accident or if the process that was using it, is actually still running? Anyone have ideas? I would like to understand why it actually got created for any of you, but not deleted. Aside from killing the process, I cannot see why thinking
> 
> didn't work for me...it comes back.

I comes back if you have another container starting with the same shared html

**Comment by scrummie02** [comment]
`Initializing nextcloud 23.0.4.1 ...
Upgrading nextcloud from 23.0.3.2 ...
su: System error
rsync: [sender] pipe: Permission denied (13)
rsync error: error in IPC code (code 14) at pipe.c(121) [sender=3.2.3]
Configuring Redis as session handler
Initializing nextcloud 23.0.4.1 ...
Upgrading nextcloud from 23.0.3.2 ...
su: System error
Another process is initializing Nextcloud. Waiting 10 seconds...`

**Comment by scrummie02** [comment]
> > > So, this is the issue with a lockfile, I don't think we can really detect if it has been created by accident or if the process that was using it, is actually still running? Anyone have ideas? I would like to understand why it actually got created for any of you, but not deleted. Aside from killing the process, I cannot see why thinking
> > 
> > 
> > didn't work for me...it comes back.
> 
> I comes back if you have another container starting with the same shared html

Thanks for replying...Here is my compose:

```
version: '3.3'

networks:
 nextcloud:

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-app
    #labels:
     # - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - nextcloud
    ports:
      - "8080:80"
    volumes:
      - /data/Docker/nextcloud/html:/var/www/html
      - /data/Docker/nextcloud/data:/srv/nextcloud/data
    depends_on:
      - mariadb
      - redis
      - av
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS='${NEXTCLOUD_FQDN}'
      - NEXTCLOUD_DATA_DIR=/srv/nextcloud/data
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxxx
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextcloud-mariadb
      - REDIS_HOST=nextcloud-redis
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5
    container_name: nextcloud-mariadb
    restart: unless-stopped
    volumes:
      - /data/Docker/nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=xxxx
      - MYSQL_USER=xxxx
    networks:
      - nextcloud

  redis:
    image: redis:6.2-alpine
    container_name: nextcloud-redis
    networks:
      - nextcloud
    restart: unless-stopped
      
  av:
    #debian: image: mkodockx/docker-clamav
    image: mkodockx/docker-clamav:alpine
    container_name: nextcloud-av
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - nextcloud
    ports:
      - "3310:3310"
    volumes:
      - clamav:/var/lib/clamav
```

**Comment by skjnldsv** [comment]
> What do you mean shared HTML?

`/data/Docker/nextcloud/html`, stop the nextcloud app service, delete the file, and run the nextcloud app service up again.
It will be created, but it is fine. What is not fine is if the file already exists _before_ the container starts

**Comment by wivaku** [comment]
Removing the lock file worked, thanks @skjnldsv!

**Comment by scrummie02** [comment]
> > What do you mean shared HTML?
> 
> `/data/Docker/nextcloud/html`:
> 
> 1. stop the nextcloud app service
> 2. delete the file
> 3. and run the nextcloud app service up again.
> 
> It will be created, but it is fine. What is not fine is if the file already exists _before_ the container starts

it's a host directory so remove all the contents?

**Comment by scrummie02** [comment]
okay stopped the container and deleted the lockfile; restarted it.

  Then this:
```
Initializing nextcloud 23.0.4.1 ...
Upgrading nextcloud from 23.0.3.2 ...
su: System error
Another process is initializing Nextcloud. Waiting 10 seconds...
```

**Comment by skjnldsv** [comment]
Seems like you are facing another unrelated issue :thinking:

**Comment by scrummie02** [comment]
> Seems like you are facing another unrelated issue 🤔

When I do delete it, it comes back and the same error.

**Comment by florentls** [comment]
I did get the same, upgrade from 22.2.7 to 23.0.4 and I get the issue.
Downgrade to 23.0.3 fix the issue.

**Comment by Mape6** [comment]
I removed the lock file and recreated the container with image of 23.0.4 and got the following log output:

Configuring Redis as session handler
Upgrading nextcloud from 23.0.3.2 ...
Initializing nextcloud 23.0.4.1 ...
touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted

The new lock file was created:
-rw-r--r-- 1 root root 0 May  8 10:35 nextcloud-init-sync.lock

Any hints to solve that problem?

**Comment by scrummie02** [comment]
> I removed the lock file and recreated the container with image of 23.0.4 and got the following log output:
> 
> ```
> 
> Configuring Redis as session handler
> 
> Upgrading nextcloud from 23.0.3.2 ...
> 
> Initializing nextcloud 23.0.4.1 ...
> 
> touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted
> 
> ```
> 
> The new lock file was created:
> 
> ```
> 
> -rw-r--r-- 1 root root 0 May  8 10:35 nextcloud-init-sync.lock
> 
> ```
> 
> Any hints to solve that problem?

Something similar to me.  

Are you using hair directories for your volumes?  I posted my compose and its still broken, been a week now I think I'm moving to filerun

**Comment by Mape6** [comment]
> Are you using hair directories for your volumes? I posted my compose and its still broken, been a week now I think I'm moving to filerun

I don't know what hair directories are. What is that?
You can find my compose file [here](https://github.com/nextcloud/docker/issues/1742#issuecomment-1117109426)

**Comment by bmltp** [comment]
> 
I just renamed(and later deleted) and the upgrade was successful.

Just in case if anyone need this

`docker exec -it nextcloud_container_name sh`
Just do ls first
`ls`
and rename or remove nextcloud-init-sync.lock
`mv nextcloud-init-sync.lock nextcloud-init-sync.nolock`
or
`rm nextcloud-init-sync.lock`

stop container

`docker-compose -f docker-composer.yml down`
start agian without -d to see logs straight
`docker-compose -f docker-composer.yml up`
wait for upgrade
once upgrade sucess.
stop and start in background
`docker-compose -f docker-composer.yml up -d`

**Comment by skjnldsv** [comment]
I still don't get how that could happen, maybe we should put that feature as optional.

**Comment by revilo951** [comment]
removing the lock file resolved it for me too

**Comment by GregorB54321** [comment]
tried to update TODAY from nextcloud:22-apache to 23.0.4.1. But Problem with the lock-file was already existing...
-rw-r--r-- 1 root     root     0 **Mai  4** 23:21 nextcloud-init-sync.lock

renamed that file after "waiting 90s".
Then there was need for restart.

`
Initializing nextcloud 23.0.4.1 ...
Upgrading nextcloud from 22.2.7.1 ...
Another process is initializing Nextcloud. Waiting 10 seconds...
[..]
Another process is initializing Nextcloud. Waiting 90 seconds...
The other process is done, assuming complete initialization
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.8. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.8. Set the 'ServerName' directive globally to suppress this message
[Fri May 13 20:15:07.906248 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/8.0.18 configured -- resuming normal operations
[Fri May 13 20:15:07.906318 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
127.0.0.1 - - [13/May/2022:20:15:37 +0000] "GET /status.php HTTP/1.1" 200 1729 "-" "curl/7.74.0"

[...]

[Fri May 13 20:16:42.681183 2022] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
Configuring Redis as session handler
Initializing nextcloud 23.0.4.1 ...
Upgrading nextcloud from 22.2.7.1 ...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
[...]
Initializing finished
    0/0 [----->----------------------]   0%AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.5. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.5. Set the 'ServerName' directive globally to suppress this message
[Fri May 13 20:19:49.976084 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/8.0.18 configured -- resuming normal operations
[Fri May 13 20:19:49.976155 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
127.0.0.1 - - [13/May/2022:20:20:25 +0000] "GET /status.php HTTP/1.1" 200 1731 "-" "curl/7.74.0"
`

but I could not find any logfiles regarding previous updates...

Best regards, Gregor

**Comment by mklemme1** [comment]
Hallo 
I had the same problem today upgrading from  23.0.4 to  23.0.5.
I do not remember any problems in earlier updates.
I got around it by deleting the lockfile as described above.

The [entry script](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh)  checks if "Another process is initializing Nextcloud." Who could that be?
Would it be safe to delete the lockfile first in the entry script?

**Comment by protree** [comment]
Hi,

had the same problem updating from 22.2.7.1 to 22.2.8.1. The "nextcloud-init-sync.lock" on my system was created during the previous update according to its timestamp. This previous update failed because of the "Allowed memory size of xxx bytes exhausted" and I had to run "occ upgrade" manually.

After removing the "nextcloud-init-sync.lock" file the update went smooth.

**Comment by meonkeys** [comment]
Related discussion: https://help.nextcloud.com/t/upgrade-locking-nextcloud-init-sync-lock-another-process-is-initializing-ephemeral-vs-persistent-lock/139412

**Comment by meonkeys** [comment]
Maybe we can avoid having to manually delete `nextcloud-init-sync.lock` if an upgrade fails halfway.

Please see: https://github.com/nextcloud/docker/issues/1756

Feedback appreciated!

**Comment by Mape6** [comment]
I did another investigation and deleted the lock file many times.
After some time I found out that if I run the nextcloud container as priviliged, the error `touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted` does not happen again and I could upgrade to 23.0.4.

**Comment by Mape6** [comment]
Regarding [docker-entrypoint.sh](https://github.com/nextcloud/docker/blob/35b8ebf954e7b55a1d1d61a8ea05bd7452abbd53/docker-entrypoint.sh#L121) The command runs as root not as www-data. I'm not really sure but wouldn't it be better if it is executed with `runs_as 'touch $lock'`

**Comment by apjyotirmay** [comment]
Facing the same issue, tried upgrading from 23.0.5 to 24.0.1

*docker-compose.yml*
```yaml
version: '2'

volumes:
  redis:
    driver: local

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.nextcloud
    restart: always
    container_name: nc_app
    working_dir: /var/www/html
    depends_on:
      - redis
      - db
    networks:
      - nextcloud
    volumes:
      - <redacted>
    environment:
      - MYSQL_PASSWORD=<redacted>
      - MYSQL_DATABASE=<redacted>
      - MYSQL_USER=<redacted>
      - MYSQL_HOST=db
      - REDIS_HOST=redis

  db:
    build:
      context: ./
      dockerfile: Dockerfile.mariadb
    container_name: nc_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<redacted>
      - MYSQL_PASSWORD=<redacted>
      - MYSQL_DATABASE=<redacted>
      - MYSQL_USER=<redacted>

  redis:
    image: redis:6.2-alpine
    container_name: nc_redis
    restart: always
    networks:
      - nextcloud

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nc_web
    restart: unless-stopped
    working_dir: /var/www/html
    networks:
      - nextcloud
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    volumes_from:
      - app

networks:
  nextcloud:
    external: true

```

*Dockerfile.nextcloud*
```Dockerfile
FROM nextcloud:24.0.1-fpm-alpine
RUN apk --no-cache add shadow && \
    groupmod --gid 1001 www-data && \
    usermod --uid 1000 www-data
```

*Dockerfile.mariadb*
```Dockerfile
FROM mariadb:10.7
RUN groupmod --gid 1001 mysql && \
    usermod --uid 1000 mysql
```
