### ISSUE TITLE
external storage wants to bind directory IN the docker container

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/docker#1746]
the external directory must be mounted as an internal directory of the docker to make it available as "external storage".
docker run  --mount type=bind,source="$(pwd)"/data,target=/home/data -it <name_of_container>

it could be a default directory "/opt/containers/nextcloud/externals" which is make available inside the container and the actual external data is "/opt/containers/nextcloud/externals/sym_link_1", "/opt/containers/nextcloud/externals/sym_link_2" ...

**Comment by ferdiga** [comment]
I would be happy to learn how to configure this with traefik

**Comment by ferdiga** [comment]
found a work around: 
(takes a bit longer to build)

docker-compose.yml
```
  nextcloud-app:
#    image: nextcloud
    build:
      context: .
      dockerfile: Dockerfile

```      
Dockerfile
```
FROM nextcloud
RUN apt-get update && apt-get install -y smbclient
```
