### ISSUE TITLE
ssl not working when trying to use example

### ISSUE THREAD

**Issue by badgerhill** [nextcloud/docker#181]
hi,

i am trying ot use this example:
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml which also should enable ssl out of the box.

i can create a database and connect to nextcloud using http. using https is not working - unable to connect. seems that nothing is listening on 443.
what am i missing?

this is my docker-compose.yml file:

```
version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /home/demo/nextcloud/db:/var/lib/postgresql/data
    env_file:
      - db.env

  app:  
    image: nextcloud:fpm
    restart: always
    volumes:
      - /home/demo/nextcloud/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    volumes:
      - /home/demo/nextcloud/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=demo.dachsberg.at
      - LETSENCRYPT_HOST=demo.mydomain.at
      - LETSENCRYPT_EMAIL=demo@mydomain.at
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 8080:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
      - DEFAULT_HOST=debian.dachsberg.at
    volumes:
      - /home/demo/nextcloud/certs:/etc/nginx/certs:ro
      - /home/demo/nextcloud/conf.d:/etc/nginx/conf.d
      - /home/demo/nextcloud/vhost.d:/etc/nginx/vhost.d
      - /home/demo/nextcloud/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /home/demo/nextcloud/certs:/etc/nginx/certs
      - /home/demo/nextcloud/conf.d:/etc/nginx/conf.d
      - /home/demo/nextcloud/vhost.d:/etc/nginx/vhost.d
      - /home/demo/nextcloud/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  nextcloud:
  certs:
  conf.d:
  vhost.d:
  html:

networks:
  proxy-tier:

```
`
