### ISSUE TITLE
Unable to login with iOS, but web interface working with data folder mounted to local NAS

### ISSUE THREAD

**Issue by dijikul** [nextcloud/docker#1828]
Following the example provided here https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml I have an encrypted instance of Nextcloud working, with one slight modification of attempting to mount the /var/www/html/data partition to a NAS on my local network.

The network mount is working and upon initial user setup I see the user folder being created, but when attempting to login with the iOS App it fails stating `Access Forbidden, Invalid Request`.

Within the Settings -> Overview page as an admin, the following is shown, but the doc link is dead: 
![image](https://user-images.githubusercontent.com/2670528/192162381-9a6561d0-af4a-41a9-b0a2-016630f319bc.png)

Similarly, none of the User Manuals work from https://docs.nextcloud.com/ making troubleshooting difficult.

Others online report issues with their reverse proxy which mirrors the screenshot, but it's unclear to me why it says the data folder is not writeable after it creates my user folders, and the folders is mounted successfully.

Currently the NAS folder is only mounted to the App server in the docker-compose file.  Is it also required to mount to the Web server as read-only?

Thanks in advance for any guidance.

**Comment by martadinata666** [comment]
idk permission of the NAS you are talking, but for reference the docker will use `www-data` user with `uid` and `gid` 33.

**Comment by dijikul** [comment]
> idk permission of the NAS you are talking, but for reference the docker will use `www-data` user with `uid` and `gid` 33.

Within the docker-compose.yml I've specified to mount the volume as so: 


```
...
  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
...

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:
  data:
    driver_opts:
      type: cifs
      o: "username=[myuser],password=[mypassword],rw,uid=82,forceuid,gid=82,forcegid,file_mode=0770,dir_mode=0770"
      device: "//192.168.1.69/the Matrix/NextCloud"
```

The volume mounts successfully but the UID was 82 of the www-data user inside the App container, when I checked.  Is it correct that only the APP Server requires mounting a data volume?

What's also confusing, is Nextcloud can definitely write to this share, as it's created my user folders, so it's unclear to me if the access is caused by the App server mount, or one of the other servers not having the mount added.
