### ISSUE TITLE
Postgres example stack doesn't start

### ISSUE THREAD

**Issue by wolkenschieber** [nextcloud/docker#1845]
The postgres stack example on [docker-hub](https://hub.docker.com/_/nextcloud) isn't starting. It seems that there's a permission issue with `postgres:latest`/`postgres:15`:

```
nextcloud-app-1  | New nextcloud instance
nextcloud-app-1  | Installing with PostgreSQL database
nextcloud-app-1  | Starting nextcloud installation
nextcloud-db-1   | 2022-10-22 08:59:25.554 UTC [69] ERROR:  permission denied for schema public at character 14
nextcloud-db-1   | 2022-10-22 08:59:25.554 UTC [69] STATEMENT:  CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))
nextcloud-app-1  | Error while trying to initialise the database: An exception occurred while executing a query: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema public
nextcloud-app-1  | LINE 1: CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, versi...
nextcloud-app-1  |                      ^
nextcloud-app-1  | Trace: #0 /var/www/html/3rdparty/doctrine/dbal/src/Connection.php(1780): Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
nextcloud-app-1  | #1 /var/www/html/3rdparty/doctrine/dbal/src/Connection.php(1719): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
nextcloud-app-1  | #2 /var/www/html/3rdparty/doctrine/dbal/src/Connection.php(1067): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'CREATE TABLE oc...', Array, Array)
nextcloud-app-1  | #3 /var/www/html/lib/private/DB/Connection.php(261): Doctrine\DBAL\Connection->executeQuery('CREATE TABLE oc...', Array, Array, NULL)
nextcloud-app-1  | #4 /var/www/html/3rdparty/doctrine/dbal/src/Connection.php(1809): OC\DB\Connection->executeQuery('CREATE TABLE oc...')
nextcloud-app-1  | #5 /var/www/html/lib/private/DB/Migrator.php(162): Doctrine\DBAL\Connection->query('CREATE TABLE oc...')
nextcloud-app-1  | #6 /var/www/html/lib/private/DB/Migrator.php(69): OC\DB\Migrator->applySchema(Object(Doctrine\DBAL\Schema\Schema))
nextcloud-app-1  | #7 /var/www/html/lib/private/DB/Connection.php(582): OC\DB\Migrator->migrate(Object(Doctrine\DBAL\Schema\Schema))
nextcloud-app-1  | #8 /var/www/html/lib/private/DB/MigrationService.php(168): OC\DB\Connection->migrateToSchema(Object(Doctrine\DBAL\Schema\Schema))
nextcloud-app-1  | #9 /var/www/html/lib/private/DB/MigrationService.php(182): OC\DB\MigrationService->createMigrationTable()
nextcloud-app-1  | #10 /var/www/html/lib/private/DB/MigrationService.php(255): OC\DB\MigrationService->getMigratedVersions()
nextcloud-app-1  | #11 /var/www/html/lib/private/DB/MigrationService.php(433): OC\DB\MigrationService->getMigrationsToExecute('latest')
nextcloud-app-1  | #12 /var/www/html/lib/private/DB/MigrationService.php(408): OC\DB\MigrationService->migrateSchemaOnly('latest')
nextcloud-app-1  | #13 /var/www/html/lib/private/Setup/AbstractDatabase.php(153): OC\DB\MigrationService->migrate('latest', true)
nextcloud-app-1  | #14 /var/www/html/lib/private/Setup.php(371): OC\Setup\AbstractDatabase->runMigrations()
nextcloud-app-1  | #15 /var/www/html/core/Command/Maintenance/Install.php(105): OC\Setup->install(Array)
nextcloud-app-1  | #16 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-app-1  | #17 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-app-1  | #18 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-app-1  | #19 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-app-1  | #20 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
nextcloud-app-1  | #21 /var/www/html/console.php(100): OC\Console\Application->run()
nextcloud-app-1  | #22 /var/www/html/occ(11): require_once('/var/www/html/c...')
nextcloud-app-1  | #23 {main}
```

Following compose file reproduces the issue:
```yaml
version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=appdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - NEXTCLOUD_ADMIN_PASSWORD=somepassword
      - NEXTCLOUD_ADMIN_USER=admin
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  db:
  nextcloud:
```
