### ISSUE TITLE
Change Default App Folder

### ISSUE THREAD

**Issue by biladina** [nextcloud/docker#1850]
hi, how to change default app folder from `/var/www/html` to something like `/var/www/html/cloud`..

I already search every document and I can't find how to change the default app folder..
why I ask this, because I am using `VIRTUAL_PATH` with [nginx-proxy/nginx-proxy](https://github.com/nginx-proxy/nginx-proxy)..
and the expected result is like this when access the cloud : `http://192.168.2.5/cloud`

this is my `docker-compose.yml` file :
```
version: '3.2'

services:
  cloud:
    image: nextcloud:stable-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html/cloud
    environment:
      VIRTUAL_HOST: 192.168.2.5
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /cloud
    env_file:
      - variables.env
    expose:
      - 80
      - 443

networks:
  default:
    name: nginx-proxy
    external: true
```

if I compose the docker, it always restart and this is the logs :
```
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Initializing nextcloud 24.0.6.1 ...
rsync: [generator] delete_file: rmdir(cloud) failed: Device or resource busy (16)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
```
