### ISSUE TITLE
Fix cron container by using `volumes_from`

### ISSUE THREAD

**Issue by relikd** [nextcloud/docker#1851]
I suggest replacing:

https://github.com/nextcloud/docker/blob/de77074a55a7d181276de5cddf9fbdb5b9e56f3e/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml#L37-L41

with:

```yml
volumes_from:
  - app
```

instead of using a direct volume mapping. (and for all example configs)

I had to debug this issue for the last two days and this all could be avoided with the proper config.
In particular, cron has no write access to the filesystem if you do not import all the same volumes.
E.g., I had this config and thought it would be enough to only import the main volume without the individual volumes within the parent volume.

```yaml
cron:
  volumes:
    - nextcloud:/var/www/html
app:
  volumes:
    - nextcloud:/var/www/html
    - ./data:/var/www/html/data
    - ./config:/var/www/html/config
    - ./custom_apps:/var/www/html/custom_apps
```
But it turns out, whenever you open a volume within another volume, the cron container will not see the content of the data, config, and custom_apps directories.

**Comment by orangelynx** [comment]
`volumes_from` is not supported by docker running in swarm mode. This is perhaps going off-topic, but I'd love to see example configurations which also work for docker swarm mode. I say this well aware that docker swarm is dying / dead and that a proper, fully distributed setup (if even possible for nextcloud) would require an even more complex docker-compose file, which is likely not in the interest of this community.

Nevertheless, for people like me, running swarm and having some services just replicated on a single host, it would be nice to have a starting point that is at least compatible with swarm mode.

**Comment by skarekrow** [comment]
This just saved me a lot more time debugging. I already wasted a fair bit since the container logs show it running just fine, but the WebUI doesn't :joy: thank you!

**Comment by joshtrichards** [comment]
HI @relikd - Thanks for your report. Yes, all volumes need to match on the app and cron containers - just like in the example provided. This is more a general Docker configuration matter:

https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference

As for using `volumes_from` - it is deprecated and not even supported in more recent Compose files:

https://docs.docker.com/compose/compose-file/compose-versioning/#version-3
https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading

`volumes` is the correct alternative.

**Comment by relikd** [comment]
And how exactly should the config file look like without `volumes_from`? I stated in the example above that it will break functionality as soon as you add other volume mappings to the app (but not cron). This is not reflected in the example config. Users might want to add custom volumes to the app – not realizing they will break cron that way.

**Comment by martadinata666** [comment]
All volumes in `app` and `cron` should in sync
```
cron:
  volumes:
    - nextcloud:/var/www/html
    - ./data:/var/www/html/data
    - ./config:/var/www/html/config
    - ./custom_apps:/var/www/html/custom_apps
app:
  volumes:
    - nextcloud:/var/www/html
    - ./data:/var/www/html/data
    - ./config:/var/www/html/config
    - ./custom_apps:/var/www/html/custom_apps
```
