### ISSUE TITLE
Container crashes on start - Config variable ${APACHE_RUN_DIR} is not defined

### ISSUE THREAD

**Issue by eltomato89** [nextcloud/docker#1859]
I am running 25.0.1-apache on my k8s cluster at home.

It was working for some time but suddenly it stopped working for whatever reason.

Pod says "CrashLoopBackOff" and refuses to start.

I have set a new entrypoint to `tail -f /dev/null` and connected into the container.
When trying to run `apache2`, following error message appears:

```
[Tue Nov 15 17:22:42.620163 2022] [core:warn] [pid 19] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot

```

When I set `APACHE_RUN_DIR`, the next `APACHE_` ENV is missing .. 

env gives the following output
```
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
NEXTCLOUD_SERVER_PORT_80_TCP=tcp://10.152.183.46:80
HOSTNAME=nextcloud-server-7f7f7f5d5-lf5gf
PHP_VERSION=8.1.12
APACHE_CONFDIR=/etc/apache2
NEXTCLOUD_VERSION=25.0.1
PHP_INI_DIR=/usr/local/etc/php
NEXTCLOUD_DB_SERVICE_PORT=3306
GPG_KEYS=<redacted> <redacted> <redacted>
NEXTCLOUD_UPDATE=0
PHP_LDFLAGS=-Wl,-O1 -pie
PWD=/var/www/html
NEXTCLOUD_DB_PORT_3306_TCP=tcp://10.152.183.148:3306
NEXTCLOUD_SERVER_PORT=tcp://10.152.183.46:80
NEXTCLOUD_DB_PORT_3306_TCP_ADDR=10.152.183.148
NEXTCLOUD_TRUSTED_DOMAINS=<redacted>
HOME=/root
PHP_MEMORY_LIMIT=512M
KUBERNETES_PORT_443_TCP=tcp://10.152.183.1:443
NEXTCLOUD_SERVER_PORT_80_TCP_PROTO=tcp
PHP_SHA256=<redacted>
NEXTCLOUD_DB_PORT_3306_TCP_PORT=3306
PHPIZE_DEPS=autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c
NEXTCLOUD_SERVER_SERVICE_HOST=10.152.183.46
TERM=xterm
PHP_URL=https://www.php.net/distributions/php-8.1.12.tar.xz
NEXTCLOUD_DB_SERVICE_PORT_TCP=3306
NEXTCLOUD_DB_PORT=tcp://10.152.183.148:3306
PHP_UPLOAD_LIMIT=512M
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
NEXTCLOUD_SERVER_SERVICE_PORT_HTTP=80
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
NEXTCLOUD_SERVER_SERVICE_PORT=80
NEXTCLOUD_DB_SERVICE_HOST=10.152.183.148
NEXTCLOUD_DB_PORT_3306_TCP_PROTO=tcp
NEXTCLOUD_SERVER_PORT_80_TCP_ADDR=10.152.183.46
KUBERNETES_PORT_443_TCP_ADDR=10.152.183.1
APACHE_ENVVARS=/etc/apache2/envvars
NEXTCLOUD_SERVER_PORT_80_TCP_PORT=80
KUBERNETES_SERVICE_HOST=10.152.183.1
KUBERNETES_PORT=tcp://10.152.183.1:443
KUBERNETES_PORT_443_TCP_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OVERWRITEPROTOCOL=https
PHP_ASC_URL=https://www.php.net/distributions/php-8.1.12.tar.xz.asc
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
_=/usr/bin/env
```

My Kubernetes Deployment (at testing time)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: nextcloud-server
  namespace: nextcloud
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nextcloud-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextcloud-server
    spec:
      containers:
      - args:
        - -f
        - /dev/null
        command:
        - tail
        env:
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: <redacted>
        - name: OVERWRITEPROTOCOL
          value: https
        - name: NEXTCLOUD_UPDATE
          value: "0"
        image: nextcloud:25.0.1-apache
        imagePullPolicy: Always
        name: nextcloud-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/data
          name: nextcloud-data
          subPath: data
        - mountPath: /var/www/html/config
          name: nextcloud-config
          subPath: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: pvc-nextcloud-data
      - name: nextcloud-config
        persistentVolumeClaim:
          claimName: pvc-nextcloud-config
```

Any Ideas?

**Comment by martadinata666** [comment]
apache got their runtime env from `envvars` that placed in `/etc/apache2/envvars`, and for some reason yours is missing? or not read correctly? And about running the apache using `apache2ctl -DFOREGROUND` will read envvars automaticaly. afaik, thats how apache run in container. 🤞🏼

**Comment by eltomato89** [comment]
Hey, thanks for your answer.

When I try to run `apache2ctl -D FOREGROUND`, the Result is this:
```
root@nextcloud-server-7f7f7f5d5-lf5gf:/var/www/html# apache2ctl -D FOREGROUND
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.1.43.146. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.1.43.146. Set the 'ServerName' directive globally to suppress this message
Bus error (core dumped)
Action '-D FOREGROUND' failed.
The Apache error log may have more information.
```

Which is basically the same thing happening, when I am not overriding the entrypoint.

I actually do have an envvar file which looks like this:
```
root@nextcloud-server-7f7f7f5d5-lf5gf:/var/www/html# cat /etc/apache2/envvars
# envvars - default environment variables for apache2ctl

# this won't be correct after changing uid
unset HOME

# for supporting multiple apache2 instances
if [ "${APACHE_CONFDIR##/etc/apache2-}" != "${APACHE_CONFDIR}" ] ; then
	SUFFIX="-${APACHE_CONFDIR##/etc/apache2-}"
else
	SUFFIX=
fi

# Since there is no sane way to get the parsed apache2 config in scripts, some
# settings are defined via environment variables and then used in apache2ctl,
# /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.
: ${APACHE_RUN_USER:=www-data}
export APACHE_RUN_USER
: ${APACHE_RUN_GROUP:=www-data}
export APACHE_RUN_GROUP
# temporary state file location. This might be changed to /run in Wheezy+1
: ${APACHE_PID_FILE:=/var/run/apache2$SUFFIX/apache2.pid}
export APACHE_PID_FILE
: ${APACHE_RUN_DIR:=/var/run/apache2$SUFFIX}
export APACHE_RUN_DIR
: ${APACHE_LOCK_DIR:=/var/lock/apache2$SUFFIX}
export APACHE_LOCK_DIR
# Only /var/log/apache2 is handled by /etc/logrotate.d/apache2.
: ${APACHE_LOG_DIR:=/var/log/apache2$SUFFIX}
export APACHE_LOG_DIR

## The locale used by some modules like mod_dav
: ${LANG:=C}
export LANG
## Uncomment the following line to use the system default locale instead:
#. /etc/default/locale

export LANG

## The command to get the status for 'apache2ctl status'.
## Some packages providing 'www-browser' need '--dump' instead of '-dump'.
#export APACHE_LYNX='www-browser -dump'

## If you need a higher file descriptor limit, uncomment and adjust the
## following line (default is 8192):
#APACHE_ULIMIT_MAX_FILES='ulimit -n 65536'

## If you would like to pass arguments to the web server, add them below
## to the APACHE_ARGUMENTS environment.
#export APACHE_ARGUMENTS=''

## Enable the debug mode for maintainer scripts.
## This will produce a verbose output on package installations of web server modules and web application
## installations which interact with Apache
#export APACHE2_MAINTSCRIPT_DEBUG=1
```

**Comment by Deaddy** [comment]
Hi, I've run into the same issue (also with ownCloud in k8s) and I think the issue is with opcache; disabling it completely does circumvent the problem.

One does not need to disable opcache completely (IIRC that had an performance impact, but it has been a few years since I tested that), it suffices to use only the filecache, which also requires setting and creating a directory. At least in the context of *cloud on server hardware this doees not come with a performance impact, as network latency between the application and redis/keydb and the database, as well as the database itself, are the main bottlenecks.

However, I did not manage to make it work with caching in shared memory enable.

My workaround is adding
```
opcache.file_cache_only=1
opcache.file_cache=/var/run/apache2/opcache
```
to the `opcache-recommended.ini` in `/usr/local/etc/php/conf.d` and create the folder `/var/run/apache2/opcache`.

Using
the helm chart (https://github.com/nextcloud/helm) one can do this workaround even via the values and initContainers and volumeMounts; I assume translation to raw k8s resources is straightforward:

```
nextcloud:
  extraVolumes:
    - name: phpconfig
      emptyDir:
        medium: Memory
    - name: opcache
      emptyDir:
        medium: Memory

  extraVolumeMounts:
    - name: phpconfig
      mountPath: /usr/local/etc/php/conf.d
    - name: opcache
      mountPath: /var/run/apache2/opcache

  extraInitContainers:
    - name: copyconfigs
      image: nextcloud:25.0.4-apache
      command:
        - bash
        - -c
        - |
          cp /usr/local/etc/php/conf.d/* /mnt/confs
          cd /mnt/confs
          echo "opcache.file_cache_only=1" >> opcache-recommended.ini
          echo "opcache.file_cache=/var/run/apache2/opcache" >> opcache-recommended.ini
      volumeMounts:
        - mountPath: /mnt/confs
          name: phpconfig
```
