### ISSUE TITLE
No way to specify non-root base path

### ISSUE THREAD

**Issue by l-dobrev** [nextcloud/docker#186]
I'd like to be able to run a next cloud container and access it from https://.../base-path/.
Currently the docker image only allows Nextcloud at the root of the server. This makes it unsuitable for deployment on a shared server or behind an SSL front-end appliance.

While a front-end (say Apache with mod_proxy) may be able to correctly rewrite incoming requests, there are numerous locations where server-relative or absolute URLs are generated/published which end up being wrong.

I am not well versed in Nextcloud structure to be able to propose a pull request.

**Comment by SnowMB** [comment]
I think you can achieve this by changing the `'overwritewebroot' => ''` setting in your `config.php` accordingly.

**Comment by l-dobrev** [comment]
Yes, that seems to be the way to do that.
This method also (seems to) allows rewriting (including the host and the protocol!) based on whether the request comes from the proxy of from intra-net users. Neat.

**Comment by erosinger** [comment]
Hi everyone, I am deploying the Nextcloud Docker container inside a Kuberntes cluster. As I have configured an NGINX ingress to serve it via `https://.../nextcloud/`, I would like to set the base-path aswell. But without touching the` config.php `inside the container. I imagine setting it through some environment variable in the deploying `nextcloud.yaml` file (or some other way in that file)? Is there an official way to do so? Looking forward to your help.

Deployment
```yaml
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud-app
          image: nextcloud
          ports:
            - containerPort: 80
```
Service
```yaml
kind: Service
metadata:
    name: nextcloud-svc
    labels:
      app: nextcloud
spec:
  ports:
    - port: 3000
      targetPort: 80
  type: NodePort
  selector:
    app: nextcloud
```
Ingress
```yaml
...
- path: /nextcloud
  backend:
    serviceName: nextcloud-svc
    servicePort: 3000
...
```
