### ISSUE TITLE
Environment variables PHP_UPLOAD_LIMIT, PHP_UPLOAD_LIMIT have no effect

### ISSUE THREAD

**Issue by skl256** [nextcloud/docker#1870]
Hello!
Environment variables PHP_UPLOAD_LIMIT, PHP_UPLOAD_LIMIT have absolutely no effect (i tested in nextcloud:25.0.1-fpm).

**Do:**

```
docker-compose:
services:
  app:
    image: nextcloud:25.0.1-fpm
    enviroment:
      - PHP_MEMORY_LIMIT: 2048M
      - PHP_UPLOAD_LIMIT: 4096M
```

**Then try to check:**

```
> docker compose exec -it app bash
> echo "<?php phpinfo(); ?>" > index.php
```
Open NextCloud in browser - values of memory_limit, upload_max_filesize in phpinfo stay 512M.

**OR**
```
> docker compose exec --user www-data -it app bash
> php -r "phpinfo();" | grep "upload_max_filesize" && php -r "phpinfo();" | grep "memory_limit"
```
Values of memory_limit, upload_max_filesize in phpinfo stay 512M.
