### ISSUE TITLE
Docker images using incorrect Nextcloud version?

### ISSUE THREAD

**Issue by jcastro** [nextcloud/docker#1879]
I've been using the docker image nextcloud:production-apache which is supposed to have more stable version 24, however this morning I updated the image and now I'm on nextcloud 25!!!

Here's my docker compose 
```
version: '3'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - /root/docker/nextcloud/db:/var/lib/postgresql/data
    env_file:
      - stack.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:production-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - /root/docker/nextcloud/nextcloud:/var/www/html
      - /mnt/DataSSD/nextcloud_data:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=2048M #Default 512M
      - PHP_UPLOAD_LIMIT=1024M #Default 512M
    env_file:
      - stack.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - /root/docker/nextcloud/nextcloud:/var/www/html
      - /mnt/DataSSD/nextcloud_data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
```
