### ISSUE TITLE
Collabora Online - Built-in CODE Server in Nextcloud docker. Documents do not load 

### ISSUE THREAD

**Issue by Japhys** [nextcloud/docker#1896]
I am using Docker behind nginx proxy manager and everything works fine. I installed Collabora Online - Built-in CODE Server  and Nextcloud office and that also seems fine. But opening an document does not work, it keeps spinning.

```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /srv/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=X
      - MYSQL_PASSWORD=X
      - MYSQL_DATABASE=X
      - MYSQL_USER=X
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /srv/nextcloud/nextcloud/:/var/www/html
    environment:
      - MYSQL_PASSWORD=X
      - MYSQL_DATABASE=X
      - MYSQL_USER=X
      - MYSQL_HOST=db
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=4096M
```

![2023-01-12_20-21](https://user-images.githubusercontent.com/24695937/212161707-19c5cca8-5ac0-4dbf-84d4-aea1d4b1c699.png)

both on desktop and mobile

![2023-01-12_20-24](https://user-images.githubusercontent.com/24695937/212161890-728b6651-3f8a-4df6-bf0d-4fa5b4902472.png)

Any idea's?
