### ISSUE TITLE
docker image cannot be associated with external datasource

### ISSUE THREAD

**Issue by share1001** [nextcloud/docker#1898]
The docker image of nextcloud runs independently, and there is no problem if it is not associated with the external database. However, if you use docker-compose or docker-link to associate with the database, an error will be reported and the docker log is as follows:

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Jan 16 16:04:23.284396 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.14 configured -- resuming normal operations
[Mon Jan 16 16:04:23.284472 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'172.17.0.1 - - [16/Jan/2023:16:57:34 +0000] "GET /core/img/app-background.jpg HTTP/1.0" 200 190778 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
```

docker-compose.yml
```
version: '3.5'

services:
  db_nextcloud:
    container_name: db_nextcloud
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW    
    networks:
      cloudnetwork: 
        ipv4_address: 172.19.0.5
    volumes:
      - "./db:/var/lib/mysql"       #./db是数据库持久化目录，可以修改
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: nextcloud!@
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud!@
    restart: always
    
  nextcloud:
    container_name: nextcloud
    image: nextcloud:25.0.2
    networks: 
      cloudnetwork: 
    ports:
      - 8061:80
      - 4433:443
    depends_on:
      - db_nextcloud
    volumes:
      - "./data:/var/www/html"      #./data是数据位置，可以修改
    restart: always
    command: ["apache2-foreground "]
networks:
  cloudnetwork:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
```
This script can run normally before nextcloud version 23, but version 25 cannot run normally, and the above error is reported
