### ISSUE TITLE
Trick to run docker nextcloud fpm with nginx in a sub directory

### ISSUE THREAD

**Issue by chen-xin** [nextcloud/docker#1919]
The official nextcloud fpm image is great but it does not support mounting to a sub directory.
It took me two long days to find this trick, record here for someone might need:

1. Compose for initialize. Note: navigate to `https://my.site/nextcloud` now will raise 404:
```
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl/nginx
        # - ${DATA_VOLUME}/www:/www
        # - ${DATA_VOLUME}/nextcloud:/www/nextcloud
      - ${DATA_VOLUME}/www:/var/www/html
      - ${DATA_VOLUME}/nextcloud:/var/www/html/nextcloud
    restart: unless-stopped

  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud1
    restart: unless-stopped
      # ports:
      # - 9000:9000
    volumes:     
      - ${DATA_VOLUME}/nextcloud:/var/www/html
      # use the following config instead of above after nextcloud initialized itself:
      # - ${DATA_VOLUME}/nextcloud:/var/www/html/nextcloud 
   ```
2. Modify last line of compose file as comments and restart containers. Note: use the modified version BEFORE initialize will cause `cannot delete non-empty directory: nextcloud`.
