### ISSUE TITLE
issue when renaming the nextcloud volume in docker compose file

### ISSUE THREAD

**Issue by leolivier** [nextcloud/docker#1937]
Hi
For some unknown reason, the .htaccess file in /var/www/html became unreadable with "bad message" errors 
I'm using docker compose and /var/www/html was mounted on a temporary volume named  nextcloud like that:
```
volumes:
  nextcloud:

services:
  nextcloud:
...
    volumes:
      - nextcloud:/var/www/html
...
```
It prevented nextcloud to restart, so I removed the container and tried to remove the volume nextcloud_nextcloud too but it failed as .htaccess was not removable.
So finally I just changed nextcloud to nextcloud2 in the docker file like that:
```
volumes:
  nextcloud2:

services:
  nextcloud:
...
    volumes:
      - nextcloud2:/var/www/html
...```

```
and restarted nextcloud.

It looks like in the situation, the /entrypoint.sh detects that nextcloud is not installed and tries to reinstall everything including starting the command `occ maintenance:install` but nextcloud is already installed actually!
So, maintenance:install command does not exist anymore, a lot of errors (10 tries) and then nextcloud finally restarted but some applications have disappeared in between (eg mail) and I had to reinstall them.

So, maybe, such a simple action as renaming a volume in the docker compose file should not lead to this situation?
