### ISSUE TITLE
EFS file system hit at 100% after update yesterday - Can't use our Nextcloud instance at all!

### ISSUE THREAD

**Issue by Normand-Nadon** [nextcloud/docker#1943]
Our setup uses EFS on AWS for storage.

After updating to the latest stable release of NC25 yesterday, the entire docker SWARM stalls to a crawl.
After investigation, it was found that Nextcloud is pounding the storage at 100% on the EFS drive.

All our stacks use the same mounting options, and Nextcloud has been working fine for the last 3 years with it too.

Here is the docker-compose file with <<<REDACTED>>> sensitive data (if you see something I forgot to redact, please advise!)

```
version: '3.7'

services: 
  app:
    image: nextcloud:25
    restart: unless-stopped
    networks:
      - db-net
    ports:
      - 8080:80
    volumes:
      - nextcloud-html:/var/www/html
      #- nextcloud-config:/var/www/html/config
      #- nextcloud-apps:/var/www/html/custom_apps
      #- nextcloud-data:/var/www/html/data
      #- nextcloud-themes:/var/www/html/themes
      #- nextcloud-local:/etc/localtime:ro
    environment:
      - TZ=America/Toronto
      - VIRTUAL_HOST=<<<REDACTED>>>
      - POSTGRES_HOST=<<<REDACTED>>>
      - POSTGRES_DB=<<<REDACTED>>>
      - POSTGRES_USER=<<<REDACTED>>>
      - POSTGRES_PASSWORD=<<<REDACTED>>>
      #- NEXTCLOUD_ADMIN_USER=<<<REDACTED>>>
      #- NEXTCLOUD_ADMIN_PASSWORD=<<<REDACTED>>>
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.cloud_insecure.rule=Host(`cloud.<<<REDACTED>>>`)
        - traefik.http.routers.cloud_insecure.middlewares=cloud-redirect@docker
        - traefik.http.routers.cloud_insecure.service=cloud-service@docker
        - traefik.http.middlewares.cloud-redirect.redirectscheme.scheme=https
        - traefik.http.routers.cloud.rule=Host(`cloud.<<<REDACTED>>>`)
        - traefik.http.routers.cloud.tls.certResolver=sample
        - traefik.http.routers.cloud.service=cloud-service@docker
        - traefik.http.services.cloud-service.loadbalancer.server.port=80
        - traefik.http.routers.dashboard.entrypoints=http,https
      placement:
                constraints: [node.role == worker]
      
  nextcloud-cron:
    image: nextcloud:21
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    entrypoint: /cron.sh
    volumes:
      - nextcloud-html:/var/www/html

    networks:
      - db-net
    deploy:
      labels:
        - traefik.enable=false
      placement:
                constraints: [node.role == worker]
      restart_policy:
        condition: any

  # ---------------------------
  # ONLY OFFICE DOCUMENT SERVER
  # ---------------------------
  onlyoffice:
    image: onlyoffice/documentserver:latest
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - db-net
    ports:
      - 8889:80
    volumes:    
      - onlyoffice-Data:/var/www/onlyoffice/Data
      - onlyoffice-log:/var/log/onlyoffice
      - onlyoffice-cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - onlyoffice-examples:/var/www/onlyoffice/documentserver-example/public/files
      - onlyoffice-fonts:/usr/share/fonts
    environment:
      - TZ=America/Toronto   
      - JWT_ENABLED=true
      - JWT_SECRET=<<<REDACTED>>>
    tty: true
    restart: unless-stopped
    deploy:
      labels:
       - traefik.enable=true
       - traefik.http.routers.office_insecure.rule=Host(`office.<<<REDACTED>>>`)
       - traefik.http.routers.office_insecure.middlewares=office-redirect@docker
       - traefik.http.routers.office_insecure.service=office-service@docker
       - traefik.http.middlewares.office-redirect.redirectscheme.scheme=https
       - traefik.http.routers.office.rule=Host(`office.<<<REDACTED>>>`)
       - traefik.http.routers.office.tls.certResolver=sample
       - traefik.http.routers.office.service=office-service@docker
       - traefik.http.services.office-service.loadbalancer.server.port=80
       # Extra headers, specific to only office
       - traefik.http.middlewares.office-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST
       - traefik.http.middlewares.office-cors.headers.accesscontrolalloworiginlist=*
       - traefik.http.middlewares.office-cors.headers.accesscontrolmaxage=100
       - traefik.http.middlewares.office-cors.headers.addvaryheader=true
       - traefik.http.middlewares.office-cors.headers.customrequestheaders.X-Forwarded-Proto=https
       - traefik.http.routers.office.middlewares=office-cors@docker

      placement:
        constraints: [node.role == worker]
       
volumes:
  nextcloud-html:
    driver_opts:
      type: "nfs"
      o: "<<<REDACTED>>>.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/nextcloud/html"
  
  onlyoffice-Data:
    driver_opts:
      type: "nfs"
      o: "<<<REDACTED>>>.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/nextcloud/onlyoffice/Data"

  onlyoffice-log:
    driver_opts:
      type: "nfs"
      o: "<<<REDACTED>>>.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/nextcloud/onlyoffice/log"

  onlyoffice-cache:
    driver_opts:
      type: "nfs"
      o: "<<<REDACTED>>>.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/nextcloud/onlyoffice/cache"

  onlyoffice-examples:
    driver_opts:
      type: "nfs"
      o: "<<<REDACTED>>>.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/nextcloud/onlyoffice/examples"

  onlyoffice-fonts:
    driver_opts:
      type: "nfs"
      o: "<<<REDACTED>>>.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/docker/nextcloud/onlyoffice/fonts"      

networks:
  db-net:
    external: true
```
