### ISSUE TITLE
Fix `NEXTCLOUD_TRUSTED_DOMAINS`

### ISSUE THREAD

**Issue by aentwist** [nextcloud/docker#1955]
## Expected Behavior

Setting `NEXTCLOUD_TRUSTED_DOMAINS` to `web` sets the Nextcloud config setting `trusted_domains` to an array `[ "web" ]`

## Actual Behavior

Setting `NEXTCLOUD_TRUSTED_DOMAINS` does not affect the Nextcloud config

## Steps to Reproduce

1. create compose.yaml
1. create Caddyfile
1. `docker compose up -d`
1. `docker exec -it app sh`
1. `cat config/config.php | grep -A 3 trusted_domains`

*compose.yaml*

```yaml
services:
  db:
    image: postgres:15.2-alpine3.17
    container_name: db
    environment:
      POSTGRES_PASSWORD: password

  app:
    image: nextcloud:26.0.0-fpm-alpine
    container_name: app
    depends_on:
      - db
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: password
      NEXTCLOUD_TRUSTED_DOMAINS: web

  web:
    image: caddy:2.6.4-alpine
    container_name: web
    ports:
      - 8080:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    volumes_from:
      - app

```

*Caddyfile*

```caddyfile
http://localhost {
    encode gzip

    root * /var/www/html
    file_server
    php_fastcgi app:9000
}

```

*output*

```shell
  'trusted_domains' =>
  array (
    0 => 'localhost:8080',
  ),
```

## Requirements

- [ ] environment variable affects Nextcloud config
- [ ] `trusted_domains` array has correct value `[ "web" ]`
