### ISSUE TITLE
CRON error docker - Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "postgres-nextcloud" to address: Temporary failure in name resolution

### ISSUE THREAD

**Issue by ALEXSANPEDRO** [nextcloud/docker#1966]
Install docker through compose file. all functions works well, but CRON dontwork from host, same error when i try use cron from separate container. 
```
ERROR:
Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "postgres-nextcloud" to address: Temporary failure in name resolution
```
But containers works well, db works good too. 

```
compose:
version: "2.1"

services:
  nextcloud:
    image: nextcloud:26.0.0-apache
    container_name: nextcloud
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Moscow
      - REDIS_HOST=redis-nextcloud
      - REDIS_HOST_PASSWORD=****
    volumes:
      - /srv/dev-disk-by-uuid-201d48fb-9acc-4ebd-ac77-4a48206a723a/dockerimg/nextcloud/nextcloud_back/apps/:/var/www/html/apps
      - /srv/dev-disk-by-uuid-201d48fb-9acc-4ebd-ac77-4a48206a723a/dockerimg/nextcloud/nextcloud_back/config/:/var/www/html/config
      - /srv/dev-disk-by-uuid-201d48fb-9acc-4ebd-ac77-4a48206a723a/dockerimg/nextcloud/nextcloud_back/data/:/var/www/html/data
      - /srv/dev-disk-by-uuid-201d48fb-9acc-4ebd-ac77-4a48206a723a/dockerimg/nextcloud/nextcloud_back/:/var/www/html
      - /srv/dev-disk-by-uuid-ea7dbf22-5c45-4f9b-acdd-0a85cdd3c60c/:/mnt/data
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini
    ports:
      - 177:80
    restart: unless-stopped
    depends_on:
      - postgres-nextcloud
      - redis-nextcloud

  postgres-nextcloud:
    image: postgres:15.2-alpine
    container_name: postgres-nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=****
    volumes:
      - /srv/dev-disk-by-uuid-201d48fb-9acc-4ebd-ac77-4a48206a723a/dockerimg/nextcloud/DB:/var/lib/postgresql/data

  redis-nextcloud:
   image: redis:alpine
   container_name: redis-nextcloud
   command: redis-server --requirepass ****
   restart: unless-stopped
```
some months ago ive successfully used nc with same settings and WORKING cron.

i believe community can help me. Googleing donot help. Cant find same error
