### ISSUE TITLE
Upgraded from 24.0.11 to 25.0.5 then 25.0.6 but site is 500'ing

### ISSUE THREAD

**Issue by cb3inco** [nextcloud/docker#1973]
I apologize as I don't know where the actual issue is as I can't find much of anyone else having problems.

A few weeks back I upgraded from 24.0.11 via a docker compose file to 25.0.5. I started getting 500 errors when trying to load Nextcloud. I thought maybe it was Traefik, but I'm able to access a test .html file I put in the Nextcloud directory with no issue and I can access cron.php (though with errors). Everything I can tell from getting into the container is that things are working properly. I can run occ commands, etc. no problems there and could monitor the logs of the cron container and they were running fine.

I just upgraded to 25.0.6 and facing the same issue as I thought maybe that version in particular was the issue. While the app upgraded just fine, I'm still getting 500 errors.

Here is the upgrade process in docker:

Configuring Redis as session handler
Initializing nextcloud 25.0.6.1 ...
Upgrading nextcloud from 25.0.5.1 ...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
The following apps have been disabled:
Initializing finished

Here is my compose file.

```
version: '3'  

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud-mariadb
    networks:
      - nextcloud
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxxxxxxxxxxxxx
      - MYSQL_PASSWORD=xxxxxxxxxxxxxxxxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  redis:
    image: redis
    container_name: nextcloud-redis
    command: redis-server --requirepass xxxxxxxxxxxx
    networks:
      - nextcloud
    volumes:
      - /nextcloud/redis:/var/lib/redis
    restart: unless-stopped

  app:
    image: nextcloud:25.0.6
    container_name: nextcloud-app
    hostname: cloud.domain.net
    privileged: true
    networks:
      - traefik
      - nextcloud
    depends_on:
      - db
      - redis
    volumes:
      - /nextcloud/www:/var/www/html
      - /nextcloud/www/config:/var/www/html/config
      - /nextcloud/www/custom_apps:/var/www/html/custom_apps
      - /nextcloud/www/data:/var/www/html/data
      - /nextcloud/www/themes:/var/www/html/themes
      - /nextcloud/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=xxxxxxxxxxxxx
      - MYSQL_PASSWORD=xxxxxxxxxxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-mariadb
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.domain.net
      - TRUSTED_PROXIES=172.18.0.0/16,172.21.0.0/16
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.domain.net`)"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,nextcloud-sec"
      - "traefik.http.middlewares.nextcloud-sec.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud-sec.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.nextcloud-sec.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-sec.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
    restart: unless-stopped

  cron:
    image: nextcloud:25.0.6
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - /nextcloud/www:/var/www/html
    entrypoint: /cron.sh
    networks:
      - nextcloud
    depends_on:
      - db
      - redis

networks:
  traefik:
    external: true
    name: traefik  
  nextcloud:
    external: false
    name: nextcloud
```

The only thing that stands out to me is the persistent nextcloud-init-sync.lock file. No matter what I do to delete it, every time the container is restarted it comes back. And I see the file has an updated timestamp to just a few minutes ago because I just ran the upgrade.

I've looked at https://github.com/nextcloud/docker/issues/1756 as a possible similar problem, or https://github.com/nextcloud/docker/issues/1749 but the recommendation of deleting the file doesn't work. 

So, if this isn't a docker issue, i'll move it to the Nextcloud server repo, but this is a bit frustrating and I've been basically down for a month now. 

For what it's worth, if I load the cron.php file in a browser, this is the information I get. Not sure if this expected or not:

```
TypeError: substr_compare(): Argument #4 ($length) must be of type ?int, string given in /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php:104 Stack trace: #0 /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php(104): substr_compare('101011000001001...', '101011000001001...', 0, '16,172.21.0.0/1...') #1 /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php(52): Symfony\Component\HttpFoundation\IpUtils::checkIp4('172.18.0.4', '172.18.0.0/16,1...') #2 /var/www/html/lib/private/AppFramework/Http/Request.php(588): Symfony\Component\HttpFoundation\IpUtils::checkIp('172.18.0.4', Array) #3 /var/www/html/lib/private/AppFramework/Http/Request.php(880): OC\AppFramework\Http\Request->isTrustedProxy(Array, '172.18.0.4') #4 /var/www/html/lib/private/AppFramework/Http/Request.php(808): OC\AppFramework\Http\Request->fromTrustedProxy() #5 /var/www/html/lib/private/Server.php(1225): OC\AppFramework\Http\Request->getInsecureServerHost() #6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server)) #7 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container)) #8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('ThemingDefaults') #9 /var/www/html/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('ThemingDefaults', false) #10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('ThemingDefaults') #11 /var/www/html/lib/private/Server.php(2156): OC\AppFramework\Utility\SimpleContainer->get('ThemingDefaults') #12 /var/www/html/lib/private/Server.php(1408): OC\Server->getThemingDefaults() #13 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server)) #14 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container)) #15 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('OCP\\Defaults') #16 /var/www/html/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Defaults', false) #17 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OCP\\Defaults') #18 /var/www/html/lib/private/legacy/OC_Util.php(521): OC\AppFramework\Utility\SimpleContainer->get('OCP\\Defaults') #19 /var/www/html/lib/base.php(687): OC_Util::checkServer(Object(OC\SystemConfig)) #20 /var/www/html/lib/base.php(1145): OC::init() #21 /var/www/html/cron.php(43): require_once('/var/www/html/l...') #22 {main}

```
And logs from the cron container.

```
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  job: 0 php -f /var/www/html/cron.php
crond: child running /bin/bash
crond: USER www-data pid   9 cmd php -f /var/www/html/cron.php
crond: wakeup dt=10
crond: wakeup dt=50
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
```

**Comment by meonkeys** [comment]
I am not a maintainer, but I have a few questions / ideas:

1. What apps do you have enabled?
2. Have you tried disabling apps?
3. Are you using the Theming app? Maybe try disabling that first...
4. Do you have a custom trusted proxy config? If so, [is the syntax correct for that](https://docs.nextcloud.com/server/25/admin_manual/configuration_server/reverse_proxy_configuration.html#defining-trusted-proxies)?
5. Are you sure that's the relevant error and stack trace?

Let's clean up that stack trace:

```text
TypeError: substr_compare(): Argument #4 ($length) must be of type ?int, string given in /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php:104

Stack trace:
 #0 /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php(104): substr_compare('101011000001001...', '101011000001001...', 0, '16,172.21.0.0/1...')
 #1 /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php(52): Symfony\Component\HttpFoundation\IpUtils::checkIp4('172.18.0.4', '172.18.0.0/16,1...')
 #2 /var/www/html/lib/private/AppFramework/Http/Request.php(588): Symfony\Component\HttpFoundation\IpUtils::checkIp('172.18.0.4', Array)
 #3 /var/www/html/lib/private/AppFramework/Http/Request.php(880): OC\AppFramework\Http\Request->isTrustedProxy(Array, '172.18.0.4')
 #4 /var/www/html/lib/private/AppFramework/Http/Request.php(808): OC\AppFramework\Http\Request->fromTrustedProxy()
 #5 /var/www/html/lib/private/Server.php(1225): OC\AppFramework\Http\Request->getInsecureServerHost()
 #6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server))
 #7 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
 #8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('ThemingDefaults')
 #9 /var/www/html/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('ThemingDefaults', false)
#10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('ThemingDefaults')
#11 /var/www/html/lib/private/Server.php(2156): OC\AppFramework\Utility\SimpleContainer->get('ThemingDefaults')
#12 /var/www/html/lib/private/Server.php(1408): OC\Server->getThemingDefaults()
#13 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#15 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('OCP\\Defaults')
#16 /var/www/html/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Defaults', false)
#17 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OCP\\Defaults')
#18 /var/www/html/lib/private/legacy/OC_Util.php(521): OC\AppFramework\Utility\SimpleContainer->get('OCP\\Defaults')
#19 /var/www/html/lib/base.php(687): OC_Util::checkServer(Object(OC\SystemConfig))
#20 /var/www/html/lib/base.php(1145): OC::init()
#21 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
#22 {main}
```

**Comment by joshtrichards** [comment]
These two things stand out first to me:

1. Your `cron` container *must* have _all_ of the same volumes mounted on it in _exactly_ the same way as your `app` container or it will not have access to the _same_ `data/`, `config/`, `apps/`, etc. This will lead to an inability for cron jobs to run (or accomplish their goals - best case) and possibly (quite easily really) all the way to mismatched data, configs, etc (worst case) [1] .

2. Your bind mounts are nested (overlap) and that can create some weirdness / unintuitive behavior and make things more fragile. Some of the concerns are actually similar to item-1. (I'd personally encourage named volumes - particularly in this situation - but that's out of scope).

Either of the above could have created a number of possible situations resulting in a broken deployment. Unfortunately, while you should (must ASAP) fix item-1 first (cron), doing so doesn't simply reverse any weirdness (i.e. on the app container side) that the condition may have created in the meantime. That will likely require some further digging to unravel and, in turn, reverse. Also, you could have an issue with your `app` container in addition to your `cron` container Docker Compose config being out of whack. :-).

* Can you provide your NC `config.php` or equivalent from `occ` (from your app container - hah - though once you straighten out `cron`'s volumes they should be guaranteed one and the same)?

* What shows up in the *app* (not cron) container's Docker logs? Or, for that matter, the nextcloud.log? The behind the scenes of that 500 error is getting noted somewhere. 

[1] Further explanation on the cron issue: In your current Docker Compose configuration, in addition to cron not having access to your real /var/www/html/config (or data or apps or themes for that matter), it will - worse - assume it does have access and simply write/modify a layer of files that are visible operationally only in the cron container (e.g. in its "/var/www/html/data"). These files would be semi-orphans - entirely independent of and in conflict with the same paths in your app container. **This is bad.** That said, it's all recoverable even in essentially the worse case as long as you take good care of your host's `/nextcloud/www/data`.

**Comment by ngrigoriev** [comment]
I think I am having the similar issue trying to set up Nextcloud properly. My main goal is to make the root filesystem read-only and eliminate root completely.

The problem is that you are trying to mess with /usr/local/etc/php/conf.d by mounting a file there. You cannot mount a file into an existing directory without losing its contents. And this image has stuff under /usr/local/etc/php/conf.d. It is a bug that the entrypoint script is writing to a path that is absolute (/usr/local/etc/php/conf.d/redis-session.ini).

**Comment by ngrigoriev** [comment]
I think I have fixed the issue I was facing with this:

```
    spec:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
        runAsUser: 33
        runAsGroup: 33
      initContainers:
        - name: volume-permissions
          image: nextcloud
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chmod 770 /var/nextcloud/data && rsync -rlDog /usr/local/etc/ /usr/local/etc-shadow/ && chown 33:33 /usr/local/etc-shadow/php/conf.d && echo \"fixed the world\""]
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: nextcloud-main
              mountPath: /usr/local/etc-shadow
              subPath: local-etc
            - mountPath: /var/nextcloud/data
              name: nextcloud-data
....
# main container
...
            - name: nextcloud-main
              mountPath: /usr/local/etc
              subPath: local-etc

```

I am creating a copy of everything that is in the original container's /usr/local/etc to a directory of my nextcloud volume and then feeding this directory as /usr/local/etc to the actual nextcloud container.
