### ISSUE TITLE
"WARNING: [pool www] server reached pm.max_children setting (5), consider raising it" with Caddy as reverse proxy

### ISSUE THREAD

**Issue by rugk** [nextcloud/docker#1977]
## Problem

I am seeing this warning in my docker log:
> WARNING: [pool www] server reached pm.max_children setting (5), consider raising it

Could it be this, that is causing Nextcloud not to respond anymore?

It seems to randomly stop working (Caddy, which is used as a reverse proxy is responding with "503 Service Unavailable") with no apparent reason. A restart of all docker containers fixed it – until the next time.

## Docker-compose

```yaml
version: '3.7'
services:

  caddy:
    image: docker.io/caddy
    restart: unless-stopped
    ports:
      - "1001:80"
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - caddy_data:/data
      - caddy_config:/config
      - nc_data:/var/www/html
    networks:
      - caddynet
    depends_on:
      - nc
    healthcheck:
      # https://stackoverflow.com/a/47722899/5008962
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/status.php", "||", "exit", "1"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    labels:
      - io.containers.autoupdate=registry

  nc:
    image: docker.io/nextcloud:25-fpm
    restart: unless-stopped
    volumes: &nextcloud_volumes
      - nc_data:/var/www/html
      - type: bind
        source: ******
        target: ******:z
      - type: bind
        source: ${HOME:?HOME variable missing}/nextcloud_config
        target: /var/www/html/config:z
    networks:
      - caddynet
      - redisnet
      - dbnet
    environment: &nextcloud_environment
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD:?REDIS_HOST_PASSWORD variable missing}
      - MYSQL_HOST=db
    env_file: &nextcloud_env_file
      - db-shared.env
    depends_on: &nextcloud_depends_on
      - db
      - redis
    expose:
      - 9000
    labels:
      - io.containers.autoupdate=registry

  redis:
    image: docker.io/redis:alpine
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD:?REDIS_HOST_PASSWORD variable missing}
    restart: unless-stopped
    networks:
      - redisnet
    expose:
      - 6379
    labels:
      - io.containers.autoupdate=registry

  cron:
    image: docker.io/nextcloud:25-fpm
    restart: unless-stopped
    volumes: *nextcloud_volumes
    entrypoint: /cron.sh
    networks:
    - redisnet
    - dbnet
    environment: *nextcloud_environment
    env_file: *nextcloud_env_file
    depends_on: *nextcloud_depends_on
    labels:
      - io.containers.autoupdate=registry

  db:
    # Nextcloud requires compressed row format only available in MariaDb 10.5 for now.
    # See https://github.com/nextcloud/server/issues/25436 and https://github.com/nextcloud/docker/issues/1536
    image: docker.io/mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnet
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD variable missing}
    env_file:
      - db-shared.env
    expose:
      - 3306
    labels:
      - io.containers.autoupdate=registry

volumes:
  db_data:
  nc_data:
  caddy_data:
  caddy_config:

networks:
  caddynet:
  dbnet:
  redisnet:
```

## Log

Full log:
```
May 09 00:39:17 HOSTNAME nextcloud_nc_1[241912]: [08-May-2023 22:39:17] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
May 09 00:39:17 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:17 +0000 "HEAD /remote.php" 200
May 09 00:39:17 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:16 +0000 "PUT /remote.php" 201
May 09 00:39:16 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:16 +0000 "PROPFIND /remote.php" 207
May 09 00:39:15 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:15 +0000 "HEAD /remote.php" 200
May 09 00:39:14 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:14 +0000 "PROPFIND /remote.php" 207
May 09 00:39:13 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:13 +0000 "HEAD /remote.php" 200
May 09 00:39:13 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:12 +0000 "PROPFIND /remote.php" 207
May 09 00:39:12 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:12 +0000 "HEAD /remote.php" 200
May 09 00:39:12 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:12 +0000 "HEAD /remote.php" 200
May 09 00:39:12 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:12 +0000 "HEAD /remote.php" 200
May 09 00:39:12 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:12 +0000 "HEAD /remote.php" 200
May 09 00:39:12 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:12 +0000 "HEAD /remote.php" 200
May 09 00:39:12 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:11 +0000 "PROPFIND /remote.php" 207
May 09 00:39:12 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:11 +0000 "HEAD /remote.php" 200
May 09 00:39:11 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:11 +0000 "HEAD /remote.php" 200
May 09 00:39:11 HOSTNAME nextcloud_nc_1[241912]: 10.89.*.* - NC_USERNAME 08/May/2023:22:39:11 +0000 "HEAD /remote.php" 200
```

## Caddy log

Caddy itself also shows something about a broken pipe:
```
{"level":"info","ts":1683500527.2928805,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000321f10"}
{"level":"info","ts":1683500527.293341,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"info","ts":1683500527.2933908,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1683500527.2935348,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1683500527.2936287,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1683500527.2936347,"msg":"serving initial configuration"}
{"level":"error","ts":1683534579.1262577,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"write tcp 10.89.2.11:80->10.89.2.11:59912: write: broken pipe"}
{"level":"error","ts":1683540142.445158,"logger":"http.log.error","msg":"unexpected EOF","request":{"remote_ip":"10.89.2.11","remote_port":"47208","proto":"HTTP/1.1","method":"POST","host":"nextcloud.****.tld","uri":"/remote.php/dav/bulk","headers":{"Accept-Encoding":["gzip, deflate"],"Mime-Version":["1.0"],"X-Forwarded-Host":["nextcloud.****.tld"],"X-Forwarded-Proto":["https"],"Cookie":[],"User-Agent":["Mozilla/5.0 (Linux) mirall/3.8.1git (Nextcloud, fedora-6.2.14-300.fc38.x86_64 ClientArchitecture: x86_64 OsArchitecture: x86_64)"],"Content-Length":["10929641"],"Accept":["*/*"],"Accept-Language":["de-DE,en,*"],"Authorization":[],"X-Request-Id":["0c56836a-20c7-461d-ab7a-076dcabd060d"],"Content-Type":["multipart/related; boundary=\"boundary_.oOo._nOVss3QggkhbTSXgsqcMMO7AFENGNSci\""],"X-Forwarded-For":["217.128.245.171"]}},"duration":814.046274892,"status":502,"err_id":"1anetvtwk","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1683555563.373478,"logger":"http.log.error","msg":"unexpected EOF","request":{"remote_ip":"10.89.2.11","remote_port":"52190","proto":"HTTP/1.1","method":"PUT","host":"nextcloud.****.tld","uri":"/remote.php/dav/uploads/****/9b97857**************00000000000-0000000006570937","headers":{"Content-Length":["6570937"],"Authorization":[],"Content-Type":["image/jpeg"],"Cookie":[],"X-Forwarded-For":["91.197.***.***"],"X-Forwarded-Proto":["https"],"User-Agent":["Mozilla/5.0 (Android) Nextcloud-android/3.24.1"],"X-Forwarded-Host":["nextcloud.****.tld"],"Accept-Encoding":["gzip"]}},"duration":169.716464559,"status":502,"err_id":"r039mxait","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1683569266.029598,"logger":"http.log.error","msg":"unexpected EOF","request":{"remote_ip":"10.89.2.11","remote_port":"35110","proto":"HTTP/1.1","method":"PUT","host":"nextcloud.****.tld","uri":"/remote.php/dav/uploads/****/3aae12dd6598db1094f9b9188820683e/0000000000000000-0000000002224893","headers":{"Cookie":[],"X-Forwarded-Proto":["https"],"Authorization":[],"Content-Type":["image/jpeg"],"Content-Length":["2224893"],"X-Forwarded-For":["31.32.212.225"],"X-Forwarded-Host":["nextcloud.****.tld"],"Accept-Encoding":["gzip"],"User-Agent":["Mozilla/5.0 (Android) Nextcloud-android/3.24.1"]}},"duration":350.527930209,"status":502,"err_id":"axzp2nyq8","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1683574388.5152335,"logger":"http.log.error","msg":"unexpected EOF","request":{"remote_ip":"10.89.2.11","remote_port":"59672","proto":"HTTP/1.1","method":"PUT","host":"nextcloud.****.tld","uri":"/remote.php/dav/uploads/***OTHER_NC_USER***/b118ccce3856baaa957a4624fae8668b/0000000001024000-0000000002047999","headers":{"Content-Length":["1024000"],"Authorization":[],"Cookie":[],"X-Forwarded-For":["82.113.99.35"],"User-Agent":["Mozilla/5.0 (Android) Nextcloud-android/3.24.1"],"Content-Type":["image/jpeg"],"X-Forwarded-Host":["nextcloud.****.tld"],"X-Forwarded-Proto":["https"],"Accept-Encoding":["gzip"]}},"duration":3.716477074,"status":502,"err_id":"qvsz9b9af","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"info","ts":1683586927.2934961,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"info","ts":1683586927.2941566,"logger":"tls","msg":"finished cleaning storage units"}
```
