### ISSUE TITLE
Caching configured and running but reported as not

### ISSUE THREAD

**Issue by ovidiub13** [nextcloud/docker#198]
I have this docker-compose file, where I've configured the Redis container, but the Admin panel in NC still reports as no cache being set.

The external network is there for the main reverse proxy to find this service.
Any other recommendations to improve on this docker-compose file are greatly appreciated.

```
version: '3'

volumes:
    nextcloud:

services:
    db:
        image: mariadb
        restart: unless-stopped
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=supersecretpassword
            - MYSQL_DATABASE=nextcloud
        networks:
            - nc

    redis:
        image: redis
        restart: unless-stopped
        networks:
            - nc

    cron:
        image: nextcloud:fpm
        restart: unless-stopped
        volumes:
            - nextcloud:/var/www/html
            - ./config:/var/www/html/config
            - /media/500GB/NextCloud/data:/var/www/html/data
            - /media/4TB/Poze/:/external/poze
        user: www-data
        entrypoint: |
            bash -c 'bash -s <<EOF
            trap "break;exit" SIGHUP SIGINT SIGTERM
            while [ ! -f /var/www/html/config/config.php ]; do
                sleep 1
            done
            while true; do
                php -f /var/www/html/cron.php
                sleep 15m
            done
            EOF'
        depends_on:
            - db
            - redis
        networks:
            - nc

    app:
        image: nextcloud:fpm
        volumes:
            - nextcloud:/var/www/html
            - ./config:/var/www/html/config
            - /media/500GB/NextCloud/data:/var/www/html/data
            - /media/4TB/Poze/:/external/poze
        restart: unless-stopped
        networks:
            - nc
        depends_on:
            - db
            - redis

    web:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - nextcloud:/var/www/html:ro
        restart: unless-stopped
        ports:
            - 80
        environment:
            - VIRTUAL_HOST=nextcloud.mydomain.com
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=nextcloud.mydomain.com
            - LETSENCRYPT_EMAIL=me@mydomain.com
        depends_on:
            - app
        networks:
            - proxy
            - nc

networks:
    proxy:
        external:
            name: mainweb_default
    nc:

```
