### ISSUE TITLE
Nginx-proxy: Howto server multiple Sites on one host? (Nextcloud in subdirectory)

### ISSUE THREAD

**Issue by obel1x** [nextcloud/docker#1992]
At https://github.com/nextcloud/docker/tree/master/.examples#with-nginx-proxy it is written "The proxy is designed to serve multiple sites on the same host machine."
Thats fine - but: could somebody pls. explain how and document it there?

What should be explained:
- Where to set which settings to get Nextcloud running in some subdirectory (e.g. "/nextcloud" on the server) for that proxy- setup?
- How to add other services? lets say another webservice on port 80 proxied to "https://sameserver.site/website" over that proxy:
```
web_nginx:
  image: nginx
  volumes:
   - ./templates:/etc/nginx/templates
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=penta-home.site
   - NGINX_PORT=80

```

saw some issues relatied to this. Am opening a new ticket, as the issues i found were about running nextcloud in some subfolder itself without proxy but doing it in a dangerous way. would like to find a working solution for this to close issues #401 and #1919
