### ISSUE TITLE
Upgrade from 25 to 26.0.2: Internal Server Error

### ISSUE THREAD

**Issue by danielkr123** [nextcloud/docker#2010]
Dear all,

I am running Nextcloud on Docker with a reverse proxy (Traefik) and automatic upgrading (Watchtower). So far, all worked very stable but last Friday, Watchtower upgraded to the new Nextcloud 26.0.2 version and since then my instance is not accessible any more.

My domain is meilenweit.eu with Nextcloud running at nextcloud.meilenweit.eu

**Error:**

Accessing my nextcloud instance via https://nextcloud.meilenweit.eu shows the following error in the browser

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

Apache logfiles are redirected to stdout and stderror in the docker image but both do not show any error:

```
lrwxrwxrwx 1 www-data www-data 11 May 23 09:40 access.log -> /dev/stdout
lrwxrwxrwx 1 www-data www-data 11 May 23 09:40 error.log -> /dev/stderr
lrwxrwxrwx 1 www-data www-data 11 May 23 09:40 other_vhosts_access.log -> /dev/stdout
```

In the container log I can only see the "Could not reliably determine the server's fully qualified domain name" error which has been there forever but never impacted my instance. I can also see that requests are reaching the instance, when I enter the URL or when my devices try to reach Nextcloud for syncing:

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message

[Sun Jun 11 10:28:06.210863 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.56 (Debian) PHP/8.2.7 configured -- resuming normal operations

[Sun Jun 11 10:28:06.210894 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

172.18.0.3 - daniel [11/Jun/2023:10:28:18 +0000] "GET /status.php HTTP/1.1" 500 409 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"

172.18.0.3 - daniel [11/Jun/2023:10:28:50 +0000] "GET /status.php HTTP/1.1" 500 409 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"

(...)
```
 

**docker-compose file:**

```
version: '3'

services:

  www-traefik:
    container_name: www-traefik
    image: traefik:2.6
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker_data/www-traefik/acme.json:/acme.json
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=webmaster@meilenweit.eu"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - 80:80
      - 8085:8080
      - 443:443
    networks:
      - traefik_proxy

  db:
    container_name: www-db
    image: mariadb:latest
    build: ./db
    restart: always
    volumes:
      - /opt/docker_data/www-db:/var/lib/mysql
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MYSQL_ROOT_PASSWORD='mysecretpassword'
    command: mysqld --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    env_file:
      - db.env
    networks:
      - default

  www-nextcloud:
    container_name: www-nextcloud
    image: nextcloud:latest
    restart: always
    volumes:
      - /opt/docker_data/www-nextcloud:/var/www/html
    labels:
      - com.centurylinklabs.watchtower.enable=true

      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      - traefik.http.middlewares.www-nextcloud-caldav.redirectregex.permanent=true
      - traefik.http.middlewares.www-nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.www-nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/

      - traefik.http.middlewares.www-nextcloud-https.redirectscheme.scheme=https

      - traefik.http.middlewares.www-nextcloud-headers.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.www-nextcloud-headers.headers.framedeny=true
      - traefik.http.middlewares.www-nextcloud-headers.headers.sslredirect=true
      - traefik.http.middlewares.www-nextcloud-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.www-nextcloud-headers.headers.stsPreload=true
      - traefik.http.middlewares.www-nextcloud-headers.headers.stsSeconds=15552000

      - traefik.http.routers.www-nextcloud-http.entrypoints=web
      - traefik.http.routers.www-nextcloud-http.rule=Host(`nextcloud.meilenweit.eu`)
      - traefik.http.routers.www-nextcloud-http.middlewares=www-nextcloud-https@docker

      - traefik.http.routers.www-nextcloud-https.entrypoints=websecure
      - traefik.http.routers.www-nextcloud-https.rule=Host(`nextcloud.meilenweit.eu`)
      - traefik.http.routers.www-nextcloud-https.middlewares=www-nextcloud-caldav,www-nextcloud-headers@docker
      - traefik.http.routers.www-nextcloud-https.tls=true
      - traefik.http.routers.www-nextcloud-https.tls.certresolver=le
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
      - www-traefik
    networks:
      - traefik_proxy
      - default

  www-collabora:
    container_name: www-collabora
    image: collabora/code
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      - traefik.http.routers.www-collabora-http.entrypoints=web
      - traefik.http.routers.www-collabora-http.rule=Host(`office.meilenweit.eu`)
      - traefik.http.routers.www-collabora-http.middlewares=default-http@file

      - traefik.http.routers.www-collabora-https.entrypoints=websecure
      - traefik.http.routers.www-collabora-https.rule=Host(`office.meilenweit.eu`)
      - traefik.http.routers.www-collabora-https.tls=true
      - traefik.http.routers.www-collabora-https.tls.certresolver=le
    cap_add:
      - MKNOD
    expose:
      - 9980
    environment:
      - "extra_params=--o:ssl.enable=false  --o:ssl.termination=true"
      - domain=nextcloud.meilenweit.eu
    depends_on:
      - www-traefik
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
```

**config.php file:**

```
<?php
$CONFIG = array (
  'instanceid' => 'mysecretinstanceid',
  'passwordsalt' => 'mysecretpasswordsalt',
  'trusted_domains' => 
  array (
    0 => 'meilenweit.eu',
    1 => 'nextcloud.meilenweit.eu',
  ),
  'datadirectory' => '/var/www/html/data',
  'version' => '26.0.2.1',
  'dbtype' => 'mysql',
  'dbhost' => 'db',
  'dbname' => 'owncloud',
  'dbuser' => 'oc_daniel',
  'dbpassword' => 'mysecretpassword',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'default_language' => 'de',
  'default_phone_region' => 'de',
  'mail_domain' => 'kram.pe',
  'mail_from_address' => 'server',
  'mail_smtphost' => 'sslout.df.eu',
  'mail_smtpport' => 465,
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => true,
  'mail_smtpname' => 'server@kram.pe',
  'mail_smtppassword' => 'mysecretpassword',
  'mail_send_plaintext_only' => false,
  'overwritehost' => 'nextcloud.meilenweit.eu',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '',
  'overwrite.cli.url' => 'https://nextcloud.meilenweit.eu',
  'htaccess.RewriteBase' => '/',
  'appcodechecker' => true,
  'updater.release.channel' => 'stable',
  'logtimezone' => 'Europe/Berlin',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mysql.utf8mb4' => true,
  'cipher' => 'AES-256-CFB',
  'secret' => 'mysecret',
  'trusted_proxies' => 
  array (
    0 => '172.18.0.0/16',
  ),
  'maintenance' => false,
  'loglevel' => 2,
  'theme' => '',
  'app_install_overwrite' => 
  array (
    0 => 'twofactor_admin',
  ),
);
```
