### ISSUE TITLE
I don't understand the instructions

### ISSUE THREAD

**Issue by docbill** [nextcloud/docker#202]
I don't understand the instructions.   It is not clear to me how I could run a command like "docker compose" and then have docker magically know which container I'm trying to update.   I think those instructions are related to if one is building the container from the git repo, rather than simply running a pulled image.

But I've tried it anyway, and this is the error I get:

```
[briemers@media1 ~]$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'

```

 

So what am I trying to do?  Just run the nextcloud image, with all data stored on my external hard drives in select folders.   For that I wrote two start-up scripts:

```
[briemers@media1 ~]$ cat nextcloud-db.sh
#!/bin/bash -x
exec docker run -d -P \
  --name=nextcloud-db \
  --restart=always \
  -e TZ=EST \
  -v "/mnt/share/spool/nextcloud/db/:/var/lib/mysql:z" \
  mariadb

```

```
[briemers@media1 ~]$ cat nextcloud.sh
 
#!/bin/bash -x
exec docker run -d -P \
   --name=nextcloud \
   --restart=always \
   -p 8080:80 \
   -e TZ=EST \
   -v "/mnt/share/spool/nextcloud/db/:/var/lib/mysql:z" \
   -v "/mnt/share/spool/nextcloud/:/var/www/html:z" \
   -v "/mnt/share/data/nextcloud/:/var/www/html/data:z" \
   --link nextcloud-db:mysql \
   nextcloud

```

It seems like this should be everything I need.   All configuration data is stored in the spool folder, and the actual files are stored in the data folder.

> Error
> Error while trying to create admin user:
> Failed to connect to the database: An
> exception occured in driver:
> SQLSTATE[HY000][2002] No such file or directory
> 

So clearly I'm either not doing something right to connect the database, or there are missing steps needed to configure the database.   I'm not sure which is the problem.

**Comment by axilleas** [comment]
Have you tried what's described here https://github.com/nextcloud/docker#base-version---apache?

The command should be `docker-compose up -d`, there's no space between them.

**Comment by marceljd** [comment]
I think you should start with this one: https://docs.docker.com/compose/gettingstarted/

Docker compose works with yml files, not with bash scripts although they can be similar. The docker run commands can be entered at the command prompt, the compose variant doesn't work that way.

**Comment by romanar** [comment]
save the below code as `docker-compose.yml` file.
`nano docker-compose.yml`
```
version: "3"
services:
  adminer:
    container_name: adminer
    depends_on:
        - mariadb
    image: adminer:4.4.0-standalone
    ports:
        - 8080:8080
    restart: unless-stopped
  mariadb:
    container_name: mariadb-nextcloud
    environment:
        - MYSQL_ROOT_PASSWORD=<mariadb password>
        - PUID=1000
        - PGID=1000
        - TZ=America/Toronto
    image: linuxserver/mariadb:latest
    ports:
        - 3306:3306
    restart: unless-stopped
    volumes:
        - /mnt/share/spool/nextcloud/db:/config
  nextcloud:
    container_name: nextcloud
    depends_on:
        - mariadb
    environment:
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=root
    image: nextcloud:latest
    links:
        - mariadb
    ports:
        - 80:80
    restart: unless-stopped
    volumes:
        - /mnt/share/spool/nextcloud/html:/var/www/html
        - /mnt/share/spool/nextcloud/custom_apps:/var/www/html/custom_apps
        - /mnt/share/spool/nextcloud/data:/var/www/html/data
        - /mnt/share/spool/nextcloud/config:/var/www/html/config
```
make sure to enter mariadb password in the `docker-compose.yml file` as you will need that later.
next run docker-compose command `docker-compose up -d` it will pull the images from docker hub and run all three containers. next you need to create nextcloud database.
`http:<local ip address>:8080` (adminer container)
![screen shot 2018-01-21 at 10 05 55 pm](https://user-images.githubusercontent.com/32021606/35203655-482c7400-fef7-11e7-95a9-0d6fc88c55a9.png)
here enter the password that you wrote in the `docker-compose.yml` file.
click on create database and configure it same as below.
![screen shot 2018-01-21 at 10 09 09 pm](https://user-images.githubusercontent.com/32021606/35203765-db470fa2-fef7-11e7-84d3-0fd4c3e5165e.png)
after that go to `http:<local ip address>:80` (nextcloud container)
enter username as password and configure it same as below.
![screen shot 2018-01-21 at 10 13 57 pm](https://user-images.githubusercontent.com/32021606/35203909-a446a0fc-fef8-11e7-95f5-14556c648117.png)
