### ISSUE TITLE
Upgrade installs version 27 instead of 26

### ISSUE THREAD

**Issue by Phillomath** [nextcloud/docker#2020]
I currently have version 25.0.4.1 installed, when I attempt to upgrade my install using the 26.0.3-alpine image it instead installs version 27.0.0.8 which then fails to migrate due to the skipped version.

I have restored from backup and re-attempted this upgrade at least 3 times with the same result.

Before and after the upgrade I am checking the version with the command:
`docker compose exec --user www-data app php occ status`

And it goes straight from:
```
  - installed: true
  - version: 25.0.4.1
  - versionstring: 25.0.4
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
```
to
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
  - installed: true
  - version: 27.0.0.8
  - versionstring: 27.0.0
  - edition: 
  - maintenance: true
  - needsDbUpgrade: true
  - productname: Nextcloud
  - extendedSupport: false
```

The relevant section from my docker-compose:
```
  app:
    #image: nextcloud:stable-apache
    image: nextcloud:26.0.3-apache
    build: .
    restart: always
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html
      - /mnt/ncdata/data:/var/www/html/data
    environment:
      - VIRTUAL_HOST=###
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - default
```
