### ISSUE TITLE
Exposing the port 9000 of nextcloud:fpm-alpine to the public network leads to RCE attacks

### ISSUE THREAD

**Issue by Urie96** [nextcloud/docker#2026]
docker-compose.yml:
```yml
services:
  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-server
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html:z
    network_mode: host
    expose:
      - '9000'
    environment:
      TZ: Asia/Shanghai
      NEXTCLOUD_ADMIN_USER:
      NEXTCLOUD_ADMIN_PASSWORD:
      NEXTCLOUD_TRUSTED_DOMAINS:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      REDIS_HOST:
      REDIS_HOST_PASSWORD:

  web:
    image: nginx:alpine
    container_name: nextcloud-web
    restart: unless-stopped
    network_mode: host
    expose:
      - '${PORT}'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nextcloud:/var/www/html:z,ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html:z
    entrypoint: /cron.sh
```
attacking process `kdevtmpfsi` in nextcloud-server container:
```sh
# ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 php-fpm: master process (/usr/local/etc/php-fpm.conf)
   59 www-data  0:03 php-fpm: pool www
   60 www-data  0:07 php-fpm: pool www
   61 www-data  0:03 php-fpm: pool www
 1572 www-data  0:02 /tmp/kinsing
 1739 www-data 10h32 /tmp/kdevtmpfsi
 2259 www-data  0:02 php-fpm: pool www
 2260 www-data  0:04 php-fpm: pool www
 2280 root      0:00 /bin/sh -c eval $(grep ^$(id -un): /etc/passwd | cut -d : -f 7-)
 2290 root      0:00 /bin/ash
 2291 root      0:00 ps -ef
```
