### ISSUE TITLE
Value too large for defined data type: AH00099: could not create /var/run/apache2/apache2.pid.j5mPFf

### ISSUE THREAD

**Issue by rajil** [nextcloud/docker#2030]
Hello,

My docker compose looks like this,

```
version: '2'


services:
  redis:
     image: redis:alpine
     restart: always

  app:
    container_name: nextcloud
    image: nextcloud:26
    restart: always
    ports:
      - 8081:80
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAIN=cloud.blah.com
    volumes:
      - /home/ubuntu/dockerdata/volumes/Nextcloud/nextcloud:/var/www/html
      - /home/ubuntu/dockerdata/volumes/Nextcloud/apps:/var/www/html/custom_apps
      - /home/ubuntu/dockerdata/volumes/Nextcloud/config:/var/www/html/config
      - /home/ubuntu/dockerdata/volumes/Nextcloud/data:/var/www/html/data
      - /mnt/files:/mnt/files
    env_file:
      - db.env

```

Unfortunately, the container never starts.

```
Configuring Redis as session handler
Initializing nextcloud 26.0.3.2 ...
New nextcloud instance
Initializing finished
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
==> but the hook folder "before-starting" is empty, so nothing to do
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.0.2. Set the 'ServerName' directive globally to suppress this message
[Sun Jul 16 13:36:22.288531 2023] [core:error] [pid 1] (75)Value too large for defined data type: AH00099: could not create /var/run/apache2/apache2.pid.j5mPFf
[Sun Jul 16 13:36:22.288554 2023] [core:error] [pid 1] AH00100: apache2: could not log pid to file /var/run/apache2/apache2.pid
```

Permissions in the volume folders is www-data.
