### ISSUE TITLE
custom_apps folder empty

### ISSUE THREAD

**Issue by psleep** [nextcloud/docker#2035]
I have the following docker-compose:

```yaml
#Nextcloud
  nc:
    image: nextcloud
    container_name: nc
    networks:
      - dockernet
    depends_on:
      - ncdb
      - ncredis
    volumes:
      - nc:/var/www/html
      - ./nc/config:/var/www/html/config
      - ./nc/custom_apps:/var/www/html/custom_apps
      - ./nc/data:/var/www/html/data
      - ./nc/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://127.0.0.1 || exit 1
      start_period: 90s
      timeout: 10s
      interval: 5s
      retries: 3
    profiles:
      - default
```

the custom_apps directory is empty and when I run a docker-compose pull / docker-compose up -d to update, I lose apps that I have installed like Notes, Calendar and Cookbook and I have to re-download and enable them. 
I dont think this is expected behaviour looking at the documentation. 

I found some references online to the apps_paths variable in config.php but I do not think that is required in my case. 

Currently running Nextcloud 27.0.1
Any suggestions or pointers greatly appreciated :)

Other than that, I have been running Nextcloud flawlessly for years - you have really built a great bit of software!

(github breaks the yaml formatting but I assure you the layout/tabs are correct :) )
