### ISSUE TITLE
Random Encryption corrupt files

### ISSUE THREAD

**Issue by DarkXero-dev** [nextcloud/docker#2097]
Hello

Nextcloud version : 27.1.3-ls280
Operating system : ArchLinux
nginx version : nginx 2023/04/13
PHP version : 8.x

The issue I am facing:

I have recently deployed Docker image of NextCloud, uploaded my stuff to it, but then when I want to view them I get corrupt files, and when I try to open them locally I get the following message.

```
HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256
CTR:signed:true:HEND
```

Portainer Stack
```
version: '2'

services:
  db:
    image: mariadb
    container_name: db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - /mnt/NextCloud/CloudNext/Database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Censored #change this
      - MYSQL_PASSWORD=Censored #change this
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    links:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_PASSWORD=Censored  #change this to match the mysql_password above
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    volumes:
      - /mnt/NextCloud/CloudNext/Config:/config
      - /mnt/NextCloud/CloudNext/Storage:/data
    ports:
      - 443:443
    restart: unless-stopped
```

Using Mariadb bridged container. server-side-encryption is disabled cannot be enabled. Accessing via https…

Steps to replicate it:

1- Deploy Container
2- Upload files n wait
3- Try downloading = encrypted files

My config.php

```
<?php
$CONFIG = array (
  'datadirectory' => '/data',
  'instanceid' => 'Censored',
  'passwordsalt' => 'Censored',
  'secret' => 'Cencored',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '192.168.2.78',
    2 => '192.168.1.88',
    3 => 'xero-vault.local',
  ),
  'dbtype' => 'mysql',
  'version' => '27.1.3.2',
  'overwrite.cli.url' => 'https://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'Censored',
  'installed' => true,
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' => 
  array (
  ),
  'twofactor_enforced_excluded_groups' => 
  array (
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => false,
  'memcache.locking' => '\\OC\\Memcache\\APCu',
  'upgrade.disable-web' => true,
);
```
