### ISSUE TITLE
Updating from 26.0.5 to 27.1.3 causes mismatch version shown with php -i and config.php/version.php

### ISSUE THREAD

**Issue by johnhelt** [nextcloud/docker#2103]
I tried updating to version 27.1.3 using the docker approach, and setting the env variable UPDATE_NEXTCLOUD=1. My docker-compose file is show below:

```
services:

  app:
    image: nextcloud:27.1.3-fpm
    hostname: app
    container_name: nextcloud
    volumes:
      - /mnt/pool/cloud/nextcloud/data:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=4096M
      - REDIS_HOST=redis
      - UPDATE_NEXTCLOUD=1
    depends_on:
     - db
     - redis
    networks:
      - nextcloud
    restart: unless-stopped
    group_add:
      - "110"
    devices:
      - '/dev/dri:/dev/dri'

  web:
   build: ./web
   restart: always
   volumes:
     - /mnt/pool/cloud/nextcloud/data:/var/www/html
   volumes_from:
     - app
   environment:
     - VIRTUAL_HOST=my.domain.com
     - LETSENCRYPT_HOST=my.domain.com
     - VIRTUAL_PORT=80
   networks:
     - nginx-proxy_proxy
     - nextcloud
   depends_on:
     - app

  redis:
    image: redis
    container_name: redis
    networks:
      - nextcloud

    restart: unless-stopped

  db:
    image: quay.io/mariadb-foundation/mariadb-devel:11.0
    hostname: mariadb
    container_name: mariadb
    volumes:
      - ~/server-volumes/mariadb/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./db.cnf:/etc/mysql/conf.d/db.cnf
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - NETWORK_ACCESS=internal
    restart: unless-stopped
    networks:
      - nextcloud


# By default this config uses default local driver,
# For custom volumes replace with volume driver configuration.

networks:
  nextcloud:
  nginx-proxy_proxy:
    external: true
```

The update finished ok. For some reason, when the update finished, it asked me to create a new admin account again. I just shut down the instance, and removed the env variable (UPDATE_NEXTCLOUD=1), and restart, after which nextcloud would start up again fine. However, when I go into "administration settings", I see that the version is still 26.0.5. I did a check of the version.php/config.php, and php-i there's a mismatch there:

php -i shows:
```
$_ENV['NEXTCLOUD_VERSION'] => 27.1.3
```

while occ:config list system shows:

```
"version": "26.0.5.1"
```

here's the entire output of occ config:list system

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.245",
            "my.domain.com"
        ],
        "overwrite.cli.url": "http:\/\/my.domain.com",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "logfile": "\/var\/www\/html\/nextcloud.log",
        "logdateformat": "F d, Y H:i:s",
        "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
        "preview_max_memory": 4096,
        "preview_max_filesize_image": 256,
        "memories.vod.disable": false,
        "memories.vod.ffmpeg": "\/usr\/local\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/local\/bin\/ffprobe",
        "maintenance": false,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie"
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memories.vod.vaapi": true,
        "updater.release.channel": "beta",
        "memories.vod.use_transpose": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "memories.video_default_quality": "-1"
    }
}
```

What's going on here?
