### ISSUE TITLE
Docker Image Update - "Start update" on WebUI

### ISSUE THREAD

**Issue by dR3b** [nextcloud/docker#2110]
Since a few versions, I need to click "Start update" on the WebUI after a Docker image update. Why?
![20231202-141010](https://github.com/nextcloud/docker/assets/9670938/a38949ce-d9cc-4bc4-a5d2-1bba9bef7f77)

Example Update:
Docker Image `nextcloud:27.1.3-apache` -> `nextcloud:27.1.4-apache`

**Comment by wwwmickey** [comment]
Hi,

What happens after you click start update? I have the same problem but after i click start update it says the update has failed.
Than i have to roll back to version 27.1.2

**Comment by dR3b** [comment]
After a click on "Start update" everything works as expected. I think with version 26 or so this behavior occurred.

**Comment by joshtrichards** [comment]
What does the Docker log show when you start up the image to trigger the update/upgrade cycle? (E.g. `docker compose logs app` or similar)

For some reason `occ upgrade` isn't being triggered.

**Comment by dR3b** [comment]
@joshtrichards 
Unfortunately I no longer have any logs, but I can copy them with the next update.

**Comment by dR3b** [comment]
So far, no, but I don't use a custom command. I will give it a try. When was this option introduced?

**Comment by joshtrichards** [comment]
Also check your Nextcloud config (including all Compose derived variables): https://github.com/nextcloud/docker/issues/2111#issuecomment-1841466670

**Comment by dR3b** [comment]
I did more tests yesterday and the same setup works perfectly, even without `NEXTCLOUD_UPDATE`!

`docker-compose.yml`:
```
version: "3.9"

networks:
  nextcloud:
    external: false

services:
  app:
    container_name: nextcloud-app
    image: nextcloud:28.0.0-apache
    init: true
    restart: always
    environment:
      REDIS_HOST: "redis"
      NEXTCLOUD_ADMIN_USER: "sysadmin"
      NEXTCLOUD_ADMIN_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxx"
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxx"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nextcloud/app/data:/var/www/html
    networks:
      - nextcloud
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis

  cron:
    container_name: nextcloud-cron
    image: nextcloud:28.0.0-apache
    init: true
    restart: always
    entrypoint: /cron.sh
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nextcloud/app/data:/var/www/html
    networks:
      - nextcloud

  db:
    container_name: nextcloud-db
    image: mysql:8.0
    init: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "xxxxxxxxxxxxxxxxxxxxx"
      MYSQL_DATABASE: "nextcloud"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./nextcloud/db/data:/var/lib/mysql
    networks:
      - nextcloud

  redis:
    container_name: nextcloud-redis
    image: redis:6.2-alpine
    init: true
    restart: always
    networks:
      - nextcloud
```
Updatelog (Level 2):
```
nextcloud-app  | Initializing nextcloud 28.0.0.11 ...
nextcloud-app  | Upgrading nextcloud from 27.1.3.2 ...
nextcloud-app  | => Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/pre-upgrade
nextcloud-app  | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
nextcloud-app  | You may use your browser or the occ upgrade command to do the upgrade
nextcloud-app  | Setting log level to debug
nextcloud-app  | Turned on maintenance mode
nextcloud-app  | Updating database schema
nextcloud-app  | Updated database
nextcloud-app  | Disabled incompatible app: files_rightclick
nextcloud-app  | Updating <federation> ...
nextcloud-app  | Updated <federation> to 1.18.0
nextcloud-app  | Updating <lookup_server_connector> ...
nextcloud-app  | Updated <lookup_server_connector> to 1.16.0
nextcloud-app  | Updating <oauth2> ...
nextcloud-app  | Updated <oauth2> to 1.16.3
nextcloud-app  | Updating <password_policy> ...
nextcloud-app  | Updated <password_policy> to 1.18.0
nextcloud-app  | Updating <photos> ...
nextcloud-app  | Updated <photos> to 2.4.0
nextcloud-app  | Updating <files> ...
nextcloud-app  | Updated <files> to 2.0.0
nextcloud-app  | Updating <activity> ...
nextcloud-app  | Updated <activity> to 2.20.0
nextcloud-app  | Updating <circles> ...
nextcloud-app  | Updated <circles> to 28.0.0-dev
nextcloud-app  | Updating <cloud_federation_api> ...
nextcloud-app  | Updated <cloud_federation_api> to 1.11.0
nextcloud-app  | Updating <dav> ...
nextcloud-app  | Fix broken values of calendar objects
nextcloud-app  |
nextcloud-app  |  Starting ...
nextcloud-app  |
nextcloud-app  | Clean up old calendar subscriptions from deleted users that were not cleaned-up
nextcloud-app  |
nextcloud-app  |     0/0 [>---------------------------]   0% Starting ...
nextcloud-app  |
nextcloud-app  | Updated <dav> to 1.29.1
nextcloud-app  | Updating <files_sharing> ...
nextcloud-app  | Updated <files_sharing> to 1.20.0
nextcloud-app  | Updating <files_trashbin> ...
nextcloud-app  | Updated <files_trashbin> to 1.18.0
nextcloud-app  | Updating <files_versions> ...
nextcloud-app  | Updated <files_versions> to 1.21.0
nextcloud-app  | Updating <sharebymail> ...
nextcloud-app  | Updated <sharebymail> to 1.18.0
nextcloud-app  | Updating <workflowengine> ...
nextcloud-app  | Updated <workflowengine> to 2.10.0
nextcloud-app  | Updating <comments> ...
nextcloud-app  | Updated <comments> to 1.18.0
nextcloud-app  | Updating <firstrunwizard> ...
nextcloud-app  | Updated <firstrunwizard> to 2.17.0
nextcloud-app  | Updating <logreader> ...
nextcloud-app  | Updated <logreader> to 2.13.0
nextcloud-app  | Updating <nextcloud_announcements> ...
nextcloud-app  | Updated <nextcloud_announcements> to 1.17.0
nextcloud-app  | Updating <notifications> ...
nextcloud-app  | Updated <notifications> to 2.16.0
nextcloud-app  | Updating <systemtags> ...
nextcloud-app  | Updated <systemtags> to 1.18.0
nextcloud-app  | Updating <theming> ...
nextcloud-app  | Migrate old user accessibility config
nextcloud-app  |
nextcloud-app  |     0/0 [->--------------------------]   0% Starting ...
nextcloud-app  |
nextcloud-app  | Updated <theming> to 2.3.0
nextcloud-app  | Updating <contactsinteraction> ...
nextcloud-app  | Updated <contactsinteraction> to 1.9.0
nextcloud-app  | Updating <dashboard> ...
nextcloud-app  | Updated <dashboard> to 7.8.0
nextcloud-app  | Updating <federatedfilesharing> ...
nextcloud-app  | Updated <federatedfilesharing> to 1.18.0
nextcloud-app  | Updating <files_pdfviewer> ...
nextcloud-app  | Updated <files_pdfviewer> to 2.9.0
nextcloud-app  | Updating <files_reminders> ...
nextcloud-app  | Updated <files_reminders> to 1.1.0
nextcloud-app  | Updating <privacy> ...
nextcloud-app  | Updated <privacy> to 1.12.0
nextcloud-app  | Updating <provisioning_api> ...
nextcloud-app  | Updated <provisioning_api> to 1.18.0
nextcloud-app  | Updating <recommendations> ...
nextcloud-app  | Updated <recommendations> to 2.0.0
nextcloud-app  | Updating <related_resources> ...
nextcloud-app  | Updated <related_resources> to 1.3.0
nextcloud-app  | Updating <serverinfo> ...
nextcloud-app  | Updated <serverinfo> to 1.18.0
nextcloud-app  | Updating <settings> ...
nextcloud-app  | Updated <settings> to 1.10.0
nextcloud-app  | Updating <support> ...
nextcloud-app  | Updated <support> to 1.11.0
nextcloud-app  | Updating <survey_client> ...
nextcloud-app  | Updated <survey_client> to 1.16.0
nextcloud-app  | Updating <text> ...
nextcloud-app  | Updated <text> to 3.9.1
nextcloud-app  | Updating <twofactor_backupcodes> ...
nextcloud-app  | Updated <twofactor_backupcodes> to 1.17.0
nextcloud-app  | Updating <updatenotification> ...
nextcloud-app  | Updated <updatenotification> to 1.18.0
nextcloud-app  | Updating <user_status> ...
nextcloud-app  | Updated <user_status> to 1.8.1
nextcloud-app  | Updating <viewer> ...
nextcloud-app  | Updated <viewer> to 2.2.0
nextcloud-app  | Updating <weather_status> ...
nextcloud-app  | Updated <weather_status> to 1.8.0
nextcloud-app  | Starting code integrity check...
nextcloud-app  | Finished code integrity check
nextcloud-app  | Update successful
nextcloud-app  | Turned off maintenance mode
nextcloud-app  | Resetting log level
```
