### ISSUE TITLE
Nextcloud docker-compose update to 27.1.3 stuck

### ISSUE THREAD

**Issue by wwwmickey** [nextcloud/docker#2111]
Hi,

I'm trying to update from 27.1.2 to 27.1.3 using the docker compose command.
In the past this workt but now I'm stuck. The 27.1.4 image has the same result.
The version parameter stays on version' => '27.1.2.1' after the update.

Docker-compose file:

```
version: "3"
volumes:
  nextcloud-data:
  nextcloud-db:
  npm-data:
  npm-ssl:
  npm-db:
  redis-db:

networks:
  frontend:
    # add this if the network is already existing!
    # external: true
  backend:

services:
  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=**********
      - MYSQL_DATABASE=**********
      - MYSQL_USER=**********
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - NEXTCLOUD_INIT_LOCK=true
      - NEXTCLOUD_INIT_HTACCESS=true
    networks:
      - frontend
      - backend
    depends_on:
      - nextcloud-db
      - redis

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=**********
      - MYSQL_PASSWORD=**********
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=**********
    networks:
      - backend

  npm-app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - DB_MYSQL_HOST=npm-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=**********
      - DB_MYSQL_PASSWORD=**********
      - DB_MYSQL_NAME=**********
    volumes:
      - npm-data:/data
      - npm-ssl:/etc/letsencrypt
    networks:
      - frontend
      - backend

  npm-db:
    image: jc21/mariadb-aria:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=**********
      - MYSQL_DATABASE=**********
      - MYSQL_USER=**********
      - MYSQL_PASSWORD=**********
    volumes:
      - npm-db:/var/lib/mysql
    networks:
      - backend

  # Add the official ClamAV container
  clamav:
    image: clamav/clamav:stable_base
    # Specify container name for easier mapping later
    restart: always
    container_name: clamav
    # Map the virus database file so it doesn't have to re-download each time
    volumes:
      - /opt/volumes/clamav:/var/lib/clamav
    networks:
      - frontend
      - backend
  
  redis:
    image: redis
    restart: always
    volumes:
      - redis-db:/data
    networks:
      - backend
```
Config.php:
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => '********',
  'passwordsalt' => '**************************************',
  'secret' => '************************************',
  'trusted_domains' => 
  array (
    0 => '**********************',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '27.1.2.1',
  'overwrite.cli.url' => 'http://*****************************',
  'overwriteprotocol' => 'https',
  'dbname' => '*****',
  'dbhost' => '********',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '********',
  'dbpassword' => '*********************',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => '**********',
  'mail_domain' => '**********',
  'mail_smtphost' => 'smtp-mail.outlook.com',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '*************',
  'mail_smtppassword' => '************',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
'host' => 'redis',
    'port' => 6379,
  ),
  'default_phone_region' => 'BE',
  'default_language' => 'nl',
  'loglevel' => 
  array (
    ' ^`^svalue=2' => '',
  ),
  'maintenance' => false,
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' => 
  array (
    0 => 'Family',
  ),
  'twofactor_enforced_excluded_groups' => 
  array (
    0 => 'guest_app',
  ),
  'updater.release.channel' => 'stable',
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
```
This massage a pears on the login page.  

![Screenshot 2023-11-05 at 14-39-37 Nextcloud](https://github.com/nextcloud/docker/assets/152704163/195bf58e-cba0-4b88-a3cf-51782344f389)

If I trie to update here it fails without an error code. It just says it has failed.

Thanks!
