### ISSUE TITLE
Nextcloud on Docker/K8s: "oc_admin" does not exist" after manifest update

### ISSUE THREAD

**Issue by qworkz11** [nextcloud/docker#2116]
Hi,

I am having troubles with my docker Nextcloud installation using Kubernetes:

After updating the Nextcloud version in the K8s manifest (`26.0.8-apache` -> `27.1.3-apache`), postgres seems to be corrupted, as it logs `FATAL:  password authentication failed for user "oc_admin"` and `Role "oc_admin" does not exist.` messages. As a consequence I cannot reach the Nextcloud UI, and all `occ` commands fail (`FATAL:  password authentication failed for user "oc_admin"`). I had experienced this error once before after some misconfiguration of mounted config files, and could only fix it by deleting all volumes and starting fresh.

I'm working on a test setup currently, so setting up a fresh Nextcloud installation is no problem, but that is not a solution once the installation is running in production.

Any ideas why this problem occurs, or how it can be fixed without data loss? Did I mis-configure something?

Container section of Nextcloud manifest:
```yaml
containers:
  - name: nextcloud
    image: nextcloud:27.1.3-apache
    ports:
      - containerPort: 80
    volumeMounts:
      - name: nextcloud-volume
        mountPath: /var/www/html
    env:
      - name: POSTGRES_DB
        value: nextcloud
      - name: POSTGRES_USER
        value: nextcloud
      - name: POSTGRES_PASSWORD
        value: nextcloud
      - name: POSTGRES_HOST
        value: nextcloud-db
      - name: NEXTCLOUD_ADMIN_USER
        value: admin
      - name: NEXTCLOUD_ADMIN_PASSWORD
        value: admin
  - name: nextcloud-cron
    image: nextcloud:27.1.3-apache
    command:
      - /cron.sh
    volumeMounts:
      - name: nextcloud-volume
        mountPath: /var/www/html
```

Container section of postgres manifest:
```yaml
containers:
  - name: nextcloud-db
    image: postgres:16.0
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: nextcloud
      - name: POSTGRES_PASSWORD
        value: nextcloud
      - name: POSTGRES_DB
        value: nextcloud
    volumeMounts:
      - mountPath: /var/lib/postgresql
        subPath: data
        name: nextcloud-db
```

Thanks!
