### ISSUE TITLE
The Nextcloud Initialization Produces Redundant Configurations Ignoring Environment Variables

### ISSUE THREAD

**Issue by manuth** [nextcloud/docker#2117]
When initializing a new Nextcloud installation, the `maintenance:install` part of the installation creates redundant settings which draw docker environment variables unfunctional.

Example of a brief `docker-compose.yml` setup:

```yml
version: "3.7"

services:
  nextcloud:
    image: nextcloud:fpm
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db
    environment:
      # Settings Required for Automated Installation
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: nextcloud
      # Database Settings
      MYSQL_HOST: db
      MYSQL_DATABASE: NextCloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      # Some Example Settings
      SMTP_HOST: example.org
      SMTP_PORT: 25
      SMTP_NAME: scott
      SMTP_PASSWORD: tiger
      MAIL_FROM_ADDRESS: john.doe
      MAIL_DOMAIN: example.org
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: cloud.example.org
      OVERWRITECLIURL: https://cloud.example.org
    volumes:
      - webroot:/var/www/html:z
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: NextCloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: nextcloud
    volumes:
      - db:/var/lib/mysql
    command:
      - --innodb_read_only_compressed=OFF

volumes:
  webroot:
  cache:
  db:
```

### Steps of reproduction:
1. Set up docker-compose environment:
   ```sh
   # Clean up pre-existing containers and volumes
   docker compose down --volumes
   # Set up environment
   docker compose up -d --build
   # Wait until the `nextcloud` service reports that it's ready to accept FPM connections
   docker compose logs --follow nextcloud
   ```
2. Examine config files:
   ```sh
   docker compose exec nextcloud bash -c 'tail -n+1 /var/www/html/config/*config.php'
   ```

### Actual Result
Take note that all settings configured using environment variables (or implicitly configured) in these files:
  - `autoconfig.php`: Database settings
  - `apcu.config.php`: Local cache settings
  - `apps.config.php`: App paths
  - `reverse-proxy.config.php`: Reverse proxy settings (overwrite host, protocol, cli etc.)
  - `smtp.config.php`: Mail settings
  - `redis.config.php`: Redis settings

However, all settings configured implicitly or using environment variables are overridden by the `config.php` file which is created during the initialization.

Take note that all settings occurring in the previously named files also occur in the `config.php` file. This means that future changes made to the environment variables won't have any effect which, as far as I assume, isn't the expected or desired behavior.

### Expected Result
Settings occurring in the files `autoconfig.php`, `apcu.config.php`, `apps.config.php`, `reverse-proxy.config.php`, `smtp.config.php`, `redis.config.php` etc. which contain implicitly configured or settings configured using environment variables should **not** re-occur in the `config.php` file in order to allow future changes to environment variables and remove confusion as to where the value of settings (such as mail settings, reverse-proxy settings and DB settings) actually come from.

Related to
  - #2086
  - #464
  - #189
  - #1312: How to allow GUI configuration? should this purposefully create overrides in `config.php` and/or show a warning?
