### ISSUE TITLE
Please support dynamic user namespaces

### ISSUE THREAD

**Issue by cptspff** [nextcloud/docker#2127]
docker-entrypoint.sh currently makes it very hard to run a Nextcloud container in an isolated [dynamic user namespace](https://docs.podman.io/en/v4.4/markdown/options/userns.container.html). Because UIDs are not known on the host before starting a container in such an environment, setting the correct file permissions to allow fine grained write access for the user running fpm or apache is impossible.

Looking at [some](https://github.com/MariaDB/mariadb-docker/blob/869b513d72c550dbcede5818576f88539a0c07f1/docker-entrypoint.sh#L196) [other](https://github.com/docker-library/postgres/blob/31aed10dbe490c13e5ca889897ee01ef3e1b91e2/docker-entrypoint.sh#L36) [entrypoints](https://github.com/element-hq/synapse/blob/742bae3761b7b2c638975f853ab6161527629240/docker/start.py#L137) usually this problem is mitigated by a simple `chown -R`.

**Comment by meonkeys** [comment]
Related:

* #359
* #458
* #1144
* #1314
* #1428

**Comment by joshtrichards** [comment]
Can you provide a more specific example of where our approach causes problems when using user namespaces?

I'd expect problems when attempting to share data with the underlying host using bind mounts (that's one of the downsides and it's not clear to me there's anything to be done about that in the image itself), but named volumes I think should be just fine...

Note we already support `--user` / `user` (related so I'm mentioning in case you're unaware).

**Comment by kingp0dd** [comment]
> Can you provide a more specific example of where our approach causes problems when using user namespaces?
> 
> I'd expect problems when attempting to share data with the underlying host using bind mounts (that's one of the downsides and it's not clear to me there's anything to be done about that in the image itself), but named volumes I think should be just fine...
> 
> Note we already support `--user` / `user` (related so I'm mentioning in case you're unaware).

May I know if user works in docker compose? I'm trying to set it to root but it seem to be defaulting to 33 always.

In my case:
- Docker running rootless
- NEXTCLOUD_DATA_DIR is a SMB CIFS folder

I mount SMB in host as user (not root):

`//truenas.internal/nextcloud-test /home/d/docker/mnt/nextcloud-test cifs credentials=/home/d/docker/mnt/cred-nextc,mfsymlinks,seal,vers=3.0,nounix,file_mode=0770,dir_mode=0770,user 0 0`

Then compose looks like:

```

    volumes:
      - ./nextcloud/www_html:/var/www/html/
      - ../../mnt/nextcloud-test:/media/nextcloud-truenas
    environment:
      - NEXTCLOUD_DATA_DIR=/media/nextcloud-truenas
     
```

Now during initial setup in Nextcloud Web GUI, I get:

```
Error
Cannot create or write into the data directory /media/nextcloud-truenas
```

This is because uid 33 doesn't have access to the mount. Container root (=local user) should be able to access the mount, so `user= 0:0` in compose should work fine

**Comment by Lumysia** [comment]
Hi, I've found a example of the permission issue described in this issue when running with a non-root user. The docker-entrypoint script fails when trying to write the Redis session configuration.

https://github.com/nextcloud/docker/blob/b326158abcd68cbd7574f44e886c529cb19f536e/docker-entrypoint.sh#L147

```log
nextcloud-1 | 2025-08-05T08:59:27.916543000Z /entrypoint.sh: 118: cannot create /usr/local/etc/php/conf.d/redis-session.ini: Permission denied
nextcloud-1 | 2025-08-05T08:59:28.965317000Z Configuring Redis as session handler
nextcloud-1 | 2025-08-05T08:59:28.965677000Z /entrypoint.sh: 118: cannot create /usr/local/etc/php/conf.d/redis-session.ini: Permission denied 
```

The problem occurs under a specific set of conditions:
- The `user: ${PUID}:${PGID}` directive is used in docker-compose.yml.
- The `REDIS_HOST` environment variable is set.

In this scenario, the entire entrypoint script is executed as the non-root user specified by PUID. However, the target directory, `/usr/local/etc/php/conf.d/`, is owned by root. As a result, the non-root user does not have the required permissions to create redis-session.ini, leading to the "Permission denied" error.

**Comment by jokay** [comment]
@joshtrichards I can confirm this problem. Using `user: 977:988` ...

```yml
services:
  app:
    image: nextcloud:32.0.1
    volumes:
      - ./data/app:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD={my-postgres-password}
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD={my-admin-nextcloud-password}
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - default
    ports:
      - 8080:80
    user: 977:988

  db:
    image: postgres:18.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD={my-postgres-password}
    networks:
      - default

  redis:
    image: redis:8.2.2-alpine
    networks:
      - default

networks:
  default:
```

... I get the following error as well:

```sh
Configuring Redis as session handler
/entrypoint.sh: 118: cannot create /usr/local/etc/php/conf.d/redis-session.ini: Permission denied
```

**Comment by jokay** [comment]
While we wait for an official entrypoint fix, here is a possible workaround for anyone running into the same issue.

Adding this ...

```yml
    configs:
      - source: redis_session_ini
        target: /usr/local/etc/php/conf.d/redis-session.ini
        uid: "977"
        gid: "988"
        mode: 0440
```

... and ...

```yml
configs:
  redis_session_ini:
    content: |
      session.save_handler = redis
      session.save_path = "tcp://redis:6379"
```

Which will result in ...

```yml
services:
  app:
    image: nextcloud:33.0.0
    volumes:
      - ./data/app:/var/www/html
    configs:
      - source: redis_session_ini
        target: /usr/local/etc/php/conf.d/redis-session.ini
        uid: "977"
        gid: "988"
        mode: 0440
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD={my-postgres-password}
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD={my-admin-nextcloud-password}
      # - REDIS_HOST=redis
      # - REDIS_HOST_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - default
    ports:
      - 8080:80
    user: 977:988

  db:
    image: postgres:18.3-alpine
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD={my-postgres-password}
    networks:
      - default

  redis:
    image: redis:8.6.1-alpine
    networks:
      - default

networks:
  default:

configs:
  redis_session_ini:
    content: |
      session.save_handler = redis
      session.save_path = "tcp://redis:6379"
```

**Comment by te-online** [comment]
I don't know why this suddenly came up during an update. Luckily I found y'alls' helpful responses ❤️  

But for one setup I've had to adapt the answers above to Podman+Quadlet+Ansible. In case someone randomly needs some inspiration, I did it like so:

<details>

<summary>nextcloud.container.j2</summary>

```
[Unit]
Description=Nextcloud container
After=local-fs.target db.service redis.service

[Container]
Image=docker.io/nextcloud:32.0.7-fpm-alpine
ContainerName=nextcloud
AutoUpdate=registry
PublishPort=9000:9000
User=www-data
Volume=/home/user/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini:U,z
Volume=/home/user/nextcloud:/var/www/html:U,z
Environment="OVERWRITEHOST={{ inventory_hostname }}"
# ... more config

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
```
</details>
<details>

<summary>redis-session.ini</summary>

```
session.save_handler = redis
session.save_path = "tcp://10.0.0.2:6379?auth={{ redis_password }}"
```

</details>
<details>

<summary>playbook.yml</summary>

```
# …more playbook tasks…
        - name: Copy extra redis-session.ini
          ansible.builtin.template:
            src: ../../config/nextcloud/redis-session.ini.j2
            dest: "/home/user/redis-session.ini"
            mode: "644"
# …more playbook tasks…
```
</details>

Good luck everyone! 😆
