### ISSUE TITLE
Integrity error after upgrading 27.1.5 to 28.0.0

### ISSUE THREAD

**Issue by mdartmann** [nextcloud/docker#2129]
After upgrading Nextcloud from 27.1.5 to 28.0.0, the integrity check fails. 

<pre>
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201
                            [current] => 24e6faa4a1361e51ff70027024f41c4b37fdb5f6f347ceb095450ddbde2d0a6b6dd1403be92a912d2889064a9736a9bed89d7dc62470035fc1299d4b977c5f46
                        )

                )

        )

)
</pre>

Compose file:
```yml
version: '3.9'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.128.0.0/16

services:
  app:
    image: nextcloud:28.0.0-fpm-alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
      - ./php-config:/usr/local/etc
    depends_on:
      - redis
    networks:
      default:
        ipv4_address: 172.128.0.5

  redis:
    image: redis:alpine
    restart: always
    networks:
      default:
        ipv4_address: 172.128.0.2
    volumes:
      - ./redis-data:/data

  web:
    image: nginx:latest
    restart: always
    ports:
      - "127.0.0.1:8101:80"
    volumes:
      - ./nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
        default:
          ipv4_address: 172.128.0.7

  cron:
    image: nextcloud:28.0.0-fpm-alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - redis
    networks:
      default:
        ipv4_address: 172.128.0.4

  nextcloud_exporter:
    restart: always
    image: xperimental/nextcloud-exporter:latest
    ports:
      - 127.0.0.1:9205:9205
    env_file:
      - exporter.env
    depends_on:
      - app
```
`occ config:list --system`:

```json
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.dartmann.net",
            "office.dartmann.net"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.dartmann.net",
        "overwritehost": "cloud.dartmann.net",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "AT",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        }
    }
}
```
