### ISSUE TITLE
Auto configuration via environment variables not working correctly

### ISSUE THREAD

**Issue by tmo1** [nextcloud/docker#2139]
Hello,

I'm trying to set up Nextcloud via `docker-compose` with auto configuration via environment variables. Setting all the variables in `docker-compose.yml` works. Setting some of them (the sensitive ones) in an `.env` file (adjacent to the `docker-compose.yml` file) does not work - I get the infamous:

```
[ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
	You need to specify one of MARIADB_ROOT_PASSWORD, MARIADB_ROOT_PASSWORD_HASH, MARIADB_ALLOW_EMPTY_ROOT_PASSWORD and MARIADB_RANDOM_ROOT_PASSWORD
```
error message. Explicitly including the `.env` file in the `db:` section fixes the problem (including in the `app:` section is not required).

This is my `docker-compose.yml` file:

```
version: '2'

services:

  db:
    image: mariadb:11.2
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    #env_file:
      #- .env
    networks:
      caddy:
        ipv4_address: 172.16.0.8

  app:
    image: nextcloud:28.0
    restart: always
    networks:
      caddy:
        ipv4_address: 172.16.0.7
    labels:
      caddy: example.com
      caddy.reverse_proxy: "{{upstreams}}"
      caddy.header: /*
      caddy.header.Strict-Transport-Security: '"max-age=15552000;"'
      caddy.rewrite_0: /.well-known/carddav /remote.php/dav
      caddy.rewrite_1: /.well-known/caldav /remote.php/dav
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=172.16.0.6
    links:
      - db
  
  cron:
    image: nextcloud:28.0
    restart: always
    volumes:
      - nextcloud:/var/www/html
    networks:
      caddy:
        ipv4_address: 172.16.0.9
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  db:
  nextcloud:

networks:
  caddy:
    external: true
```

I have no idea if my problem is related to any of the problems discussed in #593.
