### ISSUE TITLE
Nextcloud no more accessible (setup via docker-compose with proxy)

### ISSUE THREAD

**Issue by jeremyfritzen** [nextcloud/docker#2147]
Hi!

Since few days, my Nextcloud setup doesn't work anymore: Nextcloud website is no more accessible.

# My setup
Nextcloud is deployed via the following `docker-compose` file (mostly inspired by the examples in this repo), run by `podman`:
```
version: '3'

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
  mysql_password:
    file: ./mysql_password.txt
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    healthcheck:
      test: "mysqladmin ping -h localhost -u$${MYSQL_USER} --password=$$(cat $${MYSQL_PASSWORD_FILE})"
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 40s
    secrets:
      - mysql_root_password
      - mysql_password

  redis:
    image: redis:alpine
    restart: always

  app:
    build: ./nextcloud-app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=nc.mydomain.com
      - VIRTUAL_HOST=nc.mydomain.com
      - LETSENCRYPT_HOST=nc.mydomain.com
      - LETSENCRYPT_EMAIL=my-email@gmail.com
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
    secrets:
      - mysql_root_password
      - mysql_password
      - nextcloud_admin_user
      - nextcloud_admin_password
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
        #      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
        #      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
```

- docker file for nextcloud container:
```
FROM nextcloud:apache
RUN apt update && apt install -y smbclient libsmbclient-dev && rm -rf /var/lib/apt/lists/* 
RUN pecl install smbclient 
RUN docker-php-ext-enable smbclient
```

- docker file for proxy container:
```
FROM nginxproxy/nginx-proxy:1.3-alpine
COPY uploadsize.conf /etc/nginx/conf.d/uploadsize.conf
```

# Problem description
It has been working well for months but, suddenly, without changing anything on purpose, Nextcloud is no more accessible.
`podman logs` gives me the following:
- for nextcloud container (called _app_ in the `docker-compose` file above):
```
Configuring Redis as session handler
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.89.1.52. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.89.1.52. Set the 'ServerName' directive globally to suppress this message
[Mon Jan 15 19:13:45.584315 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.13 configured -- resuming normal operations
[Mon Jan 15 19:13:45.584618 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```
- for proxy container: [see logs here](https://pastebin.com/TJjVFFyb)

# What I've tried
I don't know if the problem is on the Nextcloud or the Proxy containers.
What I'm sure is that I didn't change anything on the `docker-compose` and `docker` files. I suspect that an automatic update broke something.

I tried: 
- using older docker images (1 at a time, and then both at the same time) ;

Any idea of what could be wrong?
Thank you so much for your help!
