### ISSUE TITLE
cron.php execution gets stuck when container has been running for more than 24 hours

### ISSUE THREAD

**Issue by fefrei** [nextcloud/docker#2149]
I'm having a problem with my Docker-based Nextcloud installation since upgrading to version 28. I'm unsure where the issue is, but it might be related to the container, which is why I'm reporting it here.

I'm running the image `nextcloud:28` in conjunction with `mariadb:10.5` on a Synology NAS. Cron jobs are handled using an OS-level cron job that runs the command `docker exec cloud-app su -s /bin/bash www-data -c "php -f /var/www/html/cron.php"` every 5 minutes.

Since upgrading to version 28, I'm having an issue where the cron job regularly gets stuck. If it does, it gets stuck for multiple hours at least, and I notice because the NAS starts sending out emails that cron runs were skipped because the previous invocation is still running. While the job is stuck, there is no noticeable system load, and it does not seem to be stuck in MySQL (a `SHOW FULL PROCESS LIST` in the DB shows no long-running or weird jobs).
The extremely weird thing about this (which makes me thing it might be container-related): These occurrences are not random. So far, the issue has 100% re-occurred exactly 24 hours after creating the container. Once it happens, a `docker-compose down && docker-compose up -d` not only kills the stuck job, but everything is fine afterwards, for exactly 24 hours. So far, it looks like merely restarting the app container (leaving the DB running and not re-creating the app container) has the same effect, but it has not been 24 hours yet.

Does anyone have an idea what could be wrong here, or what info I could capture to help nail this down? (I assume I'm not the only one with this issue, but depending on the cron setup, it may be hard to notice – I only notice it because my cron scheduler doesn't re-run jobs that are already running, and sends emails about this.)

Here's my full Docker Compose file:

```
version: '2'
services:
  app:
    image: 'nextcloud:28'
    container_name: 'cloud-app'
    ports:
    - '8081:80'
    volumes:
    - ./data/nextcloud-html:/var/www/html
    - ./data/nextcloud-apps:/var/www/html/custom_apps
    - ./data/nextcloud-config:/var/www/html/config
    - ./data/nextcloud-data:/var/www/html/data
    logging:
      driver: json-file
    mem_limit: 1024m
    cpu_shares: 10
    environment:
    - PHP_MEMORY_LIMIT=1024M
  db:
    image: 'mariadb:10.5'
    container_name: 'cloud-db'
    volumes:
    - ./config/db/nextcloud.cnf:/etc/mysql/conf.d/nextcloud.cnf:ro
    - ./data/db-data:/var/lib/mysql
    logging:
      driver: json-file
    mem_limit: 1024m
    cpu_shares: 10
```
