### ISSUE TITLE
Nextcloud behind traefik - Redirect loop detected

### ISSUE THREAD

**Issue by logg-sar** [nextcloud/docker#2156]
Hi there

I´ve setup nextcloud behind a traefik router.
nextcloud itself is working - if I access it local, but not behind traefik.
There seems to be a issue with the certificate for the subdomain.

```
level=error msg="Unable to obtain ACME certificate for domains \"nextcloud.placeholder.local\": unable to generate a certificate for the domains [nextcloud.placeholder.local]: error: one or more domains had a problem:\n[nextcloud.placeholder.local] acme: error: 400 :: urn:ietf:params:acme:error:connection :: xxx.xxx.xxx.xxx: Fetching http://placeholder.local/.well-known/acme-challenge/jGSFmgz-S0ZQ4L-I1LjW52SxJWZkKvxah9Jti0j_vYU: Redirect loop detected\n" providerName=http.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=nextcloud@docker rule="(Host(`nextcloud.placeholder.local`))"

``` 

Here are my configs:

docker-compose.yml
``` 
version: '3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_web
    command:
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik_web"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.to.scheme=https"
      - "--entrypoints.https.address=:443"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filePath=/logs/access.log"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/dynamic_conf.yml:/dynamic_conf.yml
      - ./logs/:/logs/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
#      - "traefik.http.routers.traefik.rule=Host(`placeholder.local`)"
      - "traefik.http.routers.traefik.rule=HostRegexp(`placeholder.local`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users="
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
#      - "traefik.http.routers.traefik-secure.rule=Host(`placeholder.local`)"
      - "traefik.http.routers.traefik-secure.rule=HostRegexp(`placeholder.local`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "providers.file.filename=/dynamic_conf.yml"
      - "traefik.http.routers.traefik-secure.middlewares=secHeaders@file,traefik-auth"
networks:
  traefik_web:
    external: true
``` 
and the traefik.yml
``` 
log:
#  level: error
  level: debug
api:
  dashboard: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "./dynamic_conf.yml"
certificatesResolvers:
  http:
    acme:
      email: me@nextcloud
      storage: acme.json
      httpChallenge:
        entryPoint: http
``` 
finally my dynamic_conf.yml
``` 
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
``` 
To be honest - I dont believe its a traefik issue, but I dont find the error.
