### ISSUE TITLE
Cron no longer works since migration to 28.0.2

### ISSUE THREAD

**Issue by Kahiogoo** [nextcloud/docker#2160]
I use nextcloud via docker on Synology and since migrating from version 27.1.5 to 28.0.2, I've been unable to get cron to work (which worked perfectly before).
Here's my configuration file: 

```
services:
  db:
    container_name: mariadb-nextcloud
    restart: unless-stopped
    image: mariadb
    command: --innodb-read-only-compressed=OFF #Maria-DB fix
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ncdb
      MYSQL_USER: 123456
      MYSQL_PASSWORD: 123456
    volumes:
      - /volume1/docker/mariadb-nextcloud:/var/lib/mysql

  redis:
    image: redis
    container_name: redis-nextcloud
    volumes:
      - /volume1/docker/nextcloud/redis:/data:rw
    restart: always

  nextcloud:
    container_name: nextcloud
    restart: unless-stopped
    image: nextcloud
    ports:
      - 5656:80 #Port change
    volumes:
      - /volume1/docker/nextcloud/apps:/var/www/html/custom_apps
      - /volume1/docker/nextcloud/config:/var/www/html/config
      - /volume1/docker/nextcloud/data:/var/www/html/data
      - /volume1/docker/nextcloud/html:/var/www/html
      - /volume1/docker/nextcloud/themes:/var/www/html/themes
    depends_on:
      - db
      - redis

  cron:
   image: nextcloud
   container_name: cron-nextcloud
   restart: always
   volumes:
      - /volume1/docker/nextcloud/apps:/var/www/html/apps
      - /volume1/docker/nextcloud/config:/var/www/html/config
      - /volume1/docker/nextcloud/data:/var/www/html/data
      - /volume1/docker/nextcloud/html:/var/www/html
   entrypoint: /cron.sh
   depends_on:
      - db
      - redis

```

And here is the error that the logs return:

```
Erreur | cron | TypeErrorOCA\Theming\ImageManager::__construct(): Argument #5 ($logger) must be of type OCP\ILogger, OC\Log\PsrLoggerAdapter given, called in /var/www/html/lib/private/Server.php on line 1177Exception thrown: TypeError
```

I'm completely at a loss, thank you very much for your help.

KG
