### ISSUE TITLE
Cron runs for a time then stops (kuma docker with nextcloud docker)

### ISSUE THREAD

**Issue by scoop96** [nextcloud/docker#2215]
At the end i will attach the docker-compose files.
![image](https://github.com/nextcloud/docker/assets/19154725/10bf8235-a010-4305-81cf-01d1b8dc75d3)

I installed and configured nextcloud, after everything is fixed i go to continue setting it up, first the cron job. 
I already had a kuma, so i configured it to connect to my domain.com/cron.php but the output (even when appears as working in kuma is still the same) this is weird, the logs (Even with level swiched to DEBUG)  not showing any info.

![image](https://github.com/nextcloud/docker/assets/19154725/02baff3e-6052-4f4d-8ae7-ced3ef285e08)

OS: ubuntu
Docker with Nginx proxy manager, and cloudflare DNS

## configurations made in nextcloud

`.htcaccess` file added these lines:

```
php_value upload_max_filesize 16G
php_value post_max_size 16G
php_value max_input_time 3600
php_value max_execution_time 3600
php_value memory_limit 2048M
```

`config/config.php` added these lines
```
'overwriteprotocol' => 'https',
'default_phone_region' => 'ES',
'loglevel' => 2,
'maintenance_window_start' => 1,
```

## nextcloud docker compose 

```
version: "3"

services:
  nextcloud_app:
    depends_on:
      - nextcloud_db
    container_name: nextcloud
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD_NEXT
      - MYSQL_DATABASE=$MYSQL_DATABASE_NEXT
      - MYSQL_USER=$MYSQL_USER_NEXT
      - MYSQL_HOST=$MYSQL_HOST_NEXT
      - REDIS_HOST=$REDIS_HOST_NEXT
      - REDIS_HOST_PASSWORD=$REDIS_HOST_PASSWORD_NEXT
    image: nextcloud
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - frontend
      - nextcloud
    links:
      - nextcloud_db
    #ports:
    #  - "8080:80"
    restart: always
    volumes:
      - "$PWD_NAS_DOCKER_VOLUMES/volumes/nextcloud/nextcloud_html:/var/www/html"
      - "$PWD_NAS_DOCKER_VOLUMES/volumes/nextcloud/nextcloud_apps:/var/www/html/custom_apps"
      - "$PWD_NAS_DOCKER_VOLUMES/volumes/nextcloud/nextcloud_config:/var/www/html/config"
      - "$PWD_NAS_DOCKER_VOLUMES/volumes/nextcloud/nextcloud_data:/var/www/html/data"
      - "$PWD_NAS_DOCKER_VOLUMES/volumes/nextcloud/nextcloud_theme:/var/www/html/themes/"



  nextcloud_db:
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD_NEXT
      - MYSQL_PASSWORD=$MYSQL_PASSWORD_NEXT
      - MYSQL_DATABASE=$MYSQL_DATABASE_NEXT
      - MYSQL_USER=$MYSQL_USER_NEXT
    image: "mariadb:10.5"
    restart: always
    labels:
      - io.portainer.accesscontrol.public
    networks:
      - nextcloud
    volumes:
      - "$PWD_NAS_DOCKER_VOLUMES/volumes/nextcloud/nextcloud_mariadb:/var/lib/mysql"


  go-vod:
    image: radialapps/go-vod
    restart: always
    depends_on:
      - nextcloud_app
    environment:
      - NEXTCLOUD_HOST=https://nextcloud.my-domain.com
      # - NEXTCLOUD_ALLOW_INSECURE=1 # (self-signed certs or no HTTPS)
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/dri:/dev/dri # VA-API (omit for NVENC)
    volumes:
      - $PWD_NAS_DOCKER_VOLUMES/volumes/nextcloud/nextcloud_html:/var/www/html:ro
    # runtime: nvidia # (NVENC)


  redis:
    container_name: nc-redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD_NEXT}
    labels:
      - io.portainer.accesscontrol.public
    ports:
      - "6379:6379"
    volumes:
      - "nextcloud_redis_data:/var/lib/redis"
      - "nextcloud_redis_conf:/usr/local/etc/redis/redis.conf"
    environment:
      - REDIS_REPLICATION_MODE=$REDIS_REPLICATION_MODE_NEXT
    networks:
      - nextcloud


volumes:
  nextcloud_redis_data:
    external: true
  nextcloud_redis_conf:
    external: true


networks:
  nextcloud:
  frontend:
    external: true
    
```
    
    
    
   ## kuma config
   
   
   ```
   version: '3.3'

volumes:
  uptimekuma:

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: always
    volumes:
      - uptimekuma:/app/data
    ports:
      - 3001:3001
    networks:
      - frontend

networks:
  frontend:
    external: true
   ```
