### ISSUE TITLE
Image for version 28.0.6 not available on Dockerhub

### ISSUE THREAD

**Issue by shankari** [nextcloud/docker#2229]
I run a standard docker-based install using the `[version]-apache` base images.

I am trying to catch up on upgrades to the nextcloud server now, and have made it up to 28.0.5

- docker-compose.yml

```
  app:
    build: ./app
    ports:
      - 9398:80
    volumes:
      - /[redacted]:/var/www/html
      - /[redacted]:/data
    restart: always
    env_file:
      - db.env
    depends_on:
      - db
```

- app/Dockerfile

```
FROM nextcloud:28.0.5-apache

RUN set -ex; \
    \
    apt-get update; \
...
```

There is no 28.06 image available on dockerhub.

- Searching for 28.0 finds the 28.0.5 image as the latest

<img width="1200" alt="Screen Shot 2024-05-26 at 6 37 50 PM" src="https://github.com/nextcloud/docker/assets/2423263/158add1c-8d6d-4c2b-a174-0d3168e8fda9">

And 28.0.6 is not visible in the list of tags either

<img width="791" alt="Screen Shot 2024-05-26 at 6 38 52 PM" src="https://github.com/nextcloud/docker/assets/2423263/8f723bfd-9b52-452d-9ecc-70a7f678b8f1">

However, the nextcloud admin interface asks me to upgrade to 28.0.6 before I upgrade to 29

<img width="568" alt="Screen Shot 2024-05-26 at 6 40 49 PM" src="https://github.com/nextcloud/docker/assets/2423263/49fec76e-00f2-4e8e-8093-828766d6ad0f">

Can you please publish an image for 28.0.6?
