### ISSUE TITLE
Environment variable PHP_MEMORY_LIMIT seems to get ignored

### ISSUE THREAD

**Issue by japa-fi** [nextcloud/docker#2249]
As stated on https://hub.docker.com/_/nextcloud , one should be able to modify the php memory limit by setting environment variable PHP_MEMORY_LIMIT.

It looks like the value is ignored, or overwritten somewhere. 
Here is my docker compose file for the nextcloud:
```
  app:
    image: nextcloud:29.0.2-apache
    container_name: nextcloud-app
    networks:
     - nextcloud_network
    environment:
     - MYSQL_HOST=nextcloud-mariadb:3306
     - MYSQL_PASSWORD=*REDACTED*
     - MYSQL_DATABASE=maria
     - MYSQL_USER=maria
     - VIRTUAL_HOST=nextcloud.example.com
     - VIRTUAL_PATH=/
     - LETSENCRYPT_HOST=nextcloud.example.com
     - LETSENCRYPT_EMAIL=administrator@example.com
     - LETSENCRYPT_TEST=false
     - PHP_MEMORY_LIMIT=1024M
    depends_on:
     - letsencrypt
     - proxy
     - db
    volumes:
     - nextcloud:/var/www/html
     - ./app/config:/var/www/html/config
     - ./app/custom_apps:/var/www/html/custom_apps
     - ./app/data:/var/www/html/data
     - ./app/themes:/var/www/html/themes
     - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

volumes:
  nextcloud:
  db:
networks:
  nextcloud_network:

````
And when testing, here are the results:
```
root@ubuntu-4gb [bash]:~/nextcloud#>docker compose restart
Container nextcloud-mariadb      Started
Container nextcloud-app          Started
Container nextcloud-letsencrypt  Started
Container nextcloud-proxy        Started
root@ubuntu-4gb [bash]:~/nextcloud#>docker compose exec -u www-data app /bin/bash
www-data@19da9378a531:~/html$ echo $PHP_MEMORY_LIMIT
512M
www-data@19da9378a531:~/html$ echo $LETSENCRYPT_TEST
false
www-data@19da9378a531:~/html$ echo $MYSQL_HOST
nextcloud-mariadb:3306
```
So the variables appear to be picked up, except for the PHP_MEMORY_LIMIT.

Checked my ./app/config/config.php, there was nothing set which would indicate a memory limit.
