### ISSUE TITLE
Add `depends_on` w/ ``condition` + healthcheck example

### ISSUE THREAD

**Issue by joshtrichards** [nextcloud/docker#2250]
Among other things, this may (should) help with some of the timing issues people sometimes report as possible bugs in the Installer.

e.g. (note: do _not_ use this one)

```
  db: 
    [...]
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--innodb_initialized" ]
        #start_period: 1m
        #start_interval: 10s
        #interval: 1m
      timeout: 5s
      retries: 6
[...]
  app:
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
```
