### ISSUE TITLE
The latest version of nextcloud does not automatically connect to the database

### ISSUE THREAD

**Issue by miltuss** [nextcloud/docker#2261]
There is a problem with the latest 29 nextcloud image, it does not automatically recognize the database connection parameters entered in the environment variables and requires manual registration of these parameters !

![image](https://github.com/user-attachments/assets/f1322f3f-ef0a-4954-962a-31851acff7d5)

While the stable image 28 immediately recognizes the MYSQL parameters and automatically connects to the database upon launch.  Should we add another variable to force version 29 to automatically connect to the database on first startup?

Here is my stack. It's the same stack that I used with `nextcloud:stable` and `nextcloud:latest` :

```
version: "3"
services:
  nextcloud-test:
    image: nextcloud:latest
    container_name: nextcloud-test
    restart: always
    depends_on:
      - nextcloud-test_db
      - nextcloud-test_valkey
    ports:
      - 127.0.0.1:10100:80
    volumes:
      - /data/nextcloud-test/config:/var/www/html/config
      - /data/nextcloud-test/data:/var/www/html/data
      - /data/nextcloud-test/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud-test/html:/var/www/html
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=vhdfjhvbhkjdfb
      - MYSQL_HOST=nextcloud-test_db
      - REDIS_HOST=nextcloud-test_valkey
      - NEXTCLOUD_TRUSTED_DOMAINS=domain.com
  nextcloud-test_db:
    image: docker.io/library/mariadb
    container_name: nextcloud-test_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /data/nextcloud-test/nextclouddb:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=vhdfjhvbhkjdfb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud-test_valkey:
    image: docker.io/valkey/valkey:alpine
    container_name: nextcloud-test_valkey
    volumes:
      - /data/nextcloud-test/valkey:/data
networks: {}
```
