### ISSUE TITLE
local external storage not working: You don't have permission to upload or create files here

### ISSUE THREAD

**Issue by ghost** [nextcloud/docker#229]
I am using the [nginx-mariadb-apache docker-compose file](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache) and it works great.

I mounted an extra volume by adding this line to the `app` service
```
  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./media:/media #this line I added
    environment:
      - VIRTUAL_HOST=moesattler.com
      - LETSENCRYPT_HOST=moesattler.com
      - LETSENCRYPT_EMAIL=letsencrypt@moesattler.com
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - proxy-tier
      - default
```

And while nextcloud is able to read it's content, it is is not able to write in it.
I tried to let everyone write by executing this on the host
```
sudo chmod -R 777 media/
```

still no luck. Any idea on how to solve this?
