### ISSUE TITLE
Cannot upload large files when using chunking

### ISSUE THREAD

**Issue by AndreiArdei** [nextcloud/docker#2295]
Hi! I've recently set up nextcloud using docker. The OS that docker runs on is Ubuntu 22.04.4 LTS. I provided the docker compose file below. My docker volume is mounted on a sepparate NFS share, therefore all volumes are mounted on the nfs share. 

```yaml
version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: nextcloud-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    volumes:
      - nextcloud_db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped

  app:
    image: nextcloud:apache
    restart: unless-stopped
    container_name: nextcloud
    volumes:
      - nextcloud_app_data:/var/www/html/data
      - nextcloud_app_opt:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - PHP_UPLOAD_LIMIT=20G
      - APACHE_BODY_LIMIT=0
    depends_on:
      - postgres
      - redis
    ports:
      - 7575:80

volumes:
  nextcloud_db:
  nextcloud_app_data:
  nextcloud_app_opt:
```

The problem I run into is that when I try to upload larger files, this fails with the error: 
`
[PHP] Error: rmdir(/mnt/ncdata/admin/uploads/web-file-upload-15252b578fdf95d6740fb72e4e6c488a-1687753536511): Directory not empty at /var/www/html/lib/private/Files/Storage/Local.php#147 
`

I managed to find the following [link to problem](https://github.com/nextcloud/server/issues/17980) however, there it is specified that the error is in the alpine version, where as I am using the `nextcloud:apache` tag. I was able to have a workaround by turning off chunking with the following command: 
```bash
sudo -u www-data php occ config:app:set files max_chunk_size --value 0
```

This seems to allow larger files now, however it has slowed down upload time considerably. Is there any known fix or work-around / other image that I could use to work around this problem?
