### ISSUE TITLE
SMTP_PASSWORD_FILE auto config failure

### ISSUE THREAD

**Issue by bcrobo** [nextcloud/docker#2304]
Hi,

I'm trying to setup Nextcloud docker image along with `MariaDB` and `redis` containers. I used `MariaDB` version `11.5.2` and `redis`version 7.4.0` and version `30`of Nextcloud. Here is my nextcloud compose file (minus the sensible infos):

```
services:
  nextcloud:
    image: nextcloud:30
    container_name: nextcloud
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - my_reverse_proxy_network
      - my_shared_service_network
    volumes:
      - ${APPDATA_DIR}/nextcloud:/var/www/html
      - ${APPDATA_DIR}/nextcloud/data:/var/www/html/data
      - ${APPDATA_DIR}/nextcloud/config:/var/www/html/config
      - ${APPDATA_DIR}/nextcloud/custom_apps:/var/www/html/custom_apps
    environment:
      TZ: ${TZ}
      # MariaDB
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_password
      MYSQL_DATABASE_FILE: /run/secrets/mariadb_nextcloud_db
      MYSQL_USER_FILE: /run/secrets/mariadb_user
      MYSQL_HOST: my-mariadb-hostname
      REDIS_HOST: my-redis-hostname
      # Already set by default but make it explicit
      REDIS_HOST_PORT: ${REDIS_PORT}
      REDIS_HOST_PASSWORD_FILE: [path to redis password file]
      NEXTCLOUD_ADMIN_USER_FILE: [path to nextcloud admin user file]
      NEXTCLOUD_ADMIN_PASSWORD_FILE: [path to nextcloud admin password file]
      NEXTCLOUD_TRUSTED_DOMAINS: [my-public-domain-name my-local-network
      APACHE_DISABLE_REWRITE_IP: 1
      TRUSTED_PROXIES: [my-proxy-network-address]
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: [my-public-domain-name]
      ## Email configuration
      SMTP_HOST: [my-smtp-server]
      SMTP_SECURE: ssl
      SMTP_PORT: ${SMTP_PORT}
      SMTP_AUTHTYPE: LOGIN
      SMTP_NAME: ${EMAIL}
      # Did not worked at my time because of smtp.config.php get_file_content
      # permission denied...
      SMTP_PASSWORD_FILE: [path to nextcloud smtp password file]
      MAIL_FROM_ADDRESS: ${EMAIL}
      MAIL_DOMAIN: [my-public-domain-name]
    secrets:
       - # list of all my secrets
    labels:
       - # some reverse proxy labels
```

When running the nextcloud container for the first time I get the following error:

```
nextcloud  | Conf remoteip already disabled
nextcloud  | Configuring Redis as session handler
nextcloud  | Initializing nextcloud 30.0.0.14 ...
nextcloud  | New nextcloud instance
nextcloud  | Installing with MySQL database
nextcloud  | => Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/pre-installation
nextcloud  | Starting nextcloud installation
nextcloud  | 
nextcloud  | Warning: file_get_contents([path to my nextcloud smtp password file]): Failed to open stream: Permission denied in /var/www/html/config/smtp.config.php on line 16
nextcloud  | An unhandled exception has been thrown:
nextcloud  | Exception: Config file has leading content, please remove everything before "<?php" in smtp.config.php in /var/www/html/lib/private/Config.php:222
nextcloud  | Stack trace:
nextcloud  | #0 /var/www/html/lib/private/Config.php(40): OC\Config->readData()
nextcloud  | #1 /var/www/html/lib/base.php(89): OC\Config->__construct('/var/www/html/c...')
nextcloud  | #2 /var/www/html/lib/base.php(569): OC::initPaths()
nextcloud  | #3 /var/www/html/lib/base.php(1132): OC::init()
nextcloud  | #4 /var/www/html/console.php(28): require_once('/var/www/html/l...')
nextcloud  | #5 /var/www/html/occ(11): require_once('/var/www/html/c...')
nextcloud  | #6 {main}Retrying install...
```

The leading content error makes me though of a suspicious character error at first glance but this seems more a php related issue. Any hints on why this is happening ? Has anyone already faced that error ?
