### ISSUE TITLE
`OBJECTSTORE_S3_SSL` does not work as documented

### ISSUE THREAD

**Issue by vbrandl** [nextcloud/docker#2308]
The documentation for `OBJECTSTORE_S3_SSL` states that it defaults to `true`:

> (default: true): Whether or not SSL/TLS should be used to communicate with object storage server

I would assume, not setting `OBJECTSTORE_S3_SSL` at all would cause Nextcloud to connect to my S3 bucket via HTTPS.

I use the following `compose.yml` for testing.

```yaml
services:
  nextcloud:
    image: nextcloud
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - SQLITE_DATABASE=/tmp/nc.db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=this-is-not-a-password
      - NEXTCLOUD_TRUSTED_DOMAINS=example.com

      - OBJECTSTORE_S3_BUCKET=${OBJECTSTORE_S3_BUCKET}
      - OBJECTSTORE_S3_HOST=${OBJECTSTORE_S3_HOST}
      - OBJECTSTORE_S3_PORT=${OBJECTSTORE_S3_PORT}
      - OBJECTSTORE_S3_KEY=${OBJECTSTORE_S3_KEY}
      - OBJECTSTORE_S3_SECRET=${OBJECTSTORE_S3_SECRET}
        #- OBJECTSTORE_S3_SSL=true
```

If i start a new instance like this, I get the following `config.php`:

```php
objectstore' =>
  array (
    'class' => '\\OC\\Files\\ObjectStore\\S3',
    'arguments' =>
    array (
      'bucket' => '<snip>',
      'region' => '',
      'hostname' => '<snip>',
      'port' => '443',
      'storageClass' => '',
      'objectPrefix' => 'urn:oid:',
      'autocreate' => false,
      'use_ssl' => false,
      'use_path_style' => false,
      'legacy_auth' => false,
      'key' => '<snip>',
      'secret' => '<snip>',
    ),
  ),
```

`use_ssl` is set to `false` but I would expect it to be `true`.

Now deleting `./data/nextcloud`, uncommenting `- OBJECTSTORE_S3_SSL=true` in `compose.yml`, `use_ssl` in `config.php` will be set to `true`.

So the documentation does not match how the image actually behaves.
