### ISSUE TITLE
413 status code with correct configuration

### ISSUE THREAD

**Issue by DataHearth** [nextcloud/docker#2397]
Hey! For the past month, I've tried to allow bigger uploads on the default nextcloud docker image with Apache (latest 31.0.0) without success. I always get the `413 Entity too large` error from the linux client. I've set every possible bit of configuration found here and there to allow it. 

Here's the docker-compose section relevant to nextcloud:

```yaml
image: datahearth/nextcloud-docker:31
restart: unless-stopped
user: ${UID}:${GID}
dns:
  - 1.1.1.1
  - 1.0.0.1
networks:
  - reverse-proxy
  - database
volumes:
  - ${APPDATA}/nextcloud/app:/var/www/html
  - ${APPDATA}/nextcloud/app-hooks/before-starting:/docker-entrypoint-hooks.d/before-starting
  - ${SHARES}/nextcloud:/data
  - ${SHARES}/logs/nextcloud:/var/log/nextcloud
environment:
  TZ: ${TZ}
  POSTGRES_HOST: postgresql16:5432
  POSTGRES_USER: ${NEXTCLOUD_DB_USER}
  POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWD}
  POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
  SMTP_HOST: xxx
  SMTP_SECURE: xxx
  SMTP_PORT: xxx
  SMTP_NAME: ${SENDGRID_USER}
  SMTP_PASSWORD: ${SENDGRID_PASSWD}
  MAIL_FROM_ADDRESS: xxx
  MAIL_DOMAIN: xxx
  NEXTCLOUD_DATA_DIR: /data
  NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.antoine-langlois.net traefik localhost
  NEXTCLOUD_INIT_HTACCESS: true
  PHP_MEMORY_LIMIT: 1024M
  PHP_UPLOAD_LIMIT: 16G
  APACHE_BODY_LIMIT: 0
labels:
  traefik.enable: true
  traefik.http.routers.nextcloud-unsecured.rule: Host(`nextcloud.${EXTERNAL_DN}`)
  traefik.http.routers.nextcloud-unsecured.entrypoints: web
  traefik.http.routers.nextcloud-unsecured.middlewares: crowdsec-bouncer@file, https-redirect@file
  traefik.http.routers.nextcloud.rule: Host(`nextcloud.${EXTERNAL_DN}`)
  traefik.http.routers.nextcloud.entrypoints: websecure
  traefik.http.routers.nextcloud.tls.certresolver: default
  traefik.http.routers.nextcloud.middlewares: nxt-headers@file, nxt-redirect@file, crowdsec-bouncer@file
```

Here's the outputs for my container configuration:
```bash
❯ docker compose exec -it nextcloud php -i | grep -E "upload_max_filesize|post_max_size|memory_limit"
memory_limit => 1024M => 1024M
post_max_size => 16G => 16G
upload_max_filesize => 16G => 16G

❯ docker compose exec -it nextcloud grep -r "LimitRequestBody" /etc/apache2/
/etc/apache2/conf-available/apache-limits.conf:LimitRequestBody ${APACHE_BODY_LIMIT}
```

I haven't modified the root `.htaccess` nor the one found in `config/.htaccess`. The `php.ini` is untouched as well. Not specific configuration lines where specified in the `config.php`.

Can anyone help me with this ? Thanks !
