### ISSUE TITLE
/entrypoint.sh: 137: cannot create /var/www/html/nextcloud-init-sync.lock: Permission denied

### ISSUE THREAD

**Issue by BarBaar44** [nextcloud/docker#2412]
Nextcloud Dockter fails to start

Log output:
`Conf remoteip already disabled
/entrypoint.sh: 137: cannot create /var/www/html/nextcloud-init-sync.lock: Permission denied
Conf remoteip already disabled
/entrypoint.sh: 137: cannot create /var/www/html/nextcloud-init-sync.lock: Permission denied`

Webinterface displays a HTTP 404

Issue occured on 2 instances since last upgrade (last Friday, 14 march). Both instances run the same config (expect for host specific settings (DNS/filelocation.etc) Did no config changes before the upgrade that may cause this behaviour.

The containers run on Fedora 41:
`[root@mail ~]# rpm -aq | grep docker
python3-docker-7.1.0-3.fc41.noarch
python3-docker+ssh-7.1.0-3.fc41.noarch
python3-docker-pycreds-0.4.0-21.fc41.noarch
python3-dockerpty-0.4.1-33.fc41.noarch
docker-cli-27.3.1-2.fc41.x86_64
docker-buildx-0.18.0-1.fc41.x86_64
docker-compose-2.30.3-1.fc41.x86_64
docker-compose-switch-1.0.5-1.fc41.x86_64
[root@mail ~]# rpm -aq | grep containerd
containerd-1.7.26-1.fc41.x86_64
`

Docker config (in Portainer):
```
`version: '3.9'

volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  frontend:
    name: frontend
    # add this if the network is already existing!
    # external: true
  backend:

services:
  nextcloud-app:
    image: nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-unsecure.entrypoints=web"
      - "traefik.http.routers.nextcloud-unsecure.rule=Host(`XXXXXXXXX`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=websecure"
      - "traefik.http.routers.nextcloud-unsecure.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`XXXXXXX`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=production"
      - "traefik.frontend.nextcloud.headers.STSSeconds=15552000"
      - "traefik.frontend.nextcloud.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.nextcloud.headers.STSPreload=true"
      - "traefik.http.middlewares.nextcloud.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.nextcloud.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nextcloud.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloud.headers.referrerPolicy=no-referrer"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud-caldav@docker"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
    restart: always
    volumes:
      - /srv/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=XXXXX
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_DOMAIN_NAME=XXXXXXX
      - NEXTCLOUD_MEMORY_LIMIT=1024M
      - TRUSTED_PROXIES=XXXX
      - APACHE_DISABLE_REWRITE_IP=1
      - OVERWRITEHOST=XXXXXX
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_INIT_HTACCESS=true
    networks:
      - frontend
      - backend

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXX
      - MYSQL_PASSWORD=XXXXXXX
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend`
```

Filesystem overview:
```
[root@mail nextcloud]# ls -alh
total 1.2M
drwxrwxrwx. 16   33 tape 4.0K Mar 14 20:17 .
drwxr-xr-x. 20 root root  284 Jul 17  2024 ..
drwxr-xr-x. 42   33 tape 4.0K Feb 26 11:25 3rdparty
drwxr-xr-x. 55   33 tape 4.0K Feb 26 11:25 apps
-rw-r--r--.  1   33 tape  26K Feb 26 11:25 AUTHORS
-rw-r--r--.  1   33 tape 2.4K Feb 26 11:25 composer.json
-rw-r--r--.  1   33 tape 3.4K Feb 26 11:25 composer.lock
drwxr-xr-x.  2   33 root 4.0K Dec  5 10:42 config
-rw-r--r--.  1   33 tape 3.8K Feb 26 11:25 console.php
-rw-r--r--.  1   33 tape  34K Feb 26 11:25 COPYING
drwxr-xr-x. 24   33 tape 4.0K Feb 26 11:25 core
-rw-r--r--.  1   33 tape 7.9K Feb 26 11:25 cron.php
drwxr-xr-x. 23   33 root 4.0K Mar  3 14:33 custom_apps
drwxrwx---. 12   33 root 4.0K Mar 13 03:40 data
drwxr-xr-x.  2   33 tape  20K Feb 26 11:25 dist
-rw-r--r--.  1   33 tape 5.7K Feb 26 11:25 .htaccess
-rw-r--r--.  1   33 tape  331 Feb 26 11:25 index.html
-rw-r--r--.  1   33 tape 3.5K Feb 26 11:25 index.php
drwxr-xr-x.  7   33 tape  141 Feb 26 11:25 lib
drwxr-xr-x.  2   33 tape 4.0K Feb 26 11:25 LICENSES
-rw-r--r--.  1   33 tape    0 Mar 14 20:17 nextcloud-init-sync.lock
-rwxr-xr-x.  1   33 tape  308 Feb 26 11:25 occ
drwxr-xr-x.  2   33 tape   55 Feb 26 11:25 ocs
drwxr-xr-x.  2   33 tape   23 Feb 26 11:25 ocs-provider
-rw-r--r--.  1   33 tape 7.2K Feb 26 11:25 package.json
-rw-r--r--.  1   33 tape 984K Feb 26 11:25 package-lock.json
-rw-r--r--.  1   33 tape 2.8K Feb 26 11:25 public.php
-rw-r--r--.  1   33 tape 4.5K Feb 26 11:25 remote.php
drwxr-xr-x.  4   33 tape  161 Feb 26 11:25 resources
drwxr-xr-x.  2   33 tape   18 Feb 26 11:25 .reuse
-rw-r--r--.  1   33 tape   26 Feb 26 11:25 robots.txt
-rw-r--r--.  1   33 tape 1.4K Feb 26 11:25 status.php
drwxr-xr-x.  3   33 root   35 Mar 19  2022 themes
-rw-r--r--.  1   33 tape  271 Feb 26 11:25 .user.ini
-rw-r--r--.  1   33 tape  384 Feb 26 11:25 version.php
```
Done so far but did not help:
- Removed the file nextcloud-init-sync.lock. Please note those file was initially owned by root. 
- Restared everything
