### ISSUE TITLE
Auto logged as admin after running `docker-compose up`

### ISSUE THREAD

**Issue by hadrien-toma** [nextcloud/docker#242]
### Steps to reproduce
I am running this compose file:
```
version: '3.4'

services:
  nextcloud:
    container_name: nextcloud
    depends_on:
      - nextcloud-db
    environment:
      - MYSQL_DATABASE=nextcloud-mysql-database
      - MYSQL_HOST=nextcloud-db
      - MYSQL_PASSWORD=nextcloud-db-password
      - MYSQL_USER=admin
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud-app-password
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TABLE_PREFIX=
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-app:/var/www/html/data
      - nextcloud-app-html:/var/www/html
      - nextcloud-app-config:/var/www/html/config
      - nextcloud-app-apps:/var/www/html/apps

volumes:
  nextcloud-1-db:
  nextcloud-1-app:
  nextcloud-1-app-html:
  nextcloud-1-app-config:
  nextcloud-1-app-apps:
```

### Environment:
* Docker version 18.01.0-ce, build 03596f5
* docker-compose version 1.18.0, build 8dd22a9
* 16.04.1-Ubuntu
