### ISSUE TITLE
Pretty URLs doesnt work - url always contains index.php

### ISSUE THREAD

**Issue by hexxone** [nextcloud/docker#2430]
I have a problem with my nextcloud docker installation.

It seems lile the `config.php` part which relates to the "[Pretty URLs](https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#pretty-urls)" does not work properly with this image.

I have the `user_saml` plugin enabled and it seems like randomly every several weeks, it either expect the ACS URL to be `index.php/apps/` or `apps/` randomly, which then leads to the problem that NO ONE can login until an admin changes it in the external Auth settings:

```
Bad Request
ACS URL of 
https://cloud.test.com/index.php/apps/user_saml/saml/acs 
doesn't match Provider ACS URL of 
https://cloud.test.com/apps/user_saml/saml/acs.
```

My config.php is literally this:

```
'overwrite.cli.url' => 'https://cloud.test.com/',
'htaccess.RewriteBase' => '/',
```

but it seems like thats not getting regarded.

Here is my docker compose:

```
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      # PUID: ${RUN_UID}
      # PGID: ${RUN_GID}
      TZ: ${RUN_TZ}
      MYSQL_HOST: nc_mariadb
      # MYSQL_* etc loaded from nc-db.env
      REDIS_HOST: nc_redis
      REDIS_HOST_PASSWORD: ${REDIS_PASS}
      NEXTCLOUD_TRUSTED_DOMAIN: "cloud.${HOST}"
      ### @TODO Add local network as a trusted proxy
      # TRUSTED_PROXIES: 192.168.90.0/24
    labels:
      traefik.enable: true
      # middleware helper 1
      traefik.http.middlewares.nc-rep.redirectregex.regex: https://(.*)/.well-known/(card|cal)dav
      traefik.http.middlewares.nc-rep.redirectregex.replacement: https://$$1/remote.php/dav/
      traefik.http.middlewares.nc-rep.redirectregex.permanent: true
      # middleware helper 2
      traefik.http.middlewares.nc-rep2.redirectregex.regex: https://(.*)/.well-known/webfinger
      traefik.http.middlewares.nc-rep2.redirectregex.replacement: https://$$1/index.php/.well-known/webfinger
      traefik.http.middlewares.nc-rep2.redirectregex.permanent: true
      # middleware helper 3
      traefik.http.middlewares.nc-rep3.redirectregex.regex: https://(.*)/.well-known/nodeinfo
      traefik.http.middlewares.nc-rep3.redirectregex.replacement: https://$$1/index.php/.well-known/nodeinfo
      traefik.http.middlewares.nc-rep3.redirectregex.permanent: true
      # middleware helper 4
      traefik.http.middlewares.nc-header.headers.referrerPolicy: no-referrer
      traefik.http.middlewares.nc-header.headers.stsSeconds: 31536000
      traefik.http.middlewares.nc-header.headers.forceSTSHeader: true
      traefik.http.middlewares.nc-header.headers.stsPreload: true
      traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.nc-header.headers.browserXssFilter: true
      traefik.http.middlewares.nc-header.headers.customFrameOptionsValue: allow-from ${HOST} *.${HOST} *;
      traefik.http.middlewares.nc-header.headers.accessControlAllowOriginList: "*"
      traefik.http.middlewares.nc-header.headers.accessControlAllowMethods: "GET, OPTIONS, PUT, POST, DELETE"
      traefik.http.middlewares.nc-header.headers.accessControlAllowHeaders: "Content-Type, Authorization, X-Requested-With"
      traefik.http.middlewares.nc-header.headers.accessControlAllowCredentials: true
      traefik.http.middlewares.nc-header.headers.accessControlMaxAge: 100
      # traefik.http.middlewares.nc-header.headers.customFrameOptionsValue: sameorigin
      # traefik.http.middlewares.nc-header.headers.contentsecuritypolicy: default-src 'self' https://${HOST} https://*.${HOST};
      # traefik.http.middlewares.nc-header.headers.customResponseHeaders.Strict-Transport-Security: 15552000
      # HTTP router
      traefik.http.routers.nextcloud-redirect.entrypoints: web
      traefik.http.routers.nextcloud-redirect.rule: Host(`cloud.${HOST}`)
      traefik.http.routers.nextcloud-redirect.middlewares: nc-header,httpsredirect@docker
      # HTTPS -> Entry router
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.rule: Host(`cloud.${HOST}`)
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.tls.certresolver: cfresolver
      traefik.http.routers.nextcloud.tls.domains[0].main: "${HOST}"
      traefik.http.routers.nextcloud.tls.domains[0].sans: "*.${HOST}"
      traefik.http.routers.nextcloud.middlewares: nc-rep,nc-rep2,nc-rep3,nc-header,error-pages@docker # ,limit@docker (nexcloud can do its own)
      traefik.http.routers.nextcloud.service: nextcloud
      # Entry
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      traefik.http.services.nextcloud.loadbalancer.passHostHeader: true
    env_file:
      - nc_db.env
    depends_on:
      - traefik
      - nc_mariadb
      - nc_redis
      - nc_onlyoffice_server
    networks:
      db_net:
        priority: 100
      web:
    volumes:
      #  - ./nextcloud/data/:/usr/src/nextcloud/
      - ./nextcloud/data/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/data/config:/var/www/html/config
      - ./nextcloud/data/data:/var/www/html/data
```
