### ISSUE TITLE
Can't have SSL active behind companion

### ISSUE THREAD

**Issue by GarethFox** [nextcloud/docker#319]
Hi,

I deployed a minimal test docker-compose stack in order to add it when successfull to my current (under dev) prod stack using following `docker-compose.yml` file, but I still have a http connection once stack is init and I connect the url:
```
version: '2'

services:
# PUBLIC web proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/nginx/html:/usr/share/nginx/html
      - /docker/letsencrypt/nginx:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=example.com
    networks:
      public:

# PUBLIC cert manager
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - /docker/letsencrypt/nginx:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      public:

# PRIVATE cloud-db
  cloud-db:
    container_name: cloud-db
    image: mariadb:latest
    restart: unless-stopped
    volumes:
       - /docker/cloud/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cloud_db
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=cloud_user
      - MYSQL_PASSWORD=654321
    networks:
      private:
        ipv4_address: 172.200.0.14

  cloud-app:
    container_name: cloud-app
    image: nextcloud:apache
    restart: unless-stopped
    depends_on:
      - cloud-db
    links:
      - cloud-db
    expose:
      - '80'
    volumes:
      - /docker/cloud/app:/var/www/html
      - /docker/cloud/app/config:/var/www/html/config
      - /docker/cloud/app/apps:/var/www/html/apps
    environment:
      - VIRTUAL_HOST=cloud.example.com
      - LETSENCRYPT_HOST=example.com,cloud.example.com
      - LETSENCRYPT_EMAIL=user@mail.com
      - NEXTCLOUD_ADMIN_USER=cloudadmin
      - NEXTCLOUD_ADMIN_PASSWORD=111111
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TABLE_PREFIX=
      - MYSQL_DATABASE=cloud_db
      - MYSQL_USER=cloud_user
      - MYSQL_PASSWORD=654321
      - MYSQL_HOST=cloud-db
    networks:
      public:
      private:
        ipv4_address: 172.200.0.15

# IPAM = IP Addr. Mngt.
networks:
  private:
    ipam:
      config:
        - subnet: 172.200.0.0/16
  public:
```
When I run `docker exec nginx-letsencrypt /app/cert_status` I get an empty:
`##### Certificate status #####`
I was expecting to have an active cert output as I use to so far.

Any idea why I can't have LE active encryption on this case ??
Thx
