### ISSUE TITLE
Port binding issue with nginx reverse proxy

### ISSUE THREAD

**Issue by weeger** [nextcloud/docker#325]
Hi there,

As I posted an issue on the nginx reverse proxy repository here https://github.com/jwilder/nginx-proxy/issues/1127, I post the specific part for NextCloud here.

I am not able to use NextCloud with a binded port when I use it with https://github.com/jwilder/nginx-proxy. It works when ports biding is like `<customPort>:<customPort>`, but never when ports is on `<customPort>:<defaultAppPort>`.

Working without proxy server at `http://dockerIP:8888`

```yml
version: '2.0'

services:
  nextcloud:
    depends_on:
    - cloud_mariadb
    environment:
      MYSQL_DATABASE: cloud
      MYSQL_HOST: cloud_mariadb
      MYSQL_PASSWORD: thisIsAReallyNotSecurePassword!
      MYSQL_USER: root
    image: nextcloud:12.0.7-apache
    ports:
    - 8888:80/tcp
    restart: always

  cloud_mariadb:
      environment:
        MYSQL_DATABASE: cloud
        MYSQL_PASSWORD: thisIsAReallyNotSecurePassword!
        MYSQL_ROOT_PASSWORD: thisIsAReallyNotSecurePassword!
        MYSQL_USER: root
      image: mariadb:10.3.6
      ports:
      - 7011:3306/tcp
      restart: always
```

Do not working with proxy server using default 80 apache port :

```yml
version: '2.0'

services:
  nextcloud:
    depends_on:
    - cloud_mariadb
    environment:
      MYSQL_DATABASE: cloud
      MYSQL_HOST: cloud_mariadb
      MYSQL_PASSWORD: thisIsAReallyNotSecurePassword!
      MYSQL_USER: root
      VIRTUAL_HOST: cloud.wex
      VIRTUAL_PORT: '8888'
    expose:
    - '8888'
    image: nextcloud:12.0.7-apache
    networks:
      reverseproxy_wex_net: null
    ports:
    - 8888:80/tcp
    restart: always

  cloud_mariadb:
      environment:
        MYSQL_DATABASE: cloud
        MYSQL_PASSWORD: thisIsAReallyNotSecurePassword!
        MYSQL_ROOT_PASSWORD: thisIsAReallyNotSecurePassword!
        MYSQL_USER: root
      image: mariadb:10.3.6
      networks:
        reverseproxy_wex_net: null
      ports:
      - 7011:3306/tcp
      restart: always

networks:
  reverseproxy_wex_net:
    external: true
```

Working again on `http://cloud.wex` after changing manually apache port into container to 8888 and changing ports configuration to :

```yml
services:
  nextcloud:
    # ....
    ports:
    - 8888:8888/tcp
```
