### ISSUE TITLE
docker-compose with nextcloud image and Dockerfile for imap doesn´t work

### ISSUE THREAD

**Issue by controlcde** [nextcloud/docker#332]
I´m trying to get nextcloud working with imap authentication. My `docker-compose.yml` looks like:

```
host.domain:
    build:
      context: /srv/docker
    container_name: host.domain
    expose:
      - 80
    links:
      - db
    depends_on:
      - nginx-letsencrypt
      - db
    volumes:
      - /srv/docker/data:/srv
      - /srv/docker/config:/var/www/html/config
      - /srv/docker/custom_apps:/var/www/html/custom_apps
      - /srv/docker/themes:/var/www/html/themes
    environment:
      - VIRTUAL_HOST=host.domain
      - LETSENCRYPT_HOST=host.domain
      - LETSENCRYPT_EMAIL=hostmaster@domain
      - NEXTCLOUD_DATA_DIR=/srv
    restart: always
```

and the `Dockerfile`

```
FROM nextcloud

RUN apt-get update \
    && apt-get install -y libc-client-dev libkrb5-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap
```

The problem is:
After starting docker-compose the only line `Building host.domain` is shown and nothing happens. If I start docker-compose with the image option the container will be generate and I could execute the commands from the Dockerfile inside the container without any problem.

docker-compose with verbose option shows

```
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- (u'docker_host.domain')
compose.service.build: Building host.domain
compose.cli.verbose_proxy.proxy_callable: docker build <- (pull=False, stream=True, nocache=False, tag=u'docker_host.domain', buildargs=None, rm=True, forcerm=False, path='/srv/docker', dockerfile=None)
```
_docker host: Debian stretch with docker-compose version 1.8.0_
