### ISSUE TITLE
Upload is very slow

### ISSUE THREAD

**Issue by chris-aeviator** [nextcloud/docker#334]
I've freshly started the Docker Image on a 2 (v)core, 4 GB Digital Ocean Droplet, using the provided Docker Compose file with `mariadb` enabled and everything so far seems fine. However, Uploads via the Web UI will run no faster than some kb/s. I'm happy to provide more info but my setup is fairly default.

**Comment by J0WI** [comment]
What kind of network/storage driver are you using (can be extracted from `docker inspect`)?

**Comment by chris-aeviator** [comment]
@J0WI thanks for your reply - I'm running all my traffic through a nginx-(reverse)-proxy network via docker (based on ``docker-compose-nginx-companion``). Other Services function well over the same network. 
Attached you'll find my config & log about the network driver:


**docker-compose.yml**
```yaml
version: '2'

volumes:
  nextcloud:
  nextcloud_db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=notMyRootPassword
      - MYSQL_PASSWORD=somethingSecret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    expose:
      - 80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      VIRTUAL_HOST: something.mydomain.io
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: something.mydomain.io
      LETSENCRYPT_EMAIL: me@mydomain.io
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
```
- Volume Driver is **local**

**docker inspect**
```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "someLongID,
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/something",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nginx-proxy": {
                    "IPAMConfig": null,
```
                    "Links": [
                        "something_db_1:something_db_1",
                        "something_db_1:db",
                        "something_db_1:db_1"
                    ],
                    "Aliases": [
                        "app",
                        "b957be9d8676"
                    ],
                    "NetworkID": "df4b15e54e13d220b6d20a0a16220be57e89b68c7d98cde095bb0fa7c1a91450",
                    "EndpointID": "0794b715436a5d907f6e327f20b0cbfdc1f7ee15b9c49cd124048ce5772e8c30",
                    "Gateway": "172.20.0.1",
                    "IPAddress": "172.20.0.21",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:[xx]:[xx]:[xx]:00:15"
                }
            }
        }
    }
```
