### ISSUE TITLE
Can't set up Nextcloud / SQLSTATE[HY000] [1045] Access denied 

### ISSUE THREAD

**Issue by IsidoreIsou** [nextcloud/docker#374]
Hello,

I'm new to docker, hope you can help me.
I am on a mac server, here is my docker-compose.yml : 

```
version: '3'

services:

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ~/.Mariadb_dk:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
#    env_file:
#      - db.env

  app:
    image: nextcloud:apache
    ports:
      - 6067:80
    restart: always
    volumes:
      - ~/.Nextcloud_dk:/var/www/html
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
#    env_file:
#      - db.env
    depends_on:
      - db
#    networks:
#      - proxy-tier
#      - default
```

Then when I try to set up nextcloud and create an admin user I got this :

> Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'mms.edifice-edition.com' (using password: YES) 

About my database :

```
MariaDB [(none)]> SELECT host, user FROM mysql.user;
+-----------+------+
| host      | user |
+-----------+------+
| %         | root |
| localhost | root |
+-----------+------+
```

Any help would be great, I'm out of idea.

Thanks !
