### ISSUE TITLE
Success !  But do I have a public www folder ?

### ISSUE THREAD

**Issue by IsidoreIsou** [nextcloud/docker#376]
Hello, (I am learning this)

I succeed running Nextcloud in docker on my mac. I can can access to my domain in https. I am happy.
BUT,
Do I have a www folder somewhere ? How can I create a "Website" like in macos server, put php files in a folder, assign a port, and access it like this : 
> https://mydomain.com:port

I am not sure to understand if I can do that or not with my set up.
Thanks for your help !

my docker-compose.yml :

```
version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ~/.Mariadb_dk:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: ***
  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - ~/.Nextcloud_dk:/var/www/html
    environment:
      - VIRTUAL_HOST=mydomain.com
      - LETSENCRYPT_HOST=mydomain.com
      - LETSENCRYPT_EMAIL=myemail
      - MYSQL_HOST=db
    depends_on:
      - db
    networks:
      - proxy-tier
      - default

  proxy:
    build: ~/proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
```
