### ISSUE TITLE
How to start a new Nextcloud container with existing named volumes?

### ISSUE THREAD

**Issue by kunxia** [nextcloud/docker#383]
I've created a Nextcloud container with the following docker-compose.yml, it creates two data volmes named docker_nextcloud and docker_db. I'm wondering how to start another container using these 2 named volumes? So I'm exepcting the original data is persisted in this way.
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXX
      - MYSQL_PASSWORD=XXXXXX
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:  
    image: nextcloud
    container_name: nextcloud-app
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
```

**Comment by mr-bolle** [comment]
You can mount this volumes into your Host.
I use often a Environment variables [.env](https://docs.docker.com/compose/environment-variables/).

**.env**
```
NEXTCLOUD_DATA=/mnt/usb1/docker_volumes/nextcloud_data
```
**docker-compose.yml**
```
    volumes:
      - $NEXTCLOUD_DATA:/var/www/html
```

**Comment by SnowMB** [comment]
You can refer to existing volumes as external:

```yaml
volumes:
  - data:
    external:
      name: nextcloud_data
  - db:
    external:
      name: nextcloud_db

```

See https://docs.docker.com/compose/compose-file/#external
