### ISSUE TITLE
Installation Wizard not accepting username and password

### ISSUE THREAD

**Issue by umardraz** [nextcloud/docker#420]
Hello

The Installation wizard is not picking mysql information Here is the information what I had provided through environment variables.

```
-e MYSQL_HOST=10.0.201.120 \
-e MYSQL_DATABASE=ncdb \
-e MYSQL_USER=ncloud \
-e MYSQL_PASSWORD=ncloud12345 \

```
On the first run the installation appears and asked for crate an admin account.

But when I clicked on Finish setup button then an error appears.

Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user ‘oc_admin15’@’%’ to database ‘client1’

```
‘dbtype’ =>; ‘mysql’,
‘version’ =>; ‘13.0.5.2’,
‘dbname’ =>; ‘ncdb’,
‘dbhost’ =>; ‘10.0.201.120’,
‘dbport’ =>; ‘’,
‘dbtableprefix’ =>; ‘’,
‘mysql.utf8mb4’ =>; true,
‘dbuser’ =>; ‘oc_admin15’,
‘dbpassword’ =>; ‘Q9hwc3uqbzqU2G9E+TkJt6XWGqmGjE’,
```

Don't know why it is not accepting username and password, the other options are ok, like dbname, dbhost.

Would you please any body help me.

**Comment by r2evans** [comment]
I'm also seeing this behavior when trying to connect to a postgres instance. 

```
root@D2SP3:/home/r2/docker# docker-compose up nextcloud
docker_postgres_1_4b526486f7ce is up-to-date
Creating docker_nextcloud_1_21d381008fc1 ... done
Attaching to docker_nextcloud_1_a56357f7c235
nextcloud_1_a56357f7c235 | Initializing nextcloud 14.0.4.2 ...
nextcloud_1_a56357f7c235 | Initializing finished
nextcloud_1_a56357f7c235 | New nextcloud instance
nextcloud_1_a56357f7c235 | Installing with PostgreSQL database
nextcloud_1_a56357f7c235 | starting nextcloud installation
nextcloud_1_a56357f7c235 | Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL:  permission denied for database "nc"
nextcloud_1_a56357f7c235 | DETAIL:  User does not have CONNECT privilege.
nextcloud_1_a56357f7c235 |  -> 
nextcloud_1_a56357f7c235 | retrying install...
nextcloud_1_a56357f7c235 | Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL:  permission denied for database "nc"
nextcloud_1_a56357f7c235 | DETAIL:  User does not have CONNECT privilege.
nextcloud_1_a56357f7c235 |  -> 
nextcloud_1_a56357f7c235 | retrying install...
```

Relevant portions of the `docker-compose.yml` file:

```yaml
version: '3.7'

services:
  traefik:
    image: traefik:1.7
    command: --api --docker
    ports:
    - "80:80"
    - "8080:8080" # webui
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:10
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=xxx
    - POSTGRES_DB=nc
    - POSTGRES_USER=nc_user
    volumes:
    - /home/r2/docker/pg:/var/lib/postgresql/data:Z
  nextcloud:
    image: nextcloud:14-apache
    depends_on:
    - postgres
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=nc
    - POSTGRES_USER=nc_user
    - POSTGRES_PASSWORD=xxx
    - NEXTCLOUD_ADMIN_USER=ncadmin
    - NEXTCLOUD_ADMIN_PASSWORD=xxx
    volumes:
    - /home/r2/docker/nc/config:/var/www/html/config:Z
    labels:
    - "traefik.frontend.rule=PathPrefixStrip:/cloud"
```

It is clearing `dbport` (nowhere does nextcloud/docker allow me to configure this in `envvars`?) and setting `dbuser` and `dbpassword` to `oc_*`, not at all what I'm configuring. The resulting `config/config.php` file after  this "hiccup":

```php
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'passwordsalt' => '9QepuB7yen9mfq7fI68YtEH/Xxnfh1',
  'secret' => 'EUUKboZz+TazUhAoqo8qViG9qHbAdSQqd3B1JN1n87Cxqd9L',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'pgsql',
  'version' => '14.0.4.2',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nc',
  'dbhost' => 'postgres',
  'dbport' => '',
  'dbtableprefix' => '',
  'dbuser' => 'oc_ncadmin60',
  'dbpassword' => '77bzrlaciblcpn32msqh579vogykit',
);
```

**Comment by r2evans** [comment]
On a whim (suggested by https://github.com/nextcloud/server/issues/1793), I also checked with `postgres:9.5`. Still fails.

Further: I can connect to the database with `nc_user` and my password, and I can create tables, so it is not a first-pass permissions problem. It appears that nextcloud/server is sabotaging the connection. (Perhaps this does not belong under nextcloud/docker.)

**Comment by r2evans** [comment]
@umardraz I think I found the culprit: https://github.com/nextcloud/docker/issues/345#issuecomment-398037012

This worked for me (on postgres):

1. `drop database nc` (the database I told nextcloud to use is `nc`, and since no tables had been created, this was instantaneous and no loss of anything).
2. Make sure the user/pass I set in `POSTGRES_*` had `CREATE DATABASE` and `CREATE ROLE` permissions in the database as a whole. I highly recommend this not be the final configuration (nextcloud should not be able to create or even see other databases!).

Since I'm on an easy test system, I didn't mind the security lapse. I have not (yet) tested with a production database, though my next step is to clone the real database and attempt an upgrade using this image. Wish me luck.

For the record, I updated my `docker-compose.yml`:

```yaml
version: '3.7'

services:
  traefik:
    image: traefik:1.7
    command: --api --docker
    ports:
    - "80:80"
    - "8080:8080" # webui
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:9.5
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=xxx
    - POSTGRES_DB=nc
    - POSTGRES_USER=nc_user
    volumes:
    - /home/r2/docker/pg:/var/lib/postgresql/data:Z
  nextcloud:
    image: nextcloud:14-apache
    depends_on:
    - postgres
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=nc
    - POSTGRES_USER=nc_user
    - POSTGRES_PASSWORD=xxx
    - NEXTCLOUD_ADMIN_USER=ncadmin
    - NEXTCLOUD_ADMIN_PASSWORD=xxx
    - NEXTCLOUD_DATA_DIR=/var/lib/nextclouddata
    volumes:
    - /home/r2/docker/nc/config:/var/www/html/config:Z
    - /home/r2/docker/nc/data:/var/lib/nextclouddata:Z
    labels:
    - "traefik.frontend.rule=PathPrefixStrip:/cloud"
```

and `config/config.php`:

```php
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'passwordsalt' => 'k9DL+pteWJB6AaSpHiCskeb0+8CUds',
  'secret' => 'YvBvUcScMOS+3pzy9m9yzs64mPb4QYrJgwXLyWQThEtMTh/F',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/lib/nextclouddata',
  'dbtype' => 'pgsql',
  'version' => '14.0.4.2',
  'overwrite.cli.url' => 'http://localhost/cloud',
  'dbname' => 'nc',
  'dbhost' => 'postgres',
  'dbport' => '',
  'dbtableprefix' => '',
  'dbuser' => 'oc_ncadmin7',
  'dbpassword' => 'NC-created-xxx',
  'installed' => true,
  'instanceid' => 'ocx15d26bvrw',
  'overwritewebroot' => '/cloud',
);
```

Notice that NC still over-rode my `dbuser` and `dbpassword`. After pasting here, I did change them back to what I had set in the `docker-compose.yml` file and they stuck this time. (I think a bit of work needs to go into streamlining this docker image ... having to juggle db-superusers and databases like that is worrisome.)
