### ISSUE TITLE
External Storage - Local Storage Disappears after Pending 

### ISSUE THREAD

**Issue by K-MTG** [nextcloud/docker#426]
I have Nextcloud running on Docker on my Mac with this [docker-compose](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache). I made a small tweak to it so I can access my external storage (external hard drive):
```
  app:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      **- /Volumes/LaCie:/Volume**
    environment:
      - VIRTUAL_HOST=email@emaple.com
      - LETSENCRYPT_HOST=email@emaple.com
      - LETSENCRYPT_EMAIL=email@emaple.com
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default
```

I was able to successfully enable local storage:
<img width="1090" alt="screen shot 2018-08-17 at 8 43 16 pm" src="https://user-images.githubusercontent.com/19272528/44295472-44d16800-a25e-11e8-9587-bf0897bd6f5b.png">

Immediately after setting up local storage, I am able to access all of my files and the data size states pending. However, after sometime only the files I accessed remain. Hence, if I have a TV show folder and click on the show SpongeBob and select season 1. All episodes from season 1 will load and the data size will update. However, if I don't select and open the other seasons (i.e season 2,3,4) those folders will disappear from nextcloud. 

I don't think this is a permission issue as Nextcloud is able to load everything during the pending state...however after the pending state...only the folders I select (during the pending state) remain. 

Also, if I create a new folder with the same name name (i.e Season 2). Nextcloud will state Season 2 already exist and the folder will show up. 

Appreciate any assistance.

Thanks

**Comment by K-MTG** [comment]
I think this might be an issue with Cron not scanning the files. Does anyone know how to resolve? Thanks

**Comment by boulgom** [comment]
I had the same issue and it was because i didn't map the directory on nextcloud_cron container
```
  nextcloud:
    image: nextcloud:fpm-alpine
    depends_on:
      - mariadb_nextcloud
    volumes:
      - nextcloud:/var/www/html
      - /docker/data:/docker/data
...
  nextcloud_cron:
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud:/var/www/html
      - /docker/data:/docker/data **<-- missing entry
    entrypoint: /cron.sh
...
```
