### ISSUE TITLE
 Using stack.yml to deploy this error

### ISSUE THREAD

**Issue by SQGE** [nextcloud/docker#456]
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL: permission denied for database "nextcloud" DETAIL: User does not have CONNECT privilege.

**Comment by SnowMB** [comment]
Hey please have a look at #345. 

It boils down to the following: If you use postgres, nextcloud has to create the database with the installation routine and can not use the automatically created one from the postgres container:

To solve this let the container create a database with a different name:

```yaml
...
services:
  image: postgres
  ...
  environment: 
    - POSTGRES_DATABASE=idontcare
  ...

```
