### ISSUE TITLE
SSL does not work when not on the standard port

### ISSUE THREAD

**Issue by jeyemwey** [nextcloud/docker#524]
I'm trying to apply this example: `.examples/docker-compose/with-nginx-proxy/mariadb/fpm/`

Since there is another web service on the server, I modified the port mapping in the compose file and my domain:

```yml
(...)
web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=[my custom domain]
      - LETSENCRYPT_HOST=[my custom domain]
      - LETSENCRYPT_EMAIL=[my email]
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 8081:80
      - 8443:443
      - 8081:80
      - 8443:443
    labels: (...)
```

Connecting via `http://[my custom domain]:8081` works fine, but HTTPS requests for `https://[my custom domain]:8443` return an nginx 500 error. This is in the logs:

```
proxy_1                  | nginx.1    | <Domain> <IP> - - [25/Oct/2018:14:31:52 +0000] "GET /apps/files/?dir=/&fileid=7 HTTP/2.0" 500 193 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
```

Does anyone know help about this?
