### ISSUE TITLE
Can volume directories be organized as a tree ?

### ISSUE THREAD

**Issue by IcyLemon** [nextcloud/docker#533]
Hi
I found that all of the volumes in /var/lib/docker/volumes are the same level, an example as follows im my host:
/var/lib/docker/volumes/prjA-web
/var/lib/docker/volumes/prjA-db
/var/lib/docker/volumes/prjB-web
/var/lib/docker/volumes/prjB-db
......

Can these directories be organized as a tree shown as below?
/var/lib/docker/volumes/prjA
-------------------------------|--web
-------------------------------|--db
/var/lib/docker/volumes/prjB
-------------------------------|--web
-------------------------------|--db

I think the tree looks more clear when there are many volumes in the service.
Thanks.

**Comment by SnowMB** [comment]
You can always instead of using just names and letting the docker engine create the directory mount folders of your host system. There you can use any structure that you want.

Example:
```
... 
services:
  db:
    image: mariadb
    volumes:
      - . /db:/var/lib/mysql
... 

  app:
    Image: nextcloud 
    volumes:
      - ./data:/var/www/html
```

If this is not sufficient, open an issue in the docker repository. This is not at all linked to the nextcloud image.
