### ISSUE TITLE
Database connection fails

### ISSUE THREAD

**Issue by Schroedingers-Cat** [nextcloud/docker#540]
I'm following the README.md of this repo but am unable to finish the WebUI setup. As the readme file does not specify where to put certain variables, I'm writing them into both apps. Here is my config: 
```yml
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=supersecret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=127.0.0.1:3306
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=supersecret

  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_PASSWORD=supersecret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=127.0.0.1:3306
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=supersecret

  web:
    image: nginx
    ports:
      - 9000:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    restart: always
```
Upon opening the WebUI, the setup screen is loaded. It doesn't ask for any database values first (the option to show database specific parameters is not there at first). I can only create an admin account. There is the first bug as these values should have been read from the environment variables.  
If I enter the admin account credentials, I get the following error:
```
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused 
```
It seems like the docker images seem to ignore certain environment variables which makes the automatic configuration currently broken.
