### ISSUE TITLE
Rebuild & push images

### ISSUE THREAD

**Issue by rcdailey** [nextcloud/docker#558]
An [issue related to running as an arbitrary user](https://github.com/docker-library/php/issues/743) was fixed recently in the `php:7.2-apache-stretch` image (See https://github.com/docker-library/php/pull/755 and https://github.com/docker-library/php/pull/745).

I verified the following configuration works:

```
version: '3.7'

services:
  app:
    image: php:7.2-apache-stretch
    user: $UID:$GID
    network_mode: bridge
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - 50080:80
    volumes:
      - ./app:/var/www/html
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - APACHE_RUN_USER=#$UID
      - APACHE_RUN_GROUP=#$GID
```

However, `nextcloud:apache` will not benefit from these changes unless you rebuild & publish again, I believe. Have you automated your deployment process so this will get handled eventually? Or must this be manually done?
