### ISSUE TITLE
Cron job is broken when running as non-root user

### ISSUE THREAD

**Issue by rcdailey** [nextcloud/docker#563]
Since https://github.com/nextcloud/docker/issues/458 is now fixed, running the cron job shell script is now broken. For reference, this is the way I set up my cron job in my docker compose (this is based on the examples in this repository)

```
  cron:
    image: nextcloud:apache
    restart: always
    user: $UID:$GID
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    entrypoint: /cron.sh
    networks:
      - nextcloud
    volumes:
      - ./nextcloud/config:/var/www/html
      - /media/nextcloud:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=db
      - APACHE_RUN_USER=#$UID
      - APACHE_RUN_GROUP=#$GID
    env_file:
      - db.env
    depends_on:
      - db
      - redis
```

As you can see, I am running as a specific user. I do the same with the Nextcloud container itself. Permissions are set up for that user in the mounted volume directories and everything works great. However, the cron job no longer works because of this code (taken from `Dockerfile-alpine.template`):

```
# entrypoint.sh and cron.sh dependencies
RUN set -ex; \
    \
    apk add --no-cache \
        rsync \
    ; \
    \
    rm /var/spool/cron/crontabs/root; \
    echo '*/15 * * * * php -f /var/www/html/cron.php' > /var/spool/cron/crontabs/www-data
```

Notice that it sets up the cron job to be run as user `www-data`, which is the default user if one was not explicitly specified when running the image. However, this does not allow support for custom users.

So _technically_ non-root user support is not really completed, but I thought I'd create this as a separate issue. I'm not sure how to fix this myself, so I held off on submitting a PR. @tilosp would it be possible to have this fixed for 14.04?
