### ISSUE TITLE
Auto-configuration based on environment variables does not work

### ISSUE THREAD

**Issue by pasikarkkainen** [nextcloud/docker#593]
It seems auto-configuration using environment variables does not work when using docker image "nextcloud:15.0.0-apache".

docker-compose.yml:

```
version: "2"

services:

  nextcloud:
    image: nextcloud:15.0.0-apache
    container_name: nextcloud
    expose:
      - "80"
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - "./data:/var/www/html:z"
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASS=secretpassword
      - NEXTCLOUD_ADMIN_USER=ncadmin
      - NEXTCLOUD_ADMIN_PASSWORD=supersecretpassword
    restart: always
```

Results in the first-time wizard having empty admin user/password, sqlite as the chosen database, and when one chooses mysql the mysql infos aren't filled in. So for some reason all those environment variables are ignored by the first-time wizard.

If I start a bash shell in the container, I can see the environment variables there just fine.

**Comment by chrisallenlane** [comment]
I am encountering the same issue.

**Comment by J0WI** [comment]
I'm not able to reproduce this

**Comment by darkdan21** [comment]
I'm having the same issue using the example docker container configuration (tried both docker-compose/with-nginx-proxy/mariadb/fpm and docker-compose/with-nginx-proxy/postgres/fpm)

**Comment by ReneCD** [comment]
I'm having the same problem.  The variables are simply being ignored.  Any idea why so many of us have this problem even though you can't reproduce it ?

**Comment by J0WI** [comment]
I used the example in https://github.com/nextcloud/docker/issues/593#issue-394863856

**Comment by ReneCD** [comment]
Example in #593?  That is this thread ?!?!

**Comment by dve** [comment]
I got the same problem, but only on an existing installation. Copy & Pasting the nextcloud parts into a new docker-compose file and starting it works like a charme...

**Comment by SnowMB** [comment]
Auto configuration will not overwrite settings if you already have an existing installation. If you are migrating or already have installed nextcloud, you have to edit the config file manually by attaching to the container or copying additional files into the container/volume.

**Comment by ReneCD** [comment]
Actually this is a new installation. I have a lot of data that I have so far accessed through CISF/SMB, and the plan now is to install nextcloud/mysql/redis containers to serve files in my local lan as well as on the internet. My lan is behind a pfsense firewall with haproxy and acme/letsencrypt, so I am not concerned with that.   

So how do I import my standard windows folder into nextcrypt? I can only find pages talking about migration from owncrypt.

**Comment by ReneCD** [comment]
Ok, I realize that is perhaps not really the relevant forum for that question, but how about this:

How can I ensure this is a new installation?  I did a "docker compose down", then "docker system prune -a".  That ought to have cleaned everything up, yet it still doesn't take the environment variables when I start over. I even went as far as to uninstall docker, remove /var/lib/docker, reinstall docker.

No matter what I do, it still comes up asking for the variables when i connect to the admin page... ?

**Comment by SnowMB** [comment]
normally `docker-compose down -v ` should be enough (`-v` ensures that the created volumes get deleted)

Can you please post your docker-compose file?

**Comment by ReneCD** [comment]
Sure:

```
version: '2'  

volumes:
  nextcloud:
  mariadb:

services:  
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /media/usb/share/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 80:80
    links:
      - mariadb
    volumes:
      - /media/usb/share/nextcloud/data/:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER = admin
      - NEXTCLOUD_ADMIN_PASSWORD = adminpass
      - NEXTCLOUD_DATA_DIR = /media/usb/share/nextcloud/data/
      - NEXTCLOUD_TRUSTED_DOMAINS = 192.168.1.90 
```
