### ISSUE TITLE
Could not reliably determine the server's FQDN

### ISSUE THREAD

**Issue by Radi8621** [nextcloud/docker#609]
Starting Docker-compose up  brings up this error, cant figure out what it means.
I tried giving Nextcloud a hostname which didnt help, the site isnt reachable on its given domainname

`nextcloud_1_e78a6c9913a5 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.4. Set the 'ServerName' directive globally to suppress this message
nextcloud_1_e78a6c9913a5 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.4. Set the 'ServerName' directive globally to suppress this message
nextcloud_1_e78a6c9913a5 | [Thu Jan 17 13:05:29.072973 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.3.1 configured -- resuming normal operations
nextcloud_1_e78a6c9913a5 | [Thu Jan 17 13:05:29.073727 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
`

**Comment by xhorntail** [comment]
Also running into this one today.
Currently working on it, I'll let you know if I find a bandaid.

**Comment by xhorntail** [comment]
Managed to resolve. Don't I feel sheepish...
Add the 'hostname' to your yaml for Apache to pick up.

`nextcloud:
    hostname: cloud.${ROOT_DOMAIN}`

**Comment by Radi8621** [comment]
works perfectly thanks

**Comment by Dextroz** [comment]
> 
> 
> Managed to resolve. Don't I feel sheepish...
> Add the 'hostname' to your yaml for Apache to pick up.
> 
> `nextcloud: hostname: cloud.${ROOT_DOMAIN}`

Hey @xhorntail @Radi8621 where abouts in the compose file does `nextcloud: hostname: cloud.${ROOT_DOMAIN}` go?

**Comment by 1bigchonk** [comment]
@Dextroz 

I added it to the app section under environment. Seems to have done the trick.
```
 app:
    build: .
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=                     
      - LETSENCRYPT_HOST=                     
      - LETSENCRYPT_EMAIL=                        
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=              
      - **NEXTCLOUD_HOSTNAME=**                      
      - NEXTCLOUD_TRUSTED_DOMAINS= 

```

**Comment by VelocityDesign** [comment]
Having this issue today.

**Comment by piraterx** [comment]
I have same issue.

**Comment by jaredthirsk** [comment]
> > Managed to resolve. Don't I feel sheepish...
> > Add the 'hostname' to your yaml for Apache to pick up.
> > `nextcloud: hostname: cloud.${ROOT_DOMAIN}`
> 
> Hey @xhorntail @Radi8621 where abouts in the compose file does `nextcloud: hostname: cloud.${ROOT_DOMAIN}` go?

There is a docker-compose directive for hostname.  

Example:
```
version: "3.0"
services:
  nextcloud:
    hostname: your-name.example.com
```

Source: https://stackoverflow.com/a/63291253/208304
