### ISSUE TITLE
Cant connect from desktop client to instance, keeps looping "connect account" page

### ISSUE THREAD

**Issue by mgscreativa** [nextcloud/docker#678]
Hi! I'm able to use my nextcloud instance from web, but can't connect through desktop client! After clicking next after writing server host, I'm redirected to **Connect to your account**, I put my credentials there, then I get redirected to **Account access**, then keeps looping **Connect to your account** then  **Account access** and so on and never connects!

**Client version: 2.5.1git**, using Ubuntu desktop 18.04

I'm using an external MariaDB server on my host, configuration went just fine, and I started the instance with this docker-compose.yml file:
```
version: '2'

services:
  web:
    image: nextcloud:stable-apache
    restart: always
    hostname: 'cloud.mgscreativa.com.ar'
    container_name: nextcloud
    ports:
    - "3080:80"
    volumes:
    - /media/data/nextcloud/data/html:/var/www/html
    - /media/data/nextcloud/data/apps:/var/www/html/custom_apps
    - /media/data/nextcloud/data/config:/var/www/html/config
    - /media/data/nextcloud/data/cloud_data:/var/www/html/data
```

I'm using apache server as proxy with this config:
```
# NextCloud pass connections to docker
<Proxy />
    Allow from localhost
</Proxy>

ProxyPreserveHost On
ProxyPass /.well-known/acme-challenge/ !
ProxyPass / http://lucas.mgscreativa.com.ar:3080/
ProxyPassReverse / http://lucas.mgscreativa.com.ar:3080/
```

Thanks in advise!
