### ISSUE TITLE
Possibly Bug: Internal Server Error Using Shared Database Network

### ISSUE THREAD

**Issue by budimanjojo** [nextcloud/docker#704]
I tried everything for nearly 10 hours already. Seems like something is broken and I don't know what :cry: 
This is what I did:
1. Create database network by doing:
`docker network create db`
2. Have all my databases and Adminer in that network so I can connect to all of them using Adminer (currently having another service working fine).
3. Compose a Nextcloud + Traefik, always end up with "Internal Server Error" and the logs show nothing unusual. I tried to use web installer by not passing the username and password, it shows up perfectly, but as soon as I put in the database information and click connect, I'm put in the "Internal Server Error" message again. I tried connecting to the database using Adminer and the database is fine. It's just Nextcloud bug I think?
Here's my docker-compose.yml (domain name is not shown of course), everything is the same with the example yml file except the database part. If I don't use external network, then Nextcloud will be successfully installed:

```
version: '3'

services:
  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - config.env
    networks:
      - db

  redis:
    image: redis:alpine
    restart: always

  nextcloud:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    env_file:
      - config.env
    depends_on:
      - nextcloud_db
      - redis
    networks:
      - traefik
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:nextcloud.example.com"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_default"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "treafik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - redis

networks:
  traefik:
    external:
      name: traefik_default
  db:
    external: true
```
And here's my config.env file (credentials and domain is not shown off course):
```
MYSQL_ROOT_PASSWORD=password
MYSQL_DATABASE=nextcloud
MYSQL_USER=user
MYSQL_PASSWORD=password
MYSQL_HOST=nextcloud_db
REDIS_HOST=redis
REDIS_PORT=6379
NEXTCLOUD_ADMIN_USER=user
NEXTCLOUD_ADMIN_PASSWORD=password
NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.example.com
```
Thank you
