### ISSUE TITLE
When specifying a docker user, receive permissions issue

### ISSUE THREAD

**Issue by Ashtonian** [nextcloud/docker#716]
I can't get the nextcloud image to stay up using docker compose when I specify a user for the image to run. 

```sh 
Initializing nextcloud 15.0.7.0 ...,
rsync: mkstemp "/var/www/html/config/.htaccess.ouuZQM" failed: Permission denied (13),
rsync: mkstemp "/var/www/html/config/.apache-pretty-urls.config.php.172yr0" failed: Permission denied (13),
rsync: mkstemp "/var/www/html/config/.apcu.config.php.UCM81d" failed: Permission denied (13),
rsync: mkstemp "/var/www/html/config/.apps.config.php.VfBICr" failed: Permission denied (13),
rsync: mkstemp "/var/www/html/config/.autoconfig.php.stuidF" failed: Permission denied (13),
rsync: mkstemp "/var/www/html/config/.config.sample.php.v6sSNS" failed: Permission denied (13),
rsync: mkstemp "/var/www/html/config/.redis.config.php.gmVto6" failed: Permission denied (13),
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2],
```
```yml
services:
  db:
    image: mariadb
    logging: *default-logging
    networks:
      - nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${NC_DB_ROOT_PASS}
      MYSQL_PASSWORD: ${NC_DB_PASS}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  redis:
    image: redis
    logging: *default-logging
    volumes:
      - redis:/data
    networks:
      - nextcloud

  nextcloud:
    image: nextcloud:apache
    logging: *default-logging
    volumes:
      - nextcloud:/var/www/html
      - nexctcloud_config:/var/www/html/config
      - nexctcloud_custom_apps:/var/www/html/custom_apps
      - nextcloud_data:/data
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: ${NC_DB_PASS}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: 
      REDIS_HOST: redis
      NEXTCLOUD_DATA_DIR: /data
    depends_on:
      - db
      - redis
    networks:
      - nextcloud
      - public
    labels:
      traefik.enable: "true"
      traefik.docker.network: "public"
      traefik.backend: "nextcloud"
      traefik.frontend.rule: "Host:"
      traefik.port: "80"
      traefik.protocol: "http"
    user: "5001:5001"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "public"
        traefik.backend: "nextcloud"
        traefik.frontend.rule: "Host:"
        traefik.port: "80"
        traefik.protocol: "http"
        # traefik.frontend.whiteList.sourceRange: 10.0.0.1/24
        # traefik.frontend.whiteList.useXForwardedFor: "true"

  nextcloud-cron:
    image: nextcloud:apache
    logging: *default-logging
    restart: always
    networks:
      - nextcloud
    volumes:
      - nextcloud:/var/www/html
      - nexctcloud_config:/var/www/html/config
      - nexctcloud_custom_apps:/var/www/html/custom_apps
    user: "5001:5001"
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    deploy:

networks:
  nextcloud:
    driver: overlay
  public:
    external: true

volumes:
  redis:
  db:
  nextcloud:
  nexctcloud_config:
  nexctcloud_custom_apps:
```
