### ISSUE TITLE
Locale problem and support for UTF-8 file names

### ISSUE THREAD

**Issue by ricardojlrufino** [nextcloud/docker#721]
Used names of files and folders with accents (Brazil pt_BR). I had to set the chart and set the environment variables.
To work I had to add these environment variables:
```
        env:
        - name: LC_ALL
          value: C.UTF-8
        - name: TZ
          value: America/SaoPaulo
```
