### ISSUE TITLE
Caddy reverse proxy index.php 404

### ISSUE THREAD

**Issue by RoGryza** [nextcloud/docker#737]
I'm trying to setup nextcloud behind a caddy reverse proxy, but I get 404 on any page I attempt to access and caddy reports `Primary script unknown`.

Relevant caddy logs:
```log
168.181.49.69 - - [02/May/2019:23:58:56 +0000] "GET / HTTP/2.0" 404 16
02/May/2019:23:58:56 +0000 [ERROR 0 /] Primary script unknown
```

Relevant nextcloud logs:
```log
172.18.0.4 -  03/May/2019:00:06:35 +0000 "GET /index.php" 404
```

docker-compose.yaml:
```yaml
version: '3'
volumes:
  nextcloud:
services:
  caddy:
    image: abiosoft/caddy
    links:
    - nextcloud
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - /configs/Caddyfile:/etc/Caddyfile:ro
    - /data/caddy:/root/.caddy
    - nextcloud:/var/www/nextcloud:ro
  postgres:
    image: postgres
    restart: always
    expose:
    - '5432'
    environment:
      POSTGRES_PASSWORD: foobar
    volumes:
    - /data/postgres:/var/lib/postgresql/data
  nextcloud:
    image: nextcloud:fpm
    links:
    - postgres
    depends_on:
    - postgres
    expose:
    - '9000'
    restart: always
    volumes:
    - nextcloud:/var/www/html
    environment:
      POSTGRES_DB: foobar
      POSTGRES_USER: foobar
      POSTGRES_PASSWORD: foobar
      POSTGRES_HOST: postgres
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: foobar
```

Caddyfile:
```
nextclouddomain {
  log stdout
  errors stderr

  root /var/www/nextcloud

  fastcgi / nextcloud:9000 php {
    env PATH /bin
  }

  header / {
    Strict-Transport-Security "max-age=15768000;"
  }

  rewrite {
    ext .svg .gif .png .html .ttf .woff .ico .jpg .jpeg
    r ^/index.php/(.+)$
    to /{1} /index.php?{1}
  }

  rewrite {
    r ^/\.well-known/host-meta$
    to /public.php?service=host-meta&{query}
  }

  rewrite {
    r ^/\.well-known/host-meta\.json$
    to /public.php?service=host-meta-json&{query}
  }

  rewrite {
    r ^/\.well-known/webfinger$
    to /public.php?service=webfinger&{query}
  }

  rewrite {
    r ^/index.php/.*$
    to /index.php?{query}
  }

  # client support (e.g. os x calendar / contacts)
  redir /.well-known/carddav /remote.php/carddav 301
  redir /.well-known/caldav /remote.php/caldav 301

  # remove trailing / as it causes errors with php-fpm
  rewrite {
    r ^/remote.php/(webdav|caldav|carddav|dav)(\/?)(\/?)$
    to /remote.php/{1}
  }

  rewrite {
    r ^/remote.php/(webdav|caldav|carddav|dav)/(.+?)(\/?)(\/?)$
    to /remote.php/{1}/{2}
  }

  rewrite {
    r ^/public.php/(dav|webdav|caldav|carddav)(\/?)(\/?)$
    to /public.php/{1}
  }

  rewrite {
    r ^/public.php/(dav|webdav|caldav|carddav)/(.+)(\/?)(\/?)$
    to /public.php/{1}/{2}
  }

# .htaccess / data / config / ... shouldn't be accessible from outside
  status 403 {
    /.htaccess
    /data
    /config
    /db_structure
    /.xml
    /README
  }
}
```
