### ISSUE TITLE
Getting redirected to https://_

### ISSUE THREAD

**Issue by vipera7** [nextcloud/docker#757]
Everytime I try to run the container I'm always redirected to https://_.

I tried to run with docker-compose : 
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /home/foo/nextcloud:/var/www/html
    restart: always
```

and run `docker-compose up -d` which give me a success message : 
```
Creating compose_db_1 ... done
Creating compose_app_1 ... done
```

And I tried the simpliest command `docker run -d -p 8080:80 nextcloud` and I'm still getting redirected to https://_

The port 8080 is not used by any service or docker
