### ISSUE TITLE
U2F not working

### ISSUE THREAD

**Issue by vc7ee** [nextcloud/docker#767]
Stuck at this:
![image](https://user-images.githubusercontent.com/38327267/58958923-80a8d000-8793-11e9-95c2-bed54a291840.png)
16.0.1, apache version, traefik

**Comment by vc7ee** [comment]
docker-compose.yml
```
version: '3'
networks:
  web:
    external: true
  internal:
    external: false

volumes:
  nxrascloud:
  nxrasdb:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - nxrasdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal
    labels:
      - traefik.enable=false
  app:
    image: nextcloud
    links:
      - db
    volumes:
      - nxrascloud:/var/www/html
      - /hdds/.dockerstorage/bgnxrs:/var/www/html/hdd
    restart: always
    labels:
      - traefik.backend=rasnx
      - traefik.frontend.rule=Host:issuedomain.tld
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:15552000
      - traefik.frontend.redirect.permanent=true
      - traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/
    networks:
      - internal
      - web
```
