### ISSUE TITLE
Specific paths as bind mounts

### ISSUE THREAD

**Issue by Windyo** [nextcloud/docker#775]
I am trying to fire up a nextcloud instance inside of Docker, in order to migrate data from NextcloudPi to the docker instance.

I used the example files and a lot of tinkering with the db.env file to get what I want - however there is one detail remaining.
The docker-compose files specify named volumes, in particular one `nextcloud` for `/var/www/html`.

Now this means that EVERYTHING related to Nextcloud is stored in there. Ideally I'de like my data (/var/www/html/data) file to be stored somewhere completely different - namely another drive that handles BTRFS snapshots and is made to host the terabytes of data that I have.

Except if I want to use named volumes for this, I can't map `/var/www/html` as subvolume mappings of named volumes get ignored as per docker-compose documentation. If I don't map `/var/www/html` it results in wonky stuff and Nextcloud won't work.

Is the only option to initialize then map every file ? Or ae there specific folders that need mapping so it works ?

Compose file (that doesn't work due to the bind mappings) for reference below. Note that if I comment out the bind mappings and map nextcloud to the html folder it works fine:

```
version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
      - themes:/var/www/html/themes
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - SMTP_HOST=auth.smtp.test.fr
      - SMTP_SECURE=ssl
      - SMTP_PORT=465
      - SMTP_AUTHTYPE=LOGIN
      - MAIL_FROM_ADDRESS=test
      - MAIL_DOMAIN=test.eu
      - SMTP_NAME=test@testcom
      - SMTP_PASSWORD=test
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - data:/var/www/html/data:ro
      - config:/var/www/html/config:ro
      - apps:/var/www/html/apps:ro
      - themes:/var/www/html/themes:ro
    environment:
      - VIRTUAL_HOST=test.test.eu
      - LETSENCRYPT_HOST=test.test.eu
      - LETSENCRYPT_EMAIL=test@test.com
      - NEXTCLOUD_TRUSTED_DOMAINS=test.test.eu
    depends_on:
      - app
    networks:
      - nginx-proxy
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
      - themes:/var/www/html/themes
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/bkp/nextcloud/ncdb
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/bkp/nextcloud/ncdata
  config:
    driver: local
    driver_opts:
     type: none
     o: bind
     device: /mnt/bkp/nextcloud/ncconfig
  apps:
    driver: local
  apps:
    driver: local
    driver_opts:
     type: none
     o: bind
     device: /mnt/bkp/nextcloud/ncapps
  themes:
    driver: local
    driver_opts:
     type: none
     o: bind
     device: /mnt/bkp/nextcloud/ncthemes

networks:
  nginx-proxy:
    external: true
```
