### ISSUE TITLE
docker-compose up from examples is failing

### ISSUE THREAD

**Issue by Moep90** [nextcloud/docker#80]
```
docker-compose version
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

```
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Set my .env file:
```
cat .env
DOMAIN=domain.name
LETSENCRYPT_EMAIL=admin@domain.name
``` 

Not really edited docker-compose.yml
```
cat docker-compose.yml
version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    restart: always

  letsencrypt-companion:
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:rw
    restart: always

  web:
    image: nginx
    container_name: nextcloud_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
      - collabora
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=
    networks:
      - proxy-tier
    restart: always

  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    networks:
      - proxy-tier
    restart: always

  db:
    image: mariadb
    container_name: db
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securepw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=othersecurepw
    networks:
      - proxy-tier
    restart: always

  redis:
    image: redis
    container_name: redis
    networks:
      - proxy-tier
    restart: always

  collabora:
    image: collabora/code
    container_name: collabora
    cap_add:
      - MKNOD
    environment:
      - domain=${DOMAIN}
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
Got following error when starting docker-compose
```
docker-compose up -d
Starting proxy
Recreating db
collabora is up-to-date
redis is up-to-date
Recreating nextcloud_fpm
Recreating nextcloud_webserver

ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint proxy (294456d5ddc7a611be9a075d06ff1816924dcb4ddb1f88defe87d7c89a3592ae): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project
```

```
docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS               NAMES
4339be331c0f        nginx                 "nginx -g 'daemon ..."   2 minutes ago       Up 2 minutes        80/tcp              nextcloud_webserver
6aee71f61fa5        nextcloud:fpm         "/entrypoint.sh ph..."   2 minutes ago       Up 2 minutes        9000/tcp            nextcloud_fpm
69cb732d5f1a        mariadb               "docker-entrypoint..."   2 minutes ago       Up 2 minutes        3306/tcp            db
6dbd3337b394        redis                 "docker-entrypoint..."   4 minutes ago       Up 4 minutes        6379/tcp            redis
461fe7838614        collabora/code        "/bin/sh -c 'bash ..."   4 minutes ago       Up 13 seconds                           collabora
e9deecf0bda6        jwilder/nginx-proxy   "/app/docker-entry..."   4 minutes ago       Created                                 proxy
```
