### ISSUE TITLE
docker-compose doesn't complete final steps

### ISSUE THREAD

**Issue by blackerking** [nextcloud/docker#813]
Hey there,
I am trying to make a yaml file with all neccassary inputs. Nextcloud is using the complete input file but doesn't finishs and asks for another logincredentials. Is there an other environment flag missing?

```
    environment:
     NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
     NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     MYSQL_HOST: mariadb
```
