### ISSUE TITLE
Can't create or write into the data directory stored on nfs share

### ISSUE THREAD

**Issue by waspinator** [nextcloud/docker#834]
Thanks for working on a docker solution to make nextcloud easier to install and update.  

I'm trying to move the data directory to outside of the standard location, but I can't seem to figure out how to give nextcloud the permission it needs to write to it. 

This is the error I get:

```
nextcloud_1     | Installing with MySQL database
nextcloud_1     | starting nextcloud installation
nextcloud_1     | Can't create or write into the data directory /data
nextcloud_1     | retrying install...
nextcloud_1     | Can't create or write into the data directory /data
nextcloud_1     | retrying install...
...
nextcloud_1     | installing of nextcloud failed!
```

This is the `docker-compose.yml` file I'm using

```
version: '3'

services:
  db:
    image: mariadb:10
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /nfs/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:5
    restart: always
      
  cron:
    build:
      context: .
      dockerfile: ./docker/nextcloud.dockerfile
    restart: always
    volumes:
      - /nfs/html:/var/www/html
      - /nfs/data:/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    environment:
      NEXTCLOUD_DATA_DIR: "/data"
      REDIS_HOST: "redis"

  nextcloud:
    build:
      context: .
      dockerfile: ./docker/nextcloud.dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - /nfs/html:/var/www/html
      - /nfs/data:/data
    restart: always
    environment:
      - VIRTUAL_HOST=nextcloud.mydomain.com
      - LETSENCRYPT_HOST=nextcloud.mydomain.com
      - NEXTCLOUD_DATA_DIR=/data
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      - REDIS_HOST=redis
      - SMTP_HOST=smtp.mymail.com
      - SMTP_SECURE=ssl
      - SMTP_PORT=465
      - SMTP_NAME=me@mydomain.com
      - SMTP_PASSWORD=password
      - MAIL_FROM_ADDRESS=nextcloud@mydomain.com
      

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - nextcloud
    restart: always
    environment:
      DOMAINS: 'nextcloud.mydomain.com -> http://nextcloud:80'
      STAGE: 'production'
      FORCE_RENEW: 'true'
```

I tried with the vanilla image and with this modified one with the same results.

```
FROM nextcloud:16

RUN mkdir /data \
    && chown -R www-data:root /data \
    && chmod -R g=u /data
```

Things seem to work if I use the default data directory, but I feel more comfortable having it somewhere else.
