### ISSUE TITLE
Problem with 128:ERROR:simp_le:1446: CA marked some of the authorizations as invalid

### ISSUE THREAD

**Issue by zinnik1** [nextcloud/docker#877]
Unfortunately, I do not get the encryption out.
So right now the stand is like this:
locally I reach the nextcloud, but only unencrypted http: // nas-ip: 4080
is not clear why I have to attach the port 4080th
externally I reach the nextcloud but again only unencrypted.
http://nextcloud.zinnik.de

Somewhere lies the mistake with Letsenscript. Unfortunately, I can not continue

My subdomain is registered with STRATO and with a CNAME on the Dyndns of my NAS (meine-nas.myqnapcloud.com.)

I'll send you the Compose file

```
`version:` '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=donchillo0501
    env_file:
      - db.env

  app:  
    image: nextcloud:fpm
    restart: always
    volumes:
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/html:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    volumes:
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/html:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=nextcloud.zinnik.de
      - LETSENCRYPT_HOST=nextcloud.zinnik.de
      - LETSENCRYPT_EMAIL=zinnik.sven@gmail.com
    depends_on:
      - app
    ports:
      - 4080:80
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 443:443
      - 80:80
#    environment:
#      - VIRTUAL_PROTO=https
#     - VIRTUAL_PORT=443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/nginx-certs:/etc/nginx/certs:ro
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/nginx-vhost.d:/etc/nginx/vhost.d
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/nginx-html:/usr/share/nginx/html
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/nginx-conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/nginx-certs:/etc/nginx/certs
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/nginx-vhost.d:/etc/nginx/vhost.d
      - /share/CACHEDEV1_DATA/Docker-Volumes/nextcloud/nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy
      
networks:
  

proxy-tier:
```

and here is the LOG of lets enscript from the portainer console

```
Creating/renewal nextcloud.zinnik.de certificates... (nextcloud.zinnik.de)


2019-09-30 08:26:00,167:INFO:simp_le:1479: Generating new certificate private key


2019-09-30 08:26:05,128:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz-v3/566433076


Challenge validation has failed, see error log.




Debugging tips: -v improves output verbosity. Help is available under --help.


/app


Sleep for 3600s
```

In the fritzbox the ports are cleared

![Unbenannt](https://user-images.githubusercontent.com/55980890/65871782-6d8fc080-e37f-11e9-8144-dd29171dd5f2.JPG)

**Comment by zinnik1** [comment]
Kann man hier was heraus lesen ?


`{`
  "identifier": {
    "type": "dns",
    "value": "nextcloud.zinnik.de"
  },
  "status": "invalid",
  "expires": "2019-10-20T19:26:30Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:unauthorized",
        "detail": "Invalid response from http://nextcloud.zinnik.de/.well-known/acme-challenge/utENV-cwEyaq7JXL-9FA-uhUwsKxU4XiwEr1ioy1yhQ [80.138.119.82]: \"\u003chtml\u003e\\r\\n\u003chead\u003e\u003ctitle\u003e404 Not Found\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody\u003e\\r\\n\u003ccenter\u003e\u003ch1\u003e404 Not Found\u003c/h1\u003e\u003c/center\u003e\\r\\n\u003chr\u003e\u003ccenter\u003enginx/1.17.3\u003c/ce\"",
        "status": 403
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/chall-v3/764350216/9INUqA",
      "token": "utENV-cwEyaq7JXL-9FA-uhUwsKxU4XiwEr1ioy1yhQ",
      "validationRecord": [
        {
          "url": "http://nextcloud.zinnik.de/.well-known/acme-challenge/utENV-cwEyaq7JXL-9FA-uhUwsKxU4XiwEr1ioy1yhQ",
          "hostname": "nextcloud.zinnik.de",
          "port": "80",
          "addressesResolved": [
            "80.138.119.82"
          ],
          "addressUsed": "80.138.119.82"
        }
      ]
    },
    {
      "type": "dns-01",
      "status": "invalid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/chall-v3/764350216/iSH2nQ",
      "token": "utENV-cwEyaq7JXL-9FA-uhUwsKxU4XiwEr1ioy1yhQ"
    },
    {
      "type": "tls-alpn-01",
      "status": "invalid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/chall-v3/764350216/lXUqTA",
      "token": "utENV-cwEyaq7JXL-9FA-uhUwsKxU4XiwEr1ioy1yhQ"
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      1
    ],
    [
      2
    ]
  ]
}``

**Comment by binarious** [comment]
Having the same problem. Error details from Let's Encrypt:
```
"challenges": [
  {
    "type": "http-01",
    "status": "invalid",
    "error": {
      "type": "urn:ietf:params:acme:error:connection",
      "detail": "Fetching https://REMOVED/.well-known/acme-challenge/7MTvqndpaS7l6xDHXPIqLYLdtesp3Gy-heC3omgkRuQ: Error getting validation data",
      "status": 400
    }
    // ...
  }
]
```
<details><summary>My docker-compose.yml</summary>
```
version: '3'

services:
  db:
    image: mariadb:10.4
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=REMOVED
    env_file:
      - db.env

  redis:
    image: redis:5.0-alpine
    restart: always

  app:
    image: nextcloud:17-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=REMOVED
      - LETSENCRYPT_HOST=REMOVED
      - LETSENCRYPT_EMAIL=REMOVED
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:17-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/volumes/nextcloud"
  db:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
```
</details>
