### ISSUE TITLE
Nextcloud Docker Compose custom folder locations

### ISSUE THREAD

**Issue by LegendaryB** [nextcloud/docker#924]
Hey Guys,

I'm trying to setup nextcloud with docker. But I want that the nextcloud related folders are mounted in a specific location.

When I use this configuration it does not work (it runs fine without problems but in the end I get only Connection Refused errors while trying to connect to the database): 

```
version: '3'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /mnt/pool/docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD=ROOTPW

  app:
    container_name: nextcloud-app
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /mnt/pool/docker/nextcloud/app:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    depends_on:
      - db

  web:
    container_name: nextcloud-nginx
    build: ./web
    restart: always
    ports:
      - 80:80
    volumes:
      - /mnt/pool/docker/nextcloud/app:/var/www/html:ro
    depends_on:
      - app 
```
Then I used the default docker compose file and it worked. My idea was then to use the local driver to bind to a location but this was also not working.

Any ideas / recommendations how to proceed?

Kind Regards,
Daniel
