### ISSUE TITLE
Upon restarting on a new node, it always prompts for a new admin user to be created.

### ISSUE THREAD

**Issue by esn89** [nextcloud/docker#950]
So I have nextcloud docker running on a machine in AWS.  
I have an autoscaling group set up where the desired amount is set as "1".  
When a node goes down and a new one starts back up with the dockerized nextcloud, it asks me to create a nextcloud admin user.

As for storage, I have offloaded the database to amazon's database and the storage as an elastic file store.

I also run a 'local-persist' command to ensure that the data volume gets exposed to my mounted elastic filesystem and when the node restarts, it will read from the old elastic file store.

```
# Gets local-persist
curl -fsSL https://raw.githubusercontent.com/CWSpear/local-persist/master/scripts/install.sh | bash
docker volume create -d local-persist -o mountpoint=/nextclouddata/nextcloud-data --name=nextcloud-data
```

My docker-compose can be seen here:

```
version: '2'

volumes:
  nextcloud-data:
    external: true

services:
  app:
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - nextcloud-data:/var/www/html
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testpassword
      - MYSQL_HOST=mysql.endpoint.com
```

What am I doing wrong where every time I restart the node, it prompts me to create a new admin user?  
What can I do to persist users?

Any help will be appreciated.  Thank you.
