### ISSUE TITLE
docker-compose - can't mount any other *.config.php on first run

### ISSUE THREAD

**Issue by Loxeno** [nextcloud/docker#957]
Hi,

I would like to add multiple *.config.php in the config folder.
This folder (in fact, its parent) is a volume as detailed [here](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml) ).

```
services:
  nc-fpm:
    image: nextcloud:fpm
    restart: always
    networks:
      - nc
    depends_on:
      - nc-db
      - nc-redis
    env_file:
      - env/prod/nc/nc-db.env
      - env/prod/nc/nc-fpm.env
    volumes:
      - nc-app:/var/www/html:rw
      - ./sources/nc/fpm/mimetypemapping.json:/var/www/html/config/mimetypemapping.json:ro
```

If I start the container from scratch, I get :

> Cannot write into "config" directory.

But if I comment the line, start the container, uncomment the line and docke-compose up, I get the config in the right place.

Do you have any idea how to solve this ?

By advance, thank you.
