### ISSUE TITLE
412 Session errors with Nextcloud 17 and Redis on Docker

### ISSUE THREAD

**Issue by JanoschDeurer** [nextcloud/docker#964]
After updating my docker-compose to nextcloud 17 I started getting a lot of 412 errors and the message "Problem loading page, reloading in 5 seconds" in the frontend. After reading this issue: https://github.com/nextcloud/server/issues/5274 I figured it would be a session problem. After disabling redis in my docker-compose everything worked again.

I'm currently running nextcloud:17.0.2-fpm-alpine and redis:5.0.7-alpine3.11

Here my docker-compose.yml file, note that I use traefik as a reverse proxy for ssl termination:
```
version: '2.3'
services:
  nextcloud:
    image: nextcloud:17.0.2-fpm-alpine
    restart: always
    environment:
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=<censored>
      - NEXTCLOUD_TRUSTED_DOMAINS=<censored>
      # - REDIS_HOST=redis
    env_file:
      - db.env
    volumes:
      - ./volumes/nextcloud/var_www_html:/var/www/html
  db:
    image: mariadb:10.4.11
    restart: always
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/db_backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=<censored>
    env_file:
      - db.env
  collabora:
    image: collabora/code:4.2.0.3
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:<censored>"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.protocol=http"
      - "traefik.port=9980"
      - "traefik.docker.network=network_web"
      - "traefik.frontend.headers.STSSeconds=315360000"
    environment:
      - domain=<censored>
      - server_name=<censored>
      - username=admin
      - password=<censored>
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
      - DONT_GEN_SSL_CERT=true
    cap_add:
      - MKNOD
    tty: true
    networks:
      - network_web
      - default
  redis:
    image: redis:5.0.7-alpine3.11
    restart: always
  cron:
    image: nextcloud:17.0.2-fpm-alpine
    restart: always
    volumes_from:
      -  nextcloud
    entrypoint: /cron.sh

  nginx:
    image: nginx:1.17.7-alpine
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:<censored>"
      - "traefik.protocol=http"
      - "traefik.port=80"
      - "traefik.docker.network=network_web"
      - "traefik.frontend.redirect.permanent='true'"
      - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.customFrameOptionsValue=sameorigin"
      - "traefik.frontend.passHostHeader=true"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud
    networks:
      - network_web
      - default

networks:
  network_web:
    name: network_web
  default:
    name: network_default
```
